### ISSUE TITLE
Can not start on VMware

### ISSUE THREAD

**Issue by lenhatvu** [SuRGeoNix/Flyleaf#10]
Hi,

I am trying to run your application on VMware (Window Server 2016) but application can not start.
After debug, i found an error at: videoDevice1 = device.QueryInterface<VideoDevice1>(); in Initialize() method in MediaRenderer.cs
Maybe the cause is dont have any monitor connected with that PC.
![image](https://user-images.githubusercontent.com/59004953/95658756-f589d800-0b46-11eb-8a83-ff533ba016b8.png)

**Comment by SuRGeoNix** [comment]
The application is for Windows Platforms with DirectX, Monitors & Sound Cards!
Thanks for sharing tho 👍
