### ISSUE TITLE
How to pass some parameters to Youtube-DL.exe to download an m3u8 link?

### ISSUE THREAD

**Issue by zydjohnHotmail** [SuRGeoNix/Flyleaf#100]
Hello:
As the latest version (3.3.10) has support for Youtube-DL plugin, I want to write some code to do the job as Youtube-DL.exe can do in the following command line:

C:\Videos\Download\> youtube-dl https://m3u8.1proxy.xyz/media/g_18/playlist.m3u8 --external-downloader ffmpeg --referer "https://bingsport.com/" -o g_18.mp4

I have downloaded and installed Youtube-DL.exe in @"C:\Program Files\YoutubeDL\Youtube-dl.exe", and edit Path variable to add this path.

But when I want to change the Youtube-DL plugin in the flyleaf solution.
I can’t find where to pass parameters, like: 
--external-downloader ffmpeg 
--referer "https://bingsport.com/" 

I can only think about using open(url), like open("https://m3u8.1proxy.xyz/media/g_18/playlist.m3u8"),
but I have to add other 2 more parameters:
--external-downloader ffmpeg 
--referer "https://bingsport.com/" 

I believe the underlying M3U8 link is still available, you can use Youtube-DL to download it, even you see some warning or error message, but downloading is going OK.
Let me know how to write the code to call Youtube-DL plugin to download the above M3U8 link and save to local hard drive.
Finally, how I can get event like “Download_Complete”?
Thanks,

**Comment by SuRGeoNix** [comment]
@zydjohnHotmail I have already answer you in previous post with a link of the line in the youtube-dl plugin where to add your options. Download_Completed already exist in downloader. Please don't create long questions for things that already answer or for how to write your own code. This is not related to the library.
