### ISSUE TITLE
frame-by-frame seeking support

### ISSUE THREAD

**Issue by swimfish09** [SuRGeoNix/Flyleaf#101]
frame-by-frame seeking support

**Comment by SuRGeoNix** [comment]
@swimfish09 I added this on master, have a look and let me know.

Keep in mind the following:-

1) ShowFramePrev() is slow performance as it requires decode all the frame before until the keyframe (this is also related to reverse playback)
2) ShowFramePrev() and ShowFrame(frameIndex) calls will cause the buffer queue to be disposed (so you loose the downloaded data in case of network stream)
3)  ShowFrame(frameIndex) uses a zero-based index, You can grab the total video frames from Player.VideoDecoder.VideoStream.TotalFrames. But you might have issues based on the video input as some videos they don't have a constant fps and it's not possible to do the right calculations.

**Comment by pssp-sven** [comment]
I‘m really glad to see that you obviously implemented these features. Based on #96 and #97 I thought it would take much longer until you‘d try to do so. I‘ll also test it and give you some feedback.

**Comment by swimfish09** [comment]
Excellent!I‘m really glad to see that you obviously implemented these features.

**Comment by pssp-sven** [comment]
Hi @SuRGeoNix,
_ShowFrameNext()_ always works like a charm. 👍
Just _ShowFramePrev()_ sometimes leads to a complete stop of the control. But most of the time it works like expected. I will have an eye on this and report more when necessary.
Thanks again for all your efforts.

**Comment by SuRGeoNix** [comment]
Yes found an issue, it should be fixed now
