### ISSUE TITLE
Reverse Playback support

### ISSUE THREAD

**Issue by swimfish09** [SuRGeoNix/Flyleaf#102]
Reverse Playback support

**Comment by SuRGeoNix** [comment]
This one is tricky to implement especially with Flyleaf's standards (performance wise). Requires decoding from one Keyframe to another and keep all those video frames in GPU which will cause large GPU memory. Let me know if the ShowFramePrev() can cover your requirements.

**Comment by SuRGeoNix** [comment]
@swimfish09 @pssp-sven This now has been added. Please let me know how this feature can be improved or if it already enough with the current implementation

**Comment by pssp-sven** [comment]
Hi @SuRGeoNix, great news, thanks. I‘ll test it and give you my feedback tomorrow.

**Comment by swimfish09** [comment]
Hi @SuRGeoNix, great news, thanks.

**Comment by pssp-sven** [comment]
Hi @SuRGeoNix,
the reverse playback really works fine. 👍
I've encountered some problems only when using functions like _ShowFramePrev()_ or _ShowFrameNext()_ if the property _ReversePlayback_ is still _true_. But when switching it to _false_ before everything works correct.
I'll give you more feedback as soon as I could use this feature more in practice.
