### ISSUE TITLE
how to use flyleaf to add watermark

### ISSUE THREAD

**Issue by swimfish09** [SuRGeoNix/Flyleaf#103]

**Comment by SuRGeoNix** [comment]
Just create a control above the VideoView? With WPF you could true transparency if required but not with WinForms. If you want more advance things you should use Vortice (SharpDX replacement) to render text or image in the DirectX pipeline.

**Comment by swimfish09** [comment]
why not use ffmpeg filter? Does flyleaf support ffmpeg filter? 
`ffplay edu.mp4 -vf drawtext="fontfile=arial.ttf:text='test':fontsize=100:x=(w-tw)/2:y=(h-th)/2:fontcolor=white@0.5:box=1:boxcolor=black@0.1:boxborderw=5"`

**Comment by SuRGeoNix** [comment]
For flyleaf it's important to use GPU processor to achieve better performance. You can check also the #94 discussion for ffmpeg filters. Imagine to apply the above filter while playing a video requires to bring all the GPU video frames down to CPU/RAM for processing it. It doesn't worth it,
