### ISSUE TITLE
"hwaccel initialisation returned error" when play udp h264 stream camera.

### ISSUE THREAD

**Issue by EjiHuang** [SuRGeoNix/Flyleaf#104]
Hi, @SuRGeoNix
I have a udp camera. And I want to use Flyleaf to play it. But it returned me an error about hwaccel.
I got some ffmpeg log info:
```log
[12.05.49.785] [#2] [Demuxer: Video] 
[Format  ] raw H.264 video/h264 | h26l,h264,264,avc 00:00:00/00:00:00 | [Seekable: True]
[Video #0] h264 yuvj420p 1920x1080 @ 25 | [BR: 0] | -10675199.02:48:05.4775808/-10675199.02:48:05.4775808 | 00:00:00/-10675199.02:48:05.4775808
[12.05.49.787] [#2] [Demuxer: Video] Opening -> Stopped
[12.05.49.787] [#2] [Decoder: Video] Stopped -> Opening
[12.05.49.788] [#2] [Decoder: Video] [VA] Success
[12.05.49.791] [#2] [Demuxer: Video] [Video #0] Enabled
[12.05.49.792] [#2] [Decoder: Video] Opening -> Stopped
[12.05.49.792] [#2] [DecoderContext] [VideoStream] #_ => #0
[12.05.49.793] [#2] [DecoderContext] [VideoInput] None => udp://127.0.0.1:50002
[12.05.49.794] [#2] [Demuxer: Video] Stopped -> Running
[12.05.49.796] [#2] [Decoder: Video] Stopped -> Running
[12.05.49.799] [#2] [Decoder: Video] [Thread] Started (Running)
[12.05.49.801] [#2] [Demuxer: Video] [Thread] Started (Running)
[12.05.49.938] [FFmpeg] [h264 @ 1877abc0] Failed setup for format d3d11: hwaccel initialisation returned error.
```

Excuse me, is the hardware decoding does not support udp h264 stream?

**Comment by SuRGeoNix** [comment]
Hi @EjiHuang,

I think a came across this one as well. I'm not an expert with video codecs but it's not simple to say "its H.264, it should work". I think it has other parameters as well (profiles) that might be the reason for the difference. Now, I am not sure if the problem is the GPU that doesn't support it or ffmpeg. If you confirm that is Flyleaf's issue I will look deeper in to this.

If any other ffmpeg player (ffplay, mpv, kodi, vlc with avformat demuxer selected) works with hardware acceleration (for this specific camera) then it's Flyleaf's issue.

**Comment by EjiHuang** [comment]
Thank you.
And you are right, I think I should do some comparative test to analyze this issue.

**Comment by SuRGeoNix** [comment]
One more thought, you might want to try to set the Video Settings -> decoder threads to 1. It's possible that the specific codec doesn't support more threads.

**Comment by EjiHuang** [comment]
![image](https://user-images.githubusercontent.com/10510947/143420301-8768b673-f4fe-400c-b26e-819af2708150.png)
Use vlc for this command:
```cmd
:sout=#transcode{vcodec=h264,acodec=none,scodec=none}:udp{dst=224.1.1.2:50002} :no-sout-all :sout-keep
```
Flyleaf works well.
Decoder threads value is default.

**Comment by SuRGeoNix** [comment]
I'm not sure what you have done. Did vlc failed as well? Or you manage to make Flyleaf work with hardware acceleration?

**Comment by EjiHuang** [comment]
Yes, vlc failed too.
So, I think the issue is in my camera.

Abuout your question, the meaning of the previous command is: 
I use vlc to stream a mp4 video to udp://224.1.1.2:50002. And I use Flyleaf to play this url. And use hardware acceleratio. It works well.

**Comment by EjiHuang** [comment]
Finally, I tried the mpv player. It can play this camera, but its hwdec not work.

**Comment by SuRGeoNix** [comment]
@EjiHuang Thanks for testing this further to confirm that it's not Flyleaf's issue :)

**Comment by EjiHuang** [comment]
@SuRGeoNix 
You're welcome.
