### ISSUE TITLE
Error when firing PlaybackCompleted event

### ISSUE THREAD

**Issue by pssp-sven** [SuRGeoNix/Flyleaf#106]
Hi @SuRGeoNix,

I've just installed the new version **3.4.0-pre**. I subscribe to the PlaybackCompleted event. As soon as the video is finished the following error occurs: 

```
PlatformNotSupportedException
Operation is not supported on this platform.

Stack Trace:
   at System.EventHandler 1.BeginInvoke(Object sender, TEventArgs e, AsyncCallback callback, Object object)
   at FlyleafLib.MediaPlayer.Player.OnPlaybackCompleted(String error)
   at FlyleafLib.MediaPlayer.Player.<Play>b__279_1()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ThreadHelper.ThreadStart()
```

Even when the event handler is empty the application crashes:

```
            _player.PlaybackCompleted += (s, e) =>
            {
            };
```

Thanks
Sven

**Comment by SuRGeoNix** [comment]
Yes this have been fixed on master branch, fixing some other bugs and I will release v3.4.0

**Comment by SuRGeoNix** [comment]
Just created another nuget package (3.4.0-pre2). Have a look and let me know

**Comment by pssp-sven** [comment]
Great, I'll have look in a minute.

**Comment by pssp-sven** [comment]
Perfect, it works again! Thanks

BTW, what is the recommended way to jump to the last frame? Right now I do the following: `_player.CurTime = _player.Duration;`

But I guess there is a better way to do it. Probably it can be done with `ShowFrame(...)`. But using `_player.Video.FramesTotal` for the last frame is not correct, isn't it?

To jump to the first frame I call: `_player.ShowFrame(0);` That works great.

**Comment by SuRGeoNix** [comment]
Normally you should just do ShowFrame(_player.Video.FramesTotal-1)

However, the total frames are calculated based on fps and might be a slightly difference from the actual value (I will have a look if possible to get from ffmpeg something more accurate but I'm afraid is not).

I think the best way it would be to enable reverse playback but don't play just start the decoder/demuxer and then manually get the frame from the decoder's video frame queue

**Comment by SuRGeoNix** [comment]
Just had a quick look and found some issues with start/end of stream on reverse playback and fix them. I have managed to decode and present from the end with the following code (if not works already it will with the next update)

````csharp
Config.Player.AutoPlay = false;
Player.Open(@"c:\root\dev\Flyleaf\VideoSamples\0.mp4");
Player.VideoDemuxer.EnableReversePlayback(Player.Duration);
Player.VideoDemuxer.Start();
Player.VideoDecoder.Start();

while (Player.VideoDecoder.IsRunning || Player.VideoDecoder.Frames.Count > 0)
	while (Player.VideoDecoder.Frames.TryDequeue(out FlyleafLib.MediaFramework.MediaFrame.VideoFrame frame))
	{
		Player.renderer.Present(frame);
		System.Threading.Thread.Sleep(1000);
	}
````
