### ISSUE TITLE
multiplayer sometimes will hang on and crash

### ISSUE THREAD

**Issue by swimfish09** [SuRGeoNix/Flyleaf#107]
multiplayer  open rtmp stream, after some time later, the application hang on.

**Comment by SuRGeoNix** [comment]
Hey @swimfish09, I've never tried rtmp and I can't find easily a sample url for testing. Can you provide one? (even private drop me an email)

If you can't try to find more information. Check [ffmpeg's rtmp](https://ffmpeg.org/ffmpeg-protocols.html#rtmp) protocol options and Master.RegisterFFmpeg with 64/AV_LOG_MAX_OFFSET.

**Comment by swimfish09** [comment]
I use nuget latest version.
Maybe it's my ffmpeg version is 4.3.1，I will change it and check later.

**Comment by SuRGeoNix** [comment]
You shouldn't use different version from ffmpeg.autogen that library uses (it's 4.4+ now). Re-open this if you have issues but provide more details.

**Comment by swimfish09** [comment]
Hi @SuRGeoNix, I tried the latest code with Test/FlyleafMultiplayer, and set debug on. Only the first player debug message is correct., others seems wrong.
![image](https://user-images.githubusercontent.com/3916975/147303768-6c30b8c9-3eef-41ba-ab62-2b6291f10c2a.png)

**Comment by SuRGeoNix** [comment]
Hi @swimfish09, yep that was another bug with master thread. Just fixed it.

Do you still have hang issues?

**Comment by swimfish09** [comment]
Actually still exist. Especially when i open 16 players and switch windows back and forth to maximize restore.
With intel graphics card is good, with nvidia graphics card the window will hang on.

**Comment by SuRGeoNix** [comment]
Have you tried any other application with 16 players and worked properly? You could try to Pause them all before Full/Normal screen. You could also try to reduce video frame even more to 2 if you have VRAM issues. If you provide more details about the 'hang on', event logs / flyleaf logs (from the debugger) I might be able to help.

**Comment by swimfish09** [comment]
Ok, I will keep investigating it.

**Comment by swimfish09** [comment]
Windows log
```
System.Collections.Generic.KeyNotFoundException
   System.ThrowHelper.ThrowKeyNotFoundException()
   System.Collections.Generic.Dictionary`2[[System.Int32, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].get_Item(Int32)
   FlyleafLib.MediaFramework.MediaDemuxer.Demuxer.UpdateCurTime()
   FlyleafLib.MediaFramework.MediaDemuxer.Demuxer.RunInternal()
   FlyleafLib.MediaFramework.RunThreadBase.Run()
   System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   System.Threading.ThreadHelper.ThreadStart()

**Comment by SuRGeoNix** [comment]
Some other people come up with this issue at the past again. But I wasn't able to identify why it is happening. This is the related line code:-

```csharp
if (CurPackets.TryPeek(out IntPtr firstPacketPtr) && ((AVPacket*)firstPacketPtr)->dts != AV_NOPTS_VALUE)
   firstPacketTs = (long) (((AVPacket*)firstPacketPtr)->dts * AVStreamToStream[((AVPacket*)firstPacketPtr)->stream_index].Timebase);
```
Can you help me reproduce it to understand what is going on exactly? I could add the try/catch again but I would prefer to understand why is this happening because it could cause more issues.

You use latest nuget and your rtmp or the rtmp urls that I sent you? Does this happening only with multiplayers?

**Comment by swimfish09** [comment]
Yes I use latest nuget.  From now, it's happened only with multiplayers, Especially with 16 players.
