### ISSUE TITLE
Can not set Speed Up/Down and adjusting the Pitch-Shift for audio when playing the video.

### ISSUE THREAD

**Issue by phamvv** [SuRGeoNix/Flyleaf#11]
Hi brother!

Thank for your project.!
i'm try to play the video and want to change Speed Up or down for player and adjusting the Pitch-Shift for audio. I have tried adding soundtouch.dll library but the result is not as expected. Can you add these functions to the player?

thank you so much!

**Comment by SuRGeoNix** [comment]
Hey,

I'm glad you enjoy this project :)

As this is a large project and i'm working on it alone only on free time, I'm afraid that I will not be able to add sound effects soon. Probably, the next important thing for audio is to support more channels and different rates.

However, if you want to play around with this, I would suggest you to start with ffmpeg API, it should support the majority of sound effects (including speed up/down & pitch-shift).
