### ISSUE TITLE
Why FlyleafLib playback speed limited to 4x?

### ISSUE THREAD

**Issue by swimfish09** [SuRGeoNix/Flyleaf#110]
Hi @SuRGeoNix , Why FlyleafLib playback speed limited to 4x? Many usage scenarios，like video surveillance  neeed 8x speed even greater.

**Comment by SuRGeoNix** [comment]
Yes I could allow it to x8 and x16. I will do it on the next update.

**Comment by swimfish09** [comment]
Ok it will be very nice.

**Comment by SuRGeoNix** [comment]
Just tried to play a video with x16. Almost burned my GPU. Requires different approach for that but I will enable it for now. Maybe seek by keyframe forward all time? (however you can't be sure what is the distance for the keyframe, it can be 1sec, it could be 15sec)

**Comment by swimfish09** [comment]
Actually, play a video with x16 will consumes a lot of gpu resources. I have tried using libvlc play a video with x16, it's also would consumes a lot of gpu resources. I think this is not a problem, if you want to play a video with x16 , you need a powerful graphics card.
