### ISSUE TITLE
Reverse Playback was more smoothly before (Winforms) (v3.4.4)

### ISSUE THREAD

**Issue by pssp-sven** [SuRGeoNix/Flyleaf#112]
Hi @SuRGeoNix,
the Reverse Playback is not as smooth as before (Winforms). In version 3.4.0-pre2 it seemed to be better. Did something change regarding this feature?

**Comment by SuRGeoNix** [comment]
Yes, it's the Config.Decoder.MaxVideoFrames that changed. You will need to manually change them so they can handle the reverse playback more smoothly.

**Comment by pssp-sven** [comment]
Setting MaxVideoFrames to 8 for reverse playing seems to work better. To play the videos forward I leave it to 4.

**Comment by pssp-sven** [comment]
Sorry, I have to revoke my previous post. The reverse playback is not as good as before. Do you have any recommendations for the MaxVideoFrames values or any other idea, what I can do about it? Thanks again.

**Comment by pssp-sven** [comment]
It depends a lot on the video format. If you  need more sample videos, please let me know. I can send them to you.

**Comment by SuRGeoNix** [comment]
It requires at lest 40 frames. However, with the new implementation (as it handles the ffmpeg's hw frame pool) it will not allow for some reason more than 80 I think. But when I tried with 40-60 frames was the same as it was before.
