### ISSUE TITLE
Reverse Seek not always working (Winforms) (v3.4.4)

### ISSUE THREAD

**Issue by pssp-sven** [SuRGeoNix/Flyleaf#113]
Hello @SuRGeoNix,
sometime the reverse seek doesn't work as expected. In version 3.4.0-pre2 this problem didn't exist.
`Player.Seek(ms, false)`
Did anything change regarding the reverse seek?

**Comment by SuRGeoNix** [comment]
Let me know if that is related with https://github.com/SuRGeoNix/Flyleaf/issues/112

**Comment by pssp-sven** [comment]
In some videos it works, but the majority of my test videos has problems. I will send you a sample video, so that you can check that yourself. Hope this helps. Thanks!

**Comment by SuRGeoNix** [comment]
Let me know how it goes with the new version.
