### ISSUE TITLE
System.InvalidOperationException: Cannot create IDXGIFactory1

### ISSUE THREAD

**Issue by swimfish09** [SuRGeoNix/Flyleaf#116]
```c#
string ffmpegLibPath = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "medialib", Environment.Is64BitProcess ? "x64" : "x32");
Master.RegisterFFmpeg(ffmpegLibPath, 24);
```
win7 use latest nuget  version.
System.TypeInitializationException: The type initializer for 'FlyleafLib.Master' threw an exception. ---> System.TypeInitializationException: The type initializer for 'FlyleafLib.MediaFramework.MediaRenderer.Renderer' threw an exception. ---> System.InvalidOperationException: Cannot create IDXGIFactory1
   at FlyleafLib.MediaFramework.MediaRenderer.Renderer..cctor()
   --- End of inner exception stack trace ---
   at FlyleafLib.MediaFramework.MediaRenderer.Renderer.GetAdapters()
   at FlyleafLib.Master..cctor()
   --- End of inner exception stack trace ---
   at FlyleafLib.Master.RegisterFFmpeg(String absolutePath, Int32 verbosity)

**Comment by swimfish09** [comment]
My fault, I don't have KB36805 installed.

**Comment by SuRGeoNix** [comment]
I have not tested the new render with older windows versions so let me know if you have any issues
