### ISSUE TITLE
Win 7 backwards compatibility with XAudio (System.DllNotFoundException: xaudio2_9.dll)

### ISSUE THREAD

**Issue by swimfish09** [SuRGeoNix/Flyleaf#117]
win 7 
use lastest nuget version
The type initializer for 'Vortice.XAudio2.XAudio2Native' threw an exception.
System.TypeInitializationException: The type initializer for 'Vortice.XAudio2.XAudio2Native' threw an exception. ---> System.DllNotFoundException: Unable to load xaudio2_9.dll or xaudio2_9redist.dll library.
   at Vortice.XAudio2.XAudio2Native.LoadXAudioLibrary()
   at Vortice.XAudio2.XAudio2Native..cctor()
   --- End of inner exception stack trace ---
   at Vortice.XAudio2.XAudio2Native.XAudio2Create(UInt32 flags, ProcessorSpecifier processorSpecifier)
   at FlyleafLib.MediaPlayer.Audio.Initialize(Int32 sampleRate)
   at FlyleafLib.MediaPlayer.Player..ctor(Config config)
   at vss_windows.Controls.VideoPreviewPlayerControl.<Open>d__115.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by SuRGeoNix** [comment]
Yes, I'm not quite sure if we can support the Win7 anymore both me but also Amer.

@amerkoleci can you a look at this one?

**Comment by SuRGeoNix** [comment]
@swimfish09 can you confirm that the player however started and was able to play video?

**Comment by amerkoleci** [comment]
You can resolve by downloading XAudio redist from nuget and add xaudio2_9redist.dll from there, I have no plans to support XAudio 2.7, sorry

**Comment by SuRGeoNix** [comment]
That's fine @amerkoleci, I guess windows update or direct MS download for XAudio could resolve it too(?). Anyways, Win7 are too old I'm not planning to support them either to be honest.

**Comment by swimfish09** [comment]
> @swimfish09 can you confirm that the player however started and was able to play video?
> 
> I guess it didn't I will fix it to be able to continue play.

app crashed

**Comment by SuRGeoNix** [comment]
Did you try the new package (v3.4.6)? I thought I fixed it to at least not crash and continue playing. Maybe you need to put the .dll files under C:\Windows or C:\Windows\system32

**Comment by swimfish09** [comment]
I have tried. The Player not crash and not playing.

**Comment by SuRGeoNix** [comment]
OK if it didn't crash it has another issue with the fallback to sw frames. If you disable the Config.Video.VideoAcceleration it should be able to play.

**Comment by swimfish09** [comment]
If disable the Config.Video.VideoAcceleration, the video brightness is dim.

**Comment by SuRGeoNix** [comment]
Possible try to force Config.Video.VideoProcessor to Flyleaf instead of D3D11

**Comment by swimfish09** [comment]
Ok, I'll try it later.

**Comment by swimfish09** [comment]
Win7 got the bellow error.
HRESULT: [0x80070057], Module: [General], ApiCode: [E_INVALIDARG/Invalid arguments]

**Comment by SuRGeoNix** [comment]
I thought you said that it was working but it only had issue with the brightness. Did you disable VA? In any case, you will have issues with Win7 as the XAudio will not be supported so I'm afraid that you will have to upgrade your windows version if you want this to work properly.

**Comment by swimfish09** [comment]
About error bellow:
HRESULT: [0x80070057], Module: [General], ApiCode: [E_INVALIDARG/Invalid arguments]
https://github.com/amerkoleci/Vortice.Windows/issues/192

**Comment by swimfish09** [comment]
After some research, maybe use latetest Flyleaf  version is difficult  to support windows 7.
Which version i can use to support both win7 and win10？For me it is important to support both os version.

**Comment by SuRGeoNix** [comment]
Flyleaf was never fully -for Video Acceleration- support Win7. If it is important for you to support Direct9 / Win7 you should check alternative solutions which are not that many, I think is just LibVLCSharp.

**Comment by SuRGeoNix** [comment]
Trying to do some testing with < Win10 version on VMs. Found an number of issues which I will try to fix on the next update. However, Win7 audio will not be fixed anyways and I'm not sure If I will be able to add support.

**Comment by swimfish09** [comment]
That was great.I'll test it right now.

**Comment by swimfish09** [comment]
It is worked well on win7, the audio maybe can be solved with xaudio2_9redist.dll.

**Comment by swimfish09** [comment]
I have tried xaudio2_9redist.dll the audio worked.

**Comment by swimfish09** [comment]
> I've fixed a number of issues and tested with Win8 and Feature levels 9.3. Which means that probably works also on Win 7. No idea about the audio though.
> 
> Tested from master whenever you can and let me know.

It is played with win7, But VA is not enabled.

**Comment by SuRGeoNix** [comment]
That's good news. Well, to implement VA with feature level < 10 requires a completely different implementation with the older DXVA which I'm not willing to implement just to support those. Just wondering, who and why is still using so old systems!
It's already a pain to keep track of changes to ensure that the backwards compatibility will not be brake.

**Comment by swimfish09** [comment]
All right.
