### ISSUE TITLE
Some video brightness is dim

### ISSUE THREAD

**Issue by swimfish09** [SuRGeoNix/Flyleaf#118]
Some video brightness is dim, older version does not have this problem.
use latest nuget version
windows 10

**Comment by SuRGeoNix** [comment]
Can you give more details? Do you mean that it fails to set the default brightness initially? Does this happen for all the videos or for specific? Can you tested with the Flyleaf WPF Sample/Control and see the Min/Max and value that initializes for brightness?

**Comment by swimfish09** [comment]
Use latest code does not have this problem.

**Comment by SuRGeoNix** [comment]
Nice, I guess I will need to have soon an updated package as it had some critical issues
