### ISSUE TITLE
How can I get mouse position from player?

### ISSUE THREAD

**Issue by EjiHuang** [SuRGeoNix/Flyleaf#119]
Hi @SuRGeoNix 

I have a question, I found that adding mouse events on the flyleaf control doesn't work. My project is base on wpf.

Like this:
```charp
xFlyleaf.PlayerGrid.MouseLeftButtonDown += PlayerGrid_MouseLeftButtonDown;
xFlyleaf.MouseLeftButtonDown += xFlyleaf_MouseLeftButtonDown;
```

Then, I saw the FlyleafLib/MediaPlayer/Player.Mouse.cs. All mouse event is base on System.Windows.Forms, right?
So, if I want to draw a bounding box on the player. I need to get the mouse position from the player. I found some funtion like PointFromScreen() and PointToScreen() to convert the position. But I don't have mouse position.

Can you give me some helps? Thank you.

**Comment by SuRGeoNix** [comment]
You can just subscribe to the underlying control events from Player.Control. And if you have issues with the default mouse bindings you can disable them from the config (Config.Player.MouseBindings.Enabled = false; Let me know if that works for you.

**Comment by EjiHuang** [comment]
Thank you.
I used (Config.Player.MouseBindings.Enabled = false;) and added Player.Control.MouseDown event.
Then, I got the mouse position from the winform control. It works great.
Although this is not the coordinate of the video frame. But I have video frame size and control size. I can convert mouse coordinate to video frame coordinate. I will keep trying.

**Comment by SuRGeoNix** [comment]
Player.renderer.GetViewport might also help you as you need to calculate also the aspect ratio
