### ISSUE TITLE
Playing corrupted/incomplete videos

### ISSUE THREAD

**Issue by JayX2MA** [SuRGeoNix/Flyleaf#123]
How can I change the codec context to set the err_detect flag to ignore_err so that corrrupted / incomplete videos will still play?

**Comment by SuRGeoNix** [comment]
I wasn't able to tested as I don't have a corrupted file for that but by checking the [format options](https://ffmpeg.org/ffmpeg-formats.html) you do it like that:-

```
Config.Demuxer.FormatOpt.Add("err_detect", "aggressive");
```
