### ISSUE TITLE
curTime is wrong when play m3u8 and with video brightness is dim

### ISSUE THREAD

**Issue by swimfish09** [SuRGeoNix/Flyleaf#125]
Use latest master code.

**Comment by SuRGeoNix** [comment]
Hey @swimfish09, first of all, be careful when you post log files, you might accidentally expose private links/information. If that's the case consider dropping me an email to avoid this.

I'm afraid that you came across with another ffmpeg bug here. I tested this with VLC and avformat (ffmpeg) demuxer and it has the same issue.

You can see that it announces wrong timestamps during the opening of the stream:

```
[Format  ] Apple HTTP Live Streaming/hls |  | 18:17:56.0359330/00:05:04.0800000 | 18:17:56.0359330/00:05:04.0800000
[Video #0] h264 yuv420p 1920x1080 @ 25 | [Color: BT709] [BR: 0] | 1.20:20:40.0766222/-10675199.02:48:05.4775808 | 1.20:20:40.0766222/00:05:04.0800000
[Audio #1-eng] pcm_alaw s16@8 8KHz mono | [BR: 64000] | 18:17:56.0359333/-10675199.02:48:05.4775808 | 18:17:56.0359333/00:05:04.0800000
```

While format context starts at 18:17:56.0359330, the video starts at 1.20:20:40.0766222.
I guess is an ffmpeg bug as VLC will work with their default demuxer for HLS.

I will try to see if I could find a workaround.

**Comment by swimfish09** [comment]
Ok

**Comment by SuRGeoNix** [comment]
One more note, my last commit changed Config.Decoder.AllowProfileMismatch default to false as it can cause issues in some cases. In your case seems that you require to turn it on to allow hardware decoding. This probably causes also your brightness issue which I'm not sure why you still having it.

**Comment by swimfish09** [comment]
After set  Config.Decoder.AllowProfileMismatch to true, the brightness issue disappear. How can i get format context starttime?
Now format context starttime is correct.

**Comment by SuRGeoNix** [comment]
https://github.com/SuRGeoNix/Flyleaf/blob/8e93bdd6acea972997f1188272d58910b540d3b0/FlyleafLib/MediaFramework/MediaDemuxer/Demuxer.cs#L1278
