### ISSUE TITLE
Sorry if this has been asked before.  Overlay timeout.

### ISSUE THREAD

**Issue by maestrith** [SuRGeoNix/Flyleaf#126]
Is there a way to set the timeout for the overlay (Play Button, Seek Slider...etc) so that it hides itself with less of a delay and also faster?  Also is there a way to just hide it by default so that it only shows on mouse over?  Thanks in advance.

**Comment by maestrith** [comment]
Is there a way to change the "filename" from "Custom IO Stream" to something a little more descriptive?

**Comment by SuRGeoNix** [comment]
FlyleafPlayer (Custom - MVVM) (WPF)

Just add a VideoView and write your UI layout within it (this xaml code will be transferred to the foreground window to achieve the real transparency)

You can also check the upcoming FlyleafPlayer sample.

**Comment by maestrith** [comment]
Nice, thank you :) There isn't a way to do this programmatically is there?  I want to have a variable number of controls and it works amazing if you add them but there are no media controls and I can not add anything over the control.

**Comment by SuRGeoNix** [comment]
If you want to overlay the video you need to add your contents within the videoview. If you want to do it programmatically you could add a ContentControl and set the content dynamically. PlayerDispose Test might be helpful for you?

**Comment by maestrith** [comment]
Sorry to bother you but is there a way to hide/show the media controls when I want to? Currently I set ActivityTimeout = 1 and when I mouse over one of the videos sometimes it will show the controls and sometimes not (I am testing it with 9 controls at the moment).  Also you have the ability to set the BorderBrush and BorderThickness but not the CornerRadius.

**Comment by SuRGeoNix** [comment]
I'm not sure what you want to do.  If you want to hide/show based on Player.Activity.Mode (Idle/Active/FullActive) you will already find samples how you can do it (with stories etc.). If you want to hide/show based on your custom expression you will need to program it manually.

The video control is on the main window not in the foreground. So I guess if you add a border/canvas outside the videoview you will be able to achieve the cornerradius?

**Comment by SuRGeoNix** [comment]
One more note. If you want to add more places that you will update the activity mode manually you can does this for example:-

```csharp
MouseDown += (o, e) => { Player?.Activity.ForceFullActive(); };
MouseMove += (o, e) => { Player?.Activity.ForceFullActive(); };
```

**Comment by maestrith** [comment]
LOL! I wasn't thinking... thanks for the clarification.  I am currently trying to work with overlaying text programmatically on top of the control.  Any pointers on where I could get more information on how to do that?

**Comment by SuRGeoNix** [comment]
Use a TextBlock with binding, generally try to use MVVM logic. I'm not a WPF/XAML expert. Flyleaf is my first project with that!

**Comment by maestrith** [comment]
Wow! Amazing job!

**Comment by maestrith** [comment]
I did some digging and I found out that WindowsFormsHost (which is what you are using to hold the FlyLeaf control (I think)) can not be drawn over in WPF :( I'm going to guess that you can not use something that plays a little more friendly with WPF?

**Comment by SuRGeoNix** [comment]
If you don't need the overlay / foreground window to add more controls above the video for true transparency you could avoid videoview and just use a your own WindowsFormsHost with flyleaf winforms control as child. The problem starts from the DirectX/SwapChain that requires a window handle for rendering. WPF uses a single handle for all the controls in the same window while winforms use different handle for each control.

Videoview is based on VLC's solution to achieve true transparency by creating a transparent foreground window to overlay the contents above the video.

**Comment by maestrith** [comment]
I am too much of a noob... I finally figured it out.  The only thing now is I don't think you can set WindowsFormsHost background transparent :( I am "happy" with what I have but I would love to have the overlays with transparencies.  Thanks for all of your help and for writing some amazing code!

**Comment by SuRGeoNix** [comment]
Thank @maestrith and glad you made it.

Why would you set WindowsFormsHost's background to transparent? If you really need something like that, it should be done (manually) in the Renderer and pixel shaders and use Flyleaf video renderer.

**Comment by maestrith** [comment]
Right, but when I use the videoview it automatically adds controls which is less than ideal.  I tried creating views and they work pretty well but the play/pause/seek/right click for more options that it provides is a lot more than I require.  All I really need is the player, and the ability to overlay a couple basic controls.  If there is a way to use the videoview without all the bells and whistles please let me know what example outlines that and I'll be thrilled :)

**Comment by SuRGeoNix** [comment]
Have a look again in the samples it will help you understand the role of videoview. By default videoview will not add any controls, you can build your own player controls on top of it. The default controls are coming with the WPF Control (Flyleaf) so just don't use this one.

**Comment by maestrith** [comment]
OK, I'll have another look at the examples.  I am just a WPF user and have never even tried anything with WInForms and through your WPF examples I had about 90% of what I needed.
