### ISSUE TITLE
Shift+Left when viewing an image causes an exception

### ISSUE THREAD

**Issue by maestrith** [SuRGeoNix/Flyleaf#127]
If you load an image into the control and then press Shift+Left it throws an exception.  I would love to be able to disable this key combination but I have no idea how.
![image](https://user-images.githubusercontent.com/2114637/156218441-97f5051a-e71e-4f0a-b147-5d08cd24f2d3.png)

**Comment by maestrith** [comment]
This is still a bug though.

**Comment by maestrith** [comment]
I would say that crashing your application is a pretty serious bug but that's just me.  I just wanted to point out that something silly like trying to jump back a frame on something that only has one frame causes it to crash.

**Comment by SuRGeoNix** [comment]
There is no application (at least so far). Just samples. I'm focusing on the library. That's what I meant and bugs like that can be easily handled by the application.
