### ISSUE TITLE
display byte[] for an image or video

### ISSUE THREAD

**Issue by maestrith** [SuRGeoNix/Flyleaf#133]
Is it possible to display a byte[] within the control?

**Comment by SuRGeoNix** [comment]
You can do this already by using Video Decoder's GetFrame (to get a specific frame) and Renderer's GetBitmap (to download it from GPU as software frame). See the FlyelafExtractor sample for more details. You can check then how to convert the Bitmap in to byte array (check [this](https://stackoverflow.com/questions/7350679/convert-a-bitmap-into-a-byte-array))

Let me know if you still need something more specific.
