### ISSUE TITLE
How can i play  from web url ?

### ISSUE THREAD

**Issue by ankeyliu** [SuRGeoNix/Flyleaf#134]

**Comment by SuRGeoNix** [comment]
You just give the web URL. For example if you provide a youtube video it should be play fine. However, must be supported by either ffmpeg or yt-dlp.

**Comment by eliacanavera** [comment]
Hi, should it works like this?
```
private void Button_Click(object sender, RoutedEventArgs e) 
{ 
	Player.Open("https://www.youtube.com/watch?v=z_l7p_E8o5g&ab_channel=NBA"); 
}
```

**Comment by SuRGeoNix** [comment]
@eliacanavera Yes but better use OpenAsync and make sure that you have the YT_DLP plugin in the Plugins folder. (You can download the latest release and copy the Plugins folder as is)

**Comment by eliacanavera** [comment]
![Screenshot 2023-12-21 130648](https://github.com/SuRGeoNix/Flyleaf/assets/118448340/11f39233-dce0-418c-967b-781016d62d20)
Inside EngineConfig I have: `PluginsPath = "C:\\Flyleaf\\Plugins"`

![Screenshot 2023-12-21 134454](https://github.com/SuRGeoNix/Flyleaf/assets/118448340/adb01539-06d0-4f4e-9f74-5de844de224d)

**Comment by SuRGeoNix** [comment]
Well not inside Libs, before that

**Comment by eliacanavera1111** [comment]
Inside or outside YoutubeDL folder? I already tried both, but for some reason it's not working (I also tried with different FlyleafPlayer(Wpf) samples).

**Comment by SuRGeoNix** [comment]
@eliacanavera Not sure what you do wrong, you will need to debug it yourself. Here is what the code does:-

```csharp
FileName        = Path.Combine(Engine.Plugins.Folder, Name, plugin_path),
```

Engine.Plugins.Folder will be set from Engine's Config.PluginsPath (default is Plugins/) the Name is from class name (YoutubeDL) and plugin_path is yt-dlp.exe so if you combine them will be Plugins/YoutubeDL/yt-dlp.exe (from your bin/output directory)
