### ISSUE TITLE
How to load subtitles?

### ISSUE THREAD

**Issue by Jacques-eMediaIT** [SuRGeoNix/Flyleaf#137]
I can't get the subtitles to load for a video. It's a .srt file with the same name as the video and it loads with other media players. Any suggestions?

**Comment by SuRGeoNix** [comment]
Do you have an issue to load subtitles generally or with a specific file only? If that's the case, can you send me the .srt? By the way, you need to load the subtitles after you open a video input.

**Comment by Jacques-eMediaIT** [comment]
Got it working now, thanks. I had to open the .srt file like the video after opening the video.

I'm busy using your NuGet libs to make a media player for myself that can censor out certain words by scanning the subtitles and then muting the audio if that line contains a banned word.
