### ISSUE TITLE
Suggestion: Outlined Subtitles

### ISSUE THREAD

**Issue by MrJacquers** [SuRGeoNix/Flyleaf#139]
I found this and was able to modify it to display centered. I think it could look nicer than the drop shadow and give extra options for things like the fill color, stroke (outline) color, thickness, etc.

https://github.com/dotnet/docs-desktop/blob/main/dotnet-desktop-guide/samples/snippets/csharp/VS_Snippets_Wpf/OutlineTextControlViewer/CSharp/OutlineTextControl.cs

public void CreateText()
        {
            System.Windows.FontStyle fontStyle = FontStyles.Normal;
            FontWeight fontWeight = FontWeights.Medium;

            if (Bold == true) fontWeight = FontWeights.Bold;
            if (Italic == true) fontStyle = FontStyles.Italic;

            // Create the formatted text based on the properties set.
            var formattedText = new FormattedText(
                Text,
                CultureInfo.GetCultureInfo("en-us"),
                FlowDirection.LeftToRight,
                new Typeface(Font, fontStyle, fontWeight, FontStretches.Normal),
                FontSize,
                System.Windows.Media.Brushes.Black // This brush does not matter since we use the geometry of the text.
                );

            formattedText.TextAlignment = TextAlignment.Center;

            // Build the geometry object that represents the text.
            _textGeometry = formattedText.BuildGeometry(new Point(formattedText.Width / 2.0, 0.0));

            // Build the geometry object that represents the text highlight.
            if (Highlight == true)
            {
                _textHighLightGeometry = formattedText.BuildHighlightGeometry(new System.Windows.Point(0, 0));
            }

            base.MinWidth = formattedText.Width;
            base.MinHeight = formattedText.Height;
        }

**Comment by SuRGeoNix** [comment]
Hi @Jacques-eMediaIT and thanks for the suggestion. Before Flyleaf v3.0, I was Direct2D for the outline text and I was thinking to re-included in the library and not in the WPF Control. I will have a look on this in the next updates.

**Comment by SuRGeoNix** [comment]
For now, I will let the user to decide his customization on application level. But I might add more options, helpers in the future.
