### ISSUE TITLE
ffmpeg 5 support?

### ISSUE THREAD

**Issue by MrJacquers** [SuRGeoNix/Flyleaf#141]
https://ffmpeg.org/index.html#news

I was just wondering if you had any plans to support the newer version? I tried by updating the NuGet package references, but it breaks a few things.

![image](https://user-images.githubusercontent.com/84329887/163541936-ff22d901-01bf-4431-af0f-2b79ed386e0a.png)

Think I might be answering my own question, but it doesn't seem stable / ready yet?

https://github.com/opencv/opencv/issues/20147

https://github.com/opencv/opencv/pull/21754

**Comment by SuRGeoNix** [comment]
Yes, I'm planning to add support for ffmpeg 5. Didn't try yet but it will require some changes (especially for HLS as I use some private ffmpeg classes). But the most important think is that it will probably have issues for the next 6 months. So I would recommended yet.

**Comment by SuRGeoNix** [comment]
Leaving a note just for anyone who lands here.

To use ffmpeg 5 you will need to use FFmpeg.AutoGen v5 nuget package to your application (which will be used from FlyleafLib nuget package which by default uses v4).
