### ISSUE TITLE
 some aac file not play properly

### ISSUE THREAD

**Issue by HamidLaktarash** [SuRGeoNix/Flyleaf#143]
Hi. I use last version. some .aac file ( Advanced Audio Coding ) play but it's duration is zero. and it's not possible to seek forward and backward. also this files don't play properly in KMPlayer , Windows Media Player and Media Classic Player. but play properly in VLC perfect. flyleaf player can't play this file properly.
why is that? may be I upload sample file for you. I suggest flyleaf player detect this files as stream and isLive property been true

**Comment by SuRGeoNix** [comment]
Yes send me a sample I will check it. It might be a ffmpeg bug thought and cant be fixed by me.

**Comment by HamidLaktarash** [comment]
https://filelu.com/33w4bad02mpe
this is link
I think too it be a ffmpeg bug

**Comment by SuRGeoNix** [comment]
What do you mean by saying 'not play properly'? I can play it just fine. The only issue is you can't seek. And I have no idea how you can seek in VLC but you don't know the duration and when you actually seek.

**Comment by HamidLaktarash** [comment]
yes you're right. I mean exactly player can't determine duration so it can't seek. I tested VLC and show duration and have ability to seek. however thanks for your reply. I find this code that set duration to zero and isLive to true. Demuxer.cs file - FillInfo() method

```
            StartTime = fmtCtx->start_time != AV_NOPTS_VALUE ? fmtCtx->start_time * 10 : 0;
            Duration = fmtCtx->duration > 0 ? fmtCtx->duration * 10 : 0;
            // TBR: Possible we can get Apple HTTP Live Streaming/hls with HLSPlaylist->finished with Duration != 0
            if (Duration == 0 && Name == "hls" && Environment.Is64BitProcess)
            {
                hlsCtx = (HLSContext*)fmtCtx->priv_data;
                StartTime = 0;
                //UpdateHLSTime(); Maybe with default 0 playlist
            }

            IsLive = Duration == 0 || hlsCtx != null;
```

when I set duration manually and add below code it work for one file

`if (fmtCtx->duration <= -500000000)
                Duration = 37000000000;
`

**Comment by SuRGeoNix** [comment]
Well I'm not quite sure what I should do with this case. I mean, it's a broken .aac file if it doesn't have the duration. I've no idea how VLC handles this and it allows you to seek without even know where your current position is or either the duration. (At least when I tried VLC I didn't see duration or any kind indicator-time on where I'm currently playing).
Possible I would expose the Duration property for write access or with an event to set it manually.

**Comment by HamidLaktarash** [comment]
Thanks a lot for the time you spend for me.

**Comment by SuRGeoNix** [comment]
I close this for now but let me know if these cases are a lot so I can see how we can handle this!
