### ISSUE TITLE
Suggestion: Single Instance

### ISSUE THREAD

**Issue by Jacques-eMediaIT** [SuRGeoNix/Flyleaf#145]
I've implemented it for my player and thought Id share my code. It does a single instance check and also sends the command line args to the existing instance. That way if you have file associations set up it works as most people would expect.

App.xamls.cs

using System;
using System.IO;
using System.IO.Pipes;
using System.Threading;
using System.Threading.Tasks;
using System.Windows;

namespace SafeMediaPlayer;

public partial class App
{
    private static Mutex _mutex = null;

    /// <summary>
    /// Overrides the <see cref="E:System.Windows.Application.Startup" /> event.
    /// </summary>
    /// <param name="e">A <see cref="T:System.Windows.StartupEventArgs" /> that contains the event data.</param>
    protected override void OnStartup(StartupEventArgs e)
    {
        // global exception handler
        DispatcherUnhandledException += App_DispatcherUnhandledException;

        // single instance check
        var createdNew = false;
        var appName = "SFW Media Player";
        _mutex = new Mutex(true, appName, out createdNew);

        if (!createdNew)
        {
            if (e.Args.Length == 1)
            {
                try
                {
                    // send cmd line args to already running instance
                    using var client = new NamedPipeClientStream(appName);
                    client.Connect(500);

                    using StreamWriter writer = new StreamWriter(client);
                    writer.Write(e.Args[0]);
                }
                catch (Exception ex)
                {
                    // do nothing
                }
            }

            Current.Shutdown();
            return;
        }

        base.OnStartup(e);

        // needed when opening files via args
        Environment.CurrentDirectory = AppDomain.CurrentDomain.BaseDirectory;

        // init and show the main window
        var mainWindow = new MainWindow();
        mainWindow.Show();

        if (e.Args.Length == 1)
        {
            mainWindow.OpenFile(e.Args[0]);
        }

        Task.Factory.StartNew(() =>
        {
            while (_mutex != null)
            {
                // listen for message from new instance
                using var server = new NamedPipeServerStream(appName);
                server.WaitForConnection();

                using var reader = new StreamReader(server);
                var args = reader.ReadToEnd();

                // must be done on the ui thread
                Dispatcher.BeginInvoke(new Action(() =>
                {
                    mainWindow.Activate();
                    //mainWindow.Topmost = true;
                    //mainWindow.Topmost = false;
                    mainWindow.Focus();

                    mainWindow.OpenFile(args);
                }));
            }
        }, TaskCreationOptions.LongRunning);
    }

    /// <summary>
    /// Handles the DispatcherUnhandledException event of the App control.
    /// </summary>
    /// <param name="sender">The source of the event.</param>
    /// <param name="e">The <see cref="System.Windows.Threading.DispatcherUnhandledExceptionEventArgs"/> instance containing the event data.</param>
    private void App_DispatcherUnhandledException(object sender, System.Windows.Threading.DispatcherUnhandledExceptionEventArgs e)
    {
        var message = e.Exception.InnerException?.Message ?? e.Exception.Message;
        MessageBox.Show(message, "Error Starting Application", MessageBoxButton.OK, MessageBoxImage.Error);
    }

    /// <summary>
    /// Overrides the <see cref="E:System.Windows.Application.Exit" /> event.
    /// </summary>
    /// <param name="e">An <see cref="T:System.Windows.ExitEventArgs" /> that contains the event data.</param>
    protected override void OnExit(ExitEventArgs e)
    {
        // TODO: cleanup if required, e.g. save current playback position
        _mutex = null;

        base.OnExit(e);
    }
}

**Comment by SuRGeoNix** [comment]
Well, that's nice! However, this should be implemented in the application level (FlyleafPlayer Sample) and not in the library or on the WPF control. I will try to spend more time with the Sample version in general to create more functionality/full player.
