### ISSUE TITLE
Proper way to change audio stream?

### ISSUE THREAD

**Issue by seafraf** [SuRGeoNix/Flyleaf#154]
Hi!

Enjoying working with this library so far, trying to use it to replace FFME as it was very buggy and appears to be unmaintained. One of the features I am trying to re-implement is the ability to change audio streams during playback, currently I have a solution that is working fine:

```csharp
if (stream != null)
{
    MediaPlayer.MainDemuxer.SwitchStream(stream);
    MediaPlayer.SeekAccurate((int)VideoCurrentTime.TotalMilliseconds);
}
```

I am wondering if there is a more suited solution for line 4?  Without that line the audio stream does change but I won't get packets from that stream for a few seconds, assuming because the old stream's packets are still buffered.

Also, would there be any way to support more than one audio stream being played back at once?  Most of the video footage my application ingests is recordings of computer screens and sometimes microphone and system sound audio tracks are split.

Thanks

**Comment by SuRGeoNix** [comment]
HI @seafraf,

Please check the [wiki](https://github.com/SuRGeoNix/Flyleaf/wiki/Player) and the samples.

Proper way to switch streams is to use the Player.Open / Player.OpenAsync. (If you don't use the player then use the decoder context Open... and not the demuxer's switchstream directly)

The double audio will not be easy to be honest. It requires to match sample rates etc. Nobody else asked for something like that so far. You might need to check the application that you create the recordings. Or another tool in between to convert it to a single audio steram.

**Comment by seafraf** [comment]
Thanks @SuRGeoNix 

I should have provided more details in my first post, sorry.  I am using the VideoView WPF control and by stream I mean AVStream, the wiki does touch on changing these streams, but as far as I could tell did not mention how to do it.

As I am using the the VideoView control, I did try:
```csharp
MediaPlayer.AudioDecoder.Open(stream);
```

But I got the same problem as before, without seeking somewhere in the video, audio stream would not change and I would just get silence until I seek'd somewhere in the video.

I am using the same FFmpeg binaries packaged with your latest release and I am using the following config:
```csharp
Engine.Start(new EngineConfig()
{
    UIRefresh           = true,
    UIRefreshInterval   = 100,
    UICurTimePerSecond  = false
});

var Config = new Config();
Config.Player.SeekAccurate = true;
Config.Player.AutoPlay     = false;

MediaPlayer = new Player(Config);
```

In regards to audio stream merging, my application actually uses FFmpeg too and is designed to do basic editing of videos output from NVIDIA Shadowplay/OBS whose audio tracks are separated on purpose so they can be enabled or disabled later or so that their volumes can be adjusted separately.  My application uses FFmpeg's libavfilter library to apply the [amix](https://ffmpeg.org/ffmpeg-filters.html#amix) filter when outputting videos, is it possible that this same filter could be used here?  Or would it be too difficult/slow for live playback?  Happy to try this myself later if you think it's not a flawed concept.

**Comment by SuRGeoNix** [comment]
Just use MediaPlayer.Open(stream) as already mention. You might also interesting to use directly command bindings from Player.Commands.Open instead of writing yours. Check the samples for more details. You will find almost everything there.

Generally, speaking I try to avoid ffmpeg filters as it requires a large file (avfilters.dll) and for video it will brake the video acceleration and the performance (as most of the are not supporting it yet). It is better to perform any converts before the final playable video file were possible. However, I have this in mind in the future to support ffmpeg filters.

You could try the following for now. Have two players, one as a video player and the other as audio player (see Config.Player.Usage). This way you could synchronize when you open one player to open also the other -audio- player with the other audio stream and control the volume separately. Let me know how it goes and if you need any assist.

**Comment by seafraf** [comment]
Great idea! I've started down this path by creating a MediaPlayer for each of the audio streams in a video when it is opened, opening the audio streams immediately.  Unfortunately, I think due to some bug this is not working, if I instantiate a player and use `OpenAsync` immediately afterwards, it will do nothing.  Calling `Open` will throw an NPE.  Either functions called later (e.g via a button press or other event) loads the stream fine though, but I would like to have this streamed opened and paused so that they are ready to be played when the video is.

Any ideas?

The following is the code that I am using, all ran when the main video's OpenCompleted event is called:
```csharp
var audioStreams = MediaPlayer.MainDemuxer.AudioStreams;

var players = new Player[audioStreams.Count];
for (int i = 0; i < audioStreams.Count; i++)
{
    var config = new Config();
    config.Player.Usage = Usage.Audio;
    config.Player.SeekAccurate          = true;
    config.Player.AutoPlay              = false;
    config.Player.MouseBindings.Enabled = false;
    config.Player.KeyBindings.Enabled   = false;

    players[i] = new Player(config);

    // Throws NPE
    // players[i].Open(audioStreams[i]);
    // players[i].Open(originalVideoURI)

    // Does nothing
    // players[i].OpenAsync(audioStreams[i]);
    // players[i].OpenAsync(originalVideoURI)

    // Never called
    //players[i].OpenCompleted += (s, e) =>
    //{
    //    Console.WriteLine($"asd");
    //};
}```

**Comment by SuRGeoNix** [comment]
You got the process wrong. You will open the same input as you open in the main player for all the other players. And then you will not parse the main player's audiostream you will need to find the same audiostream.StreamIndex on the other players. But it's too much to open each audioplayer for each stream and difficult to handle the sync between all those players.

Try to open the main player normally with one of the audio streams enabled. And open a second audio only player with the same input as the main player (here don't parse defaultAudio as parameter you will need to open it manually after the open will be completed). Then you will need to Pause/Play and Seek at both players to keep them in sync.
