### ISSUE TITLE
AVI / XVID Video Brightness Issue

### ISSUE THREAD

**Issue by MrJacquers** [SuRGeoNix/Flyleaf#155]
I've come across a strange issue where some AVI / XVID videos start playing with a lowered brightness. When I change the Video Processor to D3D11 then it corrects itself. Changing back to Auto or Flyleaf doesn't make it go darker again.

It also doesn't seem to happen again if settings have been saved, so you may need to clear saved settings to replicate the issue.

Sample video attached.

[Sample.zip](https://github.com/SuRGeoNix/Flyleaf/files/8684733/Sample.zip)

**Comment by SuRGeoNix** [comment]
Currently there is no right conversation for filters between different video processors. So when you change a video processor it will be your responsibility to reset the filters if there are no defaults. I change that to ensure that the brightness and contrast will work fine initially as a lot of users had issues.

**Comment by SuRGeoNix** [comment]
I just wondering why you should use different video processors. But now I remembered that by default D3D11 supports everything except the following: HDR and software (no hardware accelerated) video. So it could actually change when you open a different file (or video stream) and then it could reset the filters.

**Comment by MrJacquers** [comment]
The video started playing with decreased brightness, so I was just trying various things to see if it would fix it. Choosing a different processor fixed it, so I assume it has something to do with initialization. Not really a priority for me atm.

**Comment by SuRGeoNix** [comment]
It was started because you had a saved configuration file, right?

**Comment by MrJacquers** [comment]
No, no saved config file. The issue actually seems to go away if there is a saved config file.

**Comment by SuRGeoNix** [comment]
Well the sample file does not support hardware acceleration so it will use the Flyleaf video processor in any case. Just to make sure I understand correctly.
You had another video open and you change the brightness manually and then you open this one and you lost the brightness?
Or, you just open this video and the brightness was low initially? (that will be an issue)

I can not reproduce the issue because this is based on GPU's video filters and min/max/default values.

**Comment by MrJacquers** [comment]
It's the 2nd case. I made a demo video showing the issue. The 2nd time around it's fine after settings were saved. In this case I chose D3D11 when saving, but Auto also works, which makes me think it's something to do with initialization and default values.

[Brighness Issue Demo_001.zip](https://github.com/SuRGeoNix/Flyleaf/files/8686474/Brighness.Issue.Demo_001.zip)

**Comment by SuRGeoNix** [comment]
Well you use an old version, I mean it's not your fault, I don't have the latest sample compiled. Try the master if you can as this issue has been fixed at a later version of the compiled sample.

**Comment by SuRGeoNix** [comment]
I will create new sample soon

**Comment by SuRGeoNix** [comment]
Please tested with the [latest](https://github.com/SuRGeoNix/Flyleaf/releases/latest) and re-open it if you still have issues!

**Comment by MrJacquers** [comment]
Working with the latest version, thanks!
