### ISSUE TITLE
Frame stepping does not update the CurTime

### ISSUE THREAD

**Issue by f1nalspace** [SuRGeoNix/Flyleaf#159]
If i step one frame forward using Player.ShowFrameNext() or Player.ShowFramePrev() it will corrupt the Player.CurTime property and i can´t display the current time anymore. This also affects any methods that reads the current time (Player.decoder.GetCurTime()) or Player.MainDemuxer.CurTime, etc.

FlyleafLib.Controls.WPF
1.1.22-pre

**Comment by SuRGeoNix** [comment]
Hey @f1nalspace, that was working for you in 1.1.21 and not working now in 1.1.22-pre? This is not happening in the sample latest version. How can I reproduce it?

**Comment by f1nalspace** [comment]
Edit: I tested other AVIs and all have the same problem, backward frame skipping breaks the playback.

Also, I looked deeper into your source and the reason for the negative CurTime is simply because the AVFrame* has a negative pts. Maybe there is some special handling needed in that case?

**Comment by SuRGeoNix** [comment]
Can you provide me a sample video as I cannot reproduce it? The YT video did you open it with flyleaf (youtube-dl plugin)?

**Comment by f1nalspace** [comment]
You can find the video here:
[shorturl.at/pzCUY](url)

Also it looks like that i fixed it O_o

From 63cc6b22f4e1cbb20a48c7bef7001f94665f355b Mon Sep 17 00:00:00 2001
From: f1nalspace <finalspace@googlemail.com>
Date: Tue, 24 May 2022 21:33:07 +0200
Subject: [PATCH] Fixed avi backwards frame stepping is broken by ensuring that
 the pts always present or the frame is discarded

---
 .../MediaFramework/MediaDecoder/VideoDecoder.cs  | 16 ++++++----------
 1 file changed, 6 insertions(+), 10 deletions(-)

diff --git a/FlyleafLib/MediaFramework/MediaDecoder/VideoDecoder.cs b/FlyleafLib/MediaFramework/MediaDecoder/VideoDecoder.cs
index 8a36890..cfe5fef 100644
--- a/FlyleafLib/MediaFramework/MediaDecoder/VideoDecoder.cs
+++ b/FlyleafLib/MediaFramework/MediaDecoder/VideoDecoder.cs
@@ -759,7 +759,7 @@ namespace FlyleafLib.MediaFramework.MediaDecoder
                 //mFrame.timestamp = (long)(frame->pts * VideoStream.Timebase) - VideoStream.StartTime;
 
                 VideoFrame mFrame = new VideoFrame();
-                mFrame.timestamp = (long)(frame->pts * VideoStream.Timebase) - demuxer.StartTime;
+                mFrame.timestamp = (long)(frame->best_effort_timestamp * VideoStream.Timebase) - demuxer.StartTime;
                 if (CanTrace) Log.Trace($"Processes {Utils.TicksToTime(mFrame.timestamp)}");
 
                 if (!HDRDataSent && frame->side_data != null && *frame->side_data != null)
@@ -946,7 +946,7 @@ namespace FlyleafLib.MediaFramework.MediaDecoder
             while (GetFrameNext(checkExtraFrames) == 0)
             {
                 // Skip frames before our actual requested frame
-                if ((long)(frame->best_effort_timestamp * VideoStream.Timebase) < frameTimestamp)
+                if ((long)(frame->pts * VideoStream.Timebase) < frameTimestamp)
                 {
                     //Log($"[Skip] [pts: {frame->best_effort_timestamp}] [time: {Utils.TicksToTime((long)(frame->best_effort_timestamp * VideoStream.Timebase))}]");
                     av_frame_unref(frame);
@@ -991,10 +991,8 @@ namespace FlyleafLib.MediaFramework.MediaDecoder
 
                 if (ret == 0)
                 {
-                    if (frame->best_effort_timestamp == AV_NOPTS_VALUE)
-                        frame->best_effort_timestamp = frame->pts;
-
-                    if (frame->best_effort_timestamp == AV_NOPTS_VALUE)
+                    frame->pts = frame->best_effort_timestamp == AV_NOPTS_VALUE ? frame->pts : frame->best_effort_timestamp;
+                    if (frame->pts == AV_NOPTS_VALUE)
                     {
                         av_frame_unref(frame);
                         return GetFrameNext(true);
@@ -1033,10 +1031,8 @@ namespace FlyleafLib.MediaFramework.MediaDecoder
                     return ret;
                 }
 
-                if (frame->best_effort_timestamp == AV_NOPTS_VALUE)
-                    frame->best_effort_timestamp = frame->pts;
-
-                if (frame->best_effort_timestamp == AV_NOPTS_VALUE)
+                frame->pts = frame->best_effort_timestamp == AV_NOPTS_VALUE ? frame->pts : frame->best_effort_timestamp;
+                if (frame->pts == AV_NOPTS_VALUE)
                 {
                     av_frame_unref(frame);
                     return GetFrameNext(true);
-- 
2.33.0.windows.2

**Comment by SuRGeoNix** [comment]
Nice catch. I'm using pts from RunInternal (Main decoding) and best_effort_timestamp from GetFrame (Show frame prev/next).
But both of them use ProcessVideoFrame which uses pts.

**Comment by f1nalspace** [comment]
You´re welcome. I know a little bit of ffmpeg, because i ported the ffplay.c to my platform abstraction library (libfpl.org).
