### ISSUE TITLE
Downloader buffer

### ISSUE THREAD

**Issue by apeteira** [SuRGeoNix/Flyleaf#160]
Hello,
I'm using the downloader sample but I don't know how to configure download buffer.
This what i try to do :
when I click the advanced button the RTSP video start saving frames somewhere .If i wait for 5 seconds and i click the download button a file is created since the advanced button has been pressed (5 seconds before)
How can i change the time buffer  for the saved streams?
I need to save 5 seconds before and after the download button is pressed
thank you in advanced

**Comment by SuRGeoNix** [comment]
Hi @apeteira, help me to understand better. For the sample version you cannot really change any configuration. Except if you mean that you want to create your own downloader and you need some assist.

If I understand correctly, you are talking about a live RTSP camera. It's possible when you click the advanced button that it opens the session with ffmpeg and it will start downloading from that moment. Except flyleaf's main MaxBufferDuration config there is another in ffmpeg that you could mess arround.

**Comment by apeteira** [comment]
Hi @SuRGeoNix  I will try to explain you my need to see if i can use your  library for this purpose.
I'm making a speed radar app. when the app start i need to  connect to RTSP camera open session  and start saving the video to buffer , when speed triggers happens i need to save the video to a file (5 seconds before trigger) and when the trigger is lost i must stop saving to file after 5 second the trigger is gone .
with the download sample when i cliclk the advanced button you  open the rtsp  session and save the video somewhere but where? 
Can you give me some guidance if i can use your library for this  purpose .
thanks in advance

**Comment by SuRGeoNix** [comment]
Here is a very basic sample @apeteira 

```csharp
using FlyleafLib.MediaFramework.MediaContext;
```

```csharp
Downloader downloader = new Downloader(new Config());
//string error = downloader.Open(@"c:\root\dev\flyleaf\videosamples\0.mp4"); // 1. Opens default audio/video streams
string error = downloader.Open(@"c:\root\dev\flyleaf\videosamples\0.mp4", true, false, false); // 2. Opens only the first playlist item with no audio/video streams (blocks)
if (error != null)
	System.Diagnostics.Debug.WriteLine($"Open failed ({error})");

downloader.DecCtx.OpenVideoStream(downloader.DecCtx.VideoDemuxer.VideoStreams[0], false); // 2.1. Opens first video stream with no default audio (no required if we initially open with defaults)

downloader.DownloadCompleted += (o, e) => { System.Diagnostics.Debug.WriteLine($"Download " + (e ? "completed" : "failed")); };

string filename = @"c:\root\t700"; // No extension, it's safer to let the library to choose the right extension
downloader.Download(ref filename); // Async call (no blocking) should subscribe to DownloadCompleted event for results
System.Diagnostics.Debug.WriteLine($"Filename (including the extenstion) {filename}");
```

The problem with your case/requirement is that you need to actually cut a video. There is a possible way to do exactly what you want with the current flyleaflib's implementation but it might be complicated. You will need to create a custom Decoder Context and a custom Remuxer. You will use a buffer duration of 10 seconds and you will monitor it when it reaches 6 seconds you will remove from the packet queue 1 second. This way you will keep the buffer always at 5 seconds.

When the trigger happens you will change the Buffer Duration to something large as you will stop it manually when the trigger stops + 5 seconds. Then  you save the packets with your custom remuxer. And you start over again.
