### ISSUE TITLE
Could we have an option or config to save / remember window size ?

### ISSUE THREAD

**Issue by techfisha** [SuRGeoNix/Flyleaf#164]
For example, whenever i open a file, the  window autofit to 80% of  the monitor screen.

**Comment by SuRGeoNix** [comment]
Hi @techfisha, I guess you are talking about the sample version. I'm planning to code a proper player application and then we can discuss about that when it is ready. Sample version is just sample for now and not a proper player just to demonstrate the abilities of the library and WPF control.

**Comment by techz1** [comment]
Thank you for your reply, I am looking forward to the birth of the new player.

**Comment by SuRGeoNix** [comment]
I just started coding it. It's gonna be huge but hopefully soon available ;)
