### ISSUE TITLE
The function pan and zoom  perform different under engine D3D11 and Flyleaf

### ISSUE THREAD

**Issue by swimfish09** [SuRGeoNix/Flyleaf#166]
Use master code pan and zoom perform different under engine D3D11 and Flyleaf. Under  engine Flyleaf  the function is right.

**Comment by SuRGeoNix** [comment]
Can you more specific so I will reproduce the issue? Zoom with a quick test looks exactly the same.

**Comment by SuRGeoNix** [comment]
OK. I see now, these calculation (move/zoom including aspect ration) are really difficulty with D3D11. I will give it another try and at least I will fix the access violations when you go out of the window.
