### ISSUE TITLE
UDP Network Stream ?

### ISSUE THREAD

**Issue by tomvdb** [SuRGeoNix/Flyleaf#168]
Hi There,

I'm developing some satellite video software for amateur radio. I've done the project originally with vlc libraries, but am keen to try out your library instead. Does it support playing a UDP stream? In VLC i would open this stream as udp://@:4001 for example. I tried it on your compiled demo player but no luck (it did however play a video file). 

Maybe I missed something, or alternatively your library might not support it.

Thanks,
Tom

**Comment by SuRGeoNix** [comment]
Hi @tomvdb,

It does support any FFmpeg valid input so you should not have any issues. But if you do have any, I will try to fix it asap. I'm not sure if that is a valid URL for shouldn't be udp://localhost:4001? Try to enable logging as well to see what is going on. I could give help you if you decide to integrate.

Regards,
John

**Comment by tomvdb** [comment]
Hi John,

Yes, you are right. udp://localhost:4001 seems to work just fine. Did a few tests and its working fine. I'm going to integrate it into my app and do some more tests. Will let you know if any issues. 

(1) I believe I will be able to record the received stream to file ?
(2) Is it possible to have multiple players in a single app ?

![2022-06-21 09_28_11-Flyleaf v3 5 2](https://user-images.githubusercontent.com/1420347/174741555-eed09768-e23a-4654-bf12-1edd81b79992.png)
 
Will keep you updated if you are interested. 

Thanks,
Tom

**Comment by tomvdb** [comment]
ok, just another update, playing is working just fine, but can't seem to record anything. When I toggle recording it creates a file in the recordings folder, but its only a few bytes, and essentially unplayable.

Here is the logfile
[longmyndlog.txt](https://github.com/SuRGeoNix/Flyleaf/files/8947521/longmyndlog.txt)

And i've attached the output file. Let me know if you need specific info, or if I have missed anything.



https://user-images.githubusercontent.com/1420347/174765701-e25425b1-ec96-4cff-80ba-1e0f69d10da9.mp4

**Comment by SuRGeoNix** [comment]
Hi @tomvdb, you can use multiplayers and you can download/record (it is actually a remuxer, not transcoder which is faster/better performance but is possible that some formats are not supported).

Your problem with the recording was an issue with TS formats which is should be fixed at latest nuget packet. I would recommend you to clone the solution and start doing the tests there as the sample versions is not always at the latest commit. You can also force the record file with the .ts extension to ensure that you will not have issues.

**Comment by SuRGeoNix** [comment]
Just updated the sample version as well so you can test the recording for the TS and let me know if it works!

**Comment by tomvdb** [comment]
Hi John,

Not having any luck recording in my own app. Using the latest nuget package. It still creates an empty file. I'm using the following basic code to test. Also creating same empty file in recordings folder if I use the Ctrl-R shortcut

`using FlyleafLib;
using FlyleafLib.MediaPlayer;

namespace longmynd_client_ffmpeg
{
    public partial class Form1 : Form
    {

        public Player Player { get; set; }
        public Config Config { get; set; }


        public Form1()
        {
            InitializeComponent();

            EngineConfig test = new EngineConfig();

            Engine.Start(new EngineConfig()
            {
                LogOutput = "c:\\temp\\longmyndlog.txt",
                LogLevel = LogLevel.Trace,
                FFmpegLogLevel = FFmpegLogLevel.Trace,

                PluginsPath = ":Plugins",
                FFmpegPath = ":FFmpeg",
            });

            // Prepares Player's Configuration
            Config = new Config();

            // Initializes the Player
            Player = new Player(Config);

            Player.Control = flyleaf1;
        }

        private void Form1_Load(object sender, EventArgs e)
        {
            Player.OpenAsync("udp://127.0.0.1:4003");

        }

        private void button1_Click(object sender, EventArgs e)
        {
            string filename = "test.ts";

            Player.StartRecording(ref filename, true);
        }

        private void button2_Click(object sender, EventArgs e)
        {
            Player.StopRecording();
        }
    }
}`

One thing that I did notice is that even with the new nuget package it wants the older ffmpeg files, and not the new ones in your latest flyleaf player sample. For example it wants avcodec-58.dll and  not avcodec-59.dll

I should probably create a new issue rather than commenting on this closed one :p

Trace debug also added. 

[longmyndlog.txt](https://github.com/SuRGeoNix/Flyleaf/files/9008286/longmyndlog.txt)

**Comment by SuRGeoNix** [comment]
Hi @tomvdb,

Your code looks fine. Tested my self and it works ok with a .ts input. (By the way don't use "test.ts" just "test" as it will add ".ts" for you). Does this work fine with the sample version but not with your code (I thought you said at prev post that it was working)?

If you want to use ffmpeg v5 you will need to to add to your application FFmpeg Autogen 5 (nuget package) and link properly to ffmpeg 5 libraries from engine.start(). (I know this is not very clear yet I will add it in README/Wiki)
 
Regards,
John

**Comment by tomvdb** [comment]
Apologies, it seems like it does work, but very dependent on what the input stream is. ie, my app gets the udp feed from tuner, but based on who is transmitting and in what format it records for some, but for others it doesn't. I'll do some more experimentation and see if I can get back with more details. They all play fine.

T

**Comment by tomvdb** [comment]
It seems to be related to the audio codec. Most of the streams are aac, but the beacon on the satellite for example uses mp2 (according to player.audio.codec) and it doesn't record that stream. So far the others are fine. Not sure if that helps you

btw - are there any functionality for overlay on the video stream from winforms (that will also work in fullscreen)

**Comment by SuRGeoNix** [comment]
Hi @tomvdb,

You will need to ensure that this is indeed an issue with the FlyleafLib and not with your code. So, ensure that the sample version cannot record it. It sounds possible that TS cannot handle the mp2 codec but I will need you to validate this first. In some cases, I use mp3 instead of mp2 codec as it has a number of issues with ffmpeg. I might need to include your case as well. Check if you get any error message in logs for that.

The problem with WinForms is that they don't support true transparency and they have a number of issues with overlay. You can check Flyleaf's v2.x branch and see the sample version there. It was using a transparent front window as well. But that was only for a label (for subtitles). It had issues as well.

If you re-design/re-coding your app generally you should consider switching to WPF maybe?

**Comment by SuRGeoNix** [comment]
One more thing, to validate if the problem is the mp2 you can disable the audio stream (shift+a) and then record. I'm trying to test as well now.

**Comment by tomvdb** [comment]
Hi John,

Here is what I tested from my side:

(1) Does not record with or without sound (using shift-A)
(2) Can also confirm that specific video feed doesn't record in your sample app either
(3) I let it run (record) for 10 minutes, but didn't make a difference
(4)

`            string _filename = "test_recording.mkv";
            Player.StartRecording(ref _filename, false);
`
creates the mkv file but also not playable.

So, not sure what else to try. I guess it could be a issue in my code, but its just the start and stop recording commands that work on all the other streams, so not sure what I could be doing differently for that specific one.

Don't have much experience wit wpf, but will have a look at it as well. The overlay isn't that important, i'm just doing tests to see how it compares against the vlc libraries and what else I can do with it.

![image](https://user-images.githubusercontent.com/1420347/177618248-86402a19-1189-437b-9d22-5734ada39a0a.png)

Its been playing all the streams on the satellite so far and recording then, except for the beacon (its playing the beacon just fine though)

Don't worry to much about recording the beacon issue though as there is no real interest to record that :p

**Comment by SuRGeoNix** [comment]
Yes, there is nothing complex with this code so I guess it's not your code but Flyleaf or FFmpeg's issue. My problem is that I cannot reproduce it. I guess I will leave this for now as it is not urgent for you and if another complains I will look deeper in to it.
(There is an ffmpeg issue with timestamps after ~13 hours of streaming so I was thinking if it has anything to do with that but probably not)

**Comment by SuRGeoNix** [comment]
@tomvdb Just remembered that is possible to add a WPF control to WinForms. I did that with Flyleaf's WPF Control and it was working pretty good (it is included in the samples). So you could create a WPF Control just for the overlay and the video view and then just added to your WinForms project.
