### ISSUE TITLE
Recording to MP4

### ISSUE THREAD

**Issue by pubpy2015** [SuRGeoNix/Flyleaf#169]
Hi,

In case of video stream has PCM audio, Is there any way to record to MP4 instead of MKV ? (eg: only record video, not audio)

![ảnh](https://user-images.githubusercontent.com/59004953/176084521-fcda932e-e990-4d25-be8d-437385e032e7.png)

**Comment by SuRGeoNix** [comment]
It will depend on video format then. But if it supports the video codec yes. You can force it with .mp4 extension and make sure you disable audio during recording. It could be done with transcoding which I have not implemented yet.

https://en.wikipedia.org/wiki/Comparison_of_video_container_formats
