### ISSUE TITLE
Is there any method not clear last video frame?

### ISSUE THREAD

**Issue by swimfish09** [SuRGeoNix/Flyleaf#171]
Is there any method not clear last video frame before open a new video stream?

**Comment by SuRGeoNix** [comment]
Two ways:-

1)

```csharp
Player.Stop();
```

2)

```csharp
Player.Pause();
Player.renderer.DisableRendering = true;
Player.renderer.Present();
```

**Comment by SuRGeoNix** [comment]
You can use an Image and save the last frame to bitmap before disposal. Set your Image visibility with a binding when the Player.Status is Opening

**Comment by SuRGeoNix** [comment]
@swimfish09 I've just added Config.Video.ClearScreenOnOpen for this. However, you might want to use two players and when you open a new input you open it on the second one and when the open completes you swap them.
