### ISSUE TITLE
Audio become noise when open multi streams

### ISSUE THREAD

**Issue by swimfish09** [SuRGeoNix/Flyleaf#172]
Use latest master code.
1. Open more than 12 streams  and set audio mute to true.
2. Choose one stream and set mute to false
3. The audio become noise.
The same as issue [Internal player stutters above approx 12 streams](https://github.com/robvdpol/RaceControl/issues/455) mentioned.

**Comment by SuRGeoNix** [comment]
Hi @swimfish09, I will try to have a look on this one. Can you validate that this is not a hardware issue? Eg. high CPU, high GPU, RAM/VRAM? Or even better, can you test with another application that it can handle 12 streams properly?

**Comment by SuRGeoNix** [comment]
Just did a quick test without any issues with my GPU: RX 580 (8GB) and CPU: Ryzen 7 2700X (8 core)

30 Players with low quality
16 Players with 1080p (93% GPU)

No frames or audio samples were dropped even in debug mode. It doesn't seem to be a threading issue but a hardware. Eg. a CPU with few cores (eg. 2) will not be able to handle too many threads especially when the Video Acceleration fails. It could also be a GPU with not enough VRAM.

**Comment by swimfish09** [comment]
I'll try with libvlc soon.

**Comment by swimfish09** [comment]
Yes  it is  a hardware issue, with high CPU and GPU usage.
