### ISSUE TITLE
System.DllNotFoundException

### ISSUE THREAD

**Issue by sergiorpires** [SuRGeoNix/Flyleaf#174]
When I run a project with .NetFramework 4.8, I receive the following:
System.DllNotFoundException: 'Unable to load DLL 'avformat.58 under D:\Flyleaf\FFmpeg': The specified module could not be found.'.
It runs ok with .Net 6, the original example, but can't find dll's when running over .Net Framework 4.8.
What has to be done?

**Comment by SuRGeoNix** [comment]
This is FFmpeg.Autogen's issue, I will open an issue there

**Comment by SuRGeoNix** [comment]
No, this is x86/x64 in-compatibility. You use x64 libraries while your application runs as x86. Go to your Project Properties -> Build -> Unmark Prefer 32-bit. Or you can just add manually 32bit ffmpeg libraries if you want to run on x86.
