### ISSUE TITLE
how to continuous snapshot

### ISSUE THREAD

**Issue by pubpy2015** [SuRGeoNix/Flyleaf#175]
Hi,

I created a timer with interval 300ms for take snapshot from video stream (frame rate of video stream is 25 fps).
![ảnh](https://user-images.githubusercontent.com/59004953/178095722-786cc8e0-61a9-4aa6-9d87-448cf67e9fa6.png)

There is an error here:
![ảnh](https://user-images.githubusercontent.com/59004953/178095757-d812a7a3-64b9-42ce-837e-cc70968be154.png)

Can i convert VideoFrame to Bitmap without render ? (I see you call PresentOffline when GetBitmap)

**Comment by SuRGeoNix** [comment]
There is a bug with GetBitmap. It should check the LastFrame if null after the lock Device. I will fix and improve it in the next update.

**Comment by pubpy2015** [comment]
Thanks,

It works fine!
