### ISSUE TITLE
Is there a way to rotate the video stream? 

### ISSUE THREAD

**Issue by axelalex13** [SuRGeoNix/Flyleaf#176]
Some videos (especially those recorded with a phone) have a wrong orientation and I want to be able to change that or to ignore the rotation tag from video metadata. Is there any way to achieve that?

**Comment by SuRGeoNix** [comment]
Unfortunately, this is not supported yet. I will try to include it on the upcoming versions.

**Comment by t3therdev** [comment]
Hi @SuRGeoNix any update on this request to be able to rotate the stream?

**Comment by SuRGeoNix** [comment]
@t3therdev That was long ago, both stream rotation from codec parameters and user's custom Player.Rotation have been implemented. Do you have any issues with that?

**Comment by SuRGeoNix** [comment]
@t3therdev Just use Player.Rotation = [angles]

**Comment by t3therdev** [comment]
@SuRGeoNix it seems rotation is ok but what about flip/mirror? the same commands that would be from ffmpeg transpose for example?

**Comment by SuRGeoNix** [comment]
@t3therdev Let me know if that's what you wanted

**Comment by t3therdev** [comment]
@SuRGeoNix yes that works! Thanks! Can you please include it in a relase/nuget for us?

**Comment by SuRGeoNix** [comment]
@t3therdev It's published

**Comment by eliacanavera1111** [comment]
> @t3therdev That was long ago, both stream rotation from codec parameters and user's custom Player.Rotation have been implemented. Do you have any issues with that?

Hi, the rotation tag in video metadata is causing bugs sometimes, is there a command just to ignore it?

**Comment by SuRGeoNix** [comment]
Hi @eliacanavera1111, you could probably check the VideoStream.Rotation and then use the -VideoStream.Rotation?

**Comment by SuRGeoNix** [comment]
@eliacanavera1111 I would be interesting if v3.8 fixed that issue for you

**Comment by eliacanavera1111** [comment]
> @eliacanavera1111 I would be interesting if v3.8 fixed that issue for you

It took a while because I had to upgrade to .Net 8, but No it didn't fixed my specific issue, which is occasional visual artifacts on the player, like a random zoom or rotation on the video with an orientation metadata not set to top-left.
I can't tell if it's only on my ReplicaPlayer or also on the main player, because I'm rewriting that part about mirroring so I can't test appropriately for now, anyway I "solved" by re-exporting that video to have the right orientation metadata.

**Comment by SuRGeoNix** [comment]
@eliacanavera1111 Thanks for testing. I though that the video had the right metadata and it was an issue with Flyleaf.
