### ISSUE TITLE
Frame delay

### ISSUE THREAD

**Issue by pubpy2015** [SuRGeoNix/Flyleaf#18]
Hi,

I am using your code to display live stream from IP camera (rtsp url). It's work fine but not realtime. Compare with VLC, your program delay about 1 -> 3 seconds.
How to avoid this ?

![ảnh](https://user-images.githubusercontent.com/59004953/102471919-57574880-4088-11eb-9883-ae4f25b7d146.png)

**Comment by SuRGeoNix** [comment]
Hey,

I would try to use less video queues (min/max) and also i would review the format options (during open format context), both the existing once but also the the options from ffmpeg for rtsp. Two seconds are too many, i dont think the problem are the queues tho. Probabaly, rtsp option for format context.

**Comment by SuRGeoNix** [comment]
If it still happens with the new version, let me know if you have an easy way for me to test it!

**Comment by pubpy2015** [comment]
Hi,

Now your program very good.
delay 0.5 second with VLC and 1.2 second compare with video source.

![ảnh](https://user-images.githubusercontent.com/59004953/111251459-df2a0000-8641-11eb-8f45-020cb9b417de.png)

**Comment by pubpy2015** [comment]
I think you shoud split Flyleaf to 2 projects for easy maintenance, monitor change and can be using your FlyleafMediaFramework in other projects
- 1 project is FlyleafMediaFramework, include video decoder, renderer,....
- 1 project is Flyleaf user control, player setting,...

**Comment by SuRGeoNix** [comment]
Nice, we got them 😄 As you play on network (rtsp) streams you might want to try for faster opening to remove or reduce the values on the Demuxer.cs

```
av_dict_set_int(&opt, "probesize", 116 * (long)1024 * 1024, 0);
av_dict_set_int(&opt, "analyzeduration", 333 * (long)1000 * 1000, 0);
```

I know, I finally found some time to re-code the MediaDecoder but still has a lot of organize/clean up work to be done!
