### ISSUE TITLE
Calling Player.Pause () causes the video to end.

### ISSUE THREAD

**Issue by freeproa** [SuRGeoNix/Flyleaf#180]
Calling Player.Pause () causes the video to end.

**Comment by SuRGeoNix** [comment]
I guess that happens only with a specific video. Does this work with other players? Can you send me a sample to reproduce it?

**Comment by freeproa** [comment]
Sorry. My mistake.  I subscribed to Player.OpenCompleted and didn't check Status.

**Comment by freeproa** [comment]
.....of course Player.PlaybackStopped
