### ISSUE TITLE
Syncing multiple players

### ISSUE THREAD

**Issue by seafraf** [SuRGeoNix/Flyleaf#181]
Hello, I have the requirement of playing multiple audio streams from the same video at once, as suggested [here](https://github.com/SuRGeoNix/Flyleaf/issues/154#issuecomment-1126790010), I am using multiple media players to do this.

My method of synchronization currently is to SeekAccurate all audio players just before the video is played, this method seems to work sometimes but sometimes slight delays occur.  I am assuming that SeekAccurate is not instant and doing:

```csharp
Audio1.SeekAccurate(Video.CurTime)
Audio2.SeekAccurate(Video.CurTime)
Audio1.Play()
Audio2.Play()
Video.Play()
```

Is semantically wrong because SeekAccurate is not blocking/instant.  Is that right?  How would you synchronize multiple players?

Thanks in advance.

**Comment by SuRGeoNix** [comment]
Hi @seafraf, it's not possible to sync multiple players. Even if you initially sync them, they might loose sync after some time. Especially for live stream that seems impossible as they might have same timestamps but actually differ from the UTC time.
