### ISSUE TITLE
It does not recognize DLL files

### ISSUE THREAD

**Issue by ZCOREP** [SuRGeoNix/Flyleaf#182]
i install this https://www.nuget.org/packages/FlyleafLib.Controls.WPF and It doesn't work when I get the msix output of the program.
It seems that it does not recognize the dll files!! 
What should i do ?

**Comment by SuRGeoNix** [comment]
There is no issue with the package. Probably you are doing something wrong. If you provide more info I might be able to assist you.

**Comment by ZCOREP** [comment]
did you test it? when i create msix package ,
It seems that it does not recognize the dll files.

**Comment by ZCOREP** [comment]
[VideoPlayer.zip](https://github.com/SuRGeoNix/Flyleaf/files/9438164/VideoPlayer.zip)
this is my repo, test it

**Comment by SuRGeoNix** [comment]
I've not use msix for a long time now. I don't think there is an issue with Flyleaf's package but with the configuration of the msix project. I will try to confirm this on the next update.

**Comment by ZCOREP** [comment]
thanks

**Comment by SuRGeoNix** [comment]
I just tried to create the msix package and worked fine for me. So I guess your issue is with the msix configuration.

**Comment by ZCOREP** [comment]
I sent you my project,
can you help me please?
what did you do!?
can you please send me your repo?

**Comment by SuRGeoNix** [comment]
I just used a custom certificate and then right click on msix project-> Publish -> Create App packages

**Comment by SuRGeoNix** [comment]
I have not changed anything. So, probably you have an issue with VS and configuration. Cannot help much with that. Can you generally generate msix?

**Comment by ZCOREP** [comment]
i can generate MSIX for all my projects.
the problem is just with your project and your nuget package!

**Comment by SuRGeoNix** [comment]
Can you attach a screenshot and more details what and when you get the error?

**Comment by ZCOREP** [comment]
I did not got any error!
when i create MSIX packages
and the install it.
the Video player is not work,

**Comment by ZCOREP** [comment]
![image](https://user-images.githubusercontent.com/109096904/187650803-931582d1-c849-49d1-9895-16ecb967454f.png)

look at this pic please.


Directory.GetFiles(System.IO.Path.GetDirectoryName(System.Reflection.Assembly.GetEntryAssembly().Location) + "\\FFmpeg");
and its my FFMPEG Folder

**Comment by SuRGeoNix** [comment]
I still try to see the error msg dude... check the first run log of flyleaf if it executes... otherwise the windows event logs

**Comment by SuRGeoNix** [comment]
Just checked the installation and worked fine for me. Not sure what your app does (didnt check) but it runs.

**Comment by ZCOREP** [comment]
it can run but the player is not work

**Comment by SuRGeoNix** [comment]
Your problem is that it will not install the ffmpeg folder. So make sure you configure it the right way.

**Comment by ZCOREP** [comment]
install the ffmpeg folder? how ?

**Comment by ZCOREP** [comment]
Hi , Can you help ?

**Comment by SuRGeoNix** [comment]
@ZCOREP not really, this nothing to do with Flyleaf, you just need to include the ffmpeg folder on your msix which will finally place it in windows apps folder after the installation as well.

**Comment by ZCOREP** [comment]
should i add my folder in app solution or packing ?

**Comment by SuRGeoNix** [comment]
You need to do whatever msix requires to ensure the ffmpeg folder (that you configure with flyelaf's engine) will exist at that destination (in your case under installation folder/ffmpeg

**Comment by ZCOREP** [comment]
can you send me your repo with msix ?

**Comment by ZCOREP** [comment]
engineConfig.FFmpegPath = System.IO.Path.GetDirectoryName(System.Reflection.Assembly.GetEntryAssembly().Location)+"\\:FFMPEG";

is this correct ?

**Comment by ZCOREP** [comment]
![image](https://user-images.githubusercontent.com/109096904/188568935-8e61c49c-d35c-42dd-bf9d-e1a6595fb0e2.png)
look i get it error

**Comment by SuRGeoNix** [comment]
does the folder exists?
does the app have permission to that folder?
did you try to run as administrator to see if that works?

**Comment by SuRGeoNix** [comment]
WindowsApps have very special permissions (with trustedInstaller or something like that). Might not easy for you to see what is going on. Not sure if that MSIX allows you to install it in program files for example to avoid all that mess.

**Comment by ZCOREP** [comment]
yes the folder is exist.
what permission ?

**Comment by ZCOREP** [comment]
so whats your suggestion ?

**Comment by SuRGeoNix** [comment]
Your issue is with the permissions of the application to the ffmpeg folder then. I cannot support you further with the VS MSIX and windowsapps installation as I'm not that familiar.
