### ISSUE TITLE
Config.Video.BackgroundColor Auto refresh rendering

### ISSUE THREAD

**Issue by cxgym** [SuRGeoNix/Flyleaf#183]
Config.Video.BackgroundColor = (System.Windows.Media.Color)System.Windows.Media.ColorConverter.ConvertFromString("#333333");
I tried to set the background color, but when I enlarge the window, the following image will appear:

**Comment by cxgym** [comment]
fullScreen window can not Auto refresh ackgroundColor to full fill

**Comment by SuRGeoNix** [comment]
Hi @cxgym, indeed this is happening with WPF control because it will load the default themes. You could use the UIConfig for load/save the configuration (includes the themes/backcolor)

**Comment by cxgym** [comment]
ok, thank you very much

**Comment by SuRGeoNix** [comment]
I've included ThemeLoaded event on WPF control so you can listen to that event and change the config after the themes are fully loaded eg:-

```
flyleafControl.ThemeLoaded += (o, e) => playerConfig.Video.BackgroundColor = (System.Windows.Media.Color)System.Windows.Media.ColorConverter.ConvertFromString("#333333");
```
