### ISSUE TITLE
Memory Leak while GetBitmap

### ISSUE THREAD

**Issue by thanh-repo** [SuRGeoNix/Flyleaf#184]
Hi,

Hope you are doing well.

I am using FlyLeaf to extract frame of the **rtsp** stream video. I used Task with while loop to execute **GetBitMap** function. The memory increase dramatically while the Task is running.

```
private void Window_Loaded(object sender, RoutedEventArgs e)
{
    ...
    Player.OpenAsync("rtsp://...");
    Task.Run(() =>
    {
        ExtractFrame();
    });
}
```
With the void with async, the memory increases slower than without async method.
Extract function with async:
```
private async void ExtractFrame()
{
    while (true)
    {
        if (Player.Status == Status.Playing)
        {
            Bitmap Frame = Player.renderer.GetBitmap();
            if (Frame != null)
            {
                //Do something with frame;
                Frame.Dispose();
            }
        }
        await Task.Delay(500);
    }
}
```

Extract function without async:
```
private async void ExtractFrame()
{
    while (true)
    {
        this.Dispatcher.Invoke(() =>
        {
            if (Player.Status == Status.Playing)
            {
                Bitmap Frame = Player.renderer.GetBitmap();
                if (Frame != null)
                {
                    //Do something with frame;
                    Frame.Dispose();
                }
            }
        });
        await Task.Delay(500);
    }
}
```

I have reproduced the issue with local video (the same mem leak occurred) and commit at this repo:
https://github.com/thanh-repo/FlyLeaf-GetBitmap-MemLeak

Could you help me to check this issue?

Thank you!

**Comment by SuRGeoNix** [comment]
Hi @thanh-repo, I tried that with the latest (master) and the issue does not exist. I will have an updated package soon if you can't try with master now. If you still have issues let me know so I can re-open it.

**Comment by SuRGeoNix** [comment]
Just created a new package (3.5.8) so you can test it from there.
