### ISSUE TITLE
Protocol 'rtp' not on whitelist 'file,crypto,data'

### ISSUE THREAD

**Issue by mattilaiatostek** [SuRGeoNix/Flyleaf#188]
1. Start app Flyway v3.5.8 - FlyleafPlayer (WPF Control) (WPF)
2. Open the test.sdp file below

```
v=0
c=IN IP4 232.30.1.1/127
m=video 50256 RTP/AVP 35
a=rtpmap:35 H264/90000
a=source-filter:incl IN IP4 232.30.1.1 172.30.1.1
```

->
FFmpeg | Error   | [rtp @ 00000212e64f9f40] Protocol 'rtp' not on whitelist 'file,crypto,data'!
DecoderContext] [Open] C:\test\test.sdp  [Error: [avformat_open_input] Invalid data found when processing input (-1094995529)]

**Comment by SuRGeoNix** [comment]
Hi @mattilaiatostek, this affects the sample version only (I might review this on the next update). If you write your own player you can manually configure the protocol whitelist from player's configuration, eg:-

```
config.Demuxer.FormatOpt.Add("protocol_whitelist", "file,crypto,data,rtp,sdp,udp");
```
