### ISSUE TITLE
Placing controls above the Video

### ISSUE THREAD

**Issue by CapLelouch** [SuRGeoNix/Flyleaf#190]
First off, good work. Second, Is there a way to show controls above the VideoView without placing it inside it? I'm using mahapps without the titlebar and videoview covers the control buttons.

**Comment by SuRGeoNix** [comment]
Ηι @CapLelouch and thanks! You should try use a main VideoView (for you main controls) and use other VideoViews inside the main one. You should not have issues as far as you don't care about zindex of them.

**Comment by SuRGeoNix** [comment]
@CapLelouch I'm closing this but feel free to ask and I will re-open this if required.
