### ISSUE TITLE
Seek Accurate can make audio have delayed start

### ISSUE THREAD

**Issue by Brandon689** [SuRGeoNix/Flyleaf#192]
I need to use seek accurate to jump to specific timestamps of a video but sometimes the times can cause the audio to be silent for 100-1000 ms after seeking while video is playing normally. 
I understand sort of why this might happen but is there anyway to consistently do it.

**Comment by Brandon689** [comment]
I found it doesn't affect every video, some video files can never have this problem, and re-encoding a video file that has the problem into a new one removes the problem. But  I cant go and do that to hundreds of videos.

**Comment by SuRGeoNix** [comment]
I just had a look. This happens during seek accurate on decoder context's GetVideoFrame. It will demux packets but will skip audio packets until it has a video keyframe. This is how you can see this diff between audio / video. The reason of that was to avoid some issues (mainly with hls) when audio/video are not having valid timestamps after a seek request. I will review this to see if I could fix it.

**Comment by Brandon689** [comment]
Thank you. Well I'm sure you know exactly about it, my testing just made more confusion, If I take a video that suffers from this greatly, which is not most of them, then do this for clip

ffmpeg -ss 00:00:00.0 -i video.mkv -c copy -t 00:20:15.0 -map 0:v:0 -map 0:m:language:jpn output.mkv

Then the resulting video doesn't have silence at the same timestamp, and I could not make it fail at any timestamp I tried.

There might be a problem with some of my video files, that isnt the fault of Flyleaf player.

**Comment by SuRGeoNix** [comment]
I have found the issue, GetVideoFrame uses frame instead of packet to check for audio/subtitles packets timestamps which is wrong. I will create a new commit soon. Nice finding!

**Comment by Brandon689** [comment]
Uh okay, that's good to hear. You did all the work but thanks.
