### ISSUE TITLE
This line will make D3D11VideoProcessor disabled and VideoAcceleration always false

### ISSUE THREAD

**Issue by afunc233** [SuRGeoNix/Flyleaf#196]
This line will make D3D11VideoProcessor disabled and VideoAcceleration always false。
I try ffmpeg v5

and if delete this line , It works fine

https://github.com/SuRGeoNix/Flyleaf/blob/d58f045ab95419d970d04c4fd18e8502f1f2036b/FlyleafLib/MediaFramework/MediaDecoder/VideoDecoder.cs#L68

![image](https://user-images.githubusercontent.com/19919631/192281158-bce50943-2c72-41f8-b99e-78c3c28d5808.png)

This confuses me

**Comment by afunc233** [comment]
in my build

ffmpeg.autogen version 4.4.1 
` (int)AVPixelFormat.AV_PIX_FMT_D3D11  = 174 `

ffmpeg.autogen version 5.0.0 +
` (int)AVPixelFormat.AV_PIX_FMT_D3D11  = 172  `
so it's unnecessary to -2 .

 but in your build  it same 174 .

**Comment by SuRGeoNix** [comment]
Where did you install FFmpeg.Autogen v5? You should install it at your application and not upgrade the flyleaf's library v4 package.

**Comment by afunc233** [comment]
thx I will try
