### ISSUE TITLE
Reduce decoding and rendering frame rate for lower resource

### ISSUE THREAD

**Issue by pubpy2015** [SuRGeoNix/Flyleaf#20]
Hi,

can i reduce decoding and rendering frame rate for lower CPU and GPU usage ? 
ex: if frame rate of video source is 30 fps, im only need decode and display at 10, 15 fps, other frames will discard.
on my old PC (core i5 2400, AMD Radeon R7 200), for display rtsp stream from IP camera, it take ~50 % GPU:
![image](https://user-images.githubusercontent.com/59004953/106764167-1d5af980-666a-11eb-814a-c1192cac838d.png)

**Comment by SuRGeoNix** [comment]
That will not be easy, mainly for decoding and IPB frames (that I - key frames are required to decode the rest and probably P/B required as well for the next frame). However, you could try using less decoding threads or disabling the GPU Acceleration (to transfer the weight to CPU). For rending it should be easier by adding a counter for example in the Screamer and present only when the counter is % 2 == 0 for example.

**Comment by SuRGeoNix** [comment]
Second thought... even if it sounds interesting how you would dynamically lower the resources to fit the hardware during decoding/rendering on flyleaf I would suggest you to have a look on the source (rtsp stream camera) and try to change the quality (codecs). You might even be able to have two different rtsp streams (high/low quality) run at the same time?

**Comment by pubpy2015** [comment]
Yes, camera have two stream. 
When open multi cameras (grid 2x2, 3x3,...) on screen, i will connect to substream (low resolution, at VGA) of each cameras. 
When open 1 camera on screen, i am only connect to mainstream (high ressolution, 720p, 1080p) of that camera and disconect to other cameras (GPU ~ 50% as image above).

Seem decoder take alot of GPU, renderer a little.
