### ISSUE TITLE
need  seek event 

### ISSUE THREAD

**Issue by afunc233** [SuRGeoNix/Flyleaf#201]
need  seek event  and  some args . 
eg:
    SeekEvent args: CurrentPos,SeekPos
or other way to tracking seek event

**Comment by afunc233** [comment]
I'm considering using flyleaf as a playback library and I want to do some when seeking

**Comment by SuRGeoNix** [comment]
You send the seek request so you can handle it there. You could use the existing BufferingStarted / BufferingCompleted for 'loading'. Be more specific if you can't handle it already with the existing implementation so I can implement it.

**Comment by afunc233** [comment]
You mean, when I call seek, I record it myself or use BufferingStarted / BufferingCompleted ?

**Comment by SuRGeoNix** [comment]
I need you to explain the requirement more clear to see what I can do about it (if you can't use the existing implementation)

**Comment by afunc233** [comment]
i need more try. thx again. 
if need your help i will re-open this
:)
