### ISSUE TITLE
add d3d9 support 

### ISSUE THREAD

**Issue by swimfish09** [SuRGeoNix/Flyleaf#202]
Hi @SuRGeoNix ,I want to add d3d9 support for Flyleaf, Is there any available suggestion?

**Comment by SuRGeoNix** [comment]
Well there a lot of things to consider. I'm not even sure if Vortice supports it. So first you need to ensure that it does before you try to implement it.

You will need to update Renderer and VideoDecocer to support DirectX 9 with DXVA2 (AV_HWDEVICE_TYPE_DXVA2). Review the hardware formats and surface support (swap chain and I think it does not support DXGI_FORMAT_R8G8_UNORM so you will need to implement the NV12 with a different way)

Just to be clear, I was never plan to support D3D9 as it is too old and I don't see a reason to make the library more complex.
