### ISSUE TITLE
SwapPlayer Error

### ISSUE THREAD

**Issue by thanh-repo** [SuRGeoNix/Flyleaf#204]
Hi, 

I am using FlyLeaf to display multiple video views on WPF.
My idea is that I have 2 TabControl, the first tab is 1 video view, the second tab contain 4 video views on WPF Grid. When I click to Swap Button on the 4 views tab, the program swap player to the single view. 

Swap Command:
`Player.SwapPlayers(PlayerSingle.Player, Player00.Player);` 
As the debugger, the Control in Renderer class was null.

![image](https://user-images.githubusercontent.com/37483861/194838575-b3c0cce1-d3af-461a-b139-58ceedc2e087.png)

I have reproduced the error as the project named "SwapError" in my repository.
https://github.com/thanh-repo/FlyleafMinimize

Could you please help me to check this error?

Thank you~

**Comment by SuRGeoNix** [comment]
Hi @thanh-repo, the issue is that your player single has not been initialized properly because is hidden (it didn't apply the template). Let me review this and I will come back to you...

**Comment by SuRGeoNix** [comment]
Try to use Grid instead of tab control. It should work fine. However, I will review this in the next update to see how to handle this better!

**Comment by thanh-repo** [comment]
> Try to use Grid instead of tab control. It should work fine. However, I will review this in the next update to see how to handle this better!

Hi @SuRGeoNix, Thank you for your help.

Do you have any idea to use Grid with the approach? Is there anything can be used instead of TabControl?

I cannot imagine how can I apply Grid to my idea...

**Comment by SuRGeoNix** [comment]
Did you check the FlyleafMultiplayer under Tests in the solution? Ideally, I would use the Single player at the MainWindow and I would manually create the players in the Front Window of the Single player. I might use a sample for that to help you.

**Comment by SuRGeoNix** [comment]
[SwapError.zip](https://github.com/SuRGeoNix/Flyleaf/files/9746965/SwapError.zip)
Here is a quick sample from the idea described above

**Comment by SuRGeoNix** [comment]
Hey @thanh-repo, I've updated the VideoView so it will initialize the controls early on even if the template has not been initialized yet. Have a look and let me know if that works ok with you now.
