### ISSUE TITLE
Reduce frame delay

### ISSUE THREAD

**Issue by pubpy2015** [SuRGeoNix/Flyleaf#205]
Hi,

I am testing Flyleaf on 2 PCs:
On my PC window 10 with RTX 2080 super, it's realtime but on Server with RTX 4000 the frame delayed. If run for long time, delay time will be increase.

In Renderer.cs
![ảnh](https://user-images.githubusercontent.com/59004953/195249177-cb063ae4-dd4b-46e7-ac98-f74002ea0a52.png)

Can i modify to if (Monitor.TryEnter(lockDevice, 2)) for decrease the delay time ?

**Comment by SuRGeoNix** [comment]
This is probably nothing to do with your issue (this is 5 milliseconds). Can you run a trace log, that might help to spot what exactly causes the delay. I'm planning to update the low latency screamer (that's the one that you use right?).

**Comment by SuRGeoNix** [comment]
I have added a new low latency screamer mainly for cameras which supports audio as well.
It will not drop any frames for now but it will not keep the frame rate either to ensure zero latency.
I will review this, let me know your thoughts, I might just increase the speed.
Could cause some high GPU as it will render too fast sometimes.

https://github.com/SuRGeoNix/Flyleaf/commit/d8737f2beece5bb853697833bfe4aec5f70ac987

**Comment by pubpy2015** [comment]
Thanks,

May be problem is:
![ảnh](https://user-images.githubusercontent.com/59004953/195496712-9b4713d6-2e66-4208-abc3-ea1bfa5c521d.png)

Flyleaf select first Adapter as default => VA disable => delay.
After disable integrated VGA card, it works fine.
![ảnh](https://user-images.githubusercontent.com/59004953/195497326-8bdf5604-86b8-41e6-ab01-cd01b8cf5ffd.png)

Can i add code bellow for select NVIDIA as default ?
if (adapter == null)
                        {
                            for (int adapterIndex = 0; Utils.Factory.EnumAdapters1(adapterIndex, out adapter).Success; adapterIndex++)
                            {
                                Log("select default NVIDIA VGA card: " + adapter.Description1.Description);

                                if (adapter.Description1.Description.ToUpper().Contains("NVIDIA"))
                                    break;

                                adapter.Dispose();
                            }
                        }

Is any tip for enhanment video decoder in case of VA disable ? (my server: CPU Xeon Silver 4312 12 core 24 thread)
![ảnh](https://user-images.githubusercontent.com/59004953/195498132-f7ec251c-1706-4d1b-beed-f5cec8b45247.png)

**Comment by SuRGeoNix** [comment]
Glad you resolve it. You can either change the user's configuration and have Config.Video.GPUAdapter=NVIDIA or change your code (you have a fork of flyleaf right?) to select the default GPU Adapter in a different way (eg. exclude WARP devices and chose what left, if more than one, the one with the largest VRAM).

For non-hardware accelerated you could try to use less/more decoder threads and see if that has a difference (Config.Decoder.VideoThreads). You can check also SwsHighQuality if you want to increase the quality. However, if we talk about 16-bit depth or non-YUV encoded data then Flyleaf will really strangle to handle it (and probably any other media player).
