### ISSUE TITLE
rtspt:// is not supported

### ISSUE THREAD

**Issue by gaurav-raheja** [SuRGeoNix/Flyleaf#207]
in a live IP camera stream if we use rtsp:// address it uses UDP protocol by default. In this case, if network in big, player shows bad frames. To avoid bad frames, we use rtspt:// This switches stream to TCP protocol which doesnt show bad frames. 
This player is not supporting rtspt:// URL.

**Comment by SuRGeoNix** [comment]
Player's default Config.FormatOpt has this entry:-

```
defaults.Add("rtsp_transport",      "tcp");                                     // Seems UDP causing issues (use this by default?)
```

So FlyleafLib by default uses tcp for rtsp. I don't know if that's a standard to use rtspt:// scheme (I could add in the future). But for now you can just use the Config.Format options if you need to change it. Check FFmpeg's [Format](https://www.ffmpeg.org/ffmpeg-formats.html) and [Protocol](https://ffmpeg.org/ffmpeg-protocols.html) for more options.

**Comment by gaurav-raheja** [comment]
Thanks for the reply.
I tried running 25 live camera RTSP stream. Its taking very less CPU. But its taking very high GPU.
As suggest by you I tried using

        
 public static SerializableDictionary<string, string> DefaultVideoFormatOpt()

      defaults.Add("framerate", "5");
          defaults.Add("video_size", "320x240");


to reduce fps and size from ffmpeg library. But its not working.

I want to display 100 cameras on a I5 4 core and Quadro P600 GPU machine


________________________________

**Comment by SuRGeoNix** [comment]
There is no point to reduce the size on client side as it will already required to decode the original size and afterwards process it. That will be even worse. You will need to configure the cameras from server side to support lower resolutions (not main channel) and the access them with the url supported by your cameras eg. /cam/realmonitor?channel=1&subtype=1.

If you have issues with the GPU you can force it to use CPU instead with Config.Video.VideoAcceleration = false.

100 cameras are too many in general to play at the same time even for a new PC. You will not to do some more lower level to be able to to handle this. The library allows you to manually decode/show frames so you might want to have a look in to it.

**Comment by gaurav-raheja** [comment]
Can you please suggest me some of the way around to reduce GPU and run 100 cameras?

I am already using minor stream. I do have a server installed on site. I can stream data from that server. Can you suggest me some good C# library that can be used to stream data from server to client.

If flyleaf is manually decoding frames and displaying, cant we use multiple instances of windows media player to display the live stream? I tried googling on it but could not find anything.

If u want to charge anything for this support, I am ready to pay your fees. Please let me know the payment details. But please help me out in this regard.

________________________________
