### ISSUE TITLE
start with link/filename in command line?

### ISSUE THREAD

**Issue by Isayso** [SuRGeoNix/Flyleaf#208]
I would like to start your player with a filename or link (with youtube DASH audio/video) from the command line.

I have a small project in my repository, a generic video link SQL archive program and right now I start local video files and youtube links with vlc. Vlc doesn't support rumble, bitchute, lbry and probably will never.

It would be nice if you can give me a hint where to modify your code to get this. (I'm not a professional programmer) 

Thanks!

**Comment by SuRGeoNix** [comment]
Hi @Isayso, I will add it in the next update. Just edit the App.xaml.cs to

```csharp
public partial class App : Application
    {
        public static string CmdUrl { get; set; } = null;

        protected override void OnStartup(StartupEventArgs e)
        {
            base.OnStartup(e);

            if (e.Args.Length == 1)
                CmdUrl = e.Args[0];
        }
    }
```
and add this to MainWindow.xaml.cs at the end of the constructor:-

```csharp
if (App.CmdUrl != null)
    Player.OpenAsync(App.CmdUrl);
```
