### ISSUE TITLE
Digital zoom option

### ISSUE THREAD

**Issue by lkinfotechai** [SuRGeoNix/Flyleaf#209]
hi is there any way to do digital zoom in this player like vlc player. right now there is only simple zoom available.

is there any option or method to do that. any clue

**Comment by SuRGeoNix** [comment]
Hi @lkinfotechai , never came across with the digital zoom, so I will review this one the next update

**Comment by SuRGeoNix** [comment]
Hey @lkinfotechai, just had a look in to it. From my understanding there is not such an optical zoom for an application (just digital). Optical zoom is for cameras while capturing a video with their lens nothing to do with the application.

So I guess, what you are asking is the interactive digital zoom that VLC has which is to zoom on specific areas. Flyleaf does that already, you can use Ctrl with mouse wheel for zooming and then Ctrl and Pan Drag to change the location of the video that you want to zoom.

So please clarify what's the feature request that you are asking and I will re-open this then.

**Comment by lkinfotechai** [comment]
hi, so i am looking for the digital zoom like VLC or interactive zoom you are saying. 2nd i want fast forward upto 64x and reverse playback upto 8x or 16x. that is i am looking for. is that possible, or any wayout to do  this.

**Comment by SuRGeoNix** [comment]
I already answer you how it is possible to do the same as VLC with 'interactive' zoom. For the speed playback it is hardcoded limit up to x16 as it will burn the GPU if you go higher. For reverse playback setting speed is not currently supported.
