### ISSUE TITLE
Select stream quality for youtube videos

### ISSUE THREAD

**Issue by graphixillusion** [SuRGeoNix/Flyleaf#21]
Hi there. I've searched around but i'm not finding anything about it: how you can select/change the resolution with youtube videos? Thank you!

**Comment by SuRGeoNix** [comment]
Unfortunately, I've not implemented yet... hopefully at the next update I will manage to add it!

**Comment by SuRGeoNix** [comment]
Just added it on v2.5.3 (on right click menu)
