### ISSUE TITLE
QTRLE Support

### ISSUE THREAD

**Issue by Sidonai-1** [SuRGeoNix/Flyleaf#210]
I just tried to open a .mov RLE with alplha channel and it shows a black screen. I tried both with ffmpeg 4 and 5 last releases. I attach a MediaInfo screenshot.
![image](https://user-images.githubusercontent.com/58334180/201376191-d30197de-d306-491a-b776-a886f15197c4.png)

latest builds of ffplay seems to play it no problem.
![image](https://user-images.githubusercontent.com/58334180/201375741-2066881d-a920-4124-9a19-1b9d9a783f1f.png)

Thanks!

**Comment by SuRGeoNix** [comment]
ΗΙ @Sidonai-1, currently the renderer does not support alpha channel, if that's the question (I'm willing to try to support it). If you don't care about the alpha channel and you just asking why it didn't work, I will need you to provide me with more information. Ideally, with the video or part of it (you can drop me an email if not here) or the flyleaf logs (from settings->general give a log path and log level to debug)

**Comment by SuRGeoNix** [comment]
OK I found an rle [here](https://github.com/openpreserve/format-corpus/blob/master/video/Quicktime/animation.mov) and I've found also the issue but I'm not sure if by fixing this will cause other issues:-

The frame->pict_type is NONE but the frame->key_frame is 1

```csharp
if (keyFrameRequired)
{
	if (frame->pict_type != AVPictureType.AV_PICTURE_TYPE_I)
	{
		if (CanWarn) Log.Warn($"Seek to keyframe failed [{frame->pict_type} | {frame->key_frame}]");
		av_frame_unref(frame);
		continue;
	}
	else
	{
		StartTime = (long)(frame->pts * VideoStream.Timebase) - demuxer.StartTime;
		keyFrameRequired = false;
	}
}
```

**Comment by SuRGeoNix** [comment]
Looks safe so I committed

**Comment by SuRGeoNix** [comment]
Hi @Sidonai-1, can you please confirm when possible that the latest version fixed the issue?

**Comment by Sidonai-1** [comment]
> Hi @Sidonai-1, can you please confirm when possible that the latest version fixed the issue?

It works now! Thanks a lot!
