### ISSUE TITLE
Question, how to use Record feature for many players without viewing the video itself?

### ISSUE THREAD

**Issue by tecno14** [SuRGeoNix/Flyleaf#211]
Hi,
Thank you for your library,

I want to know if there is a better way to record videos directly and save resources by not viewing the video in the app.

Thank you.

**Comment by SuRGeoNix** [comment]
Hi @tecno14 and you're welcome!

Yes, you can use a downloader which is just a remuxer. It will only use the demuxer and no the decoders so it will be very light.
There is a sample in the solution but if you need more help let me know. You can use one downloader for each of your players and sync the downloader with your player. 

John
