### ISSUE TITLE
Get Timpstamp from RTSP

### ISSUE THREAD

**Issue by thanh-repo** [SuRGeoNix/Flyleaf#212]
Hi,

I am using FlyLeaf to play Onvif-RTSP from camera.
Is there any option or solution to get the timestamp from the RTSP protocal.

Thanks and Best regards.

**Comment by SuRGeoNix** [comment]
Hi @thanh-repo, do you mean during playing instead of having a zero based timestamp you want the actual one of the CurTime?

If that's the case you can just add the demuxer's start time to the CurTime's timestamp (Player.MainDemuxer.StartTime)

**Comment by thanh-repo** [comment]
No, I mean the UTC time from the RTSP device.
But what is CurTime in your program?  It is not looklike the timestamp(microtick) from start demuxing?
I created the time variable inside Demuxer:
```
public unsafe class Demuxer : RunThreadBase
{
        ...
        public long StartRealTime
        private bool FillInfo()
        {
                ...
                StartRealTime= fmtCtx->start_time_realtime;
                ...
        }
        ...
}
class MainWindow
         private void MyVoid()
         {
                  long CurrentTimeTick = Player.MainDemuxer.StartRealTime+ Player.CurTime;
         }
```
Since there are some delay between video play and time in RTSP device, I use **start_time_realtime** to get current time of RTSP device.
Then add  CurTime to StartRealTime but the time is not correct as timestamp microtick.
How can I get the timetick from start demuxing to current frame data?

Thank you~

**Comment by SuRGeoNix** [comment]
You need to check the format of start_time_realtime [here](https://ffmpeg.org/doxygen/3.4/structAVFormatContext.html)

```
Start time of the stream in real world time, in microseconds since the Unix epoch (00:00 1st January 1970).

That is, pts=0 in the stream was captured at this real world time.

muxing: Set by the caller before [avformat_write_header()](https://ffmpeg.org/doxygen/3.4/group__lavf__encoding.html#ga18b7b10bb5b94c4842de18166bc677cb). If set to either 0 or AV_NOPTS_VALUE, then the current wall-time will be used.
demuxing: Set by libavformat. AV_NOPTS_VALUE if unknown. Note that the value may become known after some number of frames have been received.
```

So to convert microseconds to ticks you just need to multiple with 10

```
StartRealTime= fmtCtx->start_time_realtime * 10;
```

**Comment by thanh-repo** [comment]
Hi @SuRGeoNix ,

I don't think we need to multiple with 10 for StartRealTime since I catch almost correct time for StartRealTime.
I have reproduced the problem in this repo: https://github.com/thanh-repo/WPF-Flyleaf-Get-Realtime

![image](https://user-images.githubusercontent.com/37483861/202060347-96745b29-a718-4cb3-ad97-32eef908e831.png)

In which: 
DateTime value at the Top-Left corner is converted from `StartTimestamp + Player.CurTime`
I also raise a MessageBox to ensure `fmtCtx->start_time_realtime != AV_NOPTS_VALUE`
```
if (fmtCtx->start_time_realtime == AV_NOPTS_VALUE)
{
    MessageBox.Show("Catch AV_NOPTS_VALUE");
}
StartTimestamp = fmtCtx->start_time_realtime;
```
Then convert the StartTimestamp to DateTime, the result almost correct to RTSP device time.

I think the problem is `Player.CurTime` value, the CurTime value increase to fast to compared to microseconds in the Unix epoch.

In addition, how can I disable MouseBindings and KeyboardBindings in the current version? The config option was removed.

Could you help me to check these issue?

Thank you~

**Comment by thanh-repo** [comment]
Thank you for the realtime, that's what I want.

But as I checked in `FlyleaftHost.cs` code, there was no option to configurate mouse and keyboard.
Should I delete these things in the code to disable mouse and keyboard:
```
            Surface.Closing     += Surface_Closing;
            Surface.KeyDown     += Surface_KeyDown;
            Surface.KeyUp       += Surface_KeyUp;
            Surface.MouseLeftButtonDown
                                += Surface_MouseLeftButtonDown;
            Surface.MouseLeftButtonUp
                                += Surface_MouseLeftButtonUp;
            Surface.MouseMove   += Surface_MouseMove;
            Surface.MouseDoubleClick
                                += Surface_MouseDoubleClick;
            Surface.DragEnter   += Surface_DragEnter;
            Surface.Drop        += Surface_Drop;
            Surface.MouseWheel  += Surface_MouseWheel;
            Surface.StateChanged+= Surface_StateChanged;
            Surface.MouseLeave  += Surface_MouseLeave;
```

```
            Overlay.KeyUp       += Overlay_KeyUp;
            Overlay.KeyDown     += Overlay_KeyDown;
            Overlay.Closing     += Overlay_Closing;
            Overlay.MouseLeftButtonDown
                                += Overlay_MouseLeftButtonDown;
            Overlay.MouseLeftButtonUp
                                += Overlay_MouseLeftButtonUp;
            Overlay.MouseWheel  += Overlay_MouseWheel;
            Overlay.MouseMove   += Overlay_MouseMove;
            Overlay.MouseLeave  += Overlay_MouseLeave;
            Overlay.MouseDoubleClick
                                += Overlay_MouseDoubleClick;
            Overlay.Drop        += Overlay_Drop;
            Overlay.DragEnter   += Overlay_DragEnter;
            Overlay.StateChanged+= Overlay_StateChanged;
```

Thanks ~

**Comment by thanh-repo** [comment]
I got it.

Thank you so much~
