### ISSUE TITLE
Unable to load DLL 'avformat.58

### ISSUE THREAD

**Issue by lowndes783** [SuRGeoNix/Flyleaf#213]
My project works fine when running in visual studio and when running without the debugger attached, but as soon as I package it into a Setup file and install, I get the below error. I've tried using a fullpath and relative paths. The FFMPEG libraries are from the 3.5.7 demo, as they aren't listed separatly for that version (I've tried upgrading to other versions, and always get the same error).

```
10.40.11.175 | Info  | [FlyleafEngine] FlyleafLib 3.5.7
10.40.11.182 | Info  | [FlyleafEngine] Loading FFmpeg libraries from ':FFmpeg'
10.40.11.239 | Error | [FlyleafEngine] Loading FFmpeg libraries ':FFmpeg' failed
Unable to load DLL 'avformat.58 under <path to FFMPEG>': The specified module could not be found.
   at FFmpeg.AutoGen.ffmpeg.LoadLibrary(String libraryName, Boolean throwException)
   at FFmpeg.AutoGen.ffmpeg.<>c.<.cctor>b__7_0(String libraryName)
   at FFmpeg.AutoGen.ffmpeg.<>c.<.cctor>b__7_342()
   at FFmpeg.AutoGen.ffmpeg.avformat_version()
   at FlyleafLib.FFmpegEngine..ctor()
```

**Comment by SuRGeoNix** [comment]
This seems duplicate to #182. Make sure you use (I guess x64) platform also for you package and that you include an "FFmpeg" Folder within the installation package. Not sure how you do that but that seems to be the issue with Microsoft Store and permissions.
