### ISSUE TITLE
MPEG1VIDEO Doesn't start at first frame

### ISSUE THREAD

**Issue by metalblade34** [SuRGeoNix/Flyleaf#214]
Hello,

i'vz got problem with video in mpeg1

The first frame displayed of a mpeg1video is not the real first frame of the video.
i'll try with 2 or 3 other mpeg1video and got the same result

Any idea ?

**Comment by SuRGeoNix** [comment]
HI @metalblade34, how exactly are you testing this? Can you provide a trace log for the initial playback? Just tested one and I see the demuxer and the decoder will process the very first frame:-

```
12.27.30.531 | Info  | [#1]     [Demuxer:  Main] Format Context Info 
[Format  ] AVI (Audio Video Interleaved)/avi | avi | 00:00:00/00:00:40.0400000 | 00:00:00/00:00:40.0400000
[Video #0] mpeg1video yuv420p 740x176 @ 25 | [Color: BT601] [BR: 104857200] | 00:00:00/00:00:40.0400000 | 00:00:00/00:00:40.0400000

...

12.27.30.612 | Trace | [#1]     [Demuxer:  Main] [Video] DTS: 00:00:00 PTS: 00:00:00 | FLPTS: 00:00:00 | CurTime: 00:00:00 | Buffered: 00:00:00
12.27.30.614 | Trace | [#1]     [Demuxer:  Main] [Video] DTS: 00:00:00.0400000 PTS: - | FLPTS: - | CurTime: 00:00:00 | Buffered: 00:00:00
12.27.30.615 | Trace | [#1]     [Demuxer:  Main] [Video] DTS: 00:00:00.1200000 PTS: - | FLPTS: - | CurTime: 00:00:00 | Buffered: 00:00:00.0400000
12.27.30.616 | Trace | [#1]     [Demuxer:  Main] [Video] DTS: 00:00:00.2000000 PTS: - | FLPTS: - | CurTime: 00:00:00 | Buffered: 00:00:00.1200000

...

12.27.30.660 | Trace | [#1]     [Decoder: Video] Processes 00:00:00
```

**Comment by metalblade34** [comment]
Hi,
I'm not using AVI but MPEG file format
Here is some log
`14.14.53.987 | Info  | [#1] [Demuxer:  Main] Format Context Info 
[Format  ] MPEG-PS (MPEG-2 Program Stream)/mpeg |  | 00:00:00.3844440/00:48:33.7600000 | 00:00:00.3844440/00:48:33.7600000
[Video #0] mpeg1video yuv420p 352x288 @ 25 | [Color: BT601] [BR: 1504400] | 00:00:00.3844444/00:48:33.7600000 | 00:00:00.3844444/00:48:33.7600000
[Audio #1-eng] mp2 s16p@0 44KHz stereo | [BR: 128000] | 00:00:00.3844444/00:48:33.6718333 | 00:00:00.3844444/00:48:33.6718333

14.14.54.063 | Trace | [#1] [Decoder: Video] Processes 00:00:00.4800004
14.14.54.090 | Trace | [#1] [Demuxer:  Main] [Video] DTS: 00:00:00.9044444 PTS: 00:00:00.9044444 | FLPTS: 00:00:00.5200004 | CurTime: 00:00:00 | Buffered: 00:00:00
14.14.54.092 | Trace | [#1] [Demuxer:  Main] [Video] DTS: 00:00:00.9444444 PTS: 00:00:00.9444444 | FLPTS: 00:00:00.5600004 | CurTime: 00:00:00.5200004 | Buffered: 00:00:00
14.14.54.093 | Trace | [#1] [Demuxer:  Main] [Video] DTS: 00:00:00.9844444 PTS: 00:00:01.1044444 | FLPTS: 00:00:00.7200004 | CurTime: 00:00:00.5200004 | Buffered: 00:00:00.0400000
`

**Comment by SuRGeoNix** [comment]
Can you drop me an email with a sample video that you use so I can reproduce it?

**Comment by metalblade34** [comment]
Yes i send you a sample

**Comment by SuRGeoNix** [comment]
It looks fine to me, from the sample you send...

```
[Format  ] MPEG-PS (MPEG-2 Program Stream)/mpeg |  | 00:00:00.5316890/00:03:03.1440000 | 00:00:00.5316890/00:03:03.1440000
[Video #0] mpeg1video yuv420p 1280x720 @ 23,976 | [Color: BT709] [BR: 104857200] | 00:00:00.5417111/00:03:02.9744555 | 00:00:00.5417111/00:03:02.9744555
[Audio #1-eng] mp2 s16p@0 48KHz stereo | [BR: 384000] | 00:00:00.5316888/00:03:03.1440000 | 00:00:00.5316888/00:03:03.1440000

17.36.36.525 | Trace | [#1]     [Decoder: Video] Processes 00:00:00.0100221

```

100221 is the flyleaf's timestamp which is the video - demuxer start time (5417111 - 5316890)

How did you notice that you miss a frame?

**Comment by metalblade34** [comment]
i will send you a better exemple with screen caps

**Comment by metalblade34** [comment]
Hi,
I send you a email with another big sample and some screencaps.

Thank you again for your amazing work on Flyleaf

**Comment by SuRGeoNix** [comment]
I've noticed that VLC with avformat demuxer has the same behavior but I think I could review this as it opens fine the first time but then you can't seek at the very beginning (if that's what you say). This seems to have broken frames in the beginning of the file so when you seek (not first time that starts from a flushed session) it will not allow to play those broken frames. I might decide to allow those if they are in the beginning.

**Comment by metalblade34** [comment]
When i force seek to 0 not with the VideoStream.StartTime i got the good start frame but not the good timecode.

**Comment by SuRGeoNix** [comment]
I didn't look into it in details but it seems that solves your issue
