### ISSUE TITLE
how to play external devices like blackmagic decklink

### ISSUE THREAD

**Issue by newsoneisb** [SuRGeoNix/Flyleaf#215]
sorry I searched but didn't find any guide on this to play decklink video in this 

edit:
also I'm getting this error on FFmpegDevices = true

> 17.17.23.548 | Info  | [FlyleafEngine] FlyleafLib 3.6.1
> 17.17.23.573 | Info  | [FlyleafEngine] Loading FFmpeg libraries from 'C:\Flyleaf\FFmpeg'
> 17.17.23.772 | Error | [FlyleafEngine] FFmpeg failed to load avdevices/avfilters/postproc
> 17.17.23.776 | Info  | [FlyleafEngine] FFmpeg Loaded (Location: C:\Flyleaf\FFmpeg, Ver: 58.76.100, #Files: 5)

thanks

**Comment by SuRGeoNix** [comment]
Hi @newsoneisb, a quick look in [ffmpeg](https://ffmpeg.org/ffmpeg-devices.html#decklink) seems to support it so I guess by using ffmpeg devices will do it as flyleaf supports them. Check also some of my notes [here](https://github.com/SuRGeoNix/Flyleaf/releases/tag/v3.5.2) until I will include them in the Wiki. If you still need help let me know and I will have a deeper look in to it.

**Comment by SuRGeoNix** [comment]
Closing this and might re-open it after your feedback.

**Comment by newsoneisb** [comment]
hi again,

actually i was testing with dshow with this command
> Player.OpenAsync(@"device://dshow?video=Blackmagic WDM Capture");

but getting this result
![Capture](https://user-images.githubusercontent.com/79453566/203575255-73ef7a10-bcae-4e20-9069-8aa1b943dbbd.PNG)

and not getting any video with these commands
> Player.OpenAsync(@"device://decklink?video=DeckLink HD Extreme");
> Player.OpenAsync(@"device://decklink?DeckLink HD Extreme");

can you please guide to get directly decklink video

thanks in adv

**Comment by SuRGeoNix** [comment]
Can you try this

```
Player.OpenAsync(@"device://decklink?""DeckLink HD Extreme""");
```
