### ISSUE TITLE
Play/Pause issue in live stream

### ISSUE THREAD

**Issue by lkinfotechai** [SuRGeoNix/Flyleaf#217]
hi i tested player on live rtsp stream. when i pause the stream for some time, it starts taking ram till i paused the stream, and start from the same point where i paused when i play.

the meaning of that - it start storing frames in memory when i paused which is not a good way to do.
in case of live stream it always starts from real time after pause and play.

please check and resolve

**Comment by SuRGeoNix** [comment]
Check Config.Demuxer.BufferDuration and you can even pass flags/format options to the ffmpeg through flyleaf's config.
