### ISSUE TITLE
How redefine default key ?

### ISSUE THREAD

**Issue by LauraKami** [SuRGeoNix/Flyleaf#220]
Hi,
I try this two solutions 

a) remove key and add new definition => don't work

```
KeyBinding key;
key = playerConfig.Player.KeyBindings.Get("SeekForward");
if (key != null) playerConfig.Player.KeyBindings.Remove("SeekForward");
playerConfig.Player.KeyBindings.Add(Key.Right, KeyBindingAction.ShowNextFrame,false,false,false);
```

b) don't remove the key, but modify action, yes it work,  ( so search key.right used where, and replace ..., not very "intuitive")
```
key = playerConfig.Player.KeyBindings.Get("SeekForward");
if (key != null) key.SetAction( () => _PlayerView1.ShowFrameNext(), true);
```

please confirm that solution b) is the one to use.

Thank you for your software and the new versions.
LauraKami

**Comment by SuRGeoNix** [comment]
Hi @LauraKami

You just found a bug, something was missing :)

here in details how you add/remove now:-

```csharp
playerConfig.Player.KeyBindings.Remove(KeyBindingAction.SeekForward); // based on embedded action or ...
playerConfig.Player.KeyBindings.Remove(Key.Right); // based on key

playerConfig.Player.KeyBindings.Add(Key.Right, KeyBindingAction.ShowNextFrame); // embedded action
playerConfig.Player.KeyBindings.AddCustom(Key.Right, false, () => Player.ShowFrameNext(), "Custom_ShowFrameNext"); // custom action
```
you can use the 2nd add for now until the next package update

**Comment by LauraKami** [comment]
Merci,
Happy to (a little)  help you to improve your software.
