### ISSUE TITLE
Realtime RTSP video stream - reduce latency?

### ISSUE THREAD

**Issue by deeks9000** [SuRGeoNix/Flyleaf#223]
We are using your Flyleaf WPF control and are very impressed with its video image quality and performance. From your source code I can see roughly how it works, although I do not claim to understand it all! 

The two key complex components appear to be:
- Native C++ interaction with the FFmpeg libraries to process H.264 and H.265 video streams
- Native DirectX video rendering using a child window (HWND), but still allowing WPF elements to be rendered on top of the DirectX video 

**Question_1:**
We are using Flyleaf in a WPF app to read and display a video stream using RTSP. We note that the RTSP/RTP communications is delegated to the FFmpeg library.

With RTSP as the main transport, we are hoping to use the Flyleaf control with low latency for near-realtime response so that we can control Pan, Tilt and Zoom on our cameras.

However, we have noticed that there is a latency delay of about 1.5 seconds and wondered if there is a video stream buffer setting or simple parameter that we can change to minimize the latency? 
Is this something that can be modified within the Flyleaf library or is the RTSP latency delay a low-level FFmpeg 'buffer feature' requiring some Platform Invoke function calls to modify?

We are running tests in parallel with another GitHub RTSP project for reference: RtspClientSharp / SimpleRtspPlayer by BogdanovKirill. This is a very useful reference as most of the code is written in C#, including the RTSP comms and WPF rendering. It is however a 4 year old repository (and therefore, 4 year old FFmpeg DLLs) and has a few quirks of it own! But, it does show a near-realtime RTSP response and so we are confident that the RTSP protocol can achieve this using FFmpeg.

If you could offer any advice on how we could reduce the RTSP latency for Flyleaf that would be very much appreciated.

**Question_2 (bug report):**
We notice that the Flyleaf WPF control has gone through a few breaking changes in the past month, e.g.
VideoView --> FlyleafHost

But, some of the WPF bindings no longer work. 
In the project: Flyleaf Player (Custom - MVVM) (WPF)
Using the Visual Studio Debug XAML in-app toolbar, it shows 4 binding errors... 
e.g. the button Show/Hide Debug no longer displays the debug view overlay

It appears that the FlyleafHost does not inherit the parent Window DataContext?

**Comment by SuRGeoNix** [comment]
Hi @deeks9000,

1) Low Latency

I've recently added a new implementation which allows audio as well. You just need to set this (in ticks):-

```csharp
Config.Player.MaxLatency = TimeSpan.FromMicroseconds(500).Ticks; // For 500ms latency
```

I don't have much feedback yet but for my quick testing was working fine.

There is an alternative low latency (1st implementation) which must be set initially in the Player's config with:-

```csharp
Config.Player.Usage = Usage.LowLatencyVideo;
```

I have another one but I don't even remember what it does (Usage.ZeroLatencyAudioVideo). I would recommend you to start with the just Config.Player.MaxLatency which uses the main playback function which is more stable and uses Speed to push the playback for low latency.

Related configuration properties are Config.Demuxer.BufferDuration and Config.Player.MinBufferDuration (by setting MaxLatency will adjust the values for you). Those configs are for flyleaf, but you can even go to ffmpeg directly for more configuration by settings the Config.Demuxer.FormatFlags (such as NO_BUFFER) and Config.Demuxer.FormatOpt (to set tcp/udp rtsp etc.)

2) I will have a look soon and answer you...

**Comment by SuRGeoNix** [comment]
Check also a related thread [here](https://github.com/SuRGeoNix/Flyleaf/issues/194)

**Comment by deeks9000** [comment]
Hi @SuRGeoNix,

Thanks very much for getting back to me so quickly!

I have just pulled in your latest changes from this afternoon and can see that the FlyleafHost overlay Grid now inherits the (Host) Window DataContext and all bindings are working again - yay!

More importantly though, your suggestion to specifically set a value for the MaxLatency property:

```
Config.Player.MaxLatency = Timespan.FromMilliseconds(500).Ticks 
``` 

...seems to work perfectly. I currently have it set at 100ms for good measure!

That is fantastic, thank you very much once again for your help.
