### ISSUE TITLE
Copy/Clone Player 

### ISSUE THREAD

**Issue by thanh-repo** [SuRGeoNix/Flyleaf#224]
Hi,
Is there any solution to clone or copy player?
My idea is that when I click the button, a new dialog window opens with the same player as the parent window.
I have simulated my idea in this repository: https://github.com/thanh-repo/FlyleafMinimize/tree/master/PlayerDuplicate

Could you help me to check this idea?
One more thing, the swap function was removed in the current version. Is there any related function in the current version?
Thanks and best regards!

**Comment by SuRGeoNix** [comment]
Hi @thanh-repo, I didn't check yet the repo but until then can you explain in more details what you want to do? Do you want to transfer the player to another window or you want to open another player with the same input/configuration of the first player?

The Swap has been removed as the FlyleafHosts have been completely separated from the Players. This means that you can unset and set anytime any Player that you want.

**Comment by thanh-repo** [comment]
Hi @SuRGeoNix,

Right, Transfer the player to another window or play the same player on the new window is okay to me.
As my repo, I transfer the player by set the player in the viewmodel(ViewModel2) of new window (Player2) by the player in the parent window (Player1)(ViewModel1): 
`
ViewModel2.Player2 = ViewModel1.Player1
`
But when I set back `ViewModel1.Player1 = ViewModel2.Player2`, the FlyleafHosts of Player1 was black.
What should I do?

**Comment by SuRGeoNix** [comment]
@thanh-repo Change your VMs (Main and Popup) to properly call OnPropertyChanged with

```csharp
Player player;
public Player Player { get => player; set { player = value; OnPropertyChanged(); } }
```

and replace your ShowPopup() with this one:

```csharp
public void ShowPopup()
{
	PopupPlayer Popup = new();
	Popup.Closed += (o, e) =>
	{
		Popup.FlyleafPlayer.Player = null; // To prevent disposal of the player
		Popup.FlyleafPlayer.Dispose(); // This should be disposed by flyleaf (after owner window has been closed)
	};
	Popup.Owner = App.Current.MainWindow;
	Popup.DataContext = VmPopup;
	TempPlayer = Player;
	Player = null;
	VmPopup.Player = TempPlayer;
	Popup.ShowDialog();
	TempPlayer = VmPopup.Player;
	VmPopup.Player = null;
	Player = TempPlayer;
}
```

**Comment by thanh-repo** [comment]
Hi @SuRGeoNix,

It works perfectly.
As your suggestion of detached, by many Google searches but I still do not understand your idea of "detached".
Could you please explain more about that?

**Comment by thanh-repo** [comment]
This is my suggestion when player full screen:
When full screen, the surface should be activated to catch keyboard event:
`FlyleafLib\Controls\WPF\FlyleafHost.cs` `Line 1675`
```
if (IsFullScreen)
{
    ...
    Surface.WindowState = WindowState.Maximized;
    Surface.Activate();
}
```

**Comment by SuRGeoNix** [comment]
When you add a FlyleafHost in your XAML it will be a WPF control and it will create a Window (Surface). It will also create another Window (Overlay) owned by the Surface if you have content. Now, by default Surface/Overlay will be "attached" to the WPF Control (FlyleafHost) so they will be owned by the Window that hosts the WPF Control and they will follow its location. Flyleaf gives you the option to have those windows as "detached", without an Owner Window and free/independent from the rest of your application. I've examples for those in Tests/WpfFlyleafHost project.

I will review the activation of the surface on maximize however you might also consider allowing the KeyBindings even for the overlay and just disable them when you have a poup / another page etc.

(I leave this open to review the disposal of FlyleafHost when the Owner has been Closed. I was expecting that Owner will close it, it seems that .NET 6 has issues with this as well, might be related)
