### ISSUE TITLE
About HDR

### ISSUE THREAD

**Issue by qian-o** [SuRGeoNix/Flyleaf#226]
I found that the maximum brightness of the video will be acquired for hdr conversion before playing the video.
However, if there is error information in the video information, it will cause video overexposure.
![image](https://user-images.githubusercontent.com/84434846/207334412-9030dcbd-888b-478f-8c47-2910ac0ae517.png)
I implemented it by referring to your code. My default maximum brightness is 1000
![image](https://user-images.githubusercontent.com/84434846/207335169-adc52d8d-6420-43cd-9458-440a00951956.png)

**Comment by SuRGeoNix** [comment]
Hi @qian-o, so I guess your suggestion is to have a 'proper' fallback in case of wrong values? (I'm downloading Sony's video to see if I can reproduce it)

**Comment by qian-o** [comment]
Yes, I suggest the default value is 1000.
Due to network reasons, I may not be able to provide you with videos.

**Comment by SuRGeoNix** [comment]
I've downloaded the original from [Sony](https://4kmedia.org/sony-camping-in-nature-4k-demo/) but the color space is not BT2020 but BT709. Flyleaf will not handle this with pixel shaders as there is no need to convert BT2020 to BT709. I'm not sure what I'm missing here.

**Comment by qian-o** [comment]
He does have an sdr version

**Comment by SuRGeoNix** [comment]
I guess I've used a different video file. But the fallback for the luminance I'm not sure if it should be 1000. Here is the current code:

```csharp
public void UpdateHDRtoSDR(AVMasteringDisplayMetadata* displayData = null, bool updateResource = true)
{
	if (VideoDecoder.VideoStream == null || VideoDecoder.VideoStream.ColorSpace != "BT2020") return;

	float lumin = displayData == null || displayData->has_luminance == 0 ? lastLumin : displayData->max_luminance.num / (float)displayData->max_luminance.den;
	lastLumin = lumin; //lumin <= 0 ? 1000 : lumin;

	psBufferData.hdrmethod = Config.Video.HDRtoSDRMethod;

	if (psBufferData.hdrmethod == HDRtoSDRMethod.Reinhard)
	{
		psBufferData.g_toneP1 = lastLumin > 0 ? (float)(Math.Log10(100) / Math.Log10(lastLumin)) : 0.72f;
		if (psBufferData.g_toneP1 < 0.1f || psBufferData.g_toneP1 > 5.0f)
			psBufferData.g_toneP1 = 0.72f;
	}
	else if (psBufferData.hdrmethod == HDRtoSDRMethod.Aces)
	{
		psBufferData.g_luminance = lastLumin > 0 ? lastLumin : 400.0f;
		psBufferData.g_toneP1 = Config.Video.HDRtoSDRTone;
	}
	else if (psBufferData.hdrmethod == HDRtoSDRMethod.Hable)
	{
		psBufferData.g_luminance = lastLumin > 0 ? lastLumin : 400.0f;
		psBufferData.g_toneP1 = 10000.0f / psBufferData.g_luminance * (2.0f / Config.Video.HDRtoSDRTone);
		psBufferData.g_toneP2 = psBufferData.g_luminance / (100.0f * Config.Video.HDRtoSDRTone);
	}

	context.UpdateSubresource(psBufferData, psBuffer);

	Present();
}
```

For Aces/Hable falls back to 400 and for Reinhard it will not be used by the shader ... here is the shader


```hlsl
...
if (hdrmethod != 0)
    {
        // BT2020 -> BT709
        color.rgb = pow(max(0.0, color.rgb), 2.4f);
        color.rgb = max(0.0, mul(color, bt2020tobt709color).rgb);
        color.rgb = pow(color.rgb, 1.0f / 2.2f);

        if (hdrmethod == Aces)
        {
            color.rgb = inversePQ(color.rgb);
            color.rgb *= (10000.0f / g_luminance) * (2.0f / g_toneP1);
            color.rgb = aces(color.rgb);
            color.rgb *= (1.24f / g_toneP1);
            color.rgb = pow(color.rgb, 0.27f);
        }
        else if (hdrmethod == Hable)
        {
            color.rgb = inversePQ(color.rgb);
            color.rgb *= g_toneP1;
            color.rgb = hable(color.rgb * g_toneP2) / hable(g_toneP2);
            color.rgb = pow(color.rgb, 1.0f / 2.2f);
        }
        else if (hdrmethod == Reinhard)
        {
            float luma = dot(color.rgb, bt709coefs);
            color.rgb *= reinhard(luma) / luma;
        }
    }
...
```

**Comment by SuRGeoNix** [comment]
I will need to find the same video so give me a link if you have one

**Comment by qian-o** [comment]
https://1drv.ms/u/s!AqPWalHFUusKgWhzi9dUdGwwaecx?e=Kn0JXY
You can try this link

**Comment by qian-o** [comment]
I choose the "Hubble" mode, but I don't know the difference between them.

**Comment by SuRGeoNix** [comment]
You can go from settings and change it, even the tone mapping values and see if it works. Almost downloaded so I will see what is going on.

**Comment by qian-o** [comment]
I understand the software operation, but I don't know why these three modes exist. Is there a link to relevant documents?

**Comment by SuRGeoNix** [comment]
Well I wish it would exist! I've review Kodi's code for this part. VLC for me crashes with this video, Pot player works fine but I need to review this in more details.

**Comment by SuRGeoNix** [comment]
Just tested with Kodi which by default uses Reinhard and I switch it to use Hable and it fails as well. In case you want to research this further until I will do as well, you can review also Kodi's implementation:

https://github.com/xbmc/xbmc/blob/master/system/shaders/output_d3d.fx
https://github.com/xbmc/xbmc/blob/master/xbmc/cores/VideoPlayer/VideoRenderers/VideoShaders/WinVideoFilter.cpp

I'm not sure if they have some issue with the Hable method or just Hable doesn't work in this case.

**Comment by SuRGeoNix** [comment]
I fix this simple now and I will review this in the future when I will review also the native HDR as it requires more time / research.
