### ISSUE TITLE
External subtitles

### ISSUE THREAD

**Issue by freeproa** [SuRGeoNix/Flyleaf#228]
Question.
There is a file structure
2.avi.
2.srt
2_en.srt
2.en.srt
Where to find SubtitleStream
Both locations are empty:
1 - Player.Subtitles.Streams
2 - Player.Playlist.Selected.ExternalSubtitlesStreams

**Comment by SuRGeoNix** [comment]
Hi @freeproa, FlyleafLib's embedded [local search for subtitles pluging](https://github.com/SuRGeoNix/Flyleaf/blob/master/FlyleafLib/Plugins/OpenSubtitles.cs#L49) currently searches only for what it saved and not generally. You can either create a PR for the embedded plugin or [create your own plugin](https://github.com/SuRGeoNix/Flyleaf/wiki/Advanced#plugins-development) to with you rules for local searching. I might try to include this on the next update but not promise as it's not a high priority.

**Comment by SuRGeoNix** [comment]
@freeproa I will close this as it shouldn't add them by default, it will require the application to do it. The best way is with a plugin that will include external subtitles stream. If you need help to develop this let me know and I will assist you.
