### ISSUE TITLE
Latest update broke WPF example 

### ISSUE THREAD

**Issue by M0n7y5** [SuRGeoNix/Flyleaf#23]
When i try to compile it it just gives me error: System.NullReferenceException
FlyleafPlayer.cs:
![image](https://user-images.githubusercontent.com/17201053/114260812-4fc10400-99d7-11eb-8a25-0e2e59087142.png)

**Comment by SuRGeoNix** [comment]
Yep, might be possible didn't check but in any case Flyleaf v2.x was mainly for WinForms (just try to set the config.mainEmbeddedList = false / and wpf to true?).

I'm almost done with Flyleaf v3.x which focuses in WPF MVVM. I will have an update soon, so check in a few days with completely new interface and easy customizable. Thanks for submitting this!

**Comment by M0n7y5** [comment]
Dont worry i found that workaround with EmbeddedList. Anyways i'll wait for that MVVM update. Its a best library for playing videos so far. 👍

**Comment by SuRGeoNix** [comment]
Thanks :) I decided to re-code also the plugins and some other API things. so it will take me few days more, but soon it will be available.

**Comment by SuRGeoNix** [comment]
Finally, is out so I'm closing this and check v3.0 wpf control and be kind as it was my first time writing xaml 🎲
