### ISSUE TITLE
Player.SeekAccurate freezes in HLS with EXT-X-DISCONTINUITY

### ISSUE THREAD

**Issue by DouglasSnt** [SuRGeoNix/Flyleaf#230]
I'm trying to watch an m3u8 playlist with multiple videos, and each video separated into smaller parts using the #EXT-X-BYTERANGE tag, like this:

> #EXTM3U
> #EXT-X-VERSION:7
> #EXT-X-TARGETDURATION:10
> #EXT-X-MEDIA-SEQUENCE:0
> #EXT-X-PLAYLIST-TYPE:VOD
> #EXT-X-MAP:URI="/vod/file-1.mp4",BYTERANGE="745@0"
> #EXTINF:10.0
> #EXT-X-BYTERANGE:5000@10000
> /vod/file-1.mp4
> #EXTINF:10.0
> #EXT-X-BYTERANGE:5000@20000
> /vod/file-1.mp4
> #EXT-X-DISCONTINUITY
> #EXT-X-MAP:URI="/vod/file-2.mp4",BYTERANGE="745@0"
> #EXTINF:10.0
> #EXT-X-BYTERANGE:5000@10000
> /vod/file-2.mp4
> #EXTINF:10.0
> #EXT-X-BYTERANGE:5000@20000
> /vod/file-2.mp4
> #EXT-X-ENDLIST

The video plays normally and the search using _Player.Seek()_ also works, but it's not very accurate.
When there is only one video in the playlist, using _Player.SeekAccurate()_ solves the problem, but when there is more than one video separated by the #EXT-X-DISCONTINUITY, tag the player freezes.

Taking a quick look at the code, _av_seek_frame()_ works correctly looking for the nearest keyframe, the problem seems to be in DecoderContext.GetVideoFrame() when it tries to discard the remaining frames until it reaches the fetched timestamp.
Because they have different files in the playlist, the values of _frame->pts_, _VideoStream.Timebase_ and _VideoDemuxer.StartTime_ can be different and non-sequential, causing the search to never end.

**Comment by SuRGeoNix** [comment]
Hi @DouglasSnt, what you say make sense, however it would be much easier to identify and fix the issue if you could provide me an HLS Url that the issue presents, including the exact steps to reproduce. You can drop me an email if you don't want to share it here. If you can't share it, you could provide a log file during the freeze (and remove the url from the logs?)

**Comment by DouglasSnt** [comment]
I can't share a Url and I'm not sure if this is a Flyleaf's bug or FFmpeg, but I can show you how to reproduce the issue.

Having a video sample and using the following command, a new video file and playlist will be created.

> ffmpeg -i "Sample.mp4" -t 00:00:30 -hls_list_size 0 -hls_flags single_file out.m3u8

The playlist will look like this:

> #EXTM3U
> #EXT-X-VERSION:4
> #EXT-X-TARGETDURATION:4
> #EXT-X-MEDIA-SEQUENCE:0
> #EXTINF:5.0,
> #EXT-X-BYTERANGE:1400000@0
> out.ts
> ...
> #EXT-X-ENDLIST

With one or more playlists ready, just manually duplicate the video ranges before the #EXT-X-ENDLIST tag, adding the tag #EXT-X-DISCONTINUITY between them, like this:

> #EXTM3U
> #EXT-X-VERSION:4
> #EXT-X-TARGETDURATION:4
> #EXT-X-MEDIA-SEQUENCE:0
> #EXTINF:5.0,
> #EXT-X-BYTERANGE:1400000@0
> out.ts
> ...
> 
> #EXT-X-DISCONTINUITY
> #EXTINF:5.0,
> #EXT-X-BYTERANGE:1400000@0
> out.ts
> ...
> 
> #EXT-X-ENDLIST

Using the default sample FlyleafPlayer (WPF Control), open the _out.m3u8_ file created earlier

When leaving the video running without interaction, the entire video is displayed correctly.
When searching the timeline, it is possible to view and navigate through the entire video, but without precision.
Adding _SeekAccurate = true_ in the player configuration, it is only possible to navigate through the area corresponding to the first video, after this area no image is displayed.

**Comment by SuRGeoNix** [comment]
Just did a quick test and couldn't reproduce it, it was working fine with seek accurate (just using ctrl+S to toggle it from the sample app). The ffmpeg produce me this m3u8

```
#EXTM3U
#EXT-X-VERSION:4
#EXT-X-TARGETDURATION:8
#EXT-X-MEDIA-SEQUENCE:0
#EXTINF:8.341667,
#EXT-X-BYTERANGE:568512@0
out.ts
#EXTINF:3.570233,
#EXT-X-BYTERANGE:348552@568512
out.ts
#EXTINF:3.903900,
#EXT-X-BYTERANGE:426948@917064
out.ts
#EXTINF:7.273933,
#EXT-X-BYTERANGE:380700@1344012
out.ts
#EXTINF:6.940267,
#EXT-X-BYTERANGE:762528@1724712
out.ts
#EXT-X-ENDLIST
```

and adding the #EXT-X-DISCONTINUITY as you said 

```
#EXTM3U
#EXT-X-VERSION:4
#EXT-X-TARGETDURATION:8
#EXT-X-MEDIA-SEQUENCE:0
#EXTINF:8.341667,
#EXT-X-BYTERANGE:568512@0
out.ts
#EXT-X-DISCONTINUITY
#EXTINF:3.570233,
#EXT-X-BYTERANGE:348552@568512
out.ts
#EXT-X-DISCONTINUITY
#EXTINF:3.903900,
#EXT-X-BYTERANGE:426948@917064
out.ts
#EXT-X-DISCONTINUITY
#EXTINF:7.273933,
#EXT-X-BYTERANGE:380700@1344012
out.ts
#EXT-X-DISCONTINUITY
#EXTINF:6.940267,
#EXT-X-BYTERANGE:762528@1724712
out.ts
#EXT-X-ENDLIST
```

do i miss something?

**Comment by DouglasSnt** [comment]
Sorry, I don't think the way I explained was very clear.

Keep the playlist headers, but instead of having just one video in the playlist, there should be other files in the same playlist separated by #EXT-X-DISCONTINUITY.

```
#EXTM3U
#EXT-X-VERSION:4
#EXT-X-TARGETDURATION:8
#EXT-X-MEDIA-SEQUENCE:0
#EXTINF:8.341667,
#EXT-X-BYTERANGE:568512@0
out.ts
#EXTINF:3.570233,
#EXT-X-BYTERANGE:348552@568512
out.ts
#EXTINF:3.903900,
#EXT-X-BYTERANGE:426948@917064
out.ts
#EXTINF:7.273933,
#EXT-X-BYTERANGE:380700@1344012
out.ts
#EXTINF:6.940267,
#EXT-X-BYTERANGE:762528@1724712
out.ts
#EXT-X-DISCONTINUITY
#EXTINF:8.341667,
#EXT-X-BYTERANGE:568512@0
out.ts
#EXTINF:3.570233,
#EXT-X-BYTERANGE:348552@568512
out.ts
#EXTINF:3.903900,
#EXT-X-BYTERANGE:426948@917064
out.ts
#EXTINF:7.273933,
#EXT-X-BYTERANGE:380700@1344012
out.ts
#EXTINF:6.940267,
#EXT-X-BYTERANGE:762528@1724712
out.ts
#EXT-X-ENDLIST
```

An image explaining the idea better:

![hls-discontinuity](https://user-images.githubusercontent.com/61507567/208970840-4f3649e8-39b5-4a73-a242-496945e66695.png)

About the #EXT-X-DISCONTINUITY tag:
https://www.rfc-editor.org/rfc/rfc8216.html#section-4.3.2.3

**Comment by SuRGeoNix** [comment]
I think I was able to create an .m3u8 in the way that you say. Two playlists with the same file (30 seconds) so even if it announces 1 minute duration it will have timestamps from 0-30'' and then again from 0-30''. So I'm not sure how you properly seek on specific playlists and timestamp. Maybe you should create the .m3u8 to continue from the 30 second for the 2nd playlist file? Even with this playlists I was not able to reproduce the freeze issue.

**Comment by DouglasSnt** [comment]
As you asked earlier, I researched ffmpeg and saw that there are several tickets about this tag, and that in the hls.c file there is nothing about the EXT-X-DISCONTINUITY tag, so this problem is really due to ffmpeg and not from Flyleaf.
Apparently ffmpeg just ignores unknown tags, concatenating everything as if it were just a single file, and without this discontinuity flag there is not enough information to get the current time of the video correctly or search accurately.
An example of a player that can correctly reproduce and search the same playlist is VideoJS, but ffmpeg is not used.
