### ISSUE TITLE
Options for ffmpeg library

### ISSUE THREAD

**Issue by homov** [SuRGeoNix/Flyleaf#233]
Sometimes it is necessary to pass specific options for the ffmpeg library. For example, switch rtsp_transport to udp or add specific http headers.

At the moment I do this by saving a dictionary **FormatOpt**, then I set the necessary parameters before calling **Player.Open**, after the call I restore **FormatOpt.** 

You also save **FormatOpt** and restore them in the method **DecoderContext.OpenDemuxerInput**.

Is this the best way to pass such parameters?

**Comment by SuRGeoNix** [comment]
Yes, the DecoderContext.OpenDemuxerInput will not reset them, it will add the additional http headers that the plugin provided (this is mainly for yt-dlp). So you have the control through the Config.Demuxer.FormatOpt
