### ISSUE TITLE
Allow initialization of engine (Engine.Start) on non-UI thread

### ISSUE THREAD

**Issue by hided** [SuRGeoNix/Flyleaf#235]
Currently Engine.Start() has to be called from the UI Thread.
This causes the application to freeze for a couple of seconds if called after the main view is displayed (WPF).
(note that in the sample WPF app, this is done before the window is shown, so this is not really noticed, but still slows down app startup with 2 seconds)

I want to initialize the player engine in a lazy manner, only when the video player is actually needed (this is not always the case in my scenario) without blocking the UI.
To achieve this I run the init on a threadpool worker thread. (which is currently not possible, hence this issue)

Turns out the only calls that require the UI thread are two Application.Exit event subscriptions:
- one within Engine.Start that disposes the players on app exit (engine.cs L70)
- one in the Logger static constructor that flushes the queue on app exit

Above event subscriptions can simply be invoked on the UI thread, which should resolve my issue.

Let me know what you think, I can also provide a PR if you agree with the things i said.

Recently switched from libvlc (.NET bindings and wpf host control) to flyleaf because vlc had too many issues and so far I'm really pleased with your project, many thanks!

**Comment by SuRGeoNix** [comment]
Hi @hided, yes that makes absolute sense. I had this in mind and also having the pixel-shaders pre-compiled within the library, so it will boot even faster. Don't bother to create a PR as I will need to review few other things as well so I will include this in the next update. Thanks for you feedback!

(Eg. You can't create a Player/Player.Config if the Engine has not been fully started, I thing I will follow the current Flyleaf's logic with Task.Run and an event to inform the user that the EngineStarted so he will be able to initialize the Player(s))

**Comment by anguzo** [comment]
@hided for lazy loading I used approach where I have FlyleafEngineWrapper which has the constructor in which Engine.Start happens. I use CommunityToolkit.Mvvm for DI and IOC and just configure services as follows:
1. Add FlyleafEngineWrapper as singleton
`
.AddSingleton<FlyleafEngineWrapper>()
`
2. Add Config as singleton and use ServiceProvider to get "dummy" FlyleafEngineWrapper
`
.AddSingleton(sp =>
{
    sp.GetService<FlyleafEngineWrapper>();
    return new Config
    {
        Player =
        {
            Usage = Usage.LowLatencyVideo,
        },
        Video =
        {
            BackgroundColor = Colors.Transparent,
        }
    };
})
`
Not the perfect soultion but imaginative one :)

**Comment by SuRGeoNix** [comment]
@hided I've added the Engine.StartAsync (check the sample project) I will also review the pre-compiled pixel shaders. Let me know if that looks ok to you.
