### ISSUE TITLE
Support for WinUI

### ISSUE THREAD

**Issue by ORRNY66** [SuRGeoNix/Flyleaf#237]
You are preparing support for WinUI as well. Thanks a lot.

**Comment by SuRGeoNix** [comment]
Already tried, WinUI should be in beta, has a lot of issues. Avalonia seems much more mature.

**Comment by SuRGeoNix** [comment]
Closing this as related to #216 and we can continue discussing this there!

**Comment by EjiHuang** [comment]
@SuRGeoNix Hi, this is a demo([NetPlayer](https://github.com/EjiHuang/NetPlayer)) I created recently about displaying video on WinUI. It uses Win2D.

**Comment by SuRGeoNix** [comment]
Hey @EjiHuang, didn't have a look yet but if you can't have an overlay content above the video I don't think that it deserves the time to integrate flyleaf. WinUI doesn't support transparent window yet as far as I saw.

**Comment by SuRGeoNix** [comment]
@EjiHuang found a better solution for WinUI by using a SwapChainPanel which Vortice.WinUI supports to pass one. I didn't implement the extra functionality yet (fullscreen/mouse bindings etc.) but the good thing is that it does not require the mess with extra windows (surface/overlay) is just another control in the main window which should solve issues like airspace and z-order.

Didn't tested much yet but I hope the performance will be good enough.

**Comment by EjiHuang** [comment]
Hi @SuRGeoNix , Thank you for your answer, I am not very familiar with SwapChainPanel, I will learn about it when I have time. 
 My solution is to use CanvasControl + Win2d to achieve video rendering and display. WinUI3 controls can be easily displayed on CanvasControl. The code below is the style of the MediaElement control I wrote.
```xaml
<ResourceDictionary
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:canvas="using:Microsoft.Graphics.Canvas.UI.Xaml"
    xmlns:controls="using:NetPlayer.WinUI.Controls"
    xmlns:local="using:NetPlayer.WinUI">

    <Style TargetType="controls:MediaElement">
        <Setter Property="Template">
            <Setter.Value>
                <ControlTemplate TargetType="controls:MediaElement">
                    <Grid
                        Background="{TemplateBinding Background}"
                        BorderBrush="{TemplateBinding BorderBrush}"
                        BorderThickness="{TemplateBinding BorderThickness}">
                        <canvas:CanvasControl x:Name="canvas" />
                        <StackPanel
                            Margin="10"
                            Padding="5"
                            HorizontalAlignment="Right"
                            VerticalAlignment="Top"
                            Background="#99000000"
                            CornerRadius="2">
                            <StackPanel Orientation="Horizontal">
                                <TextBlock Width="100" Text="FpsCurrent" />
                                <TextBlock x:Name="tblFpsCurrent" />
                            </StackPanel>
                            <StackPanel Orientation="Horizontal">
                                <TextBlock Width="100" Text="Video.BitRate" />
                                <TextBlock x:Name="tblVideoBitRate" />
                            </StackPanel>
                        </StackPanel>
                    </Grid>
                </ControlTemplate>
            </Setter.Value>
        </Setter>
    </Style>
</ResourceDictionary>
```

**Comment by SuRGeoNix** [comment]
@EjiHuang check my update with WinUI 3.0, the solution is ideal for media playback (performance wise)
