### ISSUE TITLE
'Loading FFmpeg libraries ':FFmpeg' failed'

### ISSUE THREAD

**Issue by hussainkadori** [SuRGeoNix/Flyleaf#238]
Hi,
I have a problem with loading FFmpeg in Winform app .NET 7 I added the FFmpeg libraries from this repo.

How to solve this problem?

**Comment by SuRGeoNix** [comment]
Make sure your application is compiled for x64 and that you provide the write path for the ffmpeg libraries during the engine start

**Comment by hussainkadori** [comment]
@SuRGeoNix Thanks the problem was FFmpeg.Autogen package missing

**Comment by jeeshenlee** [comment]
> I have the same issue but I'm using win32 ffmpeg downloaded from [sudo-nautilus/FFmpeg-Builds-Win32](https://github.com/sudo-nautilus/FFmpeg-Builds-Win32)
> 
> I have to run my app on x32, is Flyleaf lib x32 compatible?
> 
> NOTE: I tried the downloaded ffmpeg with FFMediaElement, it works fine.

I manage to get it to work - by using win32 (x86) version 5.1 DLL. I was using version 4.4 earlier on.
