### ISSUE TITLE
How to control the sharpness of the video?

### ISSUE THREAD

**Issue by hussainkadori** [SuRGeoNix/Flyleaf#239]
Hi,
Is there any video filter to control the sharpness of the video?

**Comment by SuRGeoNix** [comment]
Unfortunately no, currently it supports the basic video filters Brightness/Contrast and with D3D11 Video Processor you can also use Hue/Saturation. I'm planning to allow the user to have additional post-process pixel shaders for more customization as this should happen in GPU for performance reasons.
