### ISSUE TITLE
Zoom/Pan

### ISSUE THREAD

**Issue by 001simonp** [SuRGeoNix/Flyleaf#24]
Hi
Does Flyleaf have an ability to Zoom/Pan on Video ?
If not, can I request that it be considered ?

**Comment by SuRGeoNix** [comment]
Currently does not. But yes sure, I have in mind to include X Speed and Zoom/Pan. I'm working on version 3.0 to make a proper documented package/library and a better UI customizable control in WPF. I guess after that I will try to include also new features like those.

**Comment by 001simonp** [comment]
Hi John

All good.
For info, for now, I have just placed the FlyMedia player within a Panel, and zoom/Pan using the size/position of the Panel.

Unfortunately, I lose the Media bar off the bottom within the Player.
Is there a way I can hook the FlyLeafBar control to the Video playing within the Media player ?

Also, trying to us Seek to move to a specific point of the video – how can I call the current position ?


Cheers

Si

**Comment by SuRGeoNix** [comment]
For the Seeking you can use a config property (config.bar.SeekOnSlide) and set it to false. If you want to seek to a specific point you can do it i think with 3 ways... use directly the API player.Seek.... use the control playerControl.Seek or you could even se the the value to the bar playerControl.tblBar.seekBar.Value (seconds here).

Now for the panel... not sure how i can help... you could use the FlyleafBar as external control and disable the embedded maybe... or even better if you want to do it right... mess with the MediaRenderer and SharpDX to set the viewport i guess.

I think you will solve this problem easier with the upcoming v3.0 (hopefully by the end of this week)

**Comment by 001simonp** [comment]
Hi John
The playerControl.tblBar.seekBar.Value (seconds here) was exactly what I needed – thank you.
I look forward to seeing what v3.0 has to offer.

I’m unable to disable the FL_Bar, though the multi example seems ok.
Could it be that I am using VB, not C#  ?
***@***.***D73208.8B0385B0]


Thanks again

Si

**Comment by SuRGeoNix** [comment]
You could set the config.bar._Visibility == VisibilityMode.Never, or even you could create your complete new custom user control and just pass the ptr handle to the library player.InitHandle. Don't think that you will have any issues with VB but never tested to be honest.

**Comment by SuRGeoNix** [comment]
Added in v3.0
