### ISSUE TITLE
How to handle live stream failure?

### ISSUE THREAD

**Issue by hussainkadori** [SuRGeoNix/Flyleaf#240]
Hi,
How can I handle  RTSP live stream failure ? is there any event I can use?

**Comment by SuRGeoNix** [comment]
Can you describe the failure in more details? What do you see in the logs when it happens (try to even enable trace)?
In the meantime, I'm looking to provide you all possible events that you could check.

**Comment by hussainkadori** [comment]
When camera connection is lost , I need an event to show a reconnect button on the screen

**Comment by SuRGeoNix** [comment]
- Player.BufferingCompleted Event (if (!e.Success) handle error)
- Player.PlaybackStopped Event (same as above)
- Player.VideoDemuxer.TimedOut Event (However this can be normal to get timeout sometimes, check also the configuration for timeouts, you might want to check if you have more than X timeouts in Y period of time then you handle this)
