### ISSUE TITLE
D3D11 video processor issue with Zoom while Rotated

### ISSUE THREAD

**Issue by getsolved** [SuRGeoNix/Flyleaf#241]
When zooming, the video proportions sometimes change if the video is rotated 90 degrees or is already in a 90 degree rotated form.

Zooming causes the image to change only horizontally, so that it stretches out until the host is completely filled, and only then does normal zooming take place.

**Comment by SuRGeoNix** [comment]
Yes this is happening with D3D11 video processor, I will review this. Until then you might want to force Flyleaf video processor which seems that works fine.

**Comment by getsolved** [comment]
Ok, thank you for your fast reply!
Workaround with FlyLeaf processor set via config works for now!

**Comment by SuRGeoNix** [comment]
Fixed in https://github.com/SuRGeoNix/Flyleaf/commit/251761ad2b01be399e02dd39fda26828a6a627da
