### ISSUE TITLE
DVR/NVR stream play

### ISSUE THREAD

**Issue by lkinfotechai** [SuRGeoNix/Flyleaf#245]
hi 
i am looking to play stream coming from DVR/NVR of any provider like hikvision/dahua
their sdk have option to connect their NVR/DVR by providing ip,user credentials
after that they use picture box to play stream in their sdk.
now i wanted to play stream in flyleaf coming from dvr/nvr
stream is in bytes coming from these. is that possible to encode and play in flyleaf

**Comment by SuRGeoNix** [comment]
does this format works for you rtsp://admin:password@192.168.1.108:554/cam/realmonitor?channel=1&subtype=0 ?

**Comment by lkinfotechai** [comment]
in case of rtsp it is good, which nvr/dvr provides rtsp i can play the live stream easily this is ok, but i am looking for the recorded stream playback from nvr/dvr, suppose i have a hikvision nvr and inside the nvr there is HDD which is recording the stream, now i want to play that recorded stream into the flyleaf player, but i can access the HDD recorded feed only by the hikvision SDK, which comes in bytes.

**Comment by SuRGeoNix** [comment]
You could develop a flyleaf plugin which will use hikvision's SDK and passes the input to FFmpeg.
It would be nice to share it so others can use it here. I don't have the require resources to develop it myself. However, if you could provide me access for testing I could try develop it in the future.
