### ISSUE TITLE
How to set zoom position?

### ISSUE THREAD

**Issue by hussainkadori** [SuRGeoNix/Flyleaf#247]
Hi,
The zoom only scale video from the center point instead of mouse position. Is there any way to to scale from mouse position?

**Comment by SuRGeoNix** [comment]
@hussainkadori what about moving the panel? is that what you ask?

**Comment by hussainkadori** [comment]
@SuRGeoNix I mean the zoom on mouse wheel it's always scale the image from the center not the pointer position. for example when I zoom in on the corner of the image I have to pan and move the image after zooming.

**Comment by SuRGeoNix** [comment]
Yes, that make sense. I could allow you to change the center point of the zoom, however this is related to allowing the image to be smaller than the control (eg. what should happen if you have a small image in the center and your mouse pointer is outside of the image but inside in the control). I will review this in the next update.

**Comment by hussainkadori** [comment]
@SuRGeoNix  I use a Touch Screen and it works like as pinch zoom.

**Comment by SuRGeoNix** [comment]
Do you think that by providing the center point of the control for the zoom will be enough?

**Comment by hussainkadori** [comment]
I will try to set Pan offsets based on mouse position.

**Comment by SuRGeoNix** [comment]
@hussainkadori Don't waste time... I guess I should implemented for both WPF/WinForms just once for anyone

**Comment by SuRGeoNix** [comment]
@hussainkadori I've included this, if you can tested from master and let me know if that's ok with you before updating

**Comment by hussainkadori** [comment]
@SuRGeoNix Thanks it works now.
