### ISSUE TITLE
Player Status does not change to Ended if RTSP stream ends while using LowLatencyVideo.

### ISSUE THREAD

**Issue by anguzo** [SuRGeoNix/Flyleaf#248]
The output I get when RTSP stream ends when using LowLatencyVideo is:
```
10.21.29.541 | Debug | [#1]     [Demuxer:  Main] Running -> Ended
10.21.29.541 | Debug | [#1]     [Demuxer:  Main] Thread stopped (Ended)
10.21.29.545 | Debug | [#1]     [Decoder: Video] Draining
10.21.29.545 | Debug | [#1]     [Decoder: Video] Draining -> Ended
10.21.29.545 | Debug | [#1]     [Decoder: Video] Thread stopped (Ended)
```

Output when using AVS:
```
10.26.28.365 | Warn  | [#1]     [Player        ] No video frames
10.26.28.365 | Debug | [#1]     [Player        ] OnBufferingStarted
10.26.29.268 | Debug | [#1]     [Demuxer:  Main] Running -> Ended
10.26.29.268 | Debug | [#1]     [Demuxer:  Main] Thread stopped (Ended)
10.26.29.277 | Debug | [#1]     [Decoder: Video] Draining
10.26.29.277 | Debug | [#1]     [Decoder: Video] Draining -> Ended
10.26.29.277 | Debug | [#1]     [Decoder: Video] Thread stopped (Ended)
10.26.29.291 | Info  | [#1]     [Player        ] Stopped
10.26.29.291 | Debug | [#1]     [Player        ] OnBufferingCompleted
10.26.29.291 | Warn  | [#1]     [Player        ] [MediaBuffer] No video frame
10.26.29.291 | Info  | [#1]     [Player        ] Finished -> 00:00:08.4184666
10.26.29.291 | Debug | [#1]     [Player        ] [SCREAMER] Finished (Status: Ended, Error: )
```

Output when using ZeroLatencyAudioVideo:
```
10.28.04.282 | Debug | [#1]     [Demuxer:  Main] Running -> Ended
10.28.04.282 | Debug | [#1]     [Demuxer:  Main] Thread stopped (Ended)
10.28.04.303 | Debug | [#1]     [Decoder: Video] Draining
10.28.04.303 | Debug | [#1]     [Decoder: Video] Draining -> Ended
10.28.04.303 | Debug | [#1]     [Decoder: Video] Thread stopped (Ended)
10.28.04.306 | Debug | [#1]     [Player        ] Latency: 0ms | Speed: 1 | Sleep: 40ms | AvgFD: 40ms | Diff: 1863ms
10.28.04.348 | Debug | [#1]     [Player        ] [SCREAMER] Finished (Status: Ended, Error: )
```

The output also correspond to behavior, I checked that Player.PropertyChanged does not fire Status Ended.

**Comment by anguzo** [comment]
I actually tested all Usage options at some point and indeed ZeroLatency was lower latency than LowLatency and LowLatency lower latency than AVS. But I also encountered buggy behavior when using zero latency with older generation ONVIF camera so settled for LowLatency. 
So you say that setting MaxLatency in Config to 500ms will be equivalent to LowLatency? So setting MaxLatency basically defines how packets in the end of stream are disposed? I thought that different screamers also dispose of packets differently, but if it is defined by this option then there is no real need for other low latency implementations.

If you have something special in mind regarding camera testing, I might be able to do some testing for you.

**Comment by SuRGeoNix** [comment]
MaxLatency its another low latency (so you dont have to change the usage, leave the default to AVS). It uses the main code of the playback which is more stable, can use audio as well. It works by "pushing" the demuxers and decoders at end by changing the playback speed so it will not be like dropping frames.

**Comment by anguzo** [comment]
I have a video server which streams RTSP stream and also utilizes input matrix. This server is quite old so it can't automatically change input format and resolution when I change input in the matrix. Basically I a had problem where on input change input format would change before playback start which lead to player trying to play while format changes, failing since stream is recreated when format is changed and it did not reconnect since RTSP does not support auto reconnect.
When RTSP stream ends in such unexpected manner in LowLatency it did not fire Status Ended and I hasn't been able to manually reconnect to this device(input format and resolution might change, but address is still the same) since I could not determine when stream interrupted. Using AVS with MaxLatency solves this for me.
So yeah, such kinda complicated use case :)

I can test different latency options. What combinations of options in comparison to Usages are you interested in?
You have my Skype so write me there or we can discuss when it's suitable.

**Comment by SuRGeoNix** [comment]
If you can confirm that with MaxLatency everything works as expected then I guess I could get rid of the other zero/low latency methods as they use different code (screamers) and could cause other issues. I will not be available to discuss this today but we can do this another time. Even in your complicate case I guess you could handle this (see #240) with the timeout event.

**Comment by anguzo** [comment]
Overall, I tested Zero, Low, 100ms and 500ms latency as well as stock. I placed a timer to compare latencies between them:
1) Stock - 36.40
2) MaxLatency=500 - 36.76
3) MaxLatency=100 - 37.02
4) Zero - 36.99
5) Low - 36.99
Strangely zero and low latency showed the same time, but I confirm that setting max latency indeed is quite precise and can replace them both.

**Comment by SuRGeoNix** [comment]
Nice analysis! Stock you mean by not setting the MaxLatency at all?

**Comment by anguzo** [comment]
> Stock you mean by not setting the MaxLatency at all?

Yes, not setting MaxLatency nor specifying Usage.
