### ISSUE TITLE
NullReferenceException with WinForms sample

### ISSUE THREAD

**Issue by Foudge** [SuRGeoNix/Flyleaf#249]
Hi, with WinForms sample, when Engine.Start is called, I have a NullReferenceException here : https://github.com/SuRGeoNix/Flyleaf/blob/ec921886c73669f5c1670e4820fd6bd92962dece/FlyleafLib/Utils/Utils.cs#L97
In WinForms applications, Application.Current seems to be null.
If I replace Application.Current.Dispatcher with System.Windows.Threading.Dispatcher.CurrentDispatcher, the WinForms sample works... and the WPF sample works too !
I think you can replace the recovery of current dispatcher on lines 82, 89, 97 and 100. The #if DEBUG section (lines 77->80) can be deleted.
Thank you for your work 👍

**Comment by SuRGeoNix** [comment]
Hi @Foudge, hopefully now everything works fine. By changing the Engine to StartAsync it caused a number of issues. Let me know if you still have issues

**Comment by Foudge** [comment]
Yes, the WinForms sample of the last master source code is ok, and my personnal project with nuget package 3.6.9 too 👍
