### ISSUE TITLE
How to redirect to my MouseWheel handler  ?

### ISSUE THREAD

**Issue by LauraKami** [SuRGeoNix/Flyleaf#251]
Hi,
I want to replace the use of Shift MouseWheel by my code.

```
        private void PubPlayer_PreviewMouseWheel(object sender, MouseWheelEventArgs e)
        {
            if (_pubPlayer == null || e.Delta == 0)
                return;

            if ((Keyboard.IsKeyDown(Key.LeftShift) || Keyboard.IsKeyDown(Key.RightShift)))
            {
                if (e.Delta > 0)
                    _pubPlayer.ShowFrameNext();
                else
                    _pubPlayer.ShowFramePrev();

            }
        }

```

But I did not find a solution to redirect the event to my code.

```
                <fl:FlyleafHost x:Name="PubPlayer" Grid.Row="0"
                Player="{Binding WpfPlayer}" PanRotateOnShiftWheel="None" MouseBindings="None"
                PreviewMouseWheel="PubPlayer_PreviewMouseWheel" />
```
Help or example are welcome ;o)

Also, specifically for the zoom, is there a way to find a match between the zoom value and a comprehensible value like x2 x3 x10 or 1/2 1/4 ?

**Comment by SuRGeoNix** [comment]
Hi @LauraKami, FlyleafHost gives you 3 different levels (the hosted WPF control, the Surface window and the Overlay window). I guess what you want is to assign this event to both Surface/Overlay windows. Subscribe by using the PubPlayer.Surface.MouseWheel and PubPlayer.Overlay.MouseWheel events and set the PubPlayer.PanZoomOnCtrlWheel and/or PanRotateOnShiftWheel  to false (as you will handle this manually).

For the Zoom x2 you can use the current zoom value from Player.Zoom (which is pixel) and calculate the value that you want (eg. x2 will be the number of pixels of the whole frame / 2)

Let me know, if you need more help and I might give write an example for you when I will be available!

**Comment by LauraKami** [comment]
Thank you, for the Wheel it works very well.
For the zoom it is less clear, the value is 0 for 1x zoom, and the range -150 to +10000.
When you can, an example will be simpler. ;o)

**Comment by SuRGeoNix** [comment]
Yes, this is one is complicated and is related to #247 
I will need to implement this with zoom percentage instead of number of pixels to make your life easier. So give me sometime to review this and I will let you know.

**Comment by SuRGeoNix** [comment]
@LauraKami I've changed the zoom so you can use it as percentage now (default:100% and valid values 1-Max %). You can use the Player.ZoomIn/ZoomOut (based on center point or pass the mouse pointer) with the Config.Player.ZoomOffset (percentage as well). If you want to use your custom way you can set the Player.Zoom manually. Let me know if you need more help.

**Comment by LauraKami** [comment]
Yes, I tested on the demo, it works very well,
- the zoom under the cursor is a great improvement,
-  as well as the protection from losing the video outside the surface (due to too large panX/Y) .
I will integrate it as soon as it is in the nugget.
Thank you so much

**Comment by SuRGeoNix** [comment]
Great, just updated also the NuGet
