### ISSUE TITLE
Hardware decode on WMWare ?

### ISSUE THREAD

**Issue by pubpy2015** [SuRGeoNix/Flyleaf#252]
Hi,

I am running Flyleaf v3.6.10 on server create by WMWare with 4xTesla T4 but I dont know why VideoAcceleration = False:
![ảnh](https://user-images.githubusercontent.com/59004953/220558315-690c2563-24f8-4f04-852a-b46b46b89c2b.png)

![ảnh](https://user-images.githubusercontent.com/59004953/220557436-d608a35f-ceb4-4580-8a25-e89620d4f611.png)

Does the TeslaT4 not support Hardware video decode or Flyleaf can't load these cards on this server ?

**Comment by pubpy2015** [comment]
![ảnh](https://user-images.githubusercontent.com/59004953/220558405-d46b0db7-ada3-4327-89e4-43790b471451.png)

**Comment by SuRGeoNix** [comment]
Hi @pubpy2015, check the log to see which card Flyleaf uses. You might need to force it to use the T4.

**Comment by pubpy2015** [comment]
Here is log but seem dont have any TeslaT4

15.14.45.652 | Info  | [FlyleafEngine] FlyleafLib 3.6.10
15.14.45.659 | Info  | [FlyleafEngine] Loading FFmpeg libraries from ':FFmpeg'
15.14.45.718 | Info  | [FlyleafEngine] FFmpeg Loaded (Location: C:\Users\Administrator\Downloads\Flyleaf_v3.6.10\FFmpeg, Ver: 59.27.100, #Files: 4)
15.14.45.733 | Info  | [FlyleafEngine] GPU Adapters
[#1] Unknown Microsoft Basic Render Driver   [ID: 140   , LUID: 53399 , DVM: 0 B     , DSM: 0 B     , SSM: 96 GB]
[#2] Unknown Microsoft Basic Render Driver   [ID: 140   , LUID: 53666 , DVM: 0 B     , DSM: 0 B     , SSM: 96 GB]
[logs.txt](https://github.com/SuRGeoNix/Flyleaf/files/10801453/logs.txt)

**Comment by SuRGeoNix** [comment]
It seems that there is something wrong with your configuration in VMWare and GPUs. Can you confirm that this is Flyleaf's issue? Use VLC with FFmpeg demuxer maybe? or FFplay? (Did you check also the requirements for VM/WM? (Ware) to use Tesla T4 with hardware acceleration for Direct X?)

**Comment by pubpy2015** [comment]
Realy i dont know about VMWare.
Only see this config in sSphere Client:
![ảnh](https://user-images.githubusercontent.com/59004953/220807512-2c9fe024-a095-4ba0-a4c5-9dfbdf58e4e9.png)
![ảnh](https://user-images.githubusercontent.com/59004953/220807576-8dff7504-48c6-41a0-b596-306071758e0f.png)

Tesla T4 dont have video output (HDMI, DisplayPort), so Flyleaf still enumerates these GPU adapter ?
https://www.techpowerup.com/gpu-specs/tesla-t4.c3316

**Comment by SuRGeoNix** [comment]
I'm not familiar with virtual GPUs either. You will need to ensure that the configuration is right and then see if Flyleaf can support it or needs few changes to make it work. Currently, it seems that it cannot even find the GPU adapters (shows only ms basic renderers / warp software devices). From a quick look, it requires an nvidia GRID configuration for the vGPU (should check both nvidia's manual and vsphere's).

1) https://docs.nvidia.com/grid/latest/grid-software-quick-start-guide/index.html

2) https://blogs.vmware.com/apps/2018/09/using-gpus-with-virtual-machines-on-vsphere-part-3-installing-the-nvidia-grid-technology.html

**Comment by pubpy2015** [comment]
Hi,

I am trying run ffmpeg to encode a video by this command:
ffmpeg -hwaccel_device 1 -hwaccel cuda -i input.mp4 -c:v hevc_nvenc output.mp4
and it's works!
So i think there is a way to force ffmpeg in Flyleaf using GPU to decode video.
![ảnh](https://user-images.githubusercontent.com/59004953/221793983-56e71628-1b82-448e-be85-1cca7eb29b35.png)

**Comment by SuRGeoNix** [comment]
@pubpy2015 you use cude with FFmpeg, Flyleaf uses d3d11va. Does it work with d3d11va?

**Comment by pubpy2015** [comment]
No, it doesn't work with d3d11va.
I am trying to change the following:
![ảnh](https://user-images.githubusercontent.com/59004953/221820924-9ed74104-fc25-4906-a31d-d8baac3f7423.png)

application crash, but in log file there is "VA Success":

![ảnh](https://user-images.githubusercontent.com/59004953/221822236-6f62b87e-2110-4e2e-a256-8262e7619356.png)

**Comment by pubpy2015** [comment]
Do you think Tesla T4 don't have output => can not render with GPU but still decode with GPU ?
or can i setting Flyleaf using GPU to decode video and using CPU to render frame ?

**Comment by SuRGeoNix** [comment]
It probably works properly for decoding with CUDA but you hardware frame cannot be transferred to the D3D11 renderer. I don't think there is an easy way to make work like that. You should see how you can make TESLA to work with D3D11.

**Comment by SuRGeoNix** [comment]
I found also this that might be related

```
From Nvidia Driver Release Notes:
Note that for using graphics APIs on Windows (i.e. OpenGL, Vulkan, DirectX 11 and DirectX 12) or any WDDM 2.0+ based functionality on Tesla GPUs, vGPU is required. See the vGPU documentation for more information.

Downloaded Nvidia trial vGPU driver. Everything worked just fine.
```

**Comment by pubpy2015** [comment]
Sorry, now i can not setup anything relate to VMWare or driver.
I am trying to decode by cuda
const AVHWDeviceType HW_DEVICE = AVHWDeviceType.AV_HWDEVICE_TYPE_CUDA;
static int HW_PIX_FMT = (int)AVPixelFormat.AV_PIX_FMT_CUDA;

How to modify in VideoDecoder to do this ?

**Comment by SuRGeoNix** [comment]
I'm afraid that will not be easy. I'm not sure what pixel formats will be supported from CUDA and how you will render them with D3D11. This is related to https://github.com/SuRGeoNix/Flyleaf/issues/216 and I will try to support different hardware accelerations for decoding and also for rendering to support multi-platform. VideoDecoder is currently designed only to support D3D11. I'm closing this but let me know if you need more info.
