### ISSUE TITLE
Question about multiple program transport stream

### ISSUE THREAD

**Issue by HamidLaktarash** [SuRGeoNix/Flyleaf#254]
Hi John. here is correct repository.
sorry for answering late
I work on your help -> open method overload with no default
Player.Open("udp://@228.110.2.1:1234", false);
Player.Open("udp://@228.110.2.1:1234", false, false, false, false);
but can you explain how I choose a program after open call.
In addition I got some problem:
1- I call method Player.Open("udp://@228.110.2.1:1234",); Player paly one program without sound (no Audio stream) and after few second 'buffering failed' error appear in window screen and pause stream forever. I increase bufferDuration and minbufferDuration 
in configuration but it did not hlep.
2- please see your Gmail
would you mind helping me to demux stream and extract right programs and manipulate your code in MainDemuxer
send me some sample code if you can.
is there any way to extract video & audio stream with SID or PMT in mpeg stream

**Comment by SuRGeoNix** [comment]
Hi @HamidLaktarash, didn't have a look into it yet but did you check the ffmpeg options? https://ffmpeg.org/ffmpeg-formats.html

I think you are looking for scan_all_pmts ?

**Comment by SuRGeoNix** [comment]
@HamidLaktarash, any news on this one? Can you provide me a working url?

**Comment by HamidLaktarash** [comment]
thanks for your reply.
unfortunately i can`t provide you a working URL , because it is in a local network and it is impossible share through internet.
however I read https://ffmpeg.org/ffmpeg-formats.html and your codes (flyleaf), I hope my problem will fix.
can you refer me some trick or FFmpeg.AutoGen method ?

**Comment by HamidLaktarash** [comment]
Hi. few minutes ago I add `defaults.Add("scan_all_pmts",  "1");` to DefaultVideoFormatOpt in Config.cs file and nothing changes.
my IPTV stream has multiple stream with deffrent transportStreamID, Apparently Player fetch first stream and remain other streams and first stream with TransportStreamID=600 has 28 program but no audio and video
I want fetch second stream with TransportStreamID=102 in avformat_open_input() method.
Do you have any solution for my problem?
I send you an email with screenshot image from TransEdit IPTV software. do you see it?
sorry if i bother you!!!

**Comment by SuRGeoNix** [comment]
Hi @HamidLaktarash, Flyleaf's programs are based on this https://ffmpeg.org/doxygen/trunk/structAVProgram.html

I'm not sure if Flyleaf miss some functionality or you need to pass the right options to FFmpeg (use Config.Demux.FormatOpt to add/edit existing format options). I'm not familiar with all those IDs that you mention, can you confirm that with the sample version you can't find the stream that you want? Can you provide a full trace log? If Flyleaf misses this functionality I will try to add it (VLC might not using FFmpeg for that, it's possible that FFmpeg does not support it)

**Comment by HamidLaktarash** [comment]
Hi John Stamatakis. it`s me again!
I am trying to capture all my mpeg stream ("udp://@228.110.2.1:1234") with all its streams via FFMpeg to a .ts file, till i send you .ts file and you can check this file.

**Comment by SuRGeoNix** [comment]
Feel free to ask if you still need more help

**Comment by HamidLaktarash** [comment]
I am sorry. i couldn't
