### ISSUE TITLE
FlyleafHost.Wpf: Single Overlay for Multiple FlyleafHosts

### ISSUE THREAD

**Issue by DatDevSc** [SuRGeoNix/Flyleaf#255]
Hi,

Is there any solution to display some control over multiple players?

![image](https://user-images.githubusercontent.com/37483861/224058118-dace2a8b-ca33-4ca1-977c-94843f56075a.png)

**Comment by SuRGeoNix** [comment]
That's a good question. I think I was able to make it work with stand alone and multiple flyleafhosts inside it and after loading (important to do it afterwards) setting the always on top for the main Flyeafhost (stand alone). I will have to look in to it as WPF is not very happy with childs/grand-childs etc.

**Comment by SuRGeoNix** [comment]
Trying to find the best way to support this. With the new FlyleafHost it's easier to handle the z-order. Currently, it 'BringToFront' the FlyleafHost that you click (MouseDown). I could add a list of FlyleafHost's with the same Parent and inform when I change the z-order so then you could have your own window and 'BringToFront' it then so it can always be on top of the other's. Any suggestions are welcome. Possible add a new Window (Helper) that will have this functionality embedded.

**Comment by SuRGeoNix** [comment]
@DatDevSc Check my last commit and let me know what you think (You can test it with Tests/WpfFlyleafHost check the commit for the changes). Currently it will require to call BringToFront only if you use also detaching for the hosts.
