### ISSUE TITLE
Why can't players be deleted asynchronously on the UI

### ISSUE THREAD

**Issue by cxgym** [SuRGeoNix/Flyleaf#258]
Don't support it？

**Comment by SuRGeoNix** [comment]
Please provide more information. Are you talking only about the Players or for the FlyleafHosts? WPF or Winforms? For WPF it requires to set the FlyleafHost.Player DP from UI, might that causes your issue? https://github.com/SuRGeoNix/Flyleaf/blob/master/FlyleafLib/MediaPlayer/Player.cs#L485

**Comment by cxgym** [comment]
I use wpf. I want to clear multiple VideoViews on the UI. I want to implement it asynchronously, but it is not successful. The UI interface will be stuck for about 1s

**Comment by cxgym** [comment]
flyleaf v3.5.10

**Comment by SuRGeoNix** [comment]
@cxgym in v3.6 a number of issues (including performance issues) have been fixed by replacing the VideoView with FlyleafHost. Please test with the latest version let me know if the issue still exists

**Comment by cxgym** [comment]
![image](https://user-images.githubusercontent.com/20064260/224673246-c5dd42e2-6998-4b11-b9b7-1cd75e7ec012.png)

**Comment by cxgym** [comment]
v3.6.10 debug error，How to solve？thank you

**Comment by SuRGeoNix** [comment]
I don't see your code so can't really help you. Probably you create dynamically a FlyleafHost in the wrong way. If you need to create a single new player/window use stand alone mode (check https://github.com/SuRGeoNix/Flyleaf/blob/master/Tests/WpfFlyleafHost/OverlayStandAlone.xaml.cs)

**Comment by cxgym** [comment]
ok,Thank you

**Comment by SuRGeoNix** [comment]
@cxgym Closing this and let me know if you still have issues with v3.6 (check Tests/Samples/Wiki to help you with the integration and let me know if you still have issues)
