### ISSUE TITLE
Video Acceleration False on PC with Quadro RTX4000

### ISSUE THREAD

**Issue by pubpy2015** [SuRGeoNix/Flyleaf#259]
Hi,

I am using FlyLeaf on PC with CPU Intel Core i9-11900K + RAM 32 GB + Dual Quadro RTX 4000 to play a rtsp stream from camera.
Because FlyLeaf can not decode on GPU, => it using 3.5 % CPU and 4.7% GPU
![ảnh](https://user-images.githubusercontent.com/59004953/224916300-304b9065-1461-4af7-8d8c-9cb270850bcd.png)

VLC work fine with 0.2 % CPU and 12% GPU
![ảnh](https://user-images.githubusercontent.com/59004953/224916773-6a95bd5d-7865-4855-a6e4-f2c7823b87d7.png)

This is log file of flyleaf.
Please help me to debug.
![ảnh](https://user-images.githubusercontent.com/59004953/224917697-d81a57e4-96a0-4480-8138-45e44ff0f0a2.png)

[Flyleaf.FirstRun.zip](https://github.com/SuRGeoNix/Flyleaf/files/10964853/Flyleaf.FirstRun.zip)

**Comment by SuRGeoNix** [comment]
Can you try set profilemismatch to true?

**Comment by pubpy2015** [comment]
Yes, now it works.
Why you don't set profilemismatch default to true ?
![ảnh](https://user-images.githubusercontent.com/59004953/224927010-a28e5bb9-8c46-469d-8107-187e10fa5309.png)

**Comment by SuRGeoNix** [comment]
I've seen it causing problems, that's why by default is off. I'm not sure if it is possible to predict when it could cause issues so I could add an 'auto' option, with default on and also avoid the cases that causes issues. I would try to review mpv/vlc code how they handle this.

**Comment by pubpy2015** [comment]
thanks

**Comment by pubpy2015** [comment]
I am seeing you specify a GPU adapter by:
![ảnh](https://user-images.githubusercontent.com/59004953/224965812-d962cdad-3e6b-406b-b09b-f119aa53176b.png)

incase of list of GPU adapter like that, all GPU adapters has same description, how to specify a GPU adapter for video decoding
![ảnh](https://user-images.githubusercontent.com/59004953/224966105-9c49253e-fdf4-4338-91e6-fcd19691b876.png)

**Comment by SuRGeoNix** [comment]
Yes, but be advised, that luid is possible to change after system restart.
