### ISSUE TITLE
How can I set oauth2 token in the authorization header in order to reproduce an hls stream?

### ISSUE THREAD

**Issue by robertorossinivigilate** [SuRGeoNix/Flyleaf#261]
Hi, 
I'm trying to play a hls video stream that requests an OAUTH2 token in Authorization header.
How can I properly set this token?
Thanks in advance.

**Comment by SuRGeoNix** [comment]
Hi @robertorossinivigilate, you can add this through [FFmpeg format options](https://ffmpeg.org/ffmpeg-formats.html#Options-10). Just add the "headers" through Config.Demuxer.FormatOpt["headers"]

You can check how yt-dlp plugin does it [here](https://github.com/SuRGeoNix/Flyleaf/blob/master/FlyleafLib/MediaFramework/MediaContext/DecoderContext.Open.cs#L863)

**Comment by robertorossinivigilate** [comment]
It worked, thank you!
