### ISSUE TITLE
high Ram utilization 

### ISSUE THREAD

**Issue by lkinfotechai** [SuRGeoNix/Flyleaf#262]
flyleaf player is taking high ram resource,

1. i am using multiple flyleaf players for display rtsp streams,per camera rtsp stream ram is about 200-300mb, which is quite high. any solution for the same?
can e do something like vlcsharp lib which is very light weight in terms of ram or cpu.

**Comment by SuRGeoNix** [comment]
Hi @lkinfotechai, you will need to check Flyleaf's and FFmpeg's configuration options. You can minimize demuxer's buffer duration, max audio / video decoded frames/samples and pass flags/options to FFmpeg such as NOBUFFER. Let me know if you will need more information how you can achieve this.

**Comment by SuRGeoNix** [comment]
@lkinfotechai I can confirm that it will reduce a lot of ram by settings

```csharp
Config.Player.MinBufferDuration = 0;
Config.Demuxer.BufferDuration = 0;
```

Let me know if that's good enough for you

**Comment by sharmasulekh87** [comment]
> @lkinfotechai I can confirm that it will reduce a lot of ram by setting
> 
> ```cs
> Config.Player.MinBufferDuration = 0;
> Config.Demuxer.BufferDuration = 0;
> ```
> 
> (However, I would recommend to use at least 3 seconds for BufferDuration. Another note if you use MaxLatency it will adjust BufferDuration automatically)
> 
> Let me know if that's good enough for you

I have tried doing it but it do not make any difference, still the same amount of memory is being consumed.

**Comment by SuRGeoNix** [comment]
So @sharmasulekh87 you are also @lkinfotechai or another user that you have the same issue? I'm pretty sure that flyleaf is really light with resources so I will need more details if that actually happens. The only way that I can imagine that VLC uses less memory would be that for some reason Video Acceleration is not working and instead of VRAM it uses RAM. Flyleaf does not really use any RAM at all, all the allocations will be done by FFmpeg.

**Comment by sharmasulekh87** [comment]
What should be the value of max audio / video decoded frames/samples to achieve less memory usage?

**Comment by SuRGeoNix** [comment]
The ideal values are the defaults https://github.com/SuRGeoNix/Flyleaf/blob/master/FlyleafLib/Engine/Config.cs#L417

You can simple disable audio and see if you have any huge difference with the RAM allocations. Please provide a comparison with other media player to see the difference.

**Comment by sharmasulekh87** [comment]
![image](https://user-images.githubusercontent.com/78798753/225841558-20fd122d-2b46-47f3-844a-0d3acf9c9ee9.png)
memory frequently goes up to 200Mb as well

**Comment by SuRGeoNix** [comment]
@sharmasulekh87 That does not tell me much. How many inputs have you opened (you should see the difference while opening one more/a new input)? Does VA work in Flyleaf? Does VLC use FFmpeg for demuxing? You could even try a memory analyzer to see what allocations Flyleaf does but I don't think you will see anything there as FFmpeg does them.
