### ISSUE TITLE
How can I play multiple video files (local mp4 files or uris) sequentially?

### ISSUE THREAD

**Issue by robertorossinivigilate** [SuRGeoNix/Flyleaf#266]
Hello, 
I need to play a list of video files sequentially, but I don't understand how do it in the right way. May I use playlist?
Thanks in advance.

**Comment by SuRGeoNix** [comment]
Hi @robertorossinivigilate, you can either create a playlist temp file (that flyleaflib supports) or having your own playlist at your app level. Currently, FlyleafLib does not support automatically to play the next file in playlist but you can easily implemented by listening to Player.PropertyChanged event and check the Player.Status property if equals to Status.Ended so you can start the next mp4 file. Let me know if you need more help.

**Comment by robertorossinivigilate** [comment]
Thank you for your answer. I suppose that best way to implement what I need is to create a playlist at app level. Where can I find some examples of playlist implementation at app level?

**Comment by robertorossinivigilate** [comment]
Maybe I was not clear: I need some examples to implement Playlist with many PlayListItems, because I want to use OpenAsync(PlaylistItem item) method.
I found something in YoutubeDL and TorrentBitSwarm, but I need something more simple, just like a list of file uris whithin a playlist, in order to call Player.OpenAsync and pass the selected PlaylistItem.
Should I implement this way, or better use a list of strings with file uris inside, and then call Player.OpenAsync(string url)?
