### ISSUE TITLE
Player customization

### ISSUE THREAD

**Issue by robertorossinivigilate** [SuRGeoNix/Flyleaf#268]
Hello, 
I need to show a custom popup menu that open on right click, how can I show it properly? It seems that Flyleaf player avoid every kind of overlay.
Another question: sometime, opening a file uri and then pausing it, Flyleaf player doesn't show first frame. Is there a best way to do that? 
Thanks in advance.

**Comment by SuRGeoNix** [comment]
are you using WPF or WinForms?
for the 2nd question yes... you need to disable the Player.Config.Player.AutoPlay and register to Player.OpenCompleted (check e.Success) and then Player.Seek(0) eg:-

```csharp
Player.Config.Player.AutoPlay = false;
Player.OpenCompleted += (o, e) =>
{
        if (!e.Success) return;
	Player.Seek(0);
};
```

**Comment by robertorossinivigilate** [comment]
I'm using WPF.. I'll check MultipleAttached example, it seems to be useful..
For the second question, your trick works fine!
Thanks you!

**Comment by SuRGeoNix** [comment]
Read also the Wiki. You need to understand how FlyleafHost works on WPF and how to solve the airspace issues. It creates a different window. Make sure your bindings/resources and your popup is on the overlay. Let me know if you need more help.
