### ISSUE TITLE
Open and playback a plenty of Flyleaf players on the same wpf control

### ISSUE THREAD

**Issue by robertorossinivigilate** [SuRGeoNix/Flyleaf#273]
Hello, 
I'm developing a security videowall application; is it possible open up to 60 flyleaf player in the same wpf control, and playback/pause/change speed on all of them? 
If yes, which is the best configuration to do that, in order to avoid memory leak, out of memory exception, high ram/cpu consuming?
The source of each player can be local or remote mp4 files (full hd and sometimes 4k).
Thanks.

**Comment by SuRGeoNix** [comment]
Hi @robertorossinivigilate 

It's impossible to play 60 players at the same time especially in 4K resolutions.
You need to find a better way to implement this (don't play all at the same time, don't use good resolutions at all players, etc.)

Config.Demuxer.MaxBufferDuration is the main config that you need to change to something small so you will not have high RAM usage from the demuxed packets.
