### ISSUE TITLE
CurTime property is not right for some .m3u8 url,following figure,Can you give me a hint as to why

### ISSUE THREAD

**Issue by cxgym** [SuRGeoNix/Flyleaf#274]
![image](https://user-images.githubusercontent.com/20064260/230379595-32eae88a-a124-4cad-8cda-ecb4b1a206cf.png)

**Comment by SuRGeoNix** [comment]
@cxgym please be more specific when you ask a question and try to give more information. Can you attach or send me a log file?

**Comment by cxgym** [comment]
[25384-player-2023-04-06.log](https://github.com/SuRGeoNix/Flyleaf/files/11171201/25384-player-2023-04-06.log)

**Comment by cxgym** [comment]
I only have 5 minutes of this video clip,But the timestamp returned 7 minutes

**Comment by cxgym** [comment]
it not necessarily, some url is right curtime have within 10s

**Comment by cxgym** [comment]
flyleaf v3.6.10 pre didn't  have this problem,It may be URL authentication cause it？

**Comment by cxgym** [comment]
https://*/record/20230314000005.ts?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=*&X-Amz-Date=20230406T131801Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-Amz-Signature=*

**Comment by cxgym** [comment]
Sorry, I cannot provide a complete url

**Comment by cxgym** [comment]
[Trace_11080-player-2023-04-06.log](https://github.com/SuRGeoNix/Flyleaf/files/11171519/Trace_11080-player-2023-04-06.log)

**Comment by cxgym** [comment]
![image](https://user-images.githubusercontent.com/20064260/230406595-8aa53465-d676-4c8a-b0bb-85bba31f184e.png)

**Comment by cxgym** [comment]
![image](https://user-images.githubusercontent.com/20064260/230406772-0bcd2318-ad70-476e-9d3a-759257dee818.png)

**Comment by cxgym** [comment]
Do you mean there is a problem with this URL itself？

**Comment by SuRGeoNix** [comment]
The source (not the url itself) announces wrong timestamps

**Comment by cxgym** [comment]
The Format and Audio starts at 04:53 while video starts at 05:00 (7 minute difference).   I seem to understand a bit,CurTime is video timestamps should be reduce 7 minute difference？

**Comment by cxgym** [comment]
CurTime is audio starts calculate？

**Comment by cxgym** [comment]
Thank you

**Comment by swimfish09** [comment]
> This is what the Url (format) announces:
> 
> ```
> [Format  ] Apple HTTP Live Streaming/hls |  | 04:53:37.9179330/00:04:59.9950000 | 04:53:37.9179330/00:04:59.9950000
> [Video #1] h264 yuvj420p 1920x1080 @ 25 | [Color: BT709] [BR: 0] | 05:00:41.2779333/-10675199.02:48:05.4775808 | 05:00:41.2779333/00:04:59.9950000
> [Audio #0-eng] pcm_alaw s16@8 8KHz mono | [BR: 64000] | 04:53:37.9179333/-10675199.02:48:05.4775808 | 04:53:37.9179333/00:04:59.9950000
> ```
> 
> The Format and Audio starts at 04:53 while video starts at 05:00 (7 minute difference). The Format's duration is 5 minutes which means from 04:53 to 04:57 so how can the video start at 05:00? The Url announces wrong timestamps.

Can we just use video timestamp, Vlc can play the video well.

**Comment by swimfish09** [comment]
If the audio timestamp and video timestamp are not synchronized,  there will be problems with the recorded file.

**Comment by SuRGeoNix** [comment]
Did you try VLC with AV demuxer (from options->Demuxers)? There is a possibility that ffmpeg gives the timestamps wrong. Might worth trying using latest ffmpeg v6 (use FFmpeg.Autogen v6 nuget in your app to make it work).
I'm not sure what you suggest. How Flyleaf suppose to fix the wrong timestamps?

**Comment by cxgym** [comment]
![image](https://user-images.githubusercontent.com/20064260/230905612-5a4b19a3-dc82-40b3-bd31-f017678fe8cb.png)

**Comment by SuRGeoNix** [comment]
Probably requires transcoding which is currently not supported. You can force a format eg (.mp4) by specifying the extension of the filename (if you did that already let it find it manually). Please provide more info if you want help, I will stop answering in questions like that.

**Comment by cxgym** [comment]
![21932b346a2e3ce4a4a6f7b3b3cd0d4](https://user-images.githubusercontent.com/20064260/233349178-adfbcb77-1868-4596-83f5-61f8111f1988.png)

**Comment by cxgym** [comment]
I don't quite understand why there were occasional errors reported here

**Comment by cxgym** [comment]
Then it will black screen

**Comment by SuRGeoNix** [comment]
If you enable Logging we will all know (guessing you got an error before that about something)

**Comment by cxgym** [comment]
[23576-player-2023-04-20.log](https://github.com/SuRGeoNix/Flyleaf/files/11285779/23576-player-2023-04-20.log)

**Comment by cxgym** [comment]
I asynchronously open three players, load one stream separately, and then stop one stream. Reopening another stream in the original player will result in a black screen

**Comment by SuRGeoNix** [comment]
```
19.27.15.753 | Warn  | [#2]     [Renderer      ] Initialization failed (An item with the same key has already been added. Key: Contrast). Failling back to WARP device.
```

**Comment by cxgym** [comment]
what si this key?

**Comment by SuRGeoNix** [comment]
It is indeed an issue whey you start multiple players async. I will fix it.

**Comment by cxgym** [comment]
Ok, I'll first change it to synchronous, because our business has a one click playback function that requires asynchronous effects. Thank you very much.

**Comment by SuRGeoNix** [comment]
Just to make it clear, the issue is when you initialize players async no opening an input.

**Comment by cxgym** [comment]
![image](https://user-images.githubusercontent.com/20064260/233529615-1807969c-0589-41da-9cd5-f4ddf031bc1f.png)

**Comment by cxgym** [comment]
asynchronous batch player.stop() stream, Player.Playback.Stop() in renderer can trigger exception, renderer is null, it is accidental

**Comment by cxgym** [comment]
renderer?.Flush(); this can solve it? this will cause any other problems?

**Comment by cxgym** [comment]
App.App_DispatcherUnhandledExce:::message=System.NullReferenceException: Object reference not set to an instance of an object.
at Vortice.Direct3D11.ID3D11VideoDevice.CreateVideoProcessorOutputView(ID3D11Resource resource, ID3D11VideoProcessorEnumerator enum, VideoProcessorOutputViewDescription desc, ID3D11VideoProcessorOutputView& videoProcessorOutputViewIew)
at FlyleafLib.MediaFramework.MediaRenderer.Renderer.ResizeBuffers(Int32 width, Int32 height) in D:\*\flyleaf-core\MediaFramework\MediaRenderer\Renderer.SwapChain.cs:line 384
at FlyleafLib.MediaFramework.MediaRenderer.Renderer.InitializeSwapChain(IntPtr handle) in D:\*\flyleaf-core\MediaFramework\MediaRenderer\Renderer.SwapChain.cs:line 100
at FlyleafLib.MediaFramework.MediaRenderer.Renderer.Initialize(Boolean swapChain) in D:\*\flyleaf-core\MediaFramework\MediaRenderer\Renderer.Device.cs:line 236
at FlyleafLib.MediaFramework.MediaRenderer.Renderer.Flush() in D:\*\flyleaf-core\MediaFramework\MediaRenderer\Renderer.Device.cs:line 321
at FlyleafLib.MediaPlayer.Player.Stop() in D:\*\flyleaf-core\MediaPlayer\Player.Playback.cs:line 295

**Comment by SuRGeoNix** [comment]
@cxgym I pass the fixes to the latest versions and you use other versions and you don't even mention it. That's version 3.7.0.
Open a new issue (if still exists in latest ver.) so I can keep track easier and give enough information so I can fix it faster and easier :)

**Comment by cxgym** [comment]
![image](https://user-images.githubusercontent.com/20064260/233578646-dfc92cdf-96a8-4543-9e85-0bab385b450e.png)

**Comment by cxgym** [comment]
set Config.Player.Stats = true will have thread secure problem

**Comment by cxgym** [comment]
![image](https://user-images.githubusercontent.com/20064260/233580747-83ab7e63-60c5-4d02-a7a5-e5df7ad5e44f.png)

**Comment by SuRGeoNix** [comment]
I don't see the issue with tread safety there, this is in a lock (Players) block and the VideoDemuxer instance will never be destroyed.

I don't think that 3.7 with 3.7.x (latest) so far has any difference in the API or anything that could affect your business logic (can you give me an example?). I would say you should update as 3.7.x updates are fixing critical issues.

**Comment by cxgym** [comment]
it is right

**Comment by SuRGeoNix** [comment]
> ![image](https://user-images.githubusercontent.com/20064260/233580747-83ab7e63-60c5-4d02-a7a5-e5df7ad5e44f.png)

does this happen only on initialization?

**Comment by SuRGeoNix** [comment]
VideoDemuxer is created once in the constructor of DecoderContext and never gets null.

```csharp
public DecoderContext(Config config = null, int uniqueId = -1, bool enableDecoding = true) : base(config, uniqueId) {
...
VideoDemuxer = new Demuxer(Config.Demuxer, MediaType.Video, UniqueId, EnableDecoding);
```

**Comment by SuRGeoNix** [comment]
if something needs to changes is this in the Player.cs (change the order upside down)

```csharp
Engine.AddPlayer(this);
decoder = new DecoderContext(Config, PlayerId) { Tag = this };
```

**Comment by cxgym** [comment]
> > ![image](https://user-images.githubusercontent.com/20064260/233580747-83ab7e63-60c5-4d02-a7a5-e5df7ad5e44f.png)
> 
> does this happen only on initialization?

after initializing the player, execute player.openasyc() occasionally occurs without regularity

**Comment by cxgym** [comment]
> 

But the fact is that there was a null value, and I am also very confused

**Comment by SuRGeoNix** [comment]
Did you change the order?

**Comment by cxgym** [comment]
> Did you change the order?

no have,I execute it individually, not asynchronously opening the player

**Comment by cxgym** [comment]
public Demuxer              VideoDemuxer        => decoder?.VideoDemuxer;         decoder is null

**Comment by SuRGeoNix** [comment]
yes you need to change the order, test it and then i will update it if that fixes it. do this in Player.cs

```csharp
decoder = new DecoderContext(Config, PlayerId) { Tag = this };
Engine.AddPlayer(this);
```

**Comment by SuRGeoNix** [comment]
OK. I see your point with FlyleafHost.Wpf changes. It should be in v3.7.0 and not in 3.7.3-4. I could possible add the old version too.

**Comment by cxgym** [comment]
> yes you need to change the order, test it and then i will update it if that fixes it. do this in Player.cs
> 
> ```cs
> decoder = new DecoderContext(Config, PlayerId) { Tag = this };
> Engine.AddPlayer(this);
> ```

after I made the modifications the problem no again appeared,thank you very much,we will continue to monitor flyleaf, because it is excellent, thank you for your support and answer.

**Comment by SuRGeoNix** [comment]
@cxgym Do you use FlyleafME or FlyleafHost, I can restore it as FlyleafHostOld in the next update.

**Comment by cxgym** [comment]
FlyleafHost

**Comment by cxgym** [comment]
ok, good!

**Comment by cxgym** [comment]
why Player.OpenAsync(streamurl); Player.stop(); Player.OpenAsync(streamurl); can black screen? If I stop a stream, I can't open it again

**Comment by cxgym** [comment]
It is necessary for business

**Comment by cxgym** [comment]
running in VMware report warn "No video frames",it will black screen

**Comment by cxgym** [comment]
17.32.07.081 | Error | [#1]     [Renderer      ] 
D3D11 Video Processor Initialization Failed SharpGen.Runtime.SharpGenException: HRESULT: [0x80004002], Module: [General], ApiCode: [E_NOINTERFACE/No such interface supported], Message: [This interface is not supported]
at SharpGen.Runtime.Result.ThrowFailureException()
at SharpGen.Runtime.Result.CheckError()
at SharpGen.Runtime.ComObject.QueryInterface[T]()
at FlyleafLib.MediaFramework.MediaRenderer.Renderer.InitializeVideoProcessor() in C:\Flyleaf-3.7.14\FlyleafLib\MediaFramework\MediaRenderer\Renderer.VideoProcessor.cs:line 171

**Comment by SuRGeoNix** [comment]
I will need all the initialization log. MS says that this happens with WARP, so for some reason you fallback to WARP earlier. Provide Windows version, dxdiag, and full log. https://learn.microsoft.com/en-us/windows/win32/api/d3d11/nn-d3d11-id3d11videodevice

**Comment by cxgym** [comment]
[2908-player-2023-05-05.log](https://github.com/SuRGeoNix/Flyleaf/files/11404024/2908-player-2023-05-05.log)

**Comment by cxgym** [comment]
windows 10 pro x64

**Comment by cxgym** [comment]
![3fbb4dd67c9918b9fac2dc59e84961c](https://user-images.githubusercontent.com/20064260/236400910-1d79ab39-68c3-4810-99aa-1dc026c9dcb1.png)

**Comment by cxgym** [comment]
![3fbb4dd67c9918b9fac2dc59e84961c](https://user-images.githubusercontent.com/20064260/236401049-41805c40-970c-4634-8f09-02a5a0f78be9.png)

**Comment by cxgym** [comment]
![5a635510f5c50b4b85ceb2f055e5c62](https://user-images.githubusercontent.com/20064260/236401201-6e9201b9-9033-4901-bd04-586e2aee95f7.png)

**Comment by SuRGeoNix** [comment]
@cxgym You use cornerRadius?

**Comment by cxgym** [comment]
my project have not use cornerRadius,I user flyleaf demo test it

**Comment by SuRGeoNix** [comment]
which demo?

**Comment by cxgym** [comment]
![image](https://user-images.githubusercontent.com/20064260/236405564-45501758-ef08-49a3-88f7-3de1790b212c.png)

**Comment by SuRGeoNix** [comment]
Use FlyleafPlayer (WPF Control) (WPF)

**Comment by cxgym** [comment]
[208-player-2023-05-05.log](https://github.com/SuRGeoNix/Flyleaf/files/11404371/208-player-2023-05-05.log)

**Comment by cxgym** [comment]
this my project log,use FlyleafHostOld

**Comment by cxgym** [comment]
it run normal in physical machine,but in virtual machine is black screen

**Comment by SuRGeoNix** [comment]
@cxgym Use Debug LogLevel

**Comment by cxgym** [comment]
[3388-player-2023-05-05.log](https://github.com/SuRGeoNix/Flyleaf/files/11404549/3388-player-2023-05-05.log)

**Comment by SuRGeoNix** [comment]
Seems to be the same issue with #292 and Feature Levels < 10. I will look into it.

**Comment by cxgym** [comment]
When audio and video are not synchronized, Player.CurTime is not right,but I only hope get video CurTime

**Comment by SuRGeoNix** [comment]
@cxgym once again, you make no sense. Please when you want something, try to describe it in details.

**Comment by cxgym** [comment]
I have already described it very clearly,When audio and video are not synchronized, Player.CurTime back is video and audie minimum value,but I only hope get video CurTime.............

**Comment by cxgym** [comment]
> The source (not the url itself) announces wrong timestamps

this is problem

**Comment by cxgym** [comment]
![acabe805b8b0b0ede24de5474942bac](https://github.com/SuRGeoNix/Flyleaf/assets/20064260/f5fac456-7a59-48c4-a273-ca29662584a0)

**Comment by cxgym** [comment]
[vmware win7 x64 error.txt](https://github.com/SuRGeoNix/Flyleaf/files/11523001/vmware.win7.x64.error.txt)

**Comment by SuRGeoNix** [comment]
@cxgym So you were talking for the first issue that it's a broken stream (with wrong timestamps). How do you expect me to remember? This thread is too long with different issues. Please open a new issue so I can keep track of what you are talking about. Still not sure what you are trying to achieve with that broken stream. If you insist playing it you might try adding audio delay in the config?

You also seem to put a log for the other issue. Again you don't explain anything there. But I will try to have a look.

**Comment by SuRGeoNix** [comment]
For some reason I don't see the WARP device anymore (as you had in your prev log)

```
[#1] Unknown VMware SVGA 3D                  [ID: 1029  , LUID: 42541 , DVM: 4 MB    , DSM: 0 B     , SSM: 1023.51 MB]
[#2] Unknown Microsoft Basic Render Driver   [ID: 140   , LUID: 42853 , DVM: 0 B     , DSM: 0 B     , SSM: 1023.51 MB]
```

So I think the fallback couldn't success for that.

But for the SVGA I'm not sure why it is not working for you (I tried that with VM and worked for me) possible update SVGA drivers?

If you enable Debug log and also native debugging I might be able to fix this.

**Comment by cxgym** [comment]
I describe it is clearly?

**Comment by cxgym** [comment]
vd1 = Device.QueryInterface<ID3D11VideoDevice1>();

**Comment by cxgym** [comment]
![621128b4f1b1681ddfaa6528cdbb27e](https://github.com/SuRGeoNix/Flyleaf/assets/20064260/216d71b9-4da5-4563-9544-ea61fd9934e7)

**Comment by cxgym** [comment]
public enum PixelFormatType
{
    Hardware,
    Software_Handled,
    Software_Sws
}
flyleaf v3.7.16 removed support for PixelFormatType.Software_Handled when ID3D11VideoDevice CreateVideoProcessor is failed
