### ISSUE TITLE
FlyleafHost.Wpf: Window cannot be restored (from normal user running as admin)

### ISSUE THREAD

**Issue by shushu789** [SuRGeoNix/Flyleaf#277]
I use WPF FlyleafHost, I found that when using the administrator to run and play the video, after minimizing the window, the window cannot be restored, I can only restore it by setting it as the front in the task management, every time in this way. Running with the administrator is because my WPF player is called by another winform program, because another winform program needs to be run by the administrator, and I just tested it in the example (FlyleafPlayer (Custom - MVVM) (WPF)) and found that it is the same. Is there any other solution besides not running as administrator?

### Steps to reproduce the problem

* Compile the project using FlyleafLib.Controls.WPF
* Run the exe player program as an administrator in the debug or Release directory
* Minimize the window after starting the player
* Unable to restore player window from taskbar

### development environment

* Windows 10
* visual studio 2022
* FlyleafLib.Controls.WPF 1.2.11

**Comment by SuRGeoNix** [comment]
So to reproduce this, I just need to compile FlyleafPlayer (Custom - MVVM) (WPF) and run it as administrator? Because I couldn't reproduce it.

**Comment by shushu789** [comment]
thank you for your reply! You only need to compile or generate FlyleafPlayer (Custom - MVVM) (WPF) with normal permissions, and then use the right button in debug or Release to run it as an administrator (FlyleafPlayer (Custom - MVVM) (WPF).exe), you can reproduce this problem. This is true whether it is minimized via the minimize button in the upper right corner or via the taskbar app icon

**Comment by shushu789** [comment]
In addition, I add to the previous question, no matter whether the video is played or not, as long as it is run as an administrator, the window cannot be restored

**Comment by SuRGeoNix** [comment]
How do I compile or release with normal permissions?

**Comment by shushu789** [comment]
Hmm... sorry my English is not good, the translation used, there may be some problems with the expression, I mean when using visual studio to compile lyleafPlayer (Custom - MVVM) (WPF), it is not necessary to run visual studio as an administrator, and also No need to set (level="requireAdministrator") for the lyleafPlayer (Custom - MVVM) (WPF) project, just compile it with ordinary user rights, after compilation, run it as an administrator in debug (FlyleafPlayer (Custom - MVVM) ( WPF).exe), you can reproduce the above problem

**Comment by SuRGeoNix** [comment]
No worries. I had to create an app manifest to test it. From what I can see when I run it as admin (and debug it by attaching to the process) StateChanged event will not fire. I'm not sure if that's flyleaf's bug or wpf's.

**Comment by SuRGeoNix** [comment]
Well this is related to #255 and #257 which is the parent/child relationship for the FlylealHost's windows (Surface/Overlay). I will need to review those including this in the next update.

I was trying to detach the Surface (set the Parent = null) before going to maximized state and then restore back to attach which kind of works (just need to update also the size on restore). However, this separates the MainWindow in the switch apps list.

https://github.com/SuRGeoNix/Flyleaf/blob/master/FlyleafLib/Controls/WPF/FlyleafHost.cs#L1099

```
private void Surface_MouseDoubleClick(object sender, MouseButtonEventArgs e) { if (ToggleFullScreenOnDoubleClick == AvailableWindows.Surface || ToggleFullScreenOnDoubleClick == AvailableWindows.Both) { if (!IsFullScreen) Detach(); else Attach(); IsFullScreen = !IsFullScreen; e.Handled = true; } }
```

**Comment by SuRGeoNix** [comment]
@shushu789 Just retested after updating to the new flyleafhost.wpf (check master) and it seems that with the 'release' it is working fine. Please re-test and let me know.

**Comment by shushu789** [comment]
Thank you, I'll test it right now

**Comment by shushu789** [comment]
## The window cannot be restored in the following two cases

### Steps to reproduce the first case

1. Right-click the administrator to run (FlyleafPlayer (Custom - MVVM) (WPF).exe)
2. Click the minimize button in the upper right corner
3. Failed to restore from taskbar icon

### Steps to reproduce the second case

1. Right-click the administrator to run (FlyleafPlayer (Custom - MVVM) (WPF).exe)
2. Click Minimize and Restore from the taskbar icon
3. Move the restored window to any position
4. Click the minimize button in the upper right corner
5. Failed to restore from taskbar icon


## According to the above two situations, I recorded an animation respectively

* This is the first case

![test1](https://user-images.githubusercontent.com/85976805/232659232-362f3c59-946b-4160-a51e-176ad137b90b.gif)


* This is the second case

![test2](https://user-images.githubusercontent.com/85976805/232659272-896ea1fb-3617-464c-9a55-2d11c4be415f.gif)

**Comment by SuRGeoNix** [comment]
@shushu789 Did you notice that I told you 'Release' and not 'Debug' ?

**Comment by shushu789** [comment]
I noticed that although the above was tested in debug, I tested it again through Release later, and the result was the same. Tested it two hours ago
![image](https://user-images.githubusercontent.com/85976805/232676598-2970ae06-c327-4a2b-8501-c2e0c5a84b33.png)

**Comment by SuRGeoNix** [comment]
You are right sorry,  yesterday for some reason for the release it was working for me. I will review this.

**Comment by SuRGeoNix** [comment]
@shushu789 I will disappoint your. This does not look to be Flyleaf's issue but .NET's. Check https://tinyurl.com/4tmjhrv2

**Comment by SuRGeoNix** [comment]
@shushu789 After fixing a couple of issues with the new implementation it looks like that now it works fine.
