### ISSUE TITLE
to switch overlay window at run time

### ISSUE THREAD

**Issue by sharmasulekh87** [SuRGeoNix/Flyleaf#278]
I am using flyleaf host wpf, Is it possible to switch the overlay window at run time. For example, till the stream in player load (as it is having a little delay while opening live stream) , I will show an overlay window with some message like (connecting..) and after that remove it or change it back to normal with no message , only transparent overlay window. I have tried to assign a new overlay window(like any other wpf window) at run time, that works but after i am not able to hide or close or change to any other window .

**Comment by SuRGeoNix** [comment]
I think you could but I don't recommended. It will be more safe to just change the content of the overlay as you would do in any other Content normally. (eg: with Style.Triggers and Visibility)

**Comment by sharmasulekh87** [comment]
That i already did as a workaround, thanks anyways
