### ISSUE TITLE
How to intercept URL or video path before opening

### ISSUE THREAD

**Issue by shushu789** [SuRGeoNix/Flyleaf#279]
I use WPF + FlyleafHost, after I start the program, paste a URL address or file path in the player window with CTRL+V, let it open, I want to know how to get this URL address or path before it opens? Because I need to inspect them or dispose of them before opening. I know that it is possible to process the URL before the Player.Open(URL) method before the launch is complete, but as mentioned above, if the program launch is loaded, I don't know what to do with the URL or file path from the clipboard, yes In ”Player.OpenCompleted += Player_OpenCompleted“; processing? But it doesn't seem to be working, can someone provide some ideas? Thank you so much

## i want to do this
`HandleURL(URL);
 Player.Open(URL);`

**Comment by SuRGeoNix** [comment]
Just call your Command/Function before calling Flyleaf's. I will consider adding  an Player_Opening event in the future.
