### ISSUE TITLE
Playing video at speed greater than x16 or lesser than 0.25x

### ISSUE THREAD

**Issue by robertorossinivigilate** [SuRGeoNix/Flyleaf#280]
Hello,
is there any workaround to play video at speed greater than x16 or lesser than 0.25x (for a WPF project)?
Thanks in advance.

**Comment by SuRGeoNix** [comment]
I think you asked me this in the past and tried to explain you that there is no such as think like > x16 speed. It will destroy your GPU. You need something else. It's not even possible to watch or listen the audio. I will review the less than current x0.25 but for the >x16 you need to explain how this suppose to work.

**Comment by robertorossinivigilate** [comment]
No, I never asked this before, it wasn't me :) I'll try to explain why I need these speeds: in my videowall application I use many players, and sometime happens that some of them become misaligned, expecially switching from high speed (x8 or x16) to slow speed (x0.25) and viceversa. I impelemented a method that execute position check and change speed in order to align all player again; for example, changing speed to x16 having two misaligned players, I need a faster speed (x32 or x64) in order to re-aling them. In my older application I implemented this using MediaElement from PresentationFramework assembly.
Thank you for your help.

**Comment by robertorossinivigilate** [comment]
My videowall application must show recordings from cameras, and there is a single timeline, and all players must be synchronized with it. Furthermore, in the selected time interval, for each camera, we can find more then one .mp4 file, and switching between one file and the others can introduce de-sync with the timeline. 
Up to now, we fixed this problem by changing playback speed on each player; in this way user doesn't notice any sudden frame change that I would have using the Seek command.
Anyway, if you suggest this way is better, I'll try to use SeekAccurate.
