### ISSUE TITLE
8K video without sound

### ISSUE THREAD

**Issue by qinjianzhanqing** [SuRGeoNix/Flyleaf#282]
Playing 8K video without sound.

Video source download address:http://124.221.252.71/8K%20Japan.webm

**Comment by SuRGeoNix** [comment]
@qinjianzhanqing the Url is down and when I tried initially it was really slow through network bandwidth so I couldn't really test it.

Can you provide a trace log? I will give a try to test 8K my self but my system will not handle it I'm afraid. Are other players play smoothly for you with this?

**Comment by qinjianzhanqing** [comment]
The URL has resumed downloading, you can download this source for testing

**Comment by qinjianzhanqing** [comment]
@SuRGeoNix The URL has resumed downloading, you can download this source for testing

**Comment by SuRGeoNix** [comment]
@qinjianzhanqing Does it play fine with VLC/PotPlayer/mpv?

**Comment by qinjianzhanqing** [comment]
@SuRGeoNix Smooth playback with vlc player

**Comment by SuRGeoNix** [comment]
I could guess the issue is that currently the audio and video playback is on a single thread. But I will try to test it (if possible) and see. In any case I'm planning to separate the threads soon.

**Comment by SuRGeoNix** [comment]
For me VLC can't play it.

**Comment by qinjianzhanqing** [comment]
This is the resultI tested using VLC, it can be opened normally and the sound is normal
https://user-images.githubusercontent.com/20415253/233594442-eb63842c-5b41-49c8-a5a3-a1c97dca091a.mp4

**Comment by SuRGeoNix** [comment]
@qinjianzhanqing Does it uses HW decoding, can you check? (both Flyleaf and others). I think I found an issue when it uses software decoding it does not set the threads properly (it uses 1 thread instead of 16 cpu cores)

**Comment by SuRGeoNix** [comment]
Well that was the issue, it wouldn't set the threads for some reason. It plays fine now, I'm fixing also some audio improvements to play more stable and I will commit this.

**Comment by SuRGeoNix** [comment]
@qinjianzhanqing If you can re-test from master just to confirm that works fine now

**Comment by SuRGeoNix** [comment]
@qinjianzhanqing As that was a really important issue, it would be great if you can confirm that it has been fixed (just try sample version from releases). Thanks and sorry for insisting :)
