### ISSUE TITLE
Binding doesn't work inside FlyleafHost overlay content

### ISSUE THREAD

**Issue by RaoHammas** [SuRGeoNix/Flyleaf#285]
Hi, 
In WPF, I've noticed that binding is not working for elements that are inside FlyleafHost. For example: 

This textblock is inside `FlyleafHost` control and is bonded to `SomeText` property in window's data context. But this binding will not work and TextBlock will not show any value. Is this a known limitation? or there's a solution? 

Thanks.

```
<TextBlock
    HorizontalAlignment="Left"
    VerticalAlignment="Top"
    Foreground="White"
    Text="{Binding SomeText}" /> 
```

**Comment by SuRGeoNix** [comment]
@RaoHammas the content in the FlyleafHost will be transferred to another window so you lose the bindings/resources etc.
You will need to set this manually. FlyleafHost keeps your datacontext with the HostDataContext dp so you can just set this to it.

<TextBlock DataContext={Binding HostDataContext}

Let me know if you need more help

**Comment by RaoHammas** [comment]
Hey, Thanks man it worked!

**Comment by RaoHammas** [comment]
@SuRGeoNix just one more quick thing, Mouse events don't get triggered on FlyleafHost. Like the MouseMove event is not triggered at all. So, I had to overlay a grid with very low opacity and trigger a mouse event on that. Or is there another approach for this as well???

**Comment by SuRGeoNix** [comment]
@RaoHammas you need to handle FlyleafHost differently. It's not a normal WPF control but two child windows. If you want to listen to events you need to listen to FlyleafHost.Surface and FlyleafHost.Overlay events.

**Comment by RaoHammas** [comment]
@SuRGeoNix Thanks again `FlyleafHost.Surface` events working great. Highly appreciate your help and this effort of yours. So far I was able to achieve everything that I wanted with FlyLeaf.

**Comment by SundayGoGo** [comment]
> @SuRGeoNix just one more quick thing, Mouse events don't get triggered on FlyleafHost. Like the MouseMove event is not triggered at all. So, I had to overlay a grid with very low opacity and trigger a mouse event on that. Or is there another approach for this as well???

@RaoHammas  hi,I encountered the same problem as you, how did you solve it?
