### ISSUE TITLE
H266/VVC / AV1 Support

### ISSUE THREAD

**Issue by tomvdb** [SuRGeoNix/Flyleaf#288]
Hi,

Does the compiled ffmpeg include decoders for H266 and/or AV1 codecs by any chance?

Tom

**Comment by SuRGeoNix** [comment]
Hi @tomvdb,

Not sure to be honest, I compiled the defaults from https://github.com/BtbN/FFmpeg-Builds

If they don't you can always use your own builds (it supports both FFmpeg v5 and v6). For v6 just add FFmpeg.Autogen v6 to your project.

John
