### ISSUE TITLE
Question: How is Renderer.ControlHandle initialized?

### ISSUE THREAD

**Issue by dev991301** [SuRGeoNix/Flyleaf#289]
I am having problems displaying an RTSP stream using Flyleaf in a .NET 6 WPF application. 

I can see the RTSP stream gets setup and the RTP packets are being processed by Screamer. But when Render.PresentInternel(frame) is called, it sees that SCDisposed is true it returns early. It looks like the swap chain is never getting created. I can see that when Renderer.Initialize was called from the Renderer constructor, it tried to call InitializeSwapChain with the ControlHandle but the ControlHandle was 0x0. This resulted in InitializeSwapChain returning early because the handle was 0x0. I did turn on tracing but I couldn't see any relevant error messages.

So I think the problem is the ControlHandle isn't getting initialized. I am sure I am probably not reading the code thoroughly or properly but I couldn't figure out how Renderer.ControlHandle is initialized. Any suggestions that can help me debug this problem will be greatly appreciated.

**Comment by dev991301** [comment]
I worked it out. It looks like FlyLeafHost.OnPlayerChanged was never getting called. I fixed my WPF code and it works now.

**Comment by SuRGeoNix** [comment]
Glad you worked it out. Let me know if you think there is an issue from my side.
