### ISSUE TITLE
Winforms Resizing

### ISSUE THREAD

**Issue by tomvdb** [SuRGeoNix/Flyleaf#290]
Hi,

I've been successfully using FlyLeaf in my satellite receiver program. But I'm having an issue with the control resizing to the form while its playing. The picture below shows flyleafhost in the top window after I have resized the form. The bottom view is vlc which adapted to the resize. Did I miss a setting somewhere? If I stop and start playing again, then it automatically resizes correctly, but not if I resize while its playing.

![image](https://user-images.githubusercontent.com/1420347/235313104-a3d4a82d-6055-46c3-8266-da7b7224f308.png)

 Thanks for your great library!
Tom

**Comment by SuRGeoNix** [comment]
Hi @tomvdb, which FlyleafLib version and FlyleafHost are you using (WinForms/Wpf or Wpf Old?). If you Pause and Play again the resize will be fixed or after you Stop and Open again? This might be related to an issue that I've fixed in master. I will have a new version soon so you can check if that fixes it.

**Comment by tomvdb** [comment]
Hi John,

I'm using FlyleafLib 3.7.9 (latest stable on NuGet) and for the host i'm using flyleafhost 1.0.4 (WinForms)

Its fixed again after I stop and open again.

- btw, I can't seem to upgrade to host 1.0.5 (WinForms) as its complaining about me running on .NetFramework 4.7.2

Thank you,
Tom

**Comment by SuRGeoNix** [comment]
There is no FlyleafHost v1.0.X for WinForms. FlyeafHost for WinForms comes with the main FlyleafLib (3.7.9) the version that you mention is for WinUI?

**Comment by tomvdb** [comment]
Apologies, I was confused (its past my bedtime :p). I'm using 3.7.9  on a WinForms app.

**Comment by SuRGeoNix** [comment]
No worries. It's possible that it happens if you run Player.Stop from a non UI thread. But does it happen initially? What container do you have for the FlyelafHost control to resize automatically? can you check if the control actually resizes? (maybe tomorrow) :)

**Comment by tomvdb** [comment]
I can confirm that stop and play runs from a non UI thread. Also, it does happen initially. So I will play and then as I try to resize the control the video stays the same size (actually even if I double click to go fullscreen then I have fullscreen black window with the video staying same size).

As a test I put the host on an empty form (dock is set to fill).

(1) on first play it will fill the form
![image](https://user-images.githubusercontent.com/1420347/235320523-ff7c043c-c287-4de0-a789-0ce90caf7340.png)

(2) if I try to resize the form, while its playing then it stays the same size, although control is now bigger

![image](https://user-images.githubusercontent.com/1420347/235320532-7ebcdc23-504c-47f6-8842-fc600db15b84.png)

(3) if I stop, and then play it again, then it will fill the resized control as normal

![image](https://user-images.githubusercontent.com/1420347/235320549-8aab75b9-1547-4296-a999-91e59aef7275.png)


(4) If I resize again (for example, make it smaller again) then it cuts off the video (meaning video same size,but controll smaller)

![image](https://user-images.githubusercontent.com/1420347/235320553-3d5abc4e-fe47-4085-99ea-5042392bdc9b.png)

Hope I'm explaining it correctly with the pictures ?

Thanks,
Tom

**Comment by SuRGeoNix** [comment]
I think is the same issue that I've fixed on master. I will have soon a new version for you to check.

**Comment by SuRGeoNix** [comment]
@tomvdb v3.7.10 NuGet should be visible soon for you to test

**Comment by SuRGeoNix** [comment]
Just tested your tuner repo with the updated nuget and it works ;)

**Comment by tomvdb** [comment]
Thanks John, the resize works perfectly. Yes, I know, I've been fiddling, getting some audio stuttering on ffmpeg that I'm not getting on VLC so trying to figure out where the problem is as I can't reproduce it reliably (some transmissions are fine, others not). 

Thanks again for the fix! much appreciated :)

**Comment by SuRGeoNix** [comment]
Nice! Let me know if I can help
