### ISSUE TITLE
Interactive zoom similar to VLC

### ISSUE THREAD

**Issue by sharmasulekh87** [SuRGeoNix/Flyleaf#293]
I am using 3.7.14 version of flyleaf player. I have implemented interactive zoom similar to vlc using pan and zoom features. But I can achieve this using simple canvas but when I use another flyleaf player to overlap, the rectangle do not move. Please help how can i accomplish this. What should i use on the upper left corner to catch the mouse move events.
![image](https://user-images.githubusercontent.com/78798753/236599694-6ded295d-5711-484d-8104-7fe1b5815906.png)

**Comment by SuRGeoNix** [comment]
@sharmasulekh87 I will create a replica renderer inside the existing render so you can render two different swapchains with a different configuration (zoom)

**Comment by SuRGeoNix** [comment]
@sharmasulekh87 Just added support on master. Let me know if you can tested there or if you want a package. Tell me also if you work on WinForms or WPF so I can give you some tips.

**Comment by sharmasulekh87** [comment]
@SuRGeoNix Thanks for your reply. I am working on WPF. I have tested the replica player , but getting sharpgen error "Access Denied". Attaching the snapshot, 
![image](https://user-images.githubusercontent.com/78798753/236661279-778874f0-df53-4a0a-bbb1-86a44e803956.png)

Another one as 
![image](https://user-images.githubusercontent.com/78798753/236661302-494ea048-79d6-43a9-9914-c1293041299f.png)

Please guide.

**Comment by SuRGeoNix** [comment]
Do you get the error from my code (which one) or from your code (where is your code)? Enable native debug at the application project that you debug so you can see a more detailed error message (provide log with debug level)

**Comment by SuRGeoNix** [comment]
@sharmasulekh87 Any news with this?

**Comment by sharmasulekh87** [comment]
Hello @SuRGeoNix 
Sorry for the delay. I have sorted the errors but unable to deal with the mouse capture. But your latest update solves all and its working amazingly. Thank you so very much for the help. Really thanks a lot.
