### ISSUE TITLE
gstreamer with flyleaf

### ISSUE THREAD

**Issue by lkinfotechai** [SuRGeoNix/Flyleaf#294]
is there any possibility to use gstreamer pipeline with flyleaf, 
i have 2 stream of IP camera, 1 id of higher resolution, and another is of low resolution, 
by default i will play first with higher resolution, but when i want to play low resolution stream i dont want to reload the stream, i just wanted it to switch the stream resolution without player reload.

how to achieve this can you help.

**Comment by SuRGeoNix** [comment]
@lkinfotechai I'm not familiar with gstreamer can you give me an idea how you open it with Flyleaf? If you can see the streams when you open then you can switch without re-opening.

**Comment by SuRGeoNix** [comment]
@lkinfotechai Closing this but feel free to ask if you need more help.
