### ISSUE TITLE
Play video file in loop

### ISSUE THREAD

**Issue by Bhalddin** [SuRGeoNix/Flyleaf#297]
I'm wondering if Flyleaf support looping video? what is the best way to implement this feature if it is not supported by default?

**Comment by SuRGeoNix** [comment]
Hi @Bhalddin,

You can listen to Player.PropertyChanged event and check if e.PropertyName is Status and when it changes to Player.Status == Status.Ended then you do Player.Seek(0)

Hope that helps if not please feel to ask for clarifications

J
