### ISSUE TITLE
fast rtsp stream loading

### ISSUE THREAD

**Issue by pankajsaini1987** [SuRGeoNix/Flyleaf#298]
i am loading rtsp stream in flyleaf player. player takes 2-3 seconds or sometime 4-5 seconds to load rtsp stream, depending on stream resolution. as compare to vlc player which takes 1-2 seconds only to load stream, how we can reduce stream load time in flyleaf. also ram size how we can reduce ram usage per camera stream load.

**Comment by SuRGeoNix** [comment]
Hi @lkinfotechai, did you try Config.Demuxer.AllowFindStreamInfo = false ? Check also Config.Player.MinBufferDuration

**Comment by lkinfotechai** [comment]
i tried this as well, but not effect n stream load time, any other way to load it faster,
like ffplay load the stream in a second

**Comment by SuRGeoNix** [comment]
@lkinfotechai I will need a trace log to see what causes the delay
