### ISSUE TITLE
Downloader.Open throws "No audio/video found" on second Open/Download cycle

### ISSUE THREAD

**Issue by anguzo** [SuRGeoNix/Flyleaf#303]
I open and download rtsp stream like so:
```
var error = Downloader.Open(media.Source);
if (error != null) return;
// Downloader.Open() returns null when no error occurred

Downloader.Download(ref filePath, false);
```
The first time stream is opened and downloaded as expected.
The second time (re-using the same Downloader), there is error "No audio/video found".

[log.log](https://github.com/SuRGeoNix/Flyleaf/files/11522567/log.log)

**Comment by SuRGeoNix** [comment]
@anguzo I've not spend much time with the downloader tbh. But why re-using it and just not using a new one? I see it disposes everything when the download will finish/stop and the actual initialization is done during the constructor and not during open/download so it's normal.

**Comment by anguzo** [comment]
@SuRGeoNix Understood. 
I am implementing different recording behavior depending on whether media player is a network stream or a capture device.
I want to be able to record while video is closed(stopped), so that I can switch between different medium and resources are not overused. With network stream I decided to offset it to Downloader, I can then stop the actual Player. With capture device I can't show it using the Player and Download at the same time, since stream is already taken by the Player, so here I don't save resources, just hide the Player.
I will then create a new Downloader each time I start recording and dipose of it OnDownloadCompleted, if there is not a better way.
Thanks for clarifying.
