### ISSUE TITLE
Get error details while opening remote .mp4 file

### ISSUE THREAD

**Issue by robertorossinivigilate** [SuRGeoNix/Flyleaf#305]
Hello,
is it possible to get more error details, when Player.Open fail? Now the only information I get is in LastError, that in my case is:
"Error: [avformat_open_input] Server returned 401 Unauthorized (authorization failed) (-825242872)"

If I execute the same API in Postman, the response is:
{
    "type": "https://tools.ietf.org/html/rfc7235#section-3.1",
    "title": "Unauthenticated",
    "status": 401,
    "detail": "Custom detail description",
    "traceId": "|db8ffa3-44fe45f56ca93373."
}

Is there a way to get "detail": "Custom detail description" information from the response, using Flyleaf Player?
I'm developing a WPF project.
Thank you for your help.

**Comment by SuRGeoNix** [comment]
Hi @robertorossinivigilate,

Unfortunately, that will not be easy as FFmpeg will not return it back to the library. The only possible way that I can think (which I'm not even sure if you could consider it as a solution), it would be to enable trace (not sure FFmpeg log level you need to use maybe debug) log and take the error from there. But with the current implementation you can't pass a custom Stream for the logger and you can't separate from which instance the FFmpeg log is coming from (in case of multiple players/demuxers).

J

**Comment by robertorossinivigilate** [comment]
Thank you for the answer. For now I'll implement a second call to API with a custom client, and I'll try to extract error detail parsing the response content.
