### ISSUE TITLE
Streaming Time gap 

### ISSUE THREAD

**Issue by lkinfotechai** [SuRGeoNix/Flyleaf#306]
when i play a ip camera stream, in start it working real time, but after some seconds it starts slowing down.
like when i see same rtps url in vlc player and flyleaf player.

in vlc player its running real time, but in flyleaf it start making delay after some seconds,
and its increasing per minute. can you please verify why is that delay occurs.

thanks

**Comment by SuRGeoNix** [comment]
@lkinfotechai I will need to see a trace log for that. Did you try MaxLatency as you want to stay at the end? I think VLC has a default 500ms latency?

**Comment by sharmasulekh87** [comment]
> @lkinfotechai I will need to see a trace log for that. Did you try MaxLatency as you want to stay at the end? I think VLC has a default 500ms latency?

[Player.log](https://github.com/SuRGeoNix/Flyleaf/files/11564307/Player.log)

**Comment by SuRGeoNix** [comment]
@sharmasulekh87 does this happen without using the replica player?

**Comment by lkinfotechai** [comment]
the system have windows 10, but on board gpu, and we have set max latenacy 500ms
even default flyleaf exe behave the same,

**Comment by SuRGeoNix** [comment]
@lkinfotechai Just test on of my cameras with MaxLatency=1ms (started with 200ms and changed it from the player settings). I had stable playback with 1 frame distance. I think you are settings wrong the MaxLatency. Use it like this Config.Player.MaxLatency = TimeSpan.FromMilliseconds(500).Ticks;

![image](https://github.com/SuRGeoNix/Flyleaf/assets/57474895/9633bd41-a545-4f85-9a0b-bbdd8599aeec)

**Comment by SuRGeoNix** [comment]
Additionally, you didn't tell me if you have the same issue without the replica player. It might be the issue as the onboard GPU strangles and causes the delay (that's why you see vDistances negatives)

**Comment by sharmasulekh87** [comment]
How the player is calculating this latency period shown 
[Latency **7276ms**] Frames: 3 Packets: 172 Speed: 1.1

I mean which time difference is it referring to latency here.

**Comment by SuRGeoNix** [comment]
From the packets, you have 172 packets in the queue

**Comment by sharmasulekh87** [comment]
> Additionally, you didn't tell me if you have the same issue without the replica player. It might be the issue as the onboard GPU strangles and causes the delay (that's why you see vDistances negatives)

This happens with replica player and a  latency of 3-4 sec is there without replica player.

**Comment by SuRGeoNix** [comment]
Please provide another (trace) log without the replica player and with AllowFindStreamInfo set to default (true). Make sure you set the MaxLatency ticks properly (1ms = 10.000 ticks) and set this to something low (eg. 500ms).

I'm not convinced that this is a Flyleaf issue. This seems more like a wrong configuration, network issue or hardware issue.

**Comment by SuRGeoNix** [comment]
Closing this as I think that was an issue with your configuration / hardware. If not please provide more info to re-open it.

**Comment by sharmasulekh87** [comment]
After reconfiguring hardware, latency has been reduced to some extent. But now facing another issue in rendering the rtsp url with replica player. Please have a look and suggest the way out
![snap](https://github.com/SuRGeoNix/Flyleaf/assets/78798753/fe2f9452-1390-49e3-bbf2-d61f2ba28b3f)

We are using the nvidia graphic card on windows 11. Also sharing the directx details

![snap1](https://github.com/SuRGeoNix/Flyleaf/assets/78798753/ece21467-c31e-4815-86b2-abda4a2f89af)

**Comment by lkinfotechai** [comment]
please open this issue

**Comment by SuRGeoNix** [comment]
Try v3.7.20

**Comment by lkinfotechai** [comment]
when it will be released.?

**Comment by SuRGeoNix** [comment]
Wait few minutes that nuget will index it

**Comment by SuRGeoNix** [comment]
By the way you didn't explain the issue and you didn't provide a log. So just guessing again (possible wrong guess). Please open new issue when you have one and provide the required information (screenshots/logs/versions etc.). Don't make me ask everytime.
