### ISSUE TITLE
System.IO.FileNotFoundException - Could not load file or assembly 'SharpGen.Runtime

### ISSUE THREAD

**Issue by elthombre** [SuRGeoNix/Flyleaf#308]
Hi, I have an Outlook add-in project where I am trying to use the Flyleaf player on a WinForm. When it hits the line:

Engine.Start(new EngineConfig()

I receive:

System.IO.FileNotFoundException
  HResult=0x80070002
  Message=Could not load file or assembly 'SharpGen.Runtime, Version=2.0.0.0, Culture=neutral, PublicKeyToken=a7c0d43f556c6402' or one of its dependencies. The system cannot find the file specified.
  Source=<Cannot evaluate the exception source>
  StackTrace:
<Cannot evaluate the exception stack trace>

**Comment by elthombre** [comment]
Perhaps this needs to be loaded in advance through a different technique:

https://stackoverflow.com/questions/64930313/load-native-library-from-applications-runtimes-directory-in-net-5-application

**Comment by SuRGeoNix** [comment]
Hi @elthombre, are you using .NET  or .NET Framework? I think this might be an issue with Vortice that uses a beta version of SharpGen. I don't think that I could fix this in FlyleafLib, might you need to handle this at your app level. (Not even sure how you use it as plugin for outlook, you need to ensure that the plugin has the required assemblies within -same folder-)

**Comment by elthombre** [comment]
Well, to close the issue and push it back on me when it's your error... I don't understand that at all... 

The add-in uses .Net Framework 4.7.2

**Comment by elthombre** [comment]
Should I open an issue here:

https://github.com/amerkoleci/vortice

or here:

https://github.com/SharpGenTools/SharpGenTools

**Comment by SuRGeoNix** [comment]
Vortice even dropped support for .NET Framework. And this more likely a .NET Framework rather than Vortice issue. Here a related issue with references also to NuGet https://github.com/SuRGeoNix/Flyleaf/issues/84

**Comment by elthombre** [comment]
@SuRGeoNix thanks for this. interesting... I will try that installation suggestion and report back

**Comment by elthombre** [comment]
@SuRGeoNix  Hmmm... I received the following:
  
  Package 'Vortice.D3DCompiler.3.2.0' already exists in project '[Project Name].Vsto'

**Comment by SuRGeoNix** [comment]
@elthombre I'm not sure with what you are dealing with exactly so I can't really help. Might if you create a mini reproduceable sample project I will have a look (next week)

**Comment by elthombre** [comment]
@SuRGeoNix - I can do this. I have one such project that had been used for similar. I can have something tomorrow. Look at it when you can. Thanks!

**Comment by elthombre** [comment]
[FlyleafOutlookAddIn1.zip](https://github.com/SuRGeoNix/Flyleaf/files/11609953/FlyleafOutlookAddIn1.zip)


Here is a sample project.

**Comment by elthombre** [comment]
perhaps there is a platform-specific requirement?

https://stackoverflow.com/questions/76361099/failed-to-load-required-native-libraries-exception-in-an-outlook-plugin-add-in?noredirect=1#comment134653977_76361099

**Comment by SuRGeoNix** [comment]
@elthombre .NET Framework will install latest version of Vortice which are not compatible with .NET Framework. This make no sense but anyways, .NET core installs the exact version. I will try to specify that in the NuGet to avoid this mess.

For you project you can do the following. Edit the package.config to:-

```xml
<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="FFmpeg.AutoGen" version="5.1.2.1" targetFramework="net472" />
  <package id="FlyleafLib" version="3.7.18" targetFramework="net472" />
  <package id="Microsoft.Bcl.HashCode" version="1.1.1" targetFramework="net472" />
  <package id="System.Buffers" version="4.5.1" targetFramework="net472" />
  <package id="System.Memory" version="4.5.5" targetFramework="net472" />
  <package id="System.Numerics.Vectors" version="4.5.0" targetFramework="net472" />
  <package id="System.Runtime.CompilerServices.Unsafe" version="6.0.0" targetFramework="net472" />
  <package id="Vortice.D3DCompiler" version="2.4.2" targetFramework="net472" />
  <package id="Vortice.Direct3D11" version="2.4.2" targetFramework="net472" />
  <package id="Vortice.DirectComposition" version="2.4.2" targetFramework="net472" />
  <package id="Vortice.Mathematics" version="1.4.26" targetFramework="net472" />
  <package id="Vortice.MediaFoundation" version="2.4.2" targetFramework="net472" />
  <package id="Vortice.XAudio2" version="2.4.2" targetFramework="net472" />
</packages>
```

Right click on references and click Migrate package.config to PackageReference. I think this way it will work (at least I've seen the plugin in outlook not sure what it was suppose todo). You will need to ensure that all the .dll files are in the build output (all vortice and sharpgen dll as well)

**Comment by SuRGeoNix** [comment]
Another wall to cross...

```
System.Deployment.Application.InvalidDeploymentException: Strong name signature not valid for this assembly FFmpeg.AutoGen.dll.
   at Microsoft.VisualStudio.Tools.Applications.Deployment.ClickOnceAddInDeploymentManager.DownloadAddIn(TimeSpan timeout)
   at Microsoft.VisualStudio.Tools.Applications.Deployment.ClickOnceAddInDeploymentManager.InstallAddIn()
````

![image](https://github.com/SuRGeoNix/Flyleaf/assets/57474895/5f51edf1-e2b6-4fcf-b931-627489ec35e6)

**Comment by elthombre** [comment]
hmm... interesting. The .MP4 actually isn't mine but I could see where such could happen as it's difficult to control what users will send...
