### ISSUE TITLE
Can't play video with image attachments (ffmpeg recognizes them as video streams)

### ISSUE THREAD

**Issue by ahmadsafi24** [SuRGeoNix/Flyleaf#31]
Format                         : Matroska
Format version                 : Version 4 / Version 2
File size                      : 1.68 GiB
Duration                       : 1 h 50 min
Overall bit rate               : 2 191 kb/s
Writing application            : mkvmerge v42.0.0 ('Overtime') 64-bit
Writing library                : libebml v1.3.10 + libmatroska v1.5.2
Cover                          : Yes
Attachments                    : cover.jpg / small_cover.jpg / cover_land.jpg / small_cover_land.jpg

Video
ID                             : 1
Format                         : AVC
Format/Info                    : Advanced Video Codec
Format profile                 : High@L4.1
Format settings, CABAC         : Yes
Format settings, RefFrames     : 4 frames
Codec ID                       : V_MPEG4/ISO/AVC
Duration                       : 1 h 50 min
Bit rate                       : 2 000 kb/s
Width                          : 1 920 pixels
Height                         : 800 pixels
Display aspect ratio           : 2.40:1
Frame rate mode                : Constant
Frame rate                     : 23.976 (24000/1001) FPS
Color space                    : YUV
Chroma subsampling             : 4:2:0
Bit depth                      : 8 bits
Scan type                      : Progressive
Bits/(Pixel*Frame)             : 0.054
Stream size                    : 1.53 GiB (91%)
Default                        : Yes
Forced                         : No
Color range                    : Limited
Color primaries                : BT.709
Transfer characteristics       : BT.709
Matrix coefficients            : BT.709

Audio
ID                             : 3
Format                         : AAC
Format/Info                    : Advanced Audio Codec
Format profile                 : HE-AAC / LC
Codec ID                       : A_AAC
Duration                       : 1 h 50 min
Bit rate                       : 192 kb/s
Channel(s)                     : 6 channels
Channel positions              : Front: L C R, Side: L R, LFE
Sampling rate                  : 48.0 kHz / 24.0 kHz
Frame rate                     : 23.438 FPS (1024 SPF)
Compression mode               : Lossy
Stream size                    : 151 MiB (9%)
Language                       : English
Default                        : No
Forced                         : No

**Comment by SuRGeoNix** [comment]
That looks like a very common video format.  Do you have issues generally or just with a single video?
If you running in x86 try also in x64 (as the project's x86 ffmpeg libs are old)
Can you provide more information? (Debugging output, a video sample)

**Comment by SuRGeoNix** [comment]
OK. Don't bother I think I've notice the error... Tried also a video with embedded covers/images that ffmpeg recognizes as video streams. So I'll have a look.

[# Format] Matroska / WebM/matroska,webm | mkv,mk3d,mka,mks 00:00:00/00:02:36
[#0 Audio] aac fltp@0 44KHz stereo | 0
[#1 Video] h264 yuv420p 1272x720 @ 24 | 0
[#2 Video] mjpeg yuvj444p 600x882 @ 90000 | 0
[#3 Video] mjpeg yuvj444p 120x176 @ 90000 | 0
[#4 Video] mjpeg yuvj444p 1067x600 @ 90000 | 0
[#5 Video] mjpeg yuvj444p 213x120 @ 90000 | 0
