### ISSUE TITLE
Win32 API SetWindowDisplayAffinity is not working with Flyleaf player WPF sample project

### ISSUE THREAD

**Issue by vardanbalyan97** [SuRGeoNix/Flyleaf#310]
**Note : This is not an issue just want to know you point of view on this.** 

I'm making a video player using the Flyleaf WPF sample project which is this one https://github.com/SuRGeoNix/Flyleaf/tree/master/Samples/FlyleafPlayer%20(WPF%20Control)%20(WPF) and i want to restrict the user to capture the screen of the player. To achieve that microsoft provided the API SetWindowDisplayAffinity but this is not working the sample project. I have also used the API in simple WPF project it works fine but not working in sample project. Do you happen to know about the reason why it is not working with the Flyleaf WPF sample project.

Below is the code for reference :

        [DllImport("User32.dll", SetLastError = true)]
        private static extern bool SetWindowDisplayAffinity(IntPtr hWnd, uint dwAffinity);

        public const int WDA_NONE = 0x00000000;
        public const int WDA_MONITOR = 0x00000001;
        public const int WDA_EXCLUDEFROMCAPTURE = 0x00000011;

        private void Window_Loaded(object sender, RoutedEventArgs e)
        {
            IntPtr hWnd = IntPtr.Zero;
            HwndSource hwndSource = PresentationSource.FromVisual(this) as HwndSource;

            if (hwndSource != null)
            {
                hWnd = hwndSource.Handle;
            }

            if (hWnd != IntPtr.Zero)
            {
                bool result = SetWindowDisplayAffinity(hWnd, WDA_EXCLUDEFROMCAPTURE);
                if (!result)
                {
                    int errorCode = Marshal.GetLastWin32Error();
                    Console.WriteLine("Error: " + errorCode);
                }
            }
        }

 If i debug my code by getting the last error from Marshal.GetLastWin32Error() then it returns value 87 (ERROR_INVALID_PARAMETER).

Thanks

**Comment by SuRGeoNix** [comment]
@vardanbalyan97 This will work if you pass the Surface's handle (FlyleafME.SurfaceHandle).

You just need to ensure that it has been created (in the sample Window_Loaded will be fine but might be more safe to register to the new SurfaceCreated event).

**Comment by vardanbalyan97** [comment]
Thanks @SuRGeoNix you are a life saver 🙌
