### ISSUE TITLE
Issue while rendering stream after update flyleaf to 3.7.14 (also tried latest code)

### ISSUE THREAD

**Issue by sharmasulekh87** [SuRGeoNix/Flyleaf#311]
I am using the flyleaf player for Wpf in windows 11. I have tried with latest code with update mentioned as 3.7.20, but the result is same. But while rendering rtsp stream or simple file , the flyleaf player is not showing stream properly . I am attaching the screenshot here and logs as well.
![snap1](https://github.com/SuRGeoNix/Flyleaf/assets/78798753/05ea165c-d847-4d64-9641-ead880c63897)
![snap](https://github.com/SuRGeoNix/Flyleaf/assets/78798753/d82a97a9-3287-4d9d-ae87-acedcf49be57)

As you can see in replica player, the stream has been shown fine, but in original whiteness is there. 
[Player (1).log](https://github.com/SuRGeoNix/Flyleaf/files/11625229/Player.1.log)

please suggest the way out.

**Comment by SuRGeoNix** [comment]
@sharmasulekh87 Can you confirm that this is happening only when you set the ReplicaPlayer?

**Comment by lkinfotechai** [comment]
when it can be resolved, as we have to decode stream via GPU? 
please provide solution.

**Comment by SuRGeoNix** [comment]
please provide feedback to my questions so I can provide a solution (Flyleaf video processor has nothing to do with the hardware decode, you still have the decoding in GPU)

**Comment by sharmasulekh87** [comment]
> @sharmasulekh87 Can you confirm that this is happening only when you set the ReplicaPlayer? Can you also see if it is related to Config.Demuxer.AllowFindStreamInfo (set it to default - true). And one more thing, when using the Replica is recommended at least for now to use Config.Video.VideoProcessor = VideoProcessors.Flyleaf
> 
> I think the issue is because it uses D3D11VP. So if you force it to Flyleaf should work. I will do it in the renderer to force Flyleaf video processor when it uses replica as it has issues.
> 
> (By the way, why you mention 3.7.14? It was working with 3.7.13 without the replica?)

I have set as you suggest Config.Video.VideoProcessor = VideoProcessors.Flyleaf and for now its working. But on other systems , it is working without setting this. Is there any specific reason behind that?

**Comment by SuRGeoNix** [comment]
@sharmasulekh87 replica player is still new and didn't have much time to resolve some issues with D3D11VP. To be honest, not really required to work with D3D11VP, only if you want to use more filters that currently supports or de-interlaced that FlyleafVP does not support.

**Comment by sharmasulekh87** [comment]
ok..thanks for your help
