### ISSUE TITLE
How to modify the video title shown on left hand side of flyleaf bar? 

### ISSUE THREAD

**Issue by vardanbalyan97** [SuRGeoNix/Flyleaf#313]
![image](https://github.com/SuRGeoNix/Flyleaf/assets/95332701/a60e690c-9648-4051-8064-6aaa1a74ecd4)

Hi I want to modify the video title in the flyleaf bar how can I do that?

**Comment by SuRGeoNix** [comment]
Hi @vardanbalyan97, this is not related with the Flyleaf. You will need to read about WPF Grids/StackPanels etc to achieve what you want.
