### ISSUE TITLE
Audio levels for vu-meters

### ISSUE THREAD

**Issue by jeroenm2** [SuRGeoNix/Flyleaf#314]
Hi, is there a possibility to get audio level values for usage in vu-meters. I was looking into the audio frame that should hold that data I suppose. But I couldn't figure it out myself. Do you know if it is possible or if it something that has to be added on your side?

**Comment by SuRGeoNix** [comment]
Hi @jeroenm2, you can read the audio frame from Player.Audio.SamplesAdded event and analyze it in the way that you want. The format is always stereo (2 channels) - 16bits and the sample rate currently is the same as the input so you can read it from Player.Audio.SampleRate.

**Comment by jeroenm2** [comment]
Hi @SuRGeoNix, I was in the right direction. Thanks, that helped a lot
