### ISSUE TITLE
Play Rtsp delay 

### ISSUE THREAD

**Issue by SundayGoGo** [SuRGeoNix/Flyleaf#317]
hi, thank you for providing such a useful player.
I have encountered the problem of rtsp playback in use, and the delay is getting higher and higher as time goes by. I don't know whether this delay is related to the flyleaf configuration, the camera or the computer, but the final picture will become more and more delayed. The following is my opinion Configuration of flyleaf player (camera in LAN).
hope to get your reply.
```
   Config = new Config();
            Config.Player.MinBufferDuration = 0;
            Config.Player.MaxLatency = 0;
            Config.Player.MinLatency = 0;

            Config.Demuxer.FormatOpt["rtsp_transport"] = "tcp";
            Config.Demuxer.FormatOpt["fflags"] = "nobuffer";

            Config.Video.BackgroundColor = Colors.DarkGray;
            Config.Video.AspectRatio = AspectRatio.Fill;

            Config.Demuxer.BufferDuration = 0;
```

**Comment by SuRGeoNix** [comment]
Use only (instead of first 3 lines) Config.Player.MaxLatency = 500 * 1000 * 10000 (its in ticks so this is 500ms)

**Comment by SuRGeoNix** [comment]
@SundayGoGo Sorry my mistake, what I gave you were seconds and not ms. Please review my edited answer.

**Comment by SundayGoGo** [comment]
@SuRGeoNix Thanks for your answer, I've modified it, I'll keep watching for a while
