### ISSUE TITLE
Possible resource leak in Renderer.PresentOffline

### ISSUE THREAD

**Issue by gexgd0419** [SuRGeoNix/Flyleaf#318]
https://github.com/SuRGeoNix/Flyleaf/blob/441ec6fcd56f779b0d0362c3b2488c8d09aac40c/FlyleafLib/MediaFramework/MediaRenderer/Renderer.PresentOffline.cs#L32-L36

This code uses `rtv.Resource` to get its associated `ID3D11Texture2D`.

The getter of `rtv.Resource` will call [ID3D11View::GetResource](https://learn.microsoft.com/en-us/windows/win32/api/d3d11/nf-d3d11-id3d11view-getresource), which **increments the reference count of the resource by one**.

The return value of `rtv.Resource` isn't disposed here, so the associated texture will have one more reference count each time this is executed, which makes it possible to leak textures if a lot of different textures are used.

Normally, this might not cause big issues, because inside Renderer, the textures used for this purpose are reused, and this function is internal.

But I want to get the rendered textures directly from Renderer, so I used reflection to invoke it with my own textures. The returned textures couldn't be freed by calling `Dispose()` because of the one more reference count, though I could work around it by calling `Release()` once.

Also, I want to get the rendered ARGB texture residing in GPU memory, without rendering it on screen. `GetBitmap` will transfer the data to CPU memory. Is there (Or will there be) a recommended way to do this, without calling an internal function with reflection?

**Comment by SuRGeoNix** [comment]
@gexgd0419 As you said there is no leak as the same resources are re-usable. I could help you implement something more specific that you need and possible added in the library in case someone else need it. I'm afraid that by exposing device/context's resources will cause leaks if not properly dispose by the user. I'm not quite sure what you want to do but feel free to create a PR with a public "PresentOffline" and I will review it.

**Comment by SuRGeoNix** [comment]
I will review this...

**Comment by SuRGeoNix** [comment]
Thanks guys and sorry I missed that when initially mentioned by @gexgd0419
