### ISSUE TITLE
SetDelayTicks doesn't use parameter value

### ISSUE THREAD

**Issue by robvdpol** [SuRGeoNix/Flyleaf#32]
Audio.SetDelayTicks function doesn't use the 'delay' parameter and sets the delay to 0.

**Comment by SuRGeoNix** [comment]
You shouldn't access the SetDelayTicks it's for internal use (I will fix this). You change the audio delay by changing directly the DelayTicks property. Reopen this if you still have issues (have also a look at wpf flyleaf control for sample)

**Comment by robvdpol** [comment]
I don't use this function but I noticed that the code wasn't using the parameter. Just to let you know ;)

**Comment by SuRGeoNix** [comment]
Well nice catch, a lot of clean-up is required especially for public properties (having also issues with plugins that require public properties, even if there in the same namespace -loaded dll assemblies- cant access internal properties, any idea why?)

**Comment by robvdpol** [comment]
Internal properties can only be accessed from the assembly itself. You can work around this by using the [InternalsVisibleToAttribute](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.compilerservices.internalsvisibletoattribute?view=net-5.0).

**Comment by SuRGeoNix** [comment]
Seems promising thanks ;)
