### ISSUE TITLE
Issue while rendering the stream

### ISSUE THREAD

**Issue by sharmasulekh87** [SuRGeoNix/Flyleaf#320]
![image](https://github.com/SuRGeoNix/Flyleaf/assets/78798753/c0608868-d5a6-49d8-b46b-64e1e6d871dc)
Using Flyleaf WPF player latest version 3.7.16, on windows 10, getting the image like this.
Tried following cases:
1. Without replica player, any video processor works fine. I am able to work with filters as well for AUTO and D3D11.
2. With replica player , replica player rendering is fine (because i think you have forced the processor to flyleaf) but the zoomed video is like this . I can not set the video processor to flyleaf for zoomed video, as i have to use video filters like brightness etc.
3. I have tried with VideoAcceleration = false; replica player and zoomed video works fine, but then can not use video filters.
4. Moreover, with replica player and Flyleaf VideoProcessor, in some cases replica player works fine with video stream of upto resolution 2MP. But on higher resolutions, the issue is same even with Flyleaf Videoprocessor.

Please suggest a way out, so that i can use video filters as well as replica player with proper video rendering.

**Comment by SuRGeoNix** [comment]
replica does not currently support D3D11 so you can't use D3D11 filters.

**Comment by pankajsaini1987** [comment]
any solution for this.
