### ISSUE TITLE
Subtitle not visible in WinUI

### ISSUE THREAD

**Issue by Damix48** [SuRGeoNix/Flyleaf#324]
I copy and paste the [FlyleafPlayer (WinUI)](https://github.com/SuRGeoNix/Flyleaf/tree/master/Samples/FlyleafPlayer%20(WinUI)) into a packaged WinUI 3 app and the subtitle are not visibile. 

I check if the stream is enabled and it is, I can get the text using `Player.Subtitles.SubsText` but they are not shown on the player itself.

I tried with SSA/ASS and SubRip

**Comment by SuRGeoNix** [comment]
Hi @Damix48, the sample just don't currently use them I guess. Just add the binding and it will work fine.
