### ISSUE TITLE
Exception while opening rtsp url

### ISSUE THREAD

**Issue by sharmasulekh87** [SuRGeoNix/Flyleaf#327]
![image](https://github.com/SuRGeoNix/Flyleaf/assets/78798753/70e4e845-7fdd-4b2c-8cbb-b7524146468e)

and this follows from 

![image](https://github.com/SuRGeoNix/Flyleaf/assets/78798753/14459203-13c0-4336-afb2-28fa2e3ec6a9)

I am working on WPF Flyleaf player 3.7.20 . Whenever try to open rtsp url , it throws exception of format and when i continue, the player open it and play it well.  i think it also adds some delay while opening the stream. Can you please suggest me what should i do?

**Comment by SuRGeoNix** [comment]
Hi @sharmasulekh87, that seems just a debugging issue and not a release issue. However, I will try to review this in the next update.

**Comment by SuRGeoNix** [comment]
@sharmasulekh87 closing this as I wasn't able to reproduce it and you didn't provide debug log or an actual Url that can cause this issue. Please feel free to re-open with more details
