### ISSUE TITLE
WinUI: DPI Issue

### ISSUE THREAD

**Issue by kwanggaeto** [SuRGeoNix/Flyleaf#328]
<img width="427" alt="capture" src="https://github.com/SuRGeoNix/Flyleaf/assets/7101046/082cb15f-0b54-44df-93a6-01d1c0f5e009">

video position is wrong..

i'm using player on the WinUI
i just set up along to content in  #wiki.
i did controled window size and style.
but, that seem to not be rely on window size or window style.

**Comment by SuRGeoNix** [comment]
Hi @kwanggaeto, can't see the issue from just one photo. Can you check if it is a DPI issue? Can you provide code to review it when I will be available?

**Comment by kwanggaeto** [comment]
@SuRGeoNix 
oh hi :)

my codes is similar with sample code but i added some code about a window position and style in App.xaml.cs.

`m_window = new MainWindow();
m_window.Activate();
m_window.SetIsAlwaysOnTop(true);
 m_window.SetIsMaximizable(false);
m_window.SetIsMinimizable(false);
m_window.SetIsResizable(false);
var style = HwndExtensions.GetWindowStyle(m_window.GetWindowHandle());
style = style & ~WindowStyle.SysMenu;
style = style & ~WindowStyle.Caption;
HwndExtensions.SetWindowStyle(m_window.GetWindowHandle(), style);
var dpi = m_window.GetDpiForWindow();
float descaling = 100f / dpi;
m_window.MoveAndResize(0, 0, 1920* descaling, 1080* descaling);`


anyway, i realized the reason after seeing your reply that it might is relate the DPI.

so, i changed the DPI from 150% to 100%, then the video is shown in center. thanks!

but, how can i make the video display correctly regardless the DPI?

**Comment by SuRGeoNix** [comment]
@kwanggaeto I will have to review this, haven't spend much time with WinUI.
