### ISSUE TITLE
Wrong Grid render in <ViewBox>

### ISSUE THREAD

**Issue by evgaldh** [SuRGeoNix/Flyleaf#330]
Hello, i experiencing weird visual glitch in overlay, when i wrap Grid in ViewBox (see picture below)
![image](https://github.com/SuRGeoNix/Flyleaf/assets/52421906/2051f22a-5adf-4e00-bfa8-f26016c49dfe)

`<UserControl x:Class="ProbeSampler.WPF.Controls.CameraView"
             xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006" 
             xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
             
             xmlns:probeSampler="clr-namespace:ProbeSampler.WPF"
             xmlns:fl="clr-namespace:FlyleafLib.Controls.WPF;assembly=FlyleafLib"
             xmlns:ext="clr-namespace:ProbeSampler.WPF.Extensions"
             xmlns:local="clr-namespace:ProbeSampler.WPF.Controls"
             mc:Ignorable="d" 
             d:DesignHeight="450" d:DesignWidth="800">
    <Grid>
        <Grid.RowDefinitions>
            <RowDefinition Height="Auto"/>
            <RowDefinition Height="*"/>
            <RowDefinition Height="Auto"/>
        </Grid.RowDefinitions>
        <fl:FlyleafHost
            x:Name="FLHost"
            Player="{Binding Player}"
            KeyBindings="None"
            ToggleFullScreenOnDoubleClick="None"
            SwapOnDrop="None"
            OpenOnDrop="None"
            PanMoveOnCtrl="None" 
            PanRotateOnShiftWheel="None" 
            PanZoomOnCtrlWheel="None"
            VerticalAlignment="Stretch"
            Grid.Row="1">
            <Viewbox>
                <ItemsControl
                    x:Name="ItemsControl"
                    DataContext="{Binding HostDataContext}"
                    Visibility="{Binding ShowGridOverlay, Converter={StaticResource BooleanToVisibilityConverter}}"
                    ItemsSource="{Binding Borders}">
                    <ItemsControl.ItemsPanel>
                        <ItemsPanelTemplate>
                            <Grid
                                Background="Transparent"
                                x:Name="SamplerGrid"
                                ShowGridLines="True"
                                ext:GridExtentions.RowCount="{Binding RowCount}"
                                ext:GridExtentions.ColumnCount="{Binding ColumnCount}">
                            </Grid>
                        </ItemsPanelTemplate>
                    </ItemsControl.ItemsPanel>
                    <ItemsControl.ItemContainerStyle>
                        <Style>
                            <Setter Property="Grid.Row" Value="{Binding RowIndex}"/>
                            <Setter Property="Grid.Column" Value="{Binding ColumnIndex}"/>
                            <Setter Property="FrameworkElement.DataContext" Value="{Binding RelativeSource={RelativeSource Self}}"/>
                        </Style>
                    </ItemsControl.ItemContainerStyle>
                    <ItemsControl.ItemTemplate>
                        <DataTemplate>
                            <Border
                                BorderThickness="1"
                                IsHitTestVisible="True"
                                BorderBrush="Red"
                                MouseDown="Border_MouseDown"
                                Background="Transparent"/>
                        </DataTemplate>
                    </ItemsControl.ItemTemplate>
                </ItemsControl>
            </Viewbox>
        </fl:FlyleafHost>
    </Grid>
</UserControl>`

When, i don't use ViewBox as main container, Grid displays normally, but i also can't trigger mouse down event on Border items.
![image](https://github.com/SuRGeoNix/Flyleaf/assets/52421906/0dbacf77-a53d-4247-a8d6-008ac83bcd70)

**Comment by SuRGeoNix** [comment]
@evgaldh Sorry can't look deep in to it. I think your issue is with Flyleaf's windows that it creates above your main window. Check Wiki and Samples and then you can see how to handle the mouse events properly. Feel free to re-open/ask.
