### ISSUE TITLE
Using Flyleaf player with async await pattern approach

### ISSUE THREAD

**Issue by robertorossinivigilate** [SuRGeoNix/Flyleaf#331]
Hi,
I'm developing a wpf application using async await pattern, and I notice that sometimes (I don't know exactly the reason) the execution of Open method doesn't return as expected.
Looking at the code of Flyleaf player, I saw in the code instructions like Thread.Sleep and lock, and I thought this could be the cause of my problem.
Is async/await pattern a good idea for my application, or is better a Synchronous approach, if I want to use Flyleaf player?
Thank you for your help!

**Comment by SuRGeoNix** [comment]
Hi @robertorossinivigilate, you need to understand how flyleaf works (check samples and wiki as well) and then you could also use it with your own async/await. If you explain what you want to do I might be able to help you more.
