### ISSUE TITLE
max or preferred stream resolution as option

### ISSUE THREAD

**Issue by Isayso** [SuRGeoNix/Flyleaf#339]
I use your great player to play various video sources. For streams it could be helpful to set a maximum value as an option e.g. 720.

Thanks!

**Comment by Isayso** [comment]
Sorry for contacting you with this way, I have no Github access anymore.

Paste url doesn't work anymore "invalid data found" 
Thanks
     On Wednesday, August 30, 2023 at 10:52:05 PM GMT+2, John Stamatakis ***@***.***> wrote:  
 
 


Closed #339 as completed via 0fda84d.

**Comment by SuRGeoNix** [comment]
@Isayso are you sure you paste valid data? I can't see the issue. The only change is with photos/images that now ctrl+c copies the image instead of path (you can use shift+c for that)

**Comment by SuRGeoNix** [comment]
Ctrl+V works but right click Paste Url does not? (Can't reproduce it)

**Comment by Isayso** [comment]
Also not with Ctrl-V and cmd line argument.

Can I switch on a debug log file?

     On Friday, February 9, 2024 at 07:06:29 PM GMT+1, John Stamatakis ***@***.***> wrote:  
 
 


Ctrl+V works but right click Paste Url does not? (Can't reproduce it)

**Comment by Isayso** [comment]
I switched on logfile and trace BTW, in .44 the dropdown lists in logfile level are empty

19.39.39.388 | Debug | [#1] [Player ] [Keys|Down] OpenFromClipboard
19.39.39.390 | Info | [#1] [Player ] Opening https://www.youtube.com/watch?v=1EBvrJyWv2Q
19.39.39.390 | Debug | [#1] [Player ] Initializing
19.39.39.390 | Trace | [FlyleafEngine] timeBeginPeriod(1)
19.39.39.391 | Debug | [#1] [YoutubeDL ] Disposing watcher
19.39.39.391 | Debug | [#1] [YoutubeDL ] Removing folder C:\Users\ich\AppData\Local\Temp\9d86ab0b-bf6f-4244-8c84-5da911970b03
19.39.39.394 | Debug | [#1] [Player ] Initialized
19.39.39.394 | Trace | [FlyleafEngine] timeEndPeriod(1)
19.39.39.394 | Debug | [#1] [YoutubeDL ] Creating folder C:\Users\ich\AppData\Local\Temp\6fd2f39a-c5c8-4c47-bfa6-d97c6ddc6b47
19.39.39.401 | Debug | [#1] [YoutubeDL ] Process 18800 started
19.39.40.212 | Debug | [#1] [YoutubeDL ] Process 18800 stopped
19.39.40.237 | Info | [#1] [PluginHandler ] [OpenDefault] Open Success
19.39.40.237 | Info | [#1] [PluginHandler ] SuggestItem #0 - watch
19.39.40.237 | Info | [#1] [PluginHandler ] [OpenDefault] Open Item (0) Success
19.39.40.237 | Debug | [#1] [Demuxer: Main] Stopped -> Opening
19.39.40.237 | FFmpeg | Debug | [NULL @ 000001571dce9f40] Opening 'https://www.youtube.com/watch?v=1EBvrJyWv2Q' for reading
19.39.40.237 | FFmpeg | Debug | [https @ 00000157048c0700] Setting default whitelist 'http,https,tls,rtp,tcp,udp,crypto,httpproxy'
19.39.40.238 | FFmpeg | Debug | [tcp @ 00000157048dccc0] Original list of addresses:
19.39.40.238 | FFmpeg | Debug | [tcp @ 00000157048dccc0] Address 142.250.181.206 port 443
19.39.40.238 | FFmpeg | Debug | [tcp @ 00000157048dccc0] Address 142.251.209.142 port 443
19.39.40.238 | FFmpeg | Debug | [tcp @ 00000157048dccc0] Address 172.217.19.78 port 443
19.39.40.238 | FFmpeg | Debug | [tcp @ 00000157048dccc0] Interleaved list of addresses:
19.39.40.238 | FFmpeg | Debug | [tcp @ 00000157048dccc0] Address 142.250.181.206 port 443
19.39.40.238 | FFmpeg | Debug | [tcp @ 00000157048dccc0] Address 142.251.209.142 port 443
19.39.40.238 | FFmpeg | Debug | [tcp @ 00000157048dccc0] Address 172.217.19.78 port 443
19.39.40.238 | FFmpeg | Verbose | [tcp @ 00000157048dccc0] Starting connection attempt to 142.250.181.206 port 443
19.39.40.257 | FFmpeg | Verbose | [tcp @ 00000157048dccc0] Successfully connected to 142.250.181.206 port 443
19.39.40.280 | FFmpeg | Debug | [tls @ 00000157048dd000] Received incomplete handshake, need more data
19.39.40.281 | FFmpeg | Debug | [tls @ 00000157048dd000] Received incomplete handshake, need more data
19.39.40.281 | FFmpeg | Debug | [tls @ 00000157048dd000] Received incomplete handshake, need more data
19.39.40.281 | FFmpeg | Debug | [tls @ 00000157048dd000] Received incomplete handshake, need more data
19.39.40.281 | FFmpeg | Debug | [tls @ 00000157048dd000] Received incomplete handshake, need more data
19.39.40.301 | FFmpeg | Debug | [https @ 00000157048c0700] request: GET /watch?v=1EBvrJyWv2Q HTTP/1.1
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.159 Safari/537.36
Referer: https://www.youtube.com/watch?v=1EBvrJyWv2Q
Accept: */*
Range: bytes=0-
Connection: close
Host: www.youtube.com
Icy-MetaData: 1
19.39.40.363 | FFmpeg | Trace | [https @ 00000157048c0700] header='HTTP/1.1 200 OK'
19.39.40.363 | FFmpeg | Trace | [https @ 00000157048c0700] http_code=200
19.39.40.363 | FFmpeg | Trace | [https @ 00000157048c0700] header='Content-Type: text/html; charset=utf-8'
19.39.40.363 | FFmpeg | Trace | [https @ 00000157048c0700] header='X-Content-Type-Options: nosniff'
19.39.40.363 | FFmpeg | Trace | [https @ 00000157048c0700] header='Cache-Control: no-cache, no-store, max-age=0, must-revalidate'
19.39.40.363 | FFmpeg | Trace | [https @ 00000157048c0700] header='Pragma: no-cache'
19.39.40.363 | FFmpeg | Trace | [https @ 00000157048c0700] header='Expires: Mon, 01 Jan 1990 00:00:00 GMT'
19.39.40.363 | FFmpeg | Trace | [https @ 00000157048c0700] header='Date: Fri, 09 Feb 2024 18:39:39 GMT'
19.39.40.363 | FFmpeg | Trace | [https @ 00000157048c0700] header='Strict-Transport-Security: max-age=31536000'
19.39.40.363 | FFmpeg | Trace | [https @ 00000157048c0700] header='X-Frame-Options: SAMEORIGIN'
19.39.40.363 | FFmpeg | Trace | [https @ 00000157048c0700] header='Accept-CH: Sec-CH-UA-Arch, Sec-CH-UA-Bitness, Sec-CH-UA-Full-Version, Sec-CH-UA-Full-Version-List, Sec-CH-UA-Model, Sec-CH-UA-WoW64, Sec-CH-UA-Form-Factor, Sec-CH-UA-Platform, Sec-CH-UA-Platform-Version'
19.39.40.363 | FFmpeg | Trace | [https @ 00000157048c0700] header='Vary: Sec-CH-UA-Arch, Sec-CH-UA-Bitness, Sec-CH-UA-Full-Version, Sec-CH-UA-Full-Version-List, Sec-CH-UA-Model, Sec-CH-UA-WoW64, Sec-CH-UA-Form-Factor, Sec-CH-UA-Platform, Sec-CH-UA-Platform-Version'
19.39.40.363 | FFmpeg | Trace | [https @ 00000157048c0700] header='Origin-Trial: AvC9UlR6RDk2crliDsFl66RWLnTbHrDbp+DiY6AYz/PNQ4G4tdUTjrHYr2sghbkhGQAVxb7jaPTHpEVBz0uzQwkAAAB4eyJvcmlnaW4iOiJodHRwczovL3lvdXR1YmUuY29tOjQ0MyIsImZlYXR1cmUiOiJXZWJWaWV3WFJlcXVlc3RlZFdpdGhEZXByZWNhdGlvbiIsImV4cGlyeSI6MTcxOTUzMjc5OSwiaXNTdWJkb21haW4iOnRydWV9'
19.39.40.363 | FFmpeg | Trace | [https @ 00000157048c0700] header='Cross-Origin-Opener-Policy: same-origin-allow-popups; report-to="youtube_main"'
19.39.40.363 | FFmpeg | Trace | [https @ 00000157048c0700] header='Permissions-Policy: ch-ua-arch=*, ch-ua-bitness=*, ch-ua-full-version=*, ch-ua-full-version-list=*, ch-ua-model=*, ch-ua-wow64=*, ch-ua-form-factor=*, ch-ua-platform=*, ch-ua-platform-version=*'
19.39.40.363 | FFmpeg | Trace | [https @ 00000157048c0700] header='Report-To: {"group":"youtube_main","max_age":2592000,"endpoints":[{"url":"https://csp.withgoogle.com/csp/report-to/youtube_main"}]}'
19.39.40.363 | FFmpeg | Trace | [https @ 00000157048c0700] header='P3P: CP="This is not a P3P policy! See http://support.google.com/accounts/answer/151657?hl=de for more info."'
19.39.40.363 | FFmpeg | Trace | [https @ 00000157048c0700] header='Transfer-Encoding: chunked'
19.39.40.363 | FFmpeg | Trace | [https @ 00000157048c0700] header='Server: ESF'
19.39.40.363 | FFmpeg | Trace | [https @ 00000157048c0700] header='X-XSS-Protection: 0'
19.39.40.363 | FFmpeg | Trace | [https @ 00000157048c0700] header='Set-Cookie: YSC=l64-snGuUDU; Domain=.youtube.com; Path=/; Secure; HttpOnly; SameSite=none'
19.39.40.363 | FFmpeg | Trace | [https @ 00000157048c0700] header='Set-Cookie: __Secure-YEC=CgtPeTFORUJQdEMzZyjr4pmuBjIKCgJERRIEEgAgWQ%3D%3D; Domain=.youtube.com; Expires=Mon, 10-Mar-2025 18:39:38 GMT; Path=/; Secure; HttpOnly; SameSite=lax'
19.39.40.363 | FFmpeg | Trace | [https @ 00000157048c0700] header='Set-Cookie: VISITOR_PRIVACY_METADATA=CgJERRIEEgAgWQ%3D%3D; Domain=.youtube.com; Expires=Mon, 10-Mar-2025 18:39:39 GMT; Path=/; Secure; HttpOnly; SameSite=lax'
19.39.40.363 | FFmpeg | Trace | [https @ 00000157048c0700] header='Set-Cookie: VISITOR_INFO1_LIVE=; Domain=.youtube.com; Expires=Sat, 15-May-2021 18:39:39 GMT; Path=/; Secure; HttpOnly; SameSite=none'
19.39.40.363 | FFmpeg | Trace | [https @ 00000157048c0700] header='Set-Cookie: CONSENT=PENDING+846; expires=Sun, 08-Feb-2026 18:39:39 GMT; path=/; domain=.youtube.com; Secure'
19.39.40.363 | FFmpeg | Trace | [https @ 00000157048c0700] header='Alt-Svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000'
19.39.40.363 | FFmpeg | Trace | [https @ 00000157048c0700] header='Connection: close'
19.39.40.363 | FFmpeg | Trace | [https @ 00000157048c0700] header=''
19.39.40.364 | FFmpeg | Trace | [https @ 00000157048c0700] Chunked encoding data size: 8966
19.39.40.387 | FFmpeg | Trace | [https @ 00000157048c0700] Chunked encoding data size: 32768
19.39.40.407 | FFmpeg | Trace | [https @ 00000157048c0700] Chunked encoding data size: 20426
19.39.40.416 | FFmpeg | Trace | [https @ 00000157048c0700] Chunked encoding data size: 32754
19.39.40.428 | FFmpeg | Trace | [https @ 00000157048c0700] Chunked encoding data size: 12334
19.39.40.431 | FFmpeg | Trace | [https @ 00000157048c0700] Chunked encoding data size: 32754
19.39.40.440 | FFmpeg | Trace | [https @ 00000157048c0700] Chunked encoding data size: 20427
19.39.40.442 | FFmpeg | Trace | [https @ 00000157048c0700] Chunked encoding data size: 32754
19.39.40.448 | FFmpeg | Trace | [https @ 00000157048c0700] Chunked encoding data size: 12333
19.39.40.450 | FFmpeg | Trace | [https @ 00000157048c0700] Chunked encoding data size: 32754
19.39.40.455 | FFmpeg | Trace | [https @ 00000157048c0700] Chunked encoding data size: 20428
19.39.40.458 | FFmpeg | Trace | [https @ 00000157048c0700] Chunked encoding data size: 32754
19.39.40.466 | FFmpeg | Trace | [https @ 00000157048c0700] Chunked encoding data size: 12332
19.39.40.466 | FFmpeg | Trace | [https @ 00000157048c0700] Chunked encoding data size: 32754
19.39.40.468 | FFmpeg | Trace | [https @ 00000157048c0700] Chunked encoding data size: 14916
19.39.40.470 | FFmpeg | Trace | [https @ 00000157048c0700] Chunked encoding data size: 9982
19.39.40.472 | FFmpeg | Trace | [https @ 00000157048c0700] Chunked encoding data size: 32768
19.39.40.476 | FFmpeg | Trace | [https @ 00000157048c0700] Chunked encoding data size: 7846
19.39.40.478 | FFmpeg | Trace | [https @ 00000157048c0700] Chunked encoding data size: 32754
19.39.40.482 | FFmpeg | Trace | [https @ 00000157048c0700] Chunked encoding data size: 24915
19.39.40.485 | FFmpeg | Trace | [https @ 00000157048c0700] Chunked encoding data size: 32789
19.39.40.490 | FFmpeg | Trace | [https @ 00000157048c0700] Chunked encoding data size: 7810
19.39.40.491 | FFmpeg | Trace | [https @ 00000157048c0700] Chunked encoding data size: 3004
19.39.41.191 | FFmpeg | Trace | [https @ 00000157048c0700] Chunked encoding data size: 162
19.39.41.226 | FFmpeg | Trace | [https @ 00000157048c0700] Chunked encoding data size: 32768
19.39.41.246 | FFmpeg | Trace | [https @ 00000157048c0700] Chunked encoding data size: 21765
19.39.41.246 | FFmpeg | Trace | [https @ 00000157048c0700] Chunked encoding data size: 32754
19.39.41.246 | FFmpeg | Trace | [https @ 00000157048c0700] Chunked encoding data size: 10995
19.39.41.246 | FFmpeg | Trace | [https @ 00000157048c0700] Chunked encoding data size: 32754
19.39.41.246 | FFmpeg | Trace | [https @ 00000157048c0700] Chunked encoding data size: 21766
19.39.41.246 | FFmpeg | Trace | [https @ 00000157048c0700] Chunked encoding data size: 32754
19.39.41.251 | FFmpeg | Trace | [https @ 00000157048c0700] Chunked encoding data size: 10994
19.39.41.252 | FFmpeg | Trace | [https @ 00000157048c0700] Chunked encoding data size: 32754
19.39.41.257 | FFmpeg | Trace | [https @ 00000157048c0700] Chunked encoding data size: 21767
19.39.41.260 | FFmpeg | Trace | [https @ 00000157048c0700] Chunked encoding data size: 32754
19.39.41.264 | FFmpeg | Trace | [https @ 00000157048c0700] Chunked encoding data size: 10993
19.39.41.266 | FFmpeg | Trace | [https @ 00000157048c0700] Chunked encoding data size: 32862
19.39.41.270 | FFmpeg | Trace | [https @ 00000157048c0700] Chunked encoding data size: 21660
19.39.41.276 | FFmpeg | Trace | [https @ 00000157048c0700] Chunked encoding data size: 35684

     On Friday, February 9, 2024 at 07:06:29 PM GMT+1, John Stamatakis ***@***.***> wrote:  
 
 


Ctrl+V works but right click Paste Url does not? (Can't reproduce it)

**Comment by SuRGeoNix** [comment]
So I guess the issue is Open generally not just paste? Can you open other Urls rather than yt-dlp (eg. local mp4 file?)
Also can't see the error in the trace log, it's like its no all of it? Get it after you close Flyleaf to flush the log file.
I will review this tomorrow but it seems it's only a yt-dlp issue so you can check using only yt-dlp to see if it works? Or a network issue?

**Comment by SuRGeoNix** [comment]
Just noticed that you can't see also LogLevels drop down. You have a more generic issue here, not sure what is going on but that does not seem to be Flyleaf at all. which was the last version that worked ok? (.NET 8 issue?)

**Comment by Isayso** [comment]
local files mp4 are working, if I download a video with yt-dlp from command line it is working also, odd.
last version I used was .7.14

Is it possible to debug and step-through your code with visual studio? 
     On Saturday, February 10, 2024 at 09:42:09 AM GMT+1, John Stamatakis ***@***.***> wrote:  
 
 


Just noticed that you can't see also LogLevels drop down. You have a more generic issue here, not sure what is going on but that does not seem to be Flyleaf at all. which was the last version that worked ok? (.NET 8 issue?)

**Comment by Isayso** [comment]
I cloned the source code and copied yt-dlp.exe (last version) to the _here folder.
When I run a link I get the same error 

demuxer.cs line 442 ret<0 ret is negative

Hope this helps, or where should I look further?     On Saturday, February 10, 2024 at 09:42:09 AM GMT+1, John Stamatakis ***@***.***> wrote:  
 
 


Just noticed that you can't see also LogLevels drop down. You have a more generic issue here, not sure what is going on but that does not seem to be Flyleaf at all. which was the last version that worked ok? (.NET 8 issue?)

**Comment by SuRGeoNix** [comment]
No, I would start from the LogLevels that you said... if you can't see that something more generic is happening. You might compile it for .NET 6 instead of .NET 8 and see if that works.

**Comment by Isayso** [comment]
no change with .net6

-1094995529 comes from OpenFormat(url, inFmt, fmtOptExtra, out ret);
inFmt is 0x0, fmtOptExtra null, url the right url
 
if I understand correctely, this is the return value from the ffmpeg code part and it should be 0

     On Saturday, February 10, 2024 at 07:49:17 PM GMT+1, John Stamatakis ***@***.***> wrote:  
 
 


No, I would start from the LogLevels that you said... if you can't see that something more generic is happening. You might compile it for .NET 6 instead of .NET 8 and see if that works.

**Comment by SuRGeoNix** [comment]
Drop me an email if you want to debug it together with anydesk

**Comment by Isayso** [comment]
ret = avformat_open_input(fmtCtxPtr, url, inFmt, avopt == null ? null : &avopt);

Was not able to generate a better error desription, the ffmpeg avformat_open_input is throwing this error.

I will install anydesk and sent you an email.     On Sunday, February 11, 2024 at 01:06:34 PM GMT+1, John Stamatakis ***@***.***> wrote:  
 
 


Drop me an email if you want to debug it together with anydesk
