### ISSUE TITLE
AV1 video decoding isn't hardware accelerated

### ISSUE THREAD

**Issue by valery-kirichenko** [SuRGeoNix/Flyleaf#340]
I noticed that even though AV1 playback works, the player does not use GPU for decoding even though both GPU and FFmpeg support it (ffmpeg was tested using `.\ffmpeg.exe -hwaccel nvdec -c:v av1 -i video.mp4 out.mp4`). This is especially noticeable when seeking through 4K videos as the CPU get 100% utilized (and I have 32 threads at 5.4 GHz😀). I have tried both included FFmpeg 5.1.2 and FFmpeg 6.0 (with FFmpeg.AutoGen v6).

You can use this video to test it https://www.youtube.com/watch?v=7PIji8OubXU It only has HDR AV1 variants, but the issue persists even with SDR videos.

**Comment by SuRGeoNix** [comment]
@valery-kirichenko Unfortunately, NVDEC/CUVID is not currently supported by Flyleaf. It works only with [D3D11VA](https://github.com/SuRGeoNix/Flyleaf/blob/master/FlyleafLib/MediaFramework/MediaDecoder/VideoDecoder.cs#L88). I'm planning to support it in version 4 - including linux/osx - however not sure when I will be able to release it.

**Comment by valery-kirichenko** [comment]
It seems like DXVA should also support AV1 decoding based on [FFmpeg wiki](https://trac.ffmpeg.org/wiki/HWAccelIntro#DXVA2) and [Microsoft's spec](https://www.microsoft.com/en-us/download/details.aspx?id=101577), although I can't get it to work using `-hwaccel dxva2 -threads 1` for some reason (it still uses CPU but without any errors)

**Comment by SuRGeoNix** [comment]
I doubt that DXVA2 can do something more than D3D11VA. It is older and is mainly there to support Direct9.

**Comment by valery-kirichenko** [comment]
Well, I used DXVA2 here because it was something I was able to find documentation for easily :)
I tested mpv with --hwdec=d3d11va and it worked, so I believe using d3d11va should not be the issue here:
```
[   1.329][v][vd] Looking at hwdec av1-d3d11va...
[   1.329][v][vo/gpu-next] Loading hwdec drivers for format: 'd3d11'
[   1.329][v][vo/gpu-next] Loading hwdec driver 'd3d11-egl'
[   1.329][v][vo/gpu-next] Loading failed.
[   1.329][v][vo/gpu-next] Loading hwdec driver 'd3d11va'
[   1.330][v][vd] Trying hardware decoding via av1-d3d11va.
[   1.330][v][vd] Using underlying hw-decoder 'av1'
[   1.330][v][vd] Selected codec: libdav1d (dav1d AV1 decoder by VideoLAN)
[   1.330][v][vf] User filter list:
[   1.330][v][vf]   (empty)
[   1.330][v][ad] Codec list:
[   1.330][v][ad]     aac - AAC (Advanced Audio Coding)
[   1.330][v][ad]     aac_fixed (aac) - AAC (Advanced Audio Coding)
[   1.330][v][ad] Opening decoder aac
[   1.331][v][ad] Requesting 1 threads for decoding.
[   1.334][v][ad] Selected codec: aac (AAC (Advanced Audio Coding))
[   1.334][v][af] User filter list:
[   1.334][v][af]   (empty)
[   1.334][v][cplayer] Starting playback...
[   1.336][v][vd] Pixel formats supported by decoder: dxva2_vld d3d11va_vld d3d11 cuda vulkan yuv420p10le
[   1.336][v][vd] Codec profile: Main (0x0)
[   1.339][v][vd] Requesting pixfmt 'd3d11' from decoder.
[   1.339][d][ffmpeg/video] av1: Decoder GUIDs reported as supported:
[   1.339][d][ffmpeg/video] av1: {86695f12-340e-4f04-9fd3-9253dd327460} 103 106
[   1.339][d][ffmpeg/video] av1: {ee27417f-5e28-4e65-beea-1d26b508adc9} 103 106
[   1.340][d][ffmpeg/video] av1: {6f3ec719-3735-42cc-8063-65cc3cb36616} 103 106
[   1.340][d][ffmpeg/video] av1: {1b81bea4-a0c7-11d3-b984-00c04f2e73c5} 103 106
[   1.340][d][ffmpeg/video] av1: {1b81bea3-a0c7-11d3-b984-00c04f2e73c5} 103 106
[   1.340][d][ffmpeg/video] av1: {32fcfe3f-de46-4a49-861b-ac71110649d5} 103 106
[   1.340][d][ffmpeg/video] av1: {d79be8da-0cf1-4c81-b82a-69a4e236f43d} 103 106
[   1.340][d][ffmpeg/video] av1: {f9aaccbb-c2b6-4cfc-8779-5707b1760552} 103 106
[   1.341][d][ffmpeg/video] av1: {1b81be68-a0c7-11d3-b984-00c04f2e73c5} 103 106
[   1.341][d][ffmpeg/video] av1: {5b11d51b-2f4c-4452-bcc3-09f2a1160cc0} 103 106
[   1.341][d][ffmpeg/video] av1: {107af0e0-ef1a-4d19-aba8-67a163073d13} 104 106
[   1.341][d][ffmpeg/video] av1: {20bb8b0a-97aa-4571-8e99-64e60606c1a6} 104 106
[   1.341][d][ffmpeg/video] av1: {15df9b21-06c4-47f1-841e-a67c97d7f312} 103 106
[   1.342][d][ffmpeg/video] av1: {efd64d74-c9e8-41d7-a5e9-e9b0e39fa319} 103 106
[   1.342][d][ffmpeg/video] av1: {ed418a9f-010d-4eda-9ae3-9a65358d8d2e} 103 106
[   1.342][d][ffmpeg/video] av1: {9947ec6f-689b-11dc-a320-0019dbbc4184} 103 106
[   1.342][d][ffmpeg/video] av1: {33fcfe41-de46-4a49-861b-ac71110649d5} 103 106 107
[   1.342][d][ffmpeg/video] av1: {463707f8-a1d0-4585-876d-83aa6d60b89e} 103 106
[   1.342][d][ffmpeg/video] av1: {a4c749ef-6ecf-48aa-8448-50a7a1165ff7} 104 106
[   1.342][d][ffmpeg/video] av1: {dda19dc7-93b5-49f5-a9b3-2bda28a2ce6e} 104 106
[   1.343][d][ffmpeg/video] av1: {b8be4ccb-cf53-46ba-8d59-d6b8a6da5d2a} 103 104 106
[   1.343][d][ffmpeg/video] av1: {6affd11e-1d96-42b1-a215-93a31f09a53d} 103 106
[   1.343][d][ffmpeg/video] av1: {914c84a3-4078-4fa9-984c-e2f262cb5c9c} 103 106
[   1.343][d][ffmpeg/video] av1: {8a1a1031-29bc-46d0-a007-e9b092ca6767} 103 106
[   1.392][i][vd] Using hardware decoding (d3d11va).
[   1.392][v][vd] Decoder format: 7680x4320 d3d11[p010] bt.2020-ncl/bt.2020/pq/limited/auto CL=unknown
[   1.392][v][vf] [in] 7680x4320 d3d11[p010] bt.2020-ncl/bt.2020/pq/limited/display SP=49.261086 CL=mpeg2/4/h264
[   1.392][v][vf] [userdeint] 7680x4320 d3d11[p010] bt.2020-ncl/bt.2020/pq/limited/display SP=49.261086 CL=mpeg2/4/h264
[   1.392][v][vf] [userdeint] (disabled)
[   1.392][v][vf] [autorotate] 7680x4320 d3d11[p010] bt.2020-ncl/bt.2020/pq/limited/display SP=49.261086 CL=mpeg2/4/h264
[   1.392][v][vf] [autorotate] (disabled)
[   1.392][v][vf] [convert] 7680x4320 d3d11[p010] bt.2020-ncl/bt.2020/pq/limited/display SP=49.261086 CL=mpeg2/4/h264
[   1.392][v][vf] [convert] (disabled)
[   1.392][v][vf] [out] 7680x4320 d3d11[p010] bt.2020-ncl/bt.2020/pq/limited/display SP=49.261086 CL=mpeg2/4/h264
```

![image](https://github.com/SuRGeoNix/Flyleaf/assets/3050013/ecc7d5d2-1e88-4f59-b0b8-8b8930ea5cff)

**Comment by valery-kirichenko** [comment]
Also, if DXVA2 supports AV1 and it's older, then newer DX11VA should support it as well, shouldn't it?
![image](https://github.com/SuRGeoNix/Flyleaf/assets/3050013/c9441a50-fc3c-4019-83cb-75e9991eb189)

**Comment by SuRGeoNix** [comment]
Yes, are you sure that you use ffmpeg codecs/libraries that support av1? I will check mpv but make sure it is not just an issue with this.

**Comment by SuRGeoNix** [comment]
Hm... might work directly if you set this Config.Decoder.AllowProfileMismatch = true;

**Comment by valery-kirichenko** [comment]
Yes, I am pretty sure if my testing that was described in the original message was done correctly. AllowProfileMismatch set to true didn't help.
[log.txt](https://github.com/SuRGeoNix/Flyleaf/files/12486117/log.txt)

**Comment by SuRGeoNix** [comment]
Cannot see why it does not work. Can you make that If to always pass (enables VA) and add trace log only in Flyleaf if you can to review it.

https://github.com/SuRGeoNix/Flyleaf/blob/master/FlyleafLib/MediaFramework/MediaDecoder/VideoDecoder.cs#L286

**Comment by valery-kirichenko** [comment]
I get Buffering failed error
[trace.log](https://github.com/SuRGeoNix/Flyleaf/files/12488085/trace.log)

**Comment by SuRGeoNix** [comment]
Interesting... I will have a better look on the next update

http://ffmpeg.org/doxygen/trunk/group__lavc__core.html#ga4f80582a2ea9c0e141de5d6f6152008f

**Comment by SuRGeoNix** [comment]
@valery-kirichenko Can you try to change [this line](https://github.com/SuRGeoNix/Flyleaf/blob/master/FlyleafLib/MediaFramework/MediaDecoder/DecoderBase.cs#L77) to this:-

```csharp
var codec = stream.CodecID == AVCodecID.AV_CODEC_ID_AV1 ? avcodec_find_decoder_by_name("av1") : avcodec_find_decoder(stream.CodecID);
```

**Comment by valery-kirichenko** [comment]
Changing the line fixed HW acceleration :)
> By the way, from what I can see dav1d is a CPU decoder, so I'm not sure how you managed to do GPU decoding with mpv and dav1d
Yeah, I noticed that as well. Same happens with FFmpeg -hwaccel options, libdav1d in logs but video decoding is obviously HW accelerated.

**Comment by SuRGeoNix** [comment]
That's good news. I will need to review also proper fallback in software decoder if the GPU does not supported, because in this case there are different software/hardware decoders (codecs) and then I will have an update. Here a quick list that I've made with all the D3D11 hardware decoders supported by FFmpeg:

```
AV1 		| av1 		| Alliance for Open Media AV1
H264 		| h264 		| H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
HEVC 		| hevc 		| HEVC (High Efficiency Video Coding)
MPEG2VIDEO 	| mpeg2video| MPEG-2 video
VC1 		| vc1 		| SMPTE VC-1
VP9 		| vp9 		| Google VP9
WMV3 		| wmv3 		| Windows Media Video 9
```
