### ISSUE TITLE
Unable to play video file at http://

### ISSUE THREAD

**Issue by sharmasulekh87** [SuRGeoNix/Flyleaf#343]
Hello @SuRGeoNix ,
Hope you are in good heath. I have just a small query, whenever I try to play a video url starting with http://, the player searches for youtube plugin. Is this plugin mandatory to play such urls? What if I want to play the file without using this plugin?

**Comment by SuRGeoNix** [comment]
Hi @sharmasulekh87, just remove the YT-DLP plugin. But if you want it then it will need first to check if it need to be analyzed first. I could review some enchantments to avoid passing some Urls from the YT-DLP for faster open.
