### ISSUE TITLE
Video duration is 0

### ISSUE THREAD

**Issue by brischt** [SuRGeoNix/Flyleaf#345]
Hi,
I am creating a WPF application to play back a videos using this fantastic library.
Playback works well; however, the seek slider is always on the upper end and cannot be moved, because the duration of the video is reported as 0.
That's (I guess) because ffmpeg reports:  

`Duration: N/A, start: 0.000000, bitrate: N/A `

on the command line. However, I can use ffprobe with the -show_packets option and get the last packet for e.g.:
```
[PACKET]
codec_type=video
stream_index=0
pts=891
pts_time=35.640000
dts=891
dts_time=35.640000
duration=1
duration_time=0.040000
size=364800
pos=351570044
flags=K__
[/PACKET]
```

So, my question is - can I somehow convince Flyleaf to use the time plus duration of the last package, to get the seek slider working?

**Comment by SuRGeoNix** [comment]
Hi @brischt and thanks for the fantastic :)

You could try settings Duration manually but from the library's code by changing this line (in Ticks):-

https://github.com/SuRGeoNix/Flyleaf/blob/master/FlyleafLib/MediaFramework/MediaDemuxer/Demuxer.cs#L530

However, this is an invalid media file that it does not announce duration properly so I'm not sure if you ask me to somehow change the duration from the app level. It's not possible for the lib to know the last packets timestamp (before analyze it).
