### ISSUE TITLE
Start Skip Issue

### ISSUE THREAD

**Issue by MrJacquers** [SuRGeoNix/Flyleaf#346]
I've noticed that some videos skip the first 2-3 seconds. They play correctly from the start in other players like VLC. I think it may have something to do with the encoding / muxing or how it's been downloaded. Not really serious, since it's usually just the intro that does this.

Avidemux says this when I open the file:

This video contains B-frames, but presentation time stamps (PTS) are either missing or monotonically increasing. Avidemux can try to reconstruct correct PTS by decoding the entire video. This may take a lot of time. Proceed?

Sample attached.

https://github.com/SuRGeoNix/Flyleaf/assets/84329887/0257f87f-994b-4277-b548-27140b29cd9b

**Comment by SuRGeoNix** [comment]
@MrJacquers, the format has the following specs:-

```
[Format  ] QuickTime / MOV/mov,mp4,m4a,3gp,3g2,mj2 | mov,mp4,m4a,3gp,3g2,mj2,psp,m4b,ism,ismv,isma,f4v,avif | 00:00:00/00:00:10.1340000 | 00:00:00/00:00:10.1340000
[Video #0] h264 yuv420p 1280x640 @ 23,859 | [Color: BT709] [BR: 192423] | 00:00:03.0410000/00:00:07.0832666 | 00:00:03.0410000/00:00:07.0832666
[Audio #1-eng] aac fltp@16 96KHz stereo | [BR: 192438] | 00:00:00/00:00:10.1333333 | 00:00:00/00:00:10.1333333
```

If you see the audio is ~10 seconds but the video is ~5 seconds and start from the 3rd second till 7. That's why you see this strange behavior. What VLC does that Flyleaf doesn't in this case, is that it skips the audio samples until the first video frame. However, if flyleaf allows audio without video initially that might cause issues in other cases (eg. HLS)

**Comment by MrJacquers** [comment]
Thanks for checking so quickly :)

I can fix it by remuxing it with Avidemux, but it's not really a big enough issue for these files.

**Comment by MrJacquers** [comment]
btw, what tool / program did you use to get that info? I just want to check the original file, just in case the program I used to cut the sample made weird changes. Thanks.

**Comment by SuRGeoNix** [comment]
Flyleaf with debug log enabled

**Comment by MrJacquers** [comment]
Thanks. The 'original' file has more similar audio and video durations and starts. Anyway, not really a big issue and I think I understand why it's happening. Probably caused by the FF extension Videodownloadhelper and how it processes certain videos.

[Format  ] QuickTime / MOV/mov,mp4,m4a,3gp,3g2,mj2 | mov,mp4,m4a,3gp,3g2,mj2,psp,m4b,ism,ismv,isma,f4v | 00:00:00/00:49:20.4050000 | 00:00:00/00:49:20.4050000
[Video #0] h264 yuv420p 1280x640 @ 23,999 | [Color: BT709] [BR: 465620] | 00:00:00/00:49:20.3330000 | 00:00:00/00:49:20.3330000
[Audio #1-eng] aac fltp@16 96KHz stereo | [BR: 192000] | 00:00:00/00:49:20.4053333 | 00:00:00/00:49:20.4053333
[debug.txt](https://github.com/SuRGeoNix/Flyleaf/files/12640468/debug.txt)

Also attached the debug of another file with the same issue.

**Comment by SuRGeoNix** [comment]
Well the 2nd video with the attached log has another issue. It does not start with a keyframe required for the video stream. All those issues are coming from the muxer that you use. I'm not even sure if I would allow (at least initially) to play the corrupted non-key (B/P) frames if it would even play a proper frame at all. But yes, probably you will need a better program to mux them.
