### ISSUE TITLE
Suggestion for bigger Pause/Play button

### ISSUE THREAD

**Issue by Isayso** [SuRGeoNix/Flyleaf#349]
I would like to have a bigger Play/Pause button. I have seen a solution on Android app which could work.
With a single click in the player window a big Play/Pause button appears which can be  clicked. 

I added a screenshot of it. If you don't click it disappears with a timer.  The arrows are 10s jumps. 
Thanks!
  
![pause_button](https://github.com/SuRGeoNix/Flyleaf/assets/35309607/786a4e07-9694-45da-8d5a-8ab6db2b78f1)
![Play_button](https://github.com/SuRGeoNix/Flyleaf/assets/35309607/d07c0ff6-675f-4526-a9c3-41a089f3e9e2)

**Comment by SuRGeoNix** [comment]
Hi @Isayso, I'm not currently focusing on the sample/demo Player. When I will have a more powerful library I will try to code a proper media player. But please for now don't open issues(features) for the samples, only for the library.

**Comment by Isayso** [comment]
Ok, are there some other builders/examples who use the lib to take a look at? Thanks

**Comment by SuRGeoNix** [comment]
You can customize the main Flyleaf Player sample here https://github.com/SuRGeoNix/Flyleaf/tree/master/Samples/FlyleafPlayer%20(WPF%20Control)%20(WPF)
