### ISSUE TITLE
Switching streams or open a custom IO stream sometimes crashes (critical)

### ISSUE THREAD

**Issue by graphixillusion** [SuRGeoNix/Flyleaf#35]
As the title says i've tried to change the resolution of an youtube stream with last 3.1 version and it doesnt work.

**Comment by SuRGeoNix** [comment]
Can't reproduce it. Is it the specific video or generally you can't switch streams on youtube-dl videos?

**Comment by graphixillusion** [comment]
@SuRGeoNix Nope i have tried several youtube videos and i can't change streams on any of them

**Comment by graphixillusion** [comment]
@SuRGeoNix I've tried again now and now it works. I don't know why before didn't. Another quick question: did you remove the CTRL+V paste shortcut?

**Comment by SuRGeoNix** [comment]
That might be a youtube-dl issue that feeds Flyleaf sometimes with wrong URLs.

Yes,  I've not focus on the Flyleaf player at least for now. I'm focusing on the library and support the WPF controls. A lot of functionality is missing from v2.6 as a Player. I will try to bring it back soon.

Re-open this if you continue having issues with youtube-dl and if you can provide logs, would be great.

**Comment by SuRGeoNix** [comment]
Added the most of them, I will update the sample version as far as we resolve the most of the bugs of v3.1 ;)

**Comment by SuRGeoNix** [comment]
@graphixillusion Just patched the v3.1 so re-download it (updated also youtube-dl might have some issues)

https://github.com/SuRGeoNix/Flyleaf/releases/download/v3.1/Flyleaf_v3.1.7z
