### ISSUE TITLE
Seek method is using the wrong mutex - can result in thread deadlocks

### ISSUE THREAD

**Issue by signumnova** [SuRGeoNix/Flyleaf#350]
There is a flag in Seek called "taskSeekRuns" that is protected by a lock whenever it changes value, however it does not consistently use the same mutex through the code to do this.  It uses both "seeks" as well as "lockActions" in different places.

In my opinion they should all be using "seeks" otherwise competing threads are not properly synchronised in their use of this variable.

I traced this down hunting for a different issue caused by the same thing in a way: a thead deadlock condition occurring on the second call of OpenAsync to an existing player instance.

**Comment by SuRGeoNix** [comment]
Hi @signumnova and thanks for raising this issue.

From what I can see taskSeekRuns uses only lockActions and not lock with seeks. Ideally, I would like to find a way to reproduce it, but if that not possible can you confirm at which line (of each thread) the deadlock happens? (E.g. between OpenAsync and Seek?)

**Comment by signumnova** [comment]
I believe there's actually two problems here:

1. The seek method itself at around line 190 locks with the **seeks** mutex, but inside the background thread that it then launches with a Task.Run takes out a locks in two places with the **lockActions** mutex. The net effect of this is that there is no sync between those two threads on that object because both locks will succeed. 

Now the chances of this happening may be quite remote, but this kind of thing can lead to occasional problems that can be extremely hard to track down because they happen so infrequently and unpredictably. I can't give you a test case that shows this happening; for multi-threaded code particularly you can't always wait for a test case that proves the issue in practice - you have to look at the code and just recognise the potential problem that can occur because the correct pattern is not being adhered to.

2. The second issue is much more insidious because you can't see it easily from code inspection. This one I found using the debugger where the app had effectively stopping processing OpenAsync requests.  What I discovered is a form of deadlock that is not directly the result of two threads waiting on a mutex that the other held, but a sort of implicit deadlock that has the same effect. Allow me to explain:

OpenAsync (eventually) calls Player.Initialise, and there is a block of code in there that takes out a lock on lockActions, and whilst it holds that mutex it waits in a loop so long as there is a background task running:

                while (taskPlayRuns || taskSeekRuns) Thread.Sleep(5);

Now if the background Task for seeking happens to be in progress just at that moment, which it can be because of the asynchronous nature of all this, then eventually it gets to its finally clause and does this:

   lock (lockActions) taskSeekRuns = false;

But at this point it blocks because the mutex is held by OpenAsync and neither thread can go any further.

NB: All of this is extremely timing dependent in order to be able to reproduce reliably.

The conditions to get it to happen fairly easily require doing a seek to rewind when the media ends. (As you would to get videos to autorepeat). A video with only a few frames, or a static image with only one frame, is going to cause a lot of repeated seeking, hence the chances of setting up the condition are quite good.   

The issue is resolved as per my PR... simply get the seek method to only ever use its own mutex.
