### ISSUE TITLE
rtsp failed: 461 Unsupported Transport

### ISSUE THREAD

**Issue by Peter9952** [SuRGeoNix/Flyleaf#355]
My LiveStream source: rtsp://10.20.30.40:554/?freq=442&msys=dvbc&sr=6900&mtype=256qam&pids=0,16,17,18,20,2000,2001,2011,2012,2041,2071,2101 .
vlc and ffplay deliver a perfect video straight away.

FlyleafPlayer (Custom - MVVM) (WPF) from download Flyleaf-master from 20231009:

"rtsp://10.20.30.40:554/?freq=442&msys=dvbc&sr=6900&mtype=256qam&pids=0,16,17,18,20,2000,2001,2011,2012,2041,2071,2101" in the input field and "open"

brings the error -135 and in the debugger:
16.59.42.111 | Debug | [#1]     [Demuxer:  Main] Stopped -> Opening
16.59.42.177 | FFmpeg | Error   | [rtsp @ 0000022c44fa6ec0] method SETUP failed: 461 Unsupported Transport
16.59.42.184 | Debug | [#1]     [Demuxer:  Main] Opening -> Stopped
16.59.42.185 | Info  | [#1]     [Demuxer:  Main] Disposed
16.59.42.187 | Info  | [#1]     [DecoderContext] [OpenPlaylistItem] None =>  [Error: [avformat_open_input] Error number -135 occurred (-135)]
16.59.42.188 | Info  | [#1]     [DecoderContext] [Open] rtsp://10.20.30.40:554/?freq=442&msys=dvbc&sr=6900&mtype=256qam&pids=0,16,17,18,20,2000,2001,2011,2012,2041,2071,2101  [Error: [avformat_open_input] Error number -135 occurred (-135)]

Other projects in the current project folder Flyleaf-master also produce the error
Can I change anything in the sample project or does this source not work?

**Comment by SuRGeoNix** [comment]
Hi @Peter9952,

Try to set to udp as FlyleafLib by default sets rtsp transport to tcp

```csharp
Config.Demuxer.FormatOpt["rtsp_transport"] = "udp";
```

**Comment by SuRGeoNix** [comment]
@Peter9952 please give me some feedback if you still have issues

**Comment by Peter9952** [comment]
Hi SuRGeoNix
Thanks for the quick answer, the player works perfectly.
Now I would like to use the same stream with the downloader, but I get the error message shown in the attachment. udp transport is built into the config. Please can you please help me? Thank you!
[FL2.pdf](https://github.com/SuRGeoNix/Flyleaf/files/13066978/FL2.pdf)
[FLDownload.txt](https://github.com/SuRGeoNix/Flyleaf/files/13067011/FLDownload.txt)

**Comment by SuRGeoNix** [comment]
@Peter9952 the log shows tcp connection, what do you mean build in? Do the same with the config (set to udp)?

**Comment by Peter9952** [comment]
Hi SuRGeoNix
Before or after the initialization - the same error occurs - I already tried it before the last comment.
I have now carried out a new, clean installation with the version Updates to v3.7.30 (FlyleafLib) / v1.2.29 (FlyleafME) / v1.0.15 (Flyl… ). The line Config.Demuxer.FormatOpt["rtsp_transport"] = "udp" was added to both installations. The FlyleafePlayer Samples\FlyleafePlayer(Custom-MVVM)(Wpf) works, the downloader Samples\FlyleafDownloader (WinForms) brings the error described above.
In the attachment is a debug of the non-functioning downloader and, for comparison, a debug of the working player. Maybe it helped with the analysis.
[FLDownload.txt](https://github.com/SuRGeoNix/Flyleaf/files/13167017/FLDownload.txt)
[FLPlayer.txt](https://github.com/SuRGeoNix/Flyleaf/files/13167018/FLPlayer.txt)

**Comment by SuRGeoNix** [comment]
@Peter9952 probably it's your window's firewall that somehow stops your udp, try to add the application as an exception. I can't see an issue somewhere else.

**Comment by Peter9952** [comment]
I checked the firewall for a long time and didn't see any anomalies in the log. I then took a closer look at your code and was able to start the download by changing the format of the URL.
I will check again whether vlc or Flyleave meets my expectations. Thank you for your support.
