### ISSUE TITLE
Moving FlyleafHost to another window, notifying Owner change

### ISSUE THREAD

**Issue by rkinnunen** [SuRGeoNix/Flyleaf#357]
Hey,

I'm developing a program in which you can view several different video and image streams, in which I'm swapping our old video player with Flyleaf.

The simplified basic structure of the program goes:

Window
 - Tabs
    - Slots
      - SlotElements (some are elements containing FlyleafHosts, some are fully native WPF elements)

You can also open another window, which has exactly the same structure.

Tabs are drag and droppable, and I have no issue doing so within the same window. But when I drag and drop a tab onto the other window, the tab changes windows, but the FlyleafHosts are still drawn on top of the first window, Surface and Overlay windows are still children of the main window. This causes the whole program to be out of sync. Drag'n'Drop works properly with all other SlotElements, which are native WPF elements.

Drag and drop functionality is implemented with [GongSolutions WPF DragDrop](https://github.com/punker76/gong-wpf-dragdrop/)

Is there a method I should call to notify the FlyleafHosts to update their Owner property?
I tried calling Deattach() followed by Attach(), but that didn't work.

Thanks in advance,
-Riku

**Comment by saman1832** [comment]
I am also facing same issue. I have used Dragablz for dragging the Tab out. I have also tried attached and deattached property but no success.

**Comment by rkinnunen** [comment]
> Guys, is it possible to create a demo/sample so I can review this easier?

[DragDropSample.zip](https://github.com/SuRGeoNix/Flyleaf/files/13114580/DragDropSample.zip)
Here's a very simple quick demo. 

Move a tab containing Flyleaf from one window to another, Flyleaf will still be drawn on top of the old window, now blocking the empty tab. 
Swap tabs to an empty one on the window you moved Flyleaf to, and the player will then be hidden.

**Comment by SuRGeoNix** [comment]
Can you test from master to see if that fixes it?

**Comment by saman1832** [comment]
@SuRGeoNix I have tried and its working as per expectation. Thanks for fixing it quickly.
Just wanted to know when the new release with this fix will be available as nuget?

**Comment by SuRGeoNix** [comment]
@saman1832 For some reason your comment has been deleted? Can you confirm that the fix is working so I can release the NuGet?

**Comment by saman1832** [comment]
No the above fix is not working.

**Comment by SuRGeoNix** [comment]
Can you describe in detail what causes the issue now?

**Comment by saman1832** [comment]
Its working in similar way like earlier. There is no effect of code changes.
But sometime if I am applying debug point in  Host_Loaded method its working but only sometime. I am not able to debug as of now.
I am debugging.

**Comment by SuRGeoNix** [comment]
I'm facing this issue https://github.com/dotnet/wpf/ "combine them just to avoid mention" issues/3719

**Comment by saman1832** [comment]
But our application is not crashing in any scenario as well we are not using windowsform host.

**Comment by SuRGeoNix** [comment]
I'm not sure what is going on, when I wrote the fix it was working fine and now it crashes all the time. Maybe something with my GPU/driver. I cannot debug it currently.

**Comment by SuRGeoNix** [comment]
So the crash comes when I transfer one Flyleaf tab to the other window and then i try to switch tabs in this window. If I initially switch tabs before transfer it to the other window it will work fine.

**Comment by saman1832** [comment]
please try this demo
[https://drive.google.com/file/d/1y2NKArt-LTCZlh46C0cECZs7k4kM3yTW/view?usp=sharing](url)
Click on liveview then drag the liveview tab. This issue i am facing

**Comment by saman1832** [comment]
@SuRGeoNix Actually I was doing wrong. i was importing wrong dll. now I have used  xmlns:fl1="clr-namespace:FlyleafLib.Controls.WPF;assembly=FlyleafLib.Controls.WPF" this one and its working perfect.

Earlier I was using FlyleafHost but after using FlyleafME resolves my problem

Please release this as nuget

**Comment by SuRGeoNix** [comment]
@saman1832 For the last demo that you send it's another issue though, which I'm trying to fix as well

**Comment by saman1832** [comment]
> @saman1832 For the last demo that you send it's another issue though, which I'm trying to fix as well

But the above issuse with the changes you done and using FlyleafME is working perfectly. I dont how but yes its working absolutely fine with FlyleafME.

**Comment by SuRGeoNix** [comment]
@saman1832 for the last demo if you drag out the tab it will not work with the current fix (does it work for you?)

**Comment by saman1832** [comment]
> @saman1832 for the last demo if you drag out the tab it will not work with the current fix (does it work for you?)

yes it works for me If I am using FlyleafME.

**Comment by SuRGeoNix** [comment]
Please re-test with the NuGet and let me know if that solves the issue

**Comment by saman1832** [comment]
@SuRGeoNix its working fine with the NuGet. Thanks for the fix.
