### ISSUE TITLE
Reconnect Issue

### ISSUE THREAD

**Issue by zer0ne1** [SuRGeoNix/Flyleaf#359]
i can check when rtsp die but how to automatically reconnect rtsp when it becomes active?
pls help me, tks very much!

**Comment by SuRGeoNix** [comment]
Just re-open it? Or you mean how you will check if it is up? just ping it?

**Comment by zer0ne1** [comment]
That's right. Is there any way to re-open rtsp when rtsp active?

**Comment by SuRGeoNix** [comment]
@zer0ne1 When the stream disconnects start a monitor thread that pings the IP address, or check with tcp/udp full connection manually to ensure that is back again. Then just re-open it same way as you open it. Not sure if you need some specific details.
