### ISSUE TITLE
Robovoice when playing back audio at playback speed >1

### ISSUE THREAD

**Issue by Mankov-A** [SuRGeoNix/Flyleaf#360]
Audio artefacts appear when playing an audio file with a speed greater than 1 (x1.5, x2). 
Reproduced for any audio codec.

**Comment by SuRGeoNix** [comment]
Hi @Mankov-A, I guess you were talking about the latest version and for audio only playback.
Please re-test from master and let me know if that fixes the issue.
In the mean-time I will try to see if possible to include the fix also for video/audio playback as well.
