### ISSUE TITLE
Automatic play of srt stream when video output changes

### ISSUE THREAD

**Issue by saman1832** [SuRGeoNix/Flyleaf#361]
Play any live url using openasyn(url) and when the that stream is stopped and played again from source itself then there is no event to capture that source stream is played agai.
Just like we have vout event in libvlsharp do we have similar event here(like videolistener event)

And is there any way to use pass-phrase in flyleaf player

**Comment by SuRGeoNix** [comment]
@saman1832 Please describe in more details with simple words what you need so I can include it or tell you how you can already it do it

**Comment by saman1832** [comment]
In libvlc(vlc) we have vout event like videolistener.  when stream stops and starts again then I need to capture that event.
Is there any such event?

I hope you got the question.

**Comment by SuRGeoNix** [comment]
@saman1832 Yes that's clear now. Can you give me a trace log from Flyleaf when this happens? Or a way to reproduce it? How does Flyleaf currently responds?
