### ISSUE TITLE
How to pass options in flyleaf player.(for passphrase).

### ISSUE THREAD

**Issue by saman1832** [SuRGeoNix/Flyleaf#362]
@SuRGeoNix  I was going through the [https://www.ffmpeg.org/ffmpeg-protocols.html#srt](url). I want to add option of passphrase=string in flyleaf.
![image](https://github.com/SuRGeoNix/Flyleaf/assets/49141964/98fdae53-30cf-461b-ba2f-5c2f1a260148)

How I can do it?
Passphrase is used to play the encrypted stream and in ffmpeg we need to pass the option for passphrase.
ffmpeg -i input.mp4 -c:v libx264 -c:a aac -f mpegts srt://destination_address:1234?mode=live&latency=100&passphrase=your_passphrase

**Comment by SuRGeoNix** [comment]
@saman1832 test from master if you can. I've seen that mode=live will fail so double check this. Additionally, another way to add options will be through Config.Demuxer.SubtitlesFormatOpt

**Comment by saman1832** [comment]
@SuRGeoNix thanks for the quick response.
I tried with config.Demuxer.FormatOpt["passphrase"] = "string" with older flyleaf(without the new changes) able to play the srt url with passphrase.
So, if you want you can revert the changes.

**Comment by SuRGeoNix** [comment]
@saman1832, the issue with that is that you use the main demuxer for subtitles which means that you cannot have audio/video at the same time. That's the point of the new changes. It would help to ensure that it works with the master.

**Comment by saman1832** [comment]
@SuRGeoNix  got your point. let me check with master also by passing as option. Will let you know so that you can release nuget

**Comment by saman1832** [comment]
> @saman1832, the issue with that is that you use the main demuxer for subtitles which means that you cannot have audio/video at the same time. That's the point of the new changes. It would help to ensure that it works with the master. Additionally, the new changes will support also the inline options.

@SuRGeoNix  I tried to run with master but I fail. I dont know if I have done correct or not. But one more point I have used
config.Demuxer.FormatOpt["passphrase"] = "string" not Config.Demuxer.SubtitlesFormatOpt and able to play both audio and video.

**Comment by SuRGeoNix** [comment]
@saman1832 this is not helping. Did you first try to open video/audio and then again with Player.Open just the url with the options as is? Use Config.Demuxer.SubtitlesFormatOpt only if you don't pass them inline. Also, make sure you use the master properly. Check trace log as well.
