### ISSUE TITLE
Pixel issue when stream buffers(might be due to low internet connectivity).

### ISSUE THREAD

**Issue by saman1832** [SuRGeoNix/Flyleaf#363]
If any live stream buffers then with plyleaf having config:  config.Player.MaxLatency = TimeSpan.FromMilliseconds(5000).Ticks;
the pixel is getting blurred or the timestamp coming on stream going back then coming live time.(means in buffred stream showing previous frame then comes to live frame)
And if playing same stream in vlc player at the time of buffer stream is stop and when good stream comes it plays so pixalation issue doesnt occur.

Please find below images for reference.
After pixalation
![MicrosoftTeams-image (1)](https://github.com/SuRGeoNix/Flyleaf/assets/49141964/0a6745c3-bb23-418c-be3d-3332a24b710c)

Before pixalation issue
![MicrosoftTeams-image](https://github.com/SuRGeoNix/Flyleaf/assets/49141964/cfb549dc-9e5e-436e-9940-044bee959765)

Is there any way to fix this.

Meanwhile I will be creating one demo app with flyleaf and with vlc for better understanding and will share but if possible please share your suggestion meanwhile.

**Comment by SuRGeoNix** [comment]
I think I've seen this issue with udp instead of tcp streams and I would also try to turn off video acceleration to see if that fixes it.

**Comment by saman1832** [comment]
turning off the video acceleration  will not increase the CPU consumption if playing multiple players?
And it would be great if you can suggest me something to try for fixing this.

**Comment by SuRGeoNix** [comment]
it depends, if the quality is not high might be worth trying without VA. I did suggest you also to switch from udp to tcp.

**Comment by saman1832** [comment]
I thing by default flyleaf is using tcp for rtsp_transport and I tried using  config.Video.VideoAcceleration = false; but facing same issue.

**Comment by SuRGeoNix** [comment]
You will need to check FFmpeg options for low bandwidth connections but that clearly a network issue and nothing to do with Flyleaf

**Comment by saman1832** [comment]
@SuRGeoNix can we pause/play the player inside buffering started/cpmpleted event?

**Comment by SuRGeoNix** [comment]
> @SuRGeoNix can we pause/play the player inside buffering started/cpmpleted event?

Yes, but with a new Task.Run(() => Player.Pause()) not in the same thread that comes from those events.
