### ISSUE TITLE
Set position missing when i call SeekAccurate function 

### ISSUE THREAD

**Issue by ngocthanhtrinh** [SuRGeoNix/Flyleaf#364]
Hi Flyleaf team,
I used flyleaf video player to play the video (link below). When I call the SeekAccurate function to move forward and backward each frame or set a position (miliseconds), Flyleaf does not play the correct frame or position specified.
I used flyleaf play video (link below). When i call SeekAccurate function for forward and backward frame by frame or set position but Flyleaf set position missing 

https://drive.google.com/file/d/1DCOznW3LHJ9smBtDuLVixysllTnjtD-1/view?usp=sharing

**Comment by SuRGeoNix** [comment]
Hi @ngocthanhtrinh, just tried the video that you say and worked fine with the player. Did you enable Seek Accurate? (https://github.com/SuRGeoNix/Flyleaf/wiki/Player-(Key-&-Mouse-Bindings)#video) with Ctrl+S? To perform Frame Stepping use Shift+ <-/-> arrows

**Comment by ngocthanhtrinh** [comment]
> Hi @ngocthanhtrinh, just tried the video that you say and worked fine with the player. Did you enable Seek Accurate? (https://github.com/SuRGeoNix/Flyleaf/wiki/Player-(Key-&-Mouse-Bindings)#video) with Ctrl+S? To perform Frame Stepping use Shift+ <-/-> arrows
> 
> You can also use Video -> Profile Mismatch to use hardware acceleration as it seems the video has an issue and announcing a wrong profile

Thank SuRGeoNix,
I tested with pre/next frame worked but SeekForwards and Backwards not correct position

**Comment by SuRGeoNix** [comment]
@ngocthanhtrinh I'm not sure what is not working, does other video work for you? Please explain so I can fix the issue if actually exists

**Comment by ngocthanhtrinh** [comment]
@SuRGeoNix  Other video worked. When I use vlc to seek forwards and backwords to a position of 5 seconds or 10 seconds it is always correct but when using flyleaf sometimes the position can add 1 second or subtract 1 second

**Comment by SuRGeoNix** [comment]
@ngocthanhtrinh How can I reproduce it? How is this related to SeekAccurate? You just use the sample player and the arrows/mouse?

**Comment by ngocthanhtrinh** [comment]
@SuRGeoNix i call SeekAccurate function. Player.SeekAccurate(Player.CurTime + 5000) or Player.SeekAccurate(Player.CurTime - 5000)

**Comment by SuRGeoNix** [comment]
@ngocthanhtrinh Does this happen with the sample player? I'm afraid that probably you are doing something wrong with your implementation, check the log, what time do you send to seek and what you actually get?

**Comment by ngocthanhtrinh** [comment]
> @ngocthanhtrinh Does this happen with the sample player? I'm afraid that probably you are doing something wrong with your implementation, check the log, what time do you send to seek and what you actually get?

@SuRGeoNix pls check 2 videos
Flyleaf : https://drive.google.com/file/d/1s0BcoSf-045rtMdMwFGVlggl-okcK3md/view?usp=sharing
VLC: https://drive.google.com/file/d/1HFw6TY5Y4aFy8_x_E68s4bQvV52qgmqN/view?usp=sharing

I will see VLC forwards and backwards allway exactly, Flyleaf not correct

**Comment by SuRGeoNix** [comment]
@ngocthanhtrinh That was a bug with FFmpeg which was properly handle in other cases but not in this case so I've fixed it. TBH, I don't like the current fix -performance wise- (seeking 3 seconds before to ensure it will seek backwards) so I will review this in the future.
