### ISSUE TITLE
Excuse me, can multiple players be displayed simultaneously in one interface of WPF? Just like in WinForm

### ISSUE THREAD

**Issue by void-soul** [SuRGeoNix/Flyleaf#365]
Excuse me, can multiple players be displayed simultaneously in one interface of WPF? Just like in WinForm

**Comment by SuRGeoNix** [comment]
Yes, you can find a sample in the solution https://github.com/SuRGeoNix/Flyleaf/tree/master/Tests/FlyleafMultiPlayer%20(WPF)

**Comment by void-soul** [comment]
Thank you very much. In `FlyeafMultiPlayer (WPF),` I tried to overwrite another control on the player, but it was always obscured by the player, seemingly due to the creation timing,Do you have any suggestions for this situation? 😂

```
            <Grid Grid.Row="0" Grid.Column="0">
                <TextBlock
                    Padding="4"
                    HorizontalAlignment="Left"
                    VerticalAlignment="Top"
                    Panel.ZIndex="999999"
                    FontSize="14"
                    FontWeight="Bold">
                    <TextBlock.Background>
                        <SolidColorBrush Opacity="0.5" Color="#FFFFFF" />
                    </TextBlock.Background>
                    Player1
                </TextBlock>

                <flwpf:FlyleafME
                    x:Name="FlyleafME1"
                    Grid.Row="0"
                    Grid.Column="0"
                    Player="{Binding PlayerView1, Mode=TwoWay}" />
            </Grid>
```

At design time:
![Q1](https://github.com/SuRGeoNix/Flyleaf/assets/12187705/a9587fee-2fa4-4bda-b967-c602bc78a71c)

Actual runtime:
![q2](https://github.com/SuRGeoNix/Flyleaf/assets/12187705/2a719ced-a075-424e-aacd-7c664ac2125d)

**Comment by void-soul** [comment]
Thank you very much. In `FlyeafMultiPlayer (WPF),` I tried to overwrite another control on the player, but it was always obscured by the player, seemingly due to the creation timing,Do you have any suggestions for this situation? 😂
@SuRGeoNix 

```
            <Grid Grid.Row="0" Grid.Column="0">
                <TextBlock
                    Padding="4"
                    HorizontalAlignment="Left"
                    VerticalAlignment="Top"
                    Panel.ZIndex="999999"
                    FontSize="14"
                    FontWeight="Bold">
                    <TextBlock.Background>
                        <SolidColorBrush Opacity="0.5" Color="#FFFFFF" />
                    </TextBlock.Background>
                    Player1
                </TextBlock>

                <flwpf:FlyleafME
                    x:Name="FlyleafME1"
                    Grid.Row="0"
                    Grid.Column="0"
                    Player="{Binding PlayerView1, Mode=TwoWay}" />
            </Grid>
```

At design time:
![Q1](https://github.com/SuRGeoNix/Flyleaf/assets/12187705/a9587fee-2fa4-4bda-b967-c602bc78a71c)

Actual runtime:
![q2](https://github.com/SuRGeoNix/Flyleaf/assets/12187705/2a719ced-a075-424e-aacd-7c664ac2125d)

**Comment by SuRGeoNix** [comment]
@void-soul You cannot use Zindex this way with FlyleafHost/FlyleafMe as it will use two new Windows, one for the player and one for the overlay. If you want to have something above the player you will need to put it on the overlay. Check also the tests/samples you will find more examples even with common overlay for more than one players.
