### ISSUE TITLE
Continous RAM(memory) is keeps increasing when playing multiple player

### ISSUE THREAD

**Issue by saman1832** [SuRGeoNix/Flyleaf#367]
I am trying to run 10 player on single page(multiview) but the memory is keeps on increasing ad at end app crashes due to memory full.

**Comment by SuRGeoNix** [comment]
Reduce Config.Demuxer.BufferDuration
There is not any known memory leak, so if you want to open a lot of players at the same time consider configure them with low packets/frames.

**Comment by saman1832** [comment]
I am already using below config
 config.Player.MaxLatency = 0;
 config.Demuxer.BufferDuration = TimeSpan.FromSeconds(1).Ticks;

**Comment by saman1832** [comment]
currently I am using 
config.Player.MinBufferDuration = 0;
            config.Demuxer.BufferDuration = 0;
            config.Decoder.ShowCorrupted = false;
            config.Video.VideoAcceleration = true;
            config.Decoder.MaxVideoFrames = 2;
            config.Demuxer.FormatFlags |= 0x0040;
            
is this fine configuration for multiple player (20) for less RAM consumption

**Comment by SuRGeoNix** [comment]
Just remembered an issue with FFmpeg that leaks connections, however I'm not sure if that's related with your issue. In any case that does not seem to be a Flyleaf issue.

**Comment by saman1832** [comment]
ok got it. Can you just confirm that  below config is fine for no buffer?
config.Player.MinBufferDuration = 0;
config.Demuxer.BufferDuration = 0;
config.Decoder.ShowCorrupted = false;
config.Video.VideoAcceleration = true;
config.Decoder.MaxVideoFrames = 2;
config.Demuxer.FormatFlags |= 0x0040;

**Comment by SuRGeoNix** [comment]
Looks good
