### ISSUE TITLE
App getting crash when running for couple of hours.

### ISSUE THREAD

**Issue by saman1832** [SuRGeoNix/Flyleaf#368]
Window Event Viewer Logs:

Description
Faulting Application Path:	C:\Program Files (x86)\VVDN\ImpactDesktop\ImpactDesktopApp.exe
 
Problem signature
Problem Event Name:	APPCRASH
Application Name:	ImpactDesktopApp.exe
Application Version:	1.0.1.0
Application Timestamp:	641cef7e
Fault Module Name:	xaudio2_9.dll
Fault Module Version:	10.0.22000.1761
Fault Module Timestamp:	5a41a6e8
Exception Code:	c0000005
Exception Offset:	0000000000068bc0
OS Version:	10.0.22000.2.0.0.768.100
Locale ID:	16393
Additional Information 1:	b5a1
Additional Information 2:	b5a1768a409a8812157bef485ee9f9bf
Additional Information 3:	adad
Additional Information 4:	adadfe40d43dfddd2a2983cf7a537d91
 
Extra information about the problem
Bucket ID:	88c437afac9d5ac1038a621b5b7d71de (1408045703145288158)

Flyleaf Error:
[1:20 AM] Surana, Chandrakant
FFmpeg | Error   | [NULL @ 0000028410290780] PPS id out of range: 0FFmpeg | Error   | [NULL @ 0000028410290780] PPS id out of range: 0
[1:20 AM] Surana, Chandrakant
OpenPlaylistItem] None =>  [Error: [avformat_open_input] I/O error (-5)]
[1:20 AM] Surana, Chandrakant
[DecoderContext] [Open] srt://43.205.199.244:1054  [Error: [avformat_open_input] I/O error (-5)]

**Comment by SuRGeoNix** [comment]
This should be fixed with https://github.com/SuRGeoNix/Flyleaf/commit/35dd8690338b902caf65534689e415bc2c129dbf

**Comment by saman1832** [comment]
@SuRGeoNix pls let me know if nuget is available. As I can also verify.
Thanks in advance for support

**Comment by SuRGeoNix** [comment]
@saman1832 v3.7.32 is out so you can check

**Comment by saman1832** [comment]
I am checking. Will update

**Comment by saman1832** [comment]
@SuRGeoNix  with this changes srt stream is not coming. Video is not coming

**Comment by SuRGeoNix** [comment]
@saman1832 Please try to provide proper information so I would know where to look for

1) Did the crash that issue mention has been fixed?
2) About the SRT I guess that broke after 3.7.31 that I tried to support them?
3) Video is not coming does not say much to me

Please provide logs, I'm closing this as this is for another issue and seems it has been fixed, if not let me know

**Comment by saman1832** [comment]
Actually this build is not able to play the srt stream so I am not able to verify the crash issue. Again downgrading build from 3.7.32 to 3.7.30 my srt stream is able to play.
Logs in 3.7.32 build forplaying srt.

17.39.10.656 | FFmpeg | Verbose | [AVIOContext @ 000002ad56aaf3c0] Statistics: 188 bytes read, 0 seeks
17.39.10.656 | Debug | [#3]     [Demuxer:  Main] Opening -> Stopped
17.39.10.656 | Info  | [#3]     [Demuxer:  Main] Disposed
17.39.10.656 | Info  | [#3]     [DecoderContext] [OpenPlaylistItem] None =>  [Error: No audio / video stream found]
17.39.10.656 | Info  | [#3]     [DecoderContext] [Open] srt://43.205.199.244:1038  [Error: No audio / video stream found]
17.39.10.682 | Debug | [#1]     [Demuxer:  Main] Ignoring format option reconnect
17.39.10.682 | Debug | [#1]     [Demuxer:  Main] Ignoring format option reconnect_streamed
17.39.10.682 | Debug | [#1]     [Demuxer:  Main] Ignoring format option reconnect_delay_max
17.39.10.682 | Debug | [#1]     [Demuxer:  Main] Ignoring format option user_agent
17.39.10.682 | Debug | [#1]     [Demuxer:  Main] Ignoring format option rtsp_transport
17.39.10.682 | FFmpeg | Verbose | [AVIOContext @ 000002ad56aaf980] Statistics: 188 bytes read, 0 seeks
17.39.10.747 | Debug | [#1]     [Demuxer:  Main] Opening -> Stopped
17.39.10.747 | Info  | [#1]     [Demuxer:  Main] Disposed
17.39.10.747 | Info  | [#1]     [DecoderContext] [OpenPlaylistItem] None =>  [Error: Cancelled]
17.39.10.747 | Info  | [#1]     [DecoderContext] [Open] srt://43.205.199.244:1068  [Error: Cancelled]
17.39.10.747 | Debug | [#1]     [Player        ] Initialized
17.39.10.756 | Debug | [#1]     [Renderer      ] Disposing
17.39.10.776 | Info  | [#1]     [Renderer      ] Disposed
17.39.10.777 | Info  | [#1]     [Player        ] Disposed
17.39.10.777 | Debug | [#2]     [Player        ] Initializing
17.39.10.777 | Debug | [#2]     [Player        ] Initialized
17.39.10.786 | Debug | [#2]     [Renderer      ] Disposing
17.39.10.797 | Info  | [#2]     [Renderer      ] Disposed
17.39.10.797 | Info  | [#2]     [Player        ] Disposed
17.39.10.797 | Debug | [#3]     [Player        ] Initializing
17.39.10.797 | Debug | [#3]     [Player        ] Initialized
17.39.10.815 | Debug | [#3]     [Renderer      ] Disposing
17.39.10.838 | Info  | [#3]     [Renderer      ] Disposed
17.39.10.838 | Info  | [#3]     [Player        ] Disposed

**Comment by saman1832** [comment]
17.58.19.686 | FFmpeg | Debug   | [srt @ 000001c27fcedb80] Opening 'srt://43.205.199.244:1038' for reading
17.58.19.686 | FFmpeg | Debug   | [srt @ 000001c27fcac2c0] No default whitelist set
17.58.19.686 | FFmpeg | Error   | [srt @ 000001c27fcac2c0] Success
17.58.19.687 | Debug | [#1]     [Demuxer:  Main] Opening -> Stopped
17.58.19.687 | Info  | [#1]     [Demuxer:  Main] Disposed
17.58.19.687 | Info  | [#1]     [DecoderContext] [OpenPlaylistItem] None =>  [Error: [avformat_open_input] Unknown error occurred (-1313558101)]
17.58.19.687 | Info  | [#1]     [DecoderContext] [Open] srt://43.205.199.244:1038  [Error: [avformat_open_input] Unknown error occurred (-1313558101)]
17.58.19.691 | Debug | [#1]     [Player        ] Initializing
17.58.19.691 | Debug | [#1]     [Player        ] Initialized
17.58.19.719 | Debug | [#1]     [Renderer      ] Disposing
17.58.19.747 | Info  | [#1]     [Renderer      ] Disposed
17.58.19.748 | Info  | [#1]     [Player        ] Disposed

**Comment by saman1832** [comment]
> @saman1832 Please try to provide proper information so I would know where to look for
> 
> 1. Did the crash that issue mention has been fixed?
> 2. About the SRT I guess that broke after 3.7.31 that I tried to support them?
> 3. Video is not coming does not say much to me
> 
> Please provide logs, I'm closing this as this is for another issue and seems it has been fixed, if not let me know

@SuRGeoNix  as in this build itself causing stream to stuck then how would we say issue is fixed?

**Comment by saman1832** [comment]
> @saman1832 Please try to provide proper information so I would know where to look for
> 
> 1. Did the crash that issue mention has been fixed?
> 2. About the SRT I guess that broke after 3.7.31 that I tried to support them?
> 3. Video is not coming does not say much to me
> 
> Please provide logs, I'm closing this as this is for another issue and seems it has been fixed, if not let me know

How would I verify if this itself not allowing stream to play.

**Comment by SuRGeoNix** [comment]
@saman1832 after v3.7.30 I've changed the way you open the subtitles for srt:// prefix. you open it in a separate demuxer. You will need first to open the audio/video and after it is opened you will open the the srt.

**Comment by saman1832** [comment]
I don't have any subtitles in this srt video.
Yes, I remember you made changes for passing options for srt. So you mean player.openasync(srt url) this will not open srt stream?
If possible can you please revert that changes if that is not needed?

**Comment by SuRGeoNix** [comment]
Open the video, on open completed Open the srt. So simple (both times you use Player.OpenAsync)

**Comment by saman1832** [comment]
But it never comes in open completed event

**Comment by SuRGeoNix** [comment]
Cause you don't give a video url but you give srt

**Comment by saman1832** [comment]
srt is video url itself like rtsp its protocol its not subtitle.
I guess you misunderstood i might be wrong also.
Bit here srt is srt://43.205.199.244:1068 complete url open this in vlc it will play. in 3.7.30 also it will play

**Comment by saman1832** [comment]
here srt doesnt mean subtitle file, it is video url itself just like rtsp.
It would be great if you revert thses changes [https://github.com/SuRGeoNix/Flyleaf/commit/283d6ae460208a752b616d9fec02dfc8ee368454](url) in latest build 3.7.32 it will resolve the problem as there was misunderstanding of srt meaning.
I hope you got now.
Please do the needful

**Comment by SuRGeoNix** [comment]
Well Haivision are so fucking idiots then. The name SRT an AVS stream protocol. That would be so much easier to fix if you had the sample url from the beginning.

**Comment by saman1832** [comment]
Sorry it was my mistake I should elaborated the issue. Will take care from next time.
@SuRGeoNix It would be so great if you would share the nuget by reverting the 3.7.31 changes from 3.7.32 as I am stuck in between of one demo. 
It would be really helpful for me if you do this on priority.

**Comment by SuRGeoNix** [comment]
I will have a new NuGet soon for you to test

**Comment by saman1832** [comment]
Thank you so much

**Comment by saman1832** [comment]
Thank you so much

**Comment by SuRGeoNix** [comment]
v3.7.33 is ready for testing

**Comment by saman1832** [comment]
Thanks for sharing let me test

**Comment by saman1832** [comment]
![image](https://github.com/SuRGeoNix/Flyleaf/assets/49141964/2bec8983-9e8a-4894-8100-3f25d48c67f7)

please remove
else if (url.StartsWith("srt://"))
            {
                int queryStarts = url.IndexOf('?');
                inFmt = av_find_input_format("srt");

                if (queryStarts != -1)
                {
                    url = Url[..Url.IndexOf('?')];
                    string query = Url[(queryStarts + 1)..];
                    var qp = HttpUtility.ParseQueryString(query);

                    fmtOptExtra = new();
                    foreach (string p in qp)
                        fmtOptExtra.Add(p, qp[p]);
                }
            }
from demuxer.cs as you frogot to remove this in latest build.

**Comment by SuRGeoNix** [comment]
Please don't ask me to remove code, if you don't have a reason to remove it. This allow you to pass inline options srt://host:port?opt1=val1&opt2=val2

**Comment by saman1832** [comment]
I am testing will update.
This allow you to pass inline options srt://host:port?opt1=val1&opt2=val2. also I removed inFmt = av_find_input_format("srt"); from last version>> Got it.

**Comment by SuRGeoNix** [comment]
@saman1832 can you confirm now that the crash is not happening any more?

**Comment by saman1832** [comment]
As of now its not happening. But I will keep you updated if occurs.

**Comment by saman1832** [comment]
@SuRGeoNix is there any way that if buffering start then we can disable the video or something so if pixelataion occurs it cannot be shown and if buffering completes then we can enable the player. Something like that?

**Comment by SuRGeoNix** [comment]
@saman1832 if you provide me again a sample Url I might be able to debug it and see what's the issue with this. Check the [ffmpg options](https://www.ffmpeg.org/ffmpeg-protocols.html#srt)
