### ISSUE TITLE
Additional useful/required events

### ISSUE THREAD

**Issue by pubpy2015** [SuRGeoNix/Flyleaf#37]
Hi,

can you add some events of player as: OnTimeChanged (for trackbar), OnFinished (for play next file), OnError (for write error log to file), OnStateChanged (Playing, Pause, Error,...) , OnDisconnected, OnNewFrame,...

**Comment by SuRGeoNix** [comment]
Currently it has only one event OpenCompleted which fires also on failure. For Status/CurTime etc... you just register to Session/Player 's onPropertyChanged event. I would add more events if necessary just give more details what would be actually useful and can't be already done with the existing events. It's not the best performance wise practice to invoke nonsense events. Eg. OnNewFrame why would that be useful?

**Comment by pubpy2015** [comment]
Hi,

For OnNewFrame and OnDisconnected:

When the IP camera is disconnected, the system will notify the administrator by email,...
or: when you recording video stream, disconnected event will help me finish current recording file and create new file when camera reconnect (OnNewFrame)

using OnNewFrame i can calculate frame rate of live video stream,..

**Comment by SuRGeoNix** [comment]
OK I see your point with fps calculation as I don't have statistics for now (actual frames / dropped frames). However, for recording it should be included in the library (which I'm planning to do on the next updates based on remux/download that I've already done). How are you currently doing the recording?

**Comment by pubpy2015** [comment]
I am using ffmpeg.exe to recording rtsp stream

**Comment by SuRGeoNix** [comment]
Bad bad bad :) I think you could already use the downloader. Even if you want to watch at the same time you could open two different sessions i guess without any issues until I will add the recording on the currently playing stream. The downloader it will save the stream when it is stopped/failed or ended. I need to add also Status to property changed event of the downloader though. It is still under development :(

I will keep in mind all these and I will try to include them in the next update. Let me know anything else that it would be useful ;)

**Comment by pubpy2015** [comment]
Thank you very much.
I will try it.

**Comment by pubpy2015** [comment]
this is way i am implement OnNewFrame event for calculate fps, bps

![image](https://user-images.githubusercontent.com/59004953/122805220-06eccc00-d2f3-11eb-92e2-131fa14cabf4.png)

[FlyleafLib_NewFrame.zip](https://github.com/SuRGeoNix/Flyleaf/files/6688527/FlyleafLib_NewFrame.zip)

**Comment by SuRGeoNix** [comment]
Looking also in to that. I see you have the NewFrame event in the decoder's new frame which is not valid/accurate. It should be during rendering.

For the bitrate, I guess we talk for network bitrate, you have only the video stream I should add all the enabled streams on this one.

For the disconnect. I think you should just listen to propertyChanged for Status and when it's not playing/ended means disconnected. You could even validate this by implementing a ping to the camera or something. Generally, ping/sms should be on another device (router) to watch devices and send sms/emails in that case.

**Comment by pubpy2015** [comment]
No, i think in decoder is accurate because this is property of video source.
In some application as Network Camera Recording software, when connect and display multiple cameras, may be you need decrease render frame rate for reduce GPU usage or when application only recording, you can temporary disable rendering.

For disconnect, i can implement by check last time decoder new frame, if there is no new frame in 60 seconds, i will reconnect to video source and raise disconnect event (if previous state is connected or decoding status = Decoding)

**Comment by SuRGeoNix** [comment]
I think v3.3 now has enough events. I've disabled by default the Stats you can enable them from Config.Player.Stats = true
