### ISSUE TITLE
Setting user control cannot be centered in FlyeafHost of wpf

### ISSUE THREAD

**Issue by HellowZero** [SuRGeoNix/Flyleaf#370]
![Snipaste_2023-11-12_15-40-29](https://github.com/SuRGeoNix/Flyleaf/assets/24368121/6fdf54b4-3ba0-4321-9ff7-64a5c43a8dd4)
Hi！
In FlyeafHost, the width on the left is always much larger than the width on the right. I have set center and left, but it seems that it has not taken effect

**Comment by SuRGeoNix** [comment]
@HellowZero can you provide sample code to review your issue?

**Comment by HellowZero** [comment]
![Uploading Snipaste_2023-11-12_16-08-07.png…]()

**Comment by HellowZero** [comment]
![Snipaste_2023-11-12_16-08-07](https://github.com/SuRGeoNix/Flyleaf/assets/24368121/71cf4ab3-c2fe-4938-8f5c-65a0e6ffe4bc)

**Comment by HellowZero** [comment]
![Snipaste_2023-11-12_16-10-45](https://github.com/SuRGeoNix/Flyleaf/assets/24368121/8963ffb9-690f-438a-8f25-af8d6d514e23)

**Comment by SuRGeoNix** [comment]
I cannot copy the xaml from an image, please provide the actual code so I can reproduce it

**Comment by HellowZero** [comment]
<Grid  x:Name="rootGrid">
      <fl:FlyleafHost Padding="0"  x:Name="host" Player="{Binding Player}"  KeyBindings="Surface">
          <Grid  HorizontalAlignment="Center" Width="500"   DataContext="{Binding HostDataContext}" >
              <Grid.RowDefinitions>
                  <RowDefinition Height="*"></RowDefinition>
                  <RowDefinition Height="auto"></RowDefinition>
                  <RowDefinition Height="auto"></RowDefinition>
                  <RowDefinition Height="auto"></RowDefinition>
              </Grid.RowDefinitions>
              <Border CornerRadius="5" Grid.Row="1" Grid.RowSpan="3" Background="Black" Opacity="0.2"></Border>
            
 
              <Grid Grid.Row="2"   VerticalAlignment="Bottom">
                  <Grid.ColumnDefinitions>
                      <ColumnDefinition Width="Auto"></ColumnDefinition>
                      <ColumnDefinition Width="*"></ColumnDefinition>
                      <ColumnDefinition Width="Auto"></ColumnDefinition>
                  </Grid.ColumnDefinitions>
                  <TextBlock Grid.Column="0" Foreground="White" HorizontalAlignment="Left"   VerticalAlignment="Center" Text="{Binding Player.CurTime, Converter={StaticResource TicksToTime}}" d:Text="00:00:00"/>
                  <Slider Grid.Column="1" 
                           
                          IsSelectionRangeEnabled="True" 
                          SelectionStart="{Binding RelativeSource={RelativeSource Self}, Path=Value, Mode=OneWay}"
                          VerticalAlignment="Center" 
                          Value="{Binding Player.CurTime, Mode=TwoWay, Converter={StaticResource TicksToSeconds}}"
                          Maximum="{Binding Player.Duration, Converter={StaticResource TicksToSeconds}}">
                      <Slider.SelectionEnd>
                          <MultiBinding Converter="{StaticResource SumConverter}">
                              <Binding Path="SelectionStart" RelativeSource="{RelativeSource Self}" Mode="OneWay"/>
                              <Binding Path="Player.BufferedDuration" Converter="{StaticResource TicksToSeconds}" Mode="OneWay"/>
                          </MultiBinding>
                      </Slider.SelectionEnd>
                  </Slider>
                  <TextBlock Grid.Column="2" HorizontalAlignment="Center" VerticalAlignment="Center" Foreground="White" Text="{Binding Player.Duration, Converter={StaticResource TicksToTime}}" d:Text="00:00:00"/>

              </Grid>
              <TextBlock  VerticalAlignment="Center" Grid.Row="3" FontStyle="Italic" Foreground="White" Margin="5,0,0,5" Text="{Binding Player.Playlist.Selected.Title}"/>
          </Grid>
      </fl:FlyleafHost>
  </Grid>

**Comment by HellowZero** [comment]
<Grid  x:Name="rootGrid">
        <fl:FlyleafHost Padding="0"  x:Name="host" Player="{Binding Player}"  KeyBindings="Surface">
            <Grid  HorizontalAlignment="Center" Width="500"   DataContext="{Binding HostDataContext}" >
                <Grid.RowDefinitions>
                    <RowDefinition Height="*"></RowDefinition>
                    <RowDefinition Height="auto"></RowDefinition>
                    <RowDefinition Height="auto"></RowDefinition>
                    <RowDefinition Height="auto"></RowDefinition>
                </Grid.RowDefinitions>
                <Border CornerRadius="5" Grid.Row="1" Grid.RowSpan="3" Background="Black" Opacity="0.2"></Border>
              
 
                <Grid Grid.Row="2"   VerticalAlignment="Bottom">
                    <Grid.ColumnDefinitions>
                        <ColumnDefinition Width="Auto"></ColumnDefinition>
                        <ColumnDefinition Width="*"></ColumnDefinition>
                        <ColumnDefinition Width="Auto"></ColumnDefinition>
                    </Grid.ColumnDefinitions>
                    <TextBlock Grid.Column="0" Foreground="White" HorizontalAlignment="Left"   VerticalAlignment="Center" Text="{Binding Player.CurTime, Converter={StaticResource TicksToTime}}" d:Text="00:00:00"/>
                    <Slider Grid.Column="1" 
                             
                            IsSelectionRangeEnabled="True" 
                            SelectionStart="{Binding RelativeSource={RelativeSource Self}, Path=Value, Mode=OneWay}"
                            VerticalAlignment="Center" 
                            Value="{Binding Player.CurTime, Mode=TwoWay, Converter={StaticResource TicksToSeconds}}"
                            Maximum="{Binding Player.Duration, Converter={StaticResource TicksToSeconds}}">
                        <Slider.SelectionEnd>
                            <MultiBinding Converter="{StaticResource SumConverter}">
                                <Binding Path="SelectionStart" RelativeSource="{RelativeSource Self}" Mode="OneWay"/>
                                <Binding Path="Player.BufferedDuration" Converter="{StaticResource TicksToSeconds}" Mode="OneWay"/>
                            </MultiBinding>
                        </Slider.SelectionEnd>
                    </Slider>
                    <TextBlock Grid.Column="2" HorizontalAlignment="Center" VerticalAlignment="Center" Foreground="White" Text="{Binding Player.Duration, Converter={StaticResource TicksToTime}}" d:Text="00:00:00"/>

                </Grid>
                
                <TextBlock  VerticalAlignment="Center" Grid.Row="3" FontStyle="Italic" Foreground="White" Margin="5,0,0,5" Text="{Binding Player.Playlist.Selected.Title}"/>
            </Grid>
        </fl:FlyleafHost>
    </Grid>

**Comment by HellowZero** [comment]
You can change the background color of this boder for a better view
<Border CornerRadius="5" Grid.Row="1" Grid.RowSpan="3" Background="Black" Opacity="0.2"></Border>

**Comment by SuRGeoNix** [comment]
Your code works fine for me, I don't see any issue with the center alignment. I've used this code with the Sample "FlyleafPlayer (Custom - MVVM) (WPF)"

```xaml
<Grid  x:Name="rootGrid">
    <Grid.Resources>
        <fl:TicksToTimeConverter x:Key="TicksToTime"/>
        <fl:TicksToSecondsConverter x:Key="TicksToSeconds" />
    </Grid.Resources>
    <fl:FlyleafHost Padding="0"  x:Name="host" Player="{Binding Player}"  KeyBindings="Surface">
        <Grid  HorizontalAlignment="Center" Width="500"   DataContext="{Binding HostDataContext}" >
            <Grid.RowDefinitions>
                <RowDefinition Height="*"></RowDefinition>
                <RowDefinition Height="auto"></RowDefinition>
                <RowDefinition Height="auto"></RowDefinition>
                <RowDefinition Height="auto"></RowDefinition>
            </Grid.RowDefinitions>
            <Border CornerRadius="5" Grid.Row="1" Grid.RowSpan="3" Background="AliceBlue" Opacity="0.2"></Border>


            <Grid Grid.Row="2"   VerticalAlignment="Bottom">
                <Grid.ColumnDefinitions>
                    <ColumnDefinition Width="Auto"></ColumnDefinition>
                    <ColumnDefinition Width="*"></ColumnDefinition>
                    <ColumnDefinition Width="Auto"></ColumnDefinition>
                </Grid.ColumnDefinitions>
                <TextBlock Grid.Column="0" Foreground="White" HorizontalAlignment="Left"   VerticalAlignment="Center" Text="{Binding Player.CurTime, Converter={StaticResource TicksToTime}}" d:Text="00:00:00"/>
                <Slider Grid.Column="1" 
                     
                    IsSelectionRangeEnabled="True" 
                    SelectionStart="{Binding RelativeSource={RelativeSource Self}, Path=Value, Mode=OneWay}"
                    VerticalAlignment="Center" 
                    Value="{Binding Player.CurTime, Mode=TwoWay, Converter={StaticResource TicksToSeconds}}"
                    Maximum="{Binding Player.Duration, Converter={StaticResource TicksToSeconds}}">
                </Slider>
                <TextBlock Grid.Column="2" HorizontalAlignment="Center" VerticalAlignment="Center" Foreground="White" Text="{Binding Player.Duration, Converter={StaticResource TicksToTime}}" d:Text="00:00:00"/>

            </Grid>
            <!--标题-->
            <TextBlock  VerticalAlignment="Center" Grid.Row="3" FontStyle="Italic" Foreground="White" Margin="5,0,0,5" Text="{Binding Player.Playlist.Selected.Title}"/>
        </Grid>
    </fl:FlyleafHost>
</Grid>
```

**Comment by SuRGeoNix** [comment]
Any chances that this happens to you when you have enable DPI (Display Scaling anything except 100%) ?

**Comment by HellowZero** [comment]
应该是使用了MetroWindow 的原因，使用原生的wpf窗口没有发生

**Comment by HellowZero** [comment]
It should be due to the use of MetroWindow, but using a native wpf window did not occur

**Comment by SuRGeoNix** [comment]
If you provide me a proper sample with metrowindow I might be able to help you further.

**Comment by HellowZero** [comment]
> If you provide me a proper sample with metrowindow I might be able to help you further. OK I've reproduce it with MetroWindow... let me see...

OK,You can also use this https://github.com/HellowZero/PlayerDemo
Thank you

**Comment by SuRGeoNix** [comment]
For some reason it pushes the overlay 7 pixels from the left, but still trying to figure out why

**Comment by SuRGeoNix** [comment]
@HellowZero I've fixed that on master if you can tested from there otherwise at the next nuget update.

**Comment by HellowZero** [comment]
> @HellowZero I've fixed that on master if you can tested from there otherwise at the next nuget update.
very good，Thank you

**Comment by SuRGeoNix** [comment]
@HellowZero just released the NuGet tested also with your demo and seems ok. Let me know if you still have issues
