### ISSUE TITLE
Audio and video is not coming smooth for haivision stream

### ISSUE THREAD

**Issue by saman1832** [SuRGeoNix/Flyleaf#371]
Playback is not smooth(audio and video both) url: srt://hsg.demo.haivision.com:5175 But in VLC its playing smoothly

**Comment by SuRGeoNix** [comment]
Just tried and it works fine for me with latest version, same as ffplay/vlc

**Comment by saman1832** [comment]
Yes, actually I was using config with 0 buffer after increasing the buffer it's working fine

**Comment by SuRGeoNix** [comment]
Be careful with this configuration. Latency/Player Buffer/Demuxer Buffer are related to each other. Eg check config https://github.com/SuRGeoNix/Flyleaf/blob/master/FlyleafLib/Engine/Config.cs#L199

When you change the MaxLatency it will calibrate the other configs if required.
