### ISSUE TITLE
Displaying paused stream frame

### ISSUE THREAD

**Issue by rkinnunen** [SuRGeoNix/Flyleaf#372]
In the program I'm developing, you can stream a remote player via rtsp stream and control it with API queries. The player is used to view recordings of live camera streams. My problem currently is that whenever I control the player to change to a different time, seek frames backwards/forwards etc, Flyleaf won't display the image without me sending the player the play command. I know that the stream sends the data because this used to work when we we're using FFMediaElement, and therefore I'm inclined to believe this isn't an issue with FFmpeg.

Maybe this has something to do with Flyleaf registering that no frames are being continually streamed and therefore stops the demuxer and player? Maybe I missed a config value I could adjust to keep displaying the latest received frame without timing out and therefore clearing and stopping FlyleafPlayer?

**Comment by SuRGeoNix** [comment]
Please provide logs so I can review them. Seek without playing should display the frame, except if the seek does not success which is what it probably happen. But I don't see why that would happen with Play.

**Comment by rkinnunen** [comment]
To avoid confusion, I want to make clear that I am NOT using the commands for Flyleaf, I'm sending commands to a reserved recording player that is streamed over rtsp and Flyleaf is only displaying said stream.

I added the things I did to the start of the logfile.
[log.txt](https://github.com/SuRGeoNix/Flyleaf/files/13417337/log.txt)

My problem is that when I move to a different timestamp, jump forward/backward 5 seconds, or move forward/backward one frame, Flyleaf will keep displaying the frame the remote played was paused on. It will only update the frame when the remote player is playing.

What I would need it to do is display the frame even though the remote player is paused and then seeked etc. I assume the frame data is being sent, since this worked with the previous ffmpeg based media library, FFMediaElement.

**Comment by SuRGeoNix** [comment]
@rkinnunen You play a live stream (with 0 duration / unseekable) and you seek at the server side right? I think your issue is that Flyleaf tries to buffer while you seek that's why you don't see the frame until it has enough buffer to play. I think what you need to do is to set the Config.Player.MinBufferDuration = 0 so you will not have to wait before displaying a single frame.

**Comment by rkinnunen** [comment]
That did it. Thank you very much!

**Comment by SuRGeoNix** [comment]
@rkinnunen Be careful though, when you change the MaxLatency will affect the MinBufferDuration so make sure you always have it after MaxLatency
