### ISSUE TITLE
Pixilation Issue (with slow network connections)

### ISSUE THREAD

**Issue by pankajsaini1987** [SuRGeoNix/Flyleaf#373]
Hi, how we can achieve rtsp output similar to vlc player, there is some non smoothness and dullness in flyleaf as compare to vlc player, can we make it similar to vlc?

**Comment by SuRGeoNix** [comment]
I cannot fix an issue, or help, if you don't give me enough information

**Comment by saman1832** [comment]
@SuRGeoNix this is same pixelataion issue that occurs in ffmpeg and flyleaf as well when if internet connectivity is not stable but for same scenario in vlc pixelataion does not happens.

@pankajsaini1987 if you have any RRSP dummy url you can share thatt would help as I am also facing similar issue.

**Comment by SuRGeoNix** [comment]
Does vlc use AVformat demuxer (FFmpeg)? If not that's an ffmpeg issue and not flyleaf's issue. Did you try mpv, ffplay?
Please guys, when you open issue explain the issue in detail and provide a reproduceable way / sample url/file.

**Comment by SuRGeoNix** [comment]
Guys just remember and old issue which was an issue with FFmpeg
https://github.com/SuRGeoNix/Flyleaf/issues/72

**Comment by saman1832** [comment]
This is not the same issue you mentioned. In that vidoe is paying late but here pixelation occurs. I will be sharing the sample url for you to  reproduce it. Will share in couple of days.

**Comment by SuRGeoNix** [comment]
I guess what happens is a missing/corrupted packet will make the decoder to not properly decode the current frames (between keyframes). So, flyleaf will need to identify this and drain/flush the decoder before decoding the next keyframe bunch.

**Comment by t3therdev** [comment]
Hi @SuRGeoNix was there any further work on this issue? we are going to be checking with a lot of bad connection streams as well and will see what ffmpeg options we have, but i think it will also have to be at the player level, when it comes along with bad frames. We are thinking something like the ffmpeg's -err_detect ignore_err and will check some other opitons of -err_detect as well.

**Comment by SuRGeoNix** [comment]
I don't think that I could handle this on the decoder. I think is just an FFmpeg option. I might be able to help if you can provide me a reproduceable stream.

**Comment by SuRGeoNix** [comment]
Closing this until a reproduceable way will be provided or detailed explanation/logs
