### ISSUE TITLE
play offline stream

### ISSUE THREAD

**Issue by SundayGoGo** [SuRGeoNix/Flyleaf#376]
I am playing a rtsp video stream now. If the camera is not online, does flyleaf have a good callback function to get it?

**Comment by SuRGeoNix** [comment]
You will need to handle this, either with Player's status or demuxer's time out. Check your logs when the camera disconnects and find the best way to handle it. I guess what you should do, is to start a monitoring thread to ping the camera until back again and start the player.

**Comment by saman1832** [comment]
@SundayGoGo have you find a way to handle this? As I am also stuck in same usecase.

**Comment by saman1832** [comment]
Okk, I have also tried. Couple of ways using videodemuxer timeout but no success.
Please update here if you find any success

**Comment by SuRGeoNix** [comment]
Guys, I'm not sure what do you want from the library's side to implement. You want to monitor the camera and when it comes back you re-open it.

**Comment by saman1832** [comment]
@SuRGeoNix  if stream stops or stream is not playing in player then we should have some event/callback so that we can be notified and on that basis we can custom things.

**Comment by SuRGeoNix** [comment]
@saman1832 That's the PlaybackStopped event that you say (check the error or mark your own flag to separate it from your manual Player.Stop() calls)

**Comment by SuRGeoNix** [comment]
PlaybackStopped will be called always however I think your issue it was that it would try more than once (after the 1st timeout) and it would have a long delay before calling it.  https://github.com/SuRGeoNix/Flyleaf/commit/b5e95fca5ff5fd174561ea1c87870808717be3fb should fix this

**Comment by MinChanSike** [comment]
Same issue.
Play offline stream or invalid stream, eg: `rtsp://127.0.0.1:8554/live/invaid_stream_name`

```csharp
var result = Player.Open(_streamUrl); //Block here (no timeout), expected to get result.Success
```

```csharp
Player.OpenAsync(_streamUrl); //Does not get exception or event
```

**Comment by saman1832** [comment]
> PlaybackStopped will be called always however I think your issue it was that it would try more than once (after the 1st timeout) and it would have a long delay before calling it. [b5e95fc](https://github.com/SuRGeoNix/Flyleaf/commit/b5e95fca5ff5fd174561ea1c87870808717be3fb) should fix this

@SuRGeoNix have you released the nuget?

**Comment by SuRGeoNix** [comment]
@saman1832 Not yet, but I really suggest you to start using the master and proper debugging if you want to resolve issues faster

**Comment by saman1832** [comment]
Sure will do after that will update

**Comment by SuRGeoNix** [comment]
I mean use the project reference (of master) instead of NuGet so you can debug latest code and better (will help also with beta testing)

**Comment by SuRGeoNix** [comment]
@saman1832 NuGet is also out so you can test it also from there

**Comment by saman1832** [comment]
@SuRGeoNix  it is also working in similar way.
Can you please describe exactly what impact this changes will make?

**Comment by SuRGeoNix** [comment]
@saman1832 It ensures that it comes out from "Screamer" (so it calls PlaybackStopped) immediately after the first timeout. However, your issues it was that you were disposing FlyleafHost if I remember right. You have another issue I'm afraid.

**Comment by saman1832** [comment]
Anyhow I manage to fix that part as per mine requirement using player status for auto play. And it is working fine.
Really thanks for your quick responses and effort.
@SuRGeoNix
Will the new changes will impact anything as I am planning to take new build for my project as currently version "3.7.33" is working fine as I had done alot testing on this version.
