### ISSUE TITLE
Audio output device enumeration doesn't handle duplicate friendly names

### ISSUE THREAD

**Issue by signumnova** [SuRGeoNix/Flyleaf#379]
We have got cases where we have multiple audio outputs that all have the same friendly name, but still have unique ID's.

The current way this is modelled in the Engine.Audio class doesn't really allow for this possibility, because the only publicly accessible object is Engine.Audio.Devices which is a collection of (friendly name) strings.

(And as soon as you ask for ID by name this is where things don't work)

The way audio capture device enumeration is done is slightly different, and we feel the audio output enumeration should be handled in a similar way. If you have to introduce a new method call to preserve backward compatibility so be it?

Happy for us to submit a patch.

Cheers S

**Comment by SuRGeoNix** [comment]
@signumnova have a look at the commit and let me know if that's what you wanted

**Comment by signumnova** [comment]
Thanks J - Will give this new version a go
