### ISSUE TITLE
Crash if start/stop continous

### ISSUE THREAD

**Issue by pubpy2015** [SuRGeoNix/Flyleaf#38]
Hi,

I am test on WinForms Sample (Basic) by Add a button for player.Open(rtsp url) and a button on for player.Stop():
![image](https://user-images.githubusercontent.com/59004953/118403800-5871bd80-b69a-11eb-8c7e-b4240c118ac9.png)
![image](https://user-images.githubusercontent.com/59004953/118403810-658eac80-b69a-11eb-802e-1f5c03a6a752.png)

**Comment by pubpy2015** [comment]
![image](https://user-images.githubusercontent.com/59004953/118403847-9d95ef80-b69a-11eb-8454-5dfceaca1302.png)

**Comment by pubpy2015** [comment]
![image](https://user-images.githubusercontent.com/59004953/118403911-e5b51200-b69a-11eb-8aff-38354fa37202.png)

**Comment by SuRGeoNix** [comment]
player.Stop() requires re-opening. You use Stop as Pause?

**Comment by pubpy2015** [comment]
I am using  player.Open(rtsp ur) on Play button and player.Stop() on Stop button:
![image](https://user-images.githubusercontent.com/59004953/118404636-eef3ae00-b69d-11eb-9aad-f406ae289bf6.png)

**Comment by SuRGeoNix** [comment]
@pubpy2015  You and your rtsp mess :) You try to Stop before it actually opened. that's the issue...

**Comment by SuRGeoNix** [comment]
I guess that was it, let me know if otherwise. I've not finish with locks cause I was planning to update Player.cs and Plugins but nice catch.

**Comment by SuRGeoNix** [comment]
One more thing. It's your responsibility to Stop the Player before Open. So generally, consider doing player.Stop(); also on your button1

**Comment by pubpy2015** [comment]
I am trying on new code version. Better but it will make app hang in short time.
Sometime still error here:
![image](https://user-images.githubusercontent.com/59004953/118405719-34ff4080-b6a3-11eb-8b5a-2ea4c4314583.png)

Can you set player/demuxer status to Stopping and break open thread ?

**Comment by SuRGeoNix** [comment]
Did you try to Stop before Open at button1?

**Comment by pubpy2015** [comment]
No, if place Stop before Open, app will no crash but hang in more time.
If rtsp source is not available, you must wait more time before you can click Stop button.
Incase of app have multiple players, it is not convenient.
I am seeing you have DemuxInterrupt property and Stopping status. can you using this to break Open thread ?
![image](https://user-images.githubusercontent.com/59004953/118406725-48aca600-b6a7-11eb-9e74-316db5d95c2f.png)
![image](https://user-images.githubusercontent.com/59004953/118406734-5530fe80-b6a7-11eb-87df-6272a9a93422.png)

**Comment by SuRGeoNix** [comment]
What exactly are you doing? Pressing Open/Stop buttons all the time?

**Comment by pubpy2015** [comment]
I am doing an application like that:
![image](https://user-images.githubusercontent.com/59004953/118406925-69293000-b6a8-11eb-8b13-1b7a9ee43215.png)

each camera have 2 video streams, mainstream with higher resolution and substream with lower resolution.
In multiview mode, Flyleaf control will connect to substream of each camera.
when user double click to open camera1, application will stop substream of all cameras and open camera 1 with mainstream. Double click again will stop mainstream of camera1 and open substream of all cameras. => It will require open /stop continous in short time.

**Comment by SuRGeoNix** [comment]
OK I think I've fixed the whole pyramid there of Start/Stop with also fast abort of opening

**Comment by pubpy2015** [comment]
Yes, better performance but sometime still error here:
![ảnh](https://user-images.githubusercontent.com/59004953/118419522-71a05b80-b6e6-11eb-9161-5f5fbb93338f.png)

**Comment by SuRGeoNix** [comment]
My first problem is that I cannot easily test this. The second problem is that I still believe that it's not the proper way of doing this. However, give it a try but consider finding a better way of implementing this?

**Comment by SuRGeoNix** [comment]
@pubpy2015 Do you still have issues with this one, I will re-code some parts on version 3.2 (unfortunately not time for that currently).

**Comment by pubpy2015** [comment]
Yes, 

if rtsp source is ready, the problem here:
![ảnh](https://user-images.githubusercontent.com/59004953/119449980-840d3b80-bd5d-11eb-99f0-abcbf5d4bd8a.png)

If rtsp source is not available, the problem here:
![ảnh](https://user-images.githubusercontent.com/59004953/119449736-2c6ed000-bd5d-11eb-8a59-dfcbf176e983.png)

(you can try with any fake rtsp url, ex: rtsp://123.14.15.16:8554/live/c1234)

**Comment by pubpy2015** [comment]
other problem is FlyLeaf control not redraw when resize:
![ảnh](https://user-images.githubusercontent.com/59004953/119450671-76a48100-bd5e-11eb-8764-21d219375e86.png)

**Comment by pubpy2015** [comment]
What do you mean 'if rtsp source is ready' ? 
this mean rtsp source 'online' and can play by player.

The resize issue is for the designer only right?
Yes.

**Comment by pubpy2015** [comment]
> 
> 
> other problem is FlyLeaf control not redraw when resize:
> ![ảnh](https://user-images.githubusercontent.com/59004953/119450671-76a48100-bd5e-11eb-8764-21d219375e86.png)

Add bellow code in constructor will fix this problem:
// set double buffer
            this.SetStyle(ControlStyles.UserPaint | ControlStyles.OptimizedDoubleBuffer | ControlStyles.AllPaintingInWmPaint | ControlStyles.SupportsTransparentBackColor, true);

**Comment by pubpy2015** [comment]
Problems solved

Sleep 1 milisecond here:
![image](https://user-images.githubusercontent.com/59004953/122799513-056bd580-d2ec-11eb-89df-741eab2a1245.png)

Add SignalToStop() method in DecoderContext.cs
![image](https://user-images.githubusercontent.com/59004953/122799686-3a782800-d2ec-11eb-9e23-c8dcb40b15d1.png)

call Signal ToStop() before Stop():
![image](https://user-images.githubusercontent.com/59004953/122799817-6693a900-d2ec-11eb-8b32-4e3b6e5bf0b1.png)

Video test:

https://user-images.githubusercontent.com/59004953/122799844-6e534d80-d2ec-11eb-94ec-5c49edea36bb.mp4

**Comment by SuRGeoNix** [comment]
Nice, sorry but didn't have time lately to help you out with this one. I will included it on the next update (I will review general start/stop and memory leaks)

**Comment by SuRGeoNix** [comment]
Give another try with the latest version (3.1.9) and let me know if you still catch any crash!

**Comment by pubpy2015** [comment]
It works well in most cases.
Very rarely does this error:

![image](https://user-images.githubusercontent.com/59004953/126069922-06ced0e4-2c3c-4199-9799-c59eb4cd5b34.png)
![image](https://user-images.githubusercontent.com/59004953/126069926-51d430c1-d1a6-45a5-aea3-7dd42c9b71ce.png)

**Comment by SuRGeoNix** [comment]
Nice should be also fixed
