### ISSUE TITLE
how to save rtsp://192.168.20.3:554 as mp4

### ISSUE THREAD

**Issue by zhishiheng** [SuRGeoNix/Flyleaf#380]
now  I can play rtsp ，How to save while playing？

this  is my code
`  Config = new Config();
 Config.Video.BackgroundColor = Colors.Transparent;
  Player = new Player(Config);
var uri1=  "rtsp://192.168.20.3:554“
  Player.Commands.Open.Execute(uri1);`

**Comment by SuRGeoNix** [comment]
Hi @zhishiheng, use can use Player.StartRecording() however FlyleafLib currently does not support transcoding this means that it will only remux the stream so may not possible to do it in mp4 format. You could try force the extension but that might fail.

**Comment by zhishiheng** [comment]
I  play rtsp，and  i want to save the vidio. Regardless of the format

**Comment by SuRGeoNix** [comment]
@zhishiheng I think you didn't dispose/close the downloader properly. Did you try the sample downloader? (btw the filename will not exist there as its does not have an extension yet. You can get the recommended extension that it will use from (Player/decCtx.(Demuxer/VideoDemuxer).Extension)

**Comment by zhishiheng** [comment]
`  string url = "rtsp://192.168.11.196:1935";
            Player.Commands.Open.Execute(url);


            string filename = AppDomain.CurrentDomain.BaseDirectory + DateTime.Now.ToString("yyyymmdd HHmmss");

            if (!Directory.Exists(filename))
            {
                Directory.CreateDirectory(filename);
            }
            Player.StartRecording(ref filename);`
StartRecording it do not work

**Comment by zhishiheng** [comment]
Can I save the rtsp stream as a frame-by-frame picture?

**Comment by SuRGeoNix** [comment]
@zhishiheng Try sample player and press Ctrl+R can you find the recording and properly play it? If yes you are doing something wrong with your code. You pass folder for filename? check the logs

**Comment by zhishiheng** [comment]
Sorry, I may not have expressed myself accurately. I can save the video using the StartRecording method, but when I find the saved file, it only plays for a few seconds.

**Comment by SuRGeoNix** [comment]
@zhishiheng I will need more details to be able to help you. Provide logs of the Downloader/Player/Recording. It would even be more helpful  if you could provide the source Url or a sample file that it does not work for you so I can debug it myself.

**Comment by zhishiheng** [comment]
[DownloadRtsp.zip](https://github.com/SuRGeoNix/Flyleaf/files/13751658/DownloadRtsp.zip)

**Comment by zhishiheng** [comment]
this  is  my code  . I delete the FFmpeg dll

**Comment by SuRGeoNix** [comment]
@zhishiheng For me it works fine with an rtsp test stream that I created. Try to create a log to see what is going on, use this in Engine.Start:-

```
LogOutput = "log.txt",
```

also you can try to force the output to ts instead of mp4, eg:-

```
string filename = "out.ts";
Player.StartRecording(ref filename, false);
```

**Comment by zhishiheng** [comment]
[log.txt](https://github.com/SuRGeoNix/Flyleaf/files/13757640/log.txt)
`string filename = "out.ts";
Player.StartRecording(ref filename, false);`
it donot work,,,
this is  my log

**Comment by zhishiheng** [comment]
I called the TakeSnapshotToFile method and saved more than 300 images, but then an error occurred.
![Uploading error.png…]()

**Comment by zhishiheng** [comment]
![Uploading error.png…]()

**Comment by zhishiheng** [comment]
![error](https://github.com/SuRGeoNix/Flyleaf/assets/20162391/df2b80ae-06e3-4a52-8202-b8fc1ef378b3)

**Comment by SuRGeoNix** [comment]
I think the issues comes from the source stream with the DTS discontinuities. That's why I suggest to use .ts (mpegts) format which if I remember right allows them. However, might muxer requires also additional options to be able to handle this properly. All those will be review and included in v4 which will support transcoding generally as well in cases like that.

The last error (NullReference) is just because you probably disposed the Player and the Dispatcher_Tick continue to fire, just check if null to quit
