### ISSUE TITLE
download Issues

### ISSUE THREAD

**Issue by zhishiheng** [SuRGeoNix/Flyleaf#381]
The video I downloaded was only normal for the first few seconds。
Cannot play all

`Downloader downloader = new Downloader(new Config());
            string error = downloader.Open(@"rtsp://192.168.11.196:1935"); // 1. Opens default audio/video streams
           // string error = downloader.Open(@"rtsp://192.168.11.196:1935", true, false, false); // 2. Opens only the first playlist item with no audio/video streams (blocks)
            if (error != null)
                System.Diagnostics.Debug.WriteLine($"Open failed ({error})");

            downloader.DecCtx.OpenVideoStream(downloader.DecCtx.VideoDemuxer.VideoStreams[0], false); // 2.1. Opens first video stream with no default audio (no required if we initially open with defaults)

            downloader.DownloadCompleted += (o, e) =>
            {
                Console.WriteLine($"Download " + (e ? "completed" : "failed"));
                // System.Diagnostics.Debug.WriteLine($"Download " + (e ? "completed" : "failed"));
            };

            string filename = AppDomain.CurrentDomain.BaseDirectory+DateTime.Now.ToString("yyyymmdd HHmmss");// @"c:\root\t700"; // No extension, it's safer to let the library to choose the right extension

            if (!Directory.Exists(filename))
            {
                Directory.CreateDirectory(filename);
            }
            downloader.Download(ref filename); // Async call (no blocking) should subscribe to DownloadCompleted event for results

            System.Diagnostics.Debug.WriteLine($"Filename (including the extenstion) {filename}");`

**Comment by SuRGeoNix** [comment]
@zhishiheng I think you didn't dispose/close the downloader properly. Did you try the sample downloader? (btw the filename will not exist there as its does not have an extension yet. You can get the recommended extension that it will use from (Player/decCtx.(Demuxer/VideoDemuxer).Extension)

If you both want to Play you could use StartRecording as I told you instead of the Downloader.

**Comment by zhishiheng** [comment]
Thank you for your reply
I know the rtsp stream extension。us the code ,i can download the file. but the file is not normal。it can play 5s and Unable to play later, still screen

**Comment by SuRGeoNix** [comment]
@zhishiheng Does it work with the Sample/Demo app?

**Comment by SuRGeoNix** [comment]
Closing this until a reproduceable way will be provided or detailed explanation/logs

**Comment by zhishiheng** [comment]
StartRecording  work not well 。I use Player.StartRecording()  it create a file 。but  the file only play a few seconds.

**Comment by zhishiheng** [comment]
i want save each frame ， i use  TakeSnapshotToFile method  . and i use timer 1/12s take it . but i report error.
How do I do it？
