### ISSUE TITLE
ffplay/mpv comparable latency settings for rtsp, matching ffplay strings

### ISSUE THREAD

**Issue by t3therdev** [SuRGeoNix/Flyleaf#383]
Hi All,

we are very impressed with the project and are looking to move from mpv to this. we are doing some testing and the samples with changes that look to match our ffplay string are still about 1 second behind in flylead. 

for example: 
`ffplay -rtsp_transport tcp -analyzeduration 0 -probesize 32 -sync ext -fflags +nobuffer+discardcorrupt -flags low_delay -framedrop -strict experimental  -err_detect ignore_err -avioflags direct -vf setpts=0 "rtsp://streamurl"`

we have tried the following in flyleaf:

```
            Config.Demuxer.AllowFindStreamInfo = false;
            Config.Demuxer.FormatOpt["rtsp_transport"] = "tcp";
            Config.Demuxer.FormatOpt["probesize"] = "32";
            Config.Demuxer.FormatOpt["analyzeduration"] = "0";
            Config.Demuxer.FormatOpt["flags"] = "low_delay";
            Config.Demuxer.FormatOpt["flags"] = "discardcorrupt";
            Config.Demuxer.FormatOpt["fflags"] = "nobuffer";
            Config.Demuxer.FormatOpt["sync"] = "ext";
            Config.Demuxer.FormatOpt["avioflags"] = "direct";
            Config.Demuxer.FormatOpt["vf setpts"] = "0";
            Config.Demuxer.FormatOpt["framedrop"] = "1";
            Config.Demuxer.FormatOpt["strict"] = "experimental";
            Config.Demuxer.FormatOpt["max_delay"] = "0";

            Config.Player.MaxLatency = TimeSpan.FromMicroseconds(100).Ticks; // For 100ms latency
```

But still about 1 second behind mpv and ffplay. 

Any suggestions?

**Comment by SuRGeoNix** [comment]
Hi @t3therdev and thanks!

First of all correct the micro to milli seconds with TimeSpan.FromMilliseconds(100).Ticks
Generally, you shouldn't have any issues playing with low latency. Please a provide a trace log (for flyleaf) - make sure you remove any Urls/passwords so I can review it.

**Comment by t3therdev** [comment]
Hi @SuRGeoNix , please see attached log. This was about 1 second behind ffplay with the settings in the original post.

[log.txt](https://github.com/SuRGeoNix/Flyleaf/files/13626087/log.txt)

**Comment by SuRGeoNix** [comment]
@t3therdev I see the following issues:-

1) "flags" is not a valid ffmpeg format option (see [ffmpeg-formats](https://ffmpeg.org/ffmpeg-formats.html)). I would try 
```csharp
Config.Demuxer.FormatOpt["fflags"] = "+nobuffer+discardcorrupt";
```
as an alternative you could use Config.Demuxer.FormatFlags however you will need to find the proper values for that eg:-

```csharp
Config.Demuxer.FormatFlags |= 0x0040; // AVFMT_FLAG_NOBUFFER check others https://ffmpeg.org/doxygen/trunk/avformat_8h.html
```

2) "low_delay" flag is not for the format but for the [codec context options](https://ffmpeg.org/ffmpeg-codecs.html), this is missing from Flyleaf and I will added it (similar to Config.Decoder.ShowCorrupted for output_corrupt)

3) Hardware decoding failed and it seems that the CPU struggles (probably an old system?). I would try Config.Decoder.AllowProfileMismatch)

4) At least for testing I would also disable the audio and I would try with AllowFindStreamInfo = true to ensure it has all the correct stream parameters

**Comment by t3therdev** [comment]
Hi @SuRGeoNix , thanks for the reply. 

I will try that. As for hardware decoding, that is actually a question I had as part of our evaluation on using flyleaf. 

In mpv we set the following parameters after doing gpu detection:

  "hwdec": "qsv",
  "gpu-context": "d3d11",
  "gpu-api": "d3d11"

Is that something we can do in flyleaf? the particular logs we sent were actually from a 12th gen i7-1270p with intel iris xe graphics. Its possible thats newer than what flyleaf is detecting?

How can we know what hwdec is being used and how we can resolve that as well? Our next step is to try and do 16 simultaneous decodes like we do with mpv.

**Comment by SuRGeoNix** [comment]
@t3therdev Unfortunately, only D3D11 is currently supported for hwdec/gpu. I'm planning to support others in v4.

**Comment by t3therdev** [comment]
Just as a reference , this is mpv, ffplay and flyleaf

![image](https://github.com/SuRGeoNix/Flyleaf/assets/38048656/d6f12ce6-111b-4826-9f10-9b08c6c30763)

**Comment by t3therdev** [comment]
Ok, but how do we make sure hwdec is enabled?

**Comment by SuRGeoNix** [comment]
It's the Config.Video.VideoAcceleration option

**Comment by SuRGeoNix** [comment]
Can you try without hwdec with mpv to see if you get the same results?

**Comment by t3therdev** [comment]
Can you give me an example  Config.Video.VideoAcceleration line?

**Comment by SuRGeoNix** [comment]
You can check all the configs [here](https://github.com/SuRGeoNix/Flyleaf/blob/master/FlyleafLib/Engine/Config.cs)

**Comment by t3therdev** [comment]
with these settings i am getting a lot of pauses/stutters, when mpv is not and still behind 1 second. I could give you remote access to some test streams, its pretty easy to compare the ffplay command line.

**Comment by SuRGeoNix** [comment]
Sure, drop me an email with the details

**Comment by SuRGeoNix** [comment]
@t3therdev with the following config I play stable with the same latency of ffplay

```csharp
Config.Decoder.ShowCorrupted = false;
Config.Decoder.LowDelay = true;
Config.Decoder.AllowProfileMismatch = true;
Config.Demuxer.FormatOpt["fflags"] = "+nobuffer+discardcorrupt";
Config.Demuxer.FormatOpt["max_delay"] = "0";
Config.Player.MaxLatency = TimeSpan.FromMilliseconds(100).Ticks;
```

**Comment by SuRGeoNix** [comment]
@t3therdev NuGet also ready if you want to test it from there

**Comment by t3therdev** [comment]
@SuRGeoNix thanks for the quick response. Pulled latest and it is working. We will keep testing and be in touch soon.
