### ISSUE TITLE
opening delay in fragmented mp4

### ISSUE THREAD

**Issue by sharmasulekh87** [SuRGeoNix/Flyleaf#384]
Hi @SuRGeoNix ,
I am trying to play some large size(around 600-700 MB) fragmented mp4 files that are shared on network and it took around 10 sec to open the stream. Can you please suggest something that i can add to reduce this delay. Here are the logs showing opening and opened stream timings:
[log.txt](https://github.com/SuRGeoNix/Flyleaf/files/13627016/log.txt).
Please tell me if anything more is needed check this tihng.

**Comment by SuRGeoNix** [comment]
Hi @sharmasulekh87,

you can use Config.Demuxer.AllowFindStreamInfo = false;

also check Config.Demuxer.FormatOpt["probesize"] and Config.Demuxer.FormatOpt["analyzeduration"]

**Comment by sharmasulekh87** [comment]
I have set probesize and analyze duration...but still probe size shown in logs is 2048. I will try using Config.Demuxer.AllowFindStreamInfo and will revert.
