### ISSUE TITLE
SamplesAdded causes the program to crash

### ISSUE THREAD

**Issue by Lizhengbo0304** [SuRGeoNix/Flyleaf#385]
```c#
 private void AudioOnSamplesAdded(object? sender, AudioFrame e)
    {
        try
        {

            var samples = new short[e.dataLen];
            Marshal.Copy(e.dataPtr, samples, 0, samples.Length);

            var leftSamples = samples.Take(e.dataLen / 2).ToArray();
            var rightSamples = samples.Skip(e.dataLen / 2).ToArray();

            DrawVuMeterLeftValue = VolumeHelper.CalculateRms(leftSamples);

            DrawVuMeterRightValue = VolumeHelper.CalculateRms(rightSamples);
            Console.WriteLine($"{DrawVuMeterLeftValue:00.00} -- {DrawVuMeterRightValue:00.00}");
        }
        catch (Exception exception)
        {
            Console.WriteLine(exception);
        }
    }
``` 
Marshal.Copy(e.dataPtr, samples, 0, samples.Length);This line of code causes the program to crash.
Except：
System.ExecutionEngineException: Exception of type 'System.ExecutionEngineException' was thrown.
IDE Out：
Fatal error. Internal CLR error. (0x80131506) 
at System.Buffer._Memmove(Byte ByRef, Byte ByRef, UIntPtr)
at System.Runtime.InteropServices.Marshal.CopyToManaged[[System.Int16, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](IntPtr, Int16[], Int32, Int32)
at FlyleafLib.MediaPlayer.Audio.AddSamples(FlyleafLib.MediaFramework.MediaFrame.AudioFrame)
at FlyleafLib.MediaPlayer.Player.Screamer()
at FlyleafLib.MediaPlayer.Player.<Play>b__293_0()
at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
Net 7，WPF，Flyleaf V1.2.34,

**Comment by Lizhengbo0304** [comment]
There is no problem when using a single FlyleafHost, but when my program uses multiple FlyleafHosts in the same window, the sampledAdded() method will throw an exception at some point.

**Comment by SuRGeoNix** [comment]
@Lizhengbo0304 Check the log, I think the issue is that the underlying audio circular buffer re-initializes. I could add an event there so you can lock it.

**Comment by Lizhengbo0304** [comment]
[https://github.com/Lizhengbo0304/ArchiveFiles/blob/main/Flyleaf.FirstRun.log](url)
Here is the link to my log file. Unfortunately, I was unable to find any specific error information within it. The log stops at the line that says "Open" There is no additional output when the error occurs.

**Comment by SuRGeoNix** [comment]
@Lizhengbo0304 Tried to reproduce it with your code but I couldn't. There was an open issue in dotnet for this but not sure if that is related (possible try to update runtime/sdk). I will review this to provide a lock when the circular buffer re-initializes as that might be causing this.

**Comment by Lizhengbo0304** [comment]
I mentioned before that this method works fine when only one player is used. However, when two or more players are used to play a file on a network disk, the frequency of exceptions increases rapidly. I have been forced to cancel the call to this method.

**Comment by SuRGeoNix** [comment]
@Lizhengbo0304 I'm not sure how to handle this, not even sure if that's flyleaf's issue. I exposed Player.AudioDecoder.CircularBufferLocker to use it within your code which might fix it.
