### ISSUE TITLE
RTSP Streams - Best Practices

### ISSUE THREAD

**Issue by madrianr** [SuRGeoNix/Flyleaf#388]
Hello,

we have an App with 4 Live Camera RTSP Streams (Local WLAN) and one RTSP Livestream from our Provider (Internet)...

now we use the following settings - but the latency is to height:

`               Config1 = new Config();

                Config1.Video.BackgroundColor = Colors.Black;
                
                Config1.Audio.Enabled = false;
                Config1.Player.MaxLatency = 500 * 10000;
                Config1.Demuxer.FormatOpt["rtsp_transport"] = "tcp";
                Config1.Demuxer.FormatOpt["fflags"] = "nobuffer";
                Config1.Demuxer.BufferDuration = 0;
`

how to optimize this - I have read some postimngs but there are so many possible settings - are there any Best Practices
for such a scenario?

Regards Robert

**Comment by SuRGeoNix** [comment]
Hi @madrianr,

For low latency, I would recommend the following configuration:-

```csharp
//Config.Decoder.LowDelay = true; // This will auto enabled based on MaxLatency (introduced in 3.7.38)
//Config.Demuxer.BufferDuration = x; // This will auto adjust based on MaxLatency

Config.Audio.Enabled = false; // Audio can have large gaps with video and cause higher latency
Config.Decoder.MaxVideoFrames = 2; // Reduce from default 4 for lower RAM/GPU usage and allowing demuxer to work better (if you have audio consider also reducing MaxAudioFrames to 5)
Config.Demuxer.FormatOpt["fflags"] = "+nobuffer+discardcorrupt"; // Note + here required check logs if you get an error settings this
Config.Player.MaxLatency = TimeSpan.FromMilliseconds(500).Ticks;
//Config.Player.LatencySpeedChangeInterval = TimeSpan.FromMilliseconds(400).Ticks; // Adjust this based on the MaxLatency (might worth going lower in your case)
//Config.Demuxer.FormatOpt["omit_video_pes_length" = "0"; // Consider also this option for mpeg-ts formats?
```

**Comment by madrianr** [comment]
Thanks, works very good now!
