### ISSUE TITLE
Can we use openAsync(url) again inside player opencomplete event?

### ISSUE THREAD

**Issue by saman1832** [SuRGeoNix/Flyleaf#389]
Can we use openAsync(url) again inside player opencomplete event if e.Success is false so that stream is open successfully.?
If yes so do we need to use task for opensasync or directly?

**Comment by SuRGeoNix** [comment]
OpenAsync will create a Task anyways so you don't need to create your own Task. It is safe to call it as is in OpenCompleted event.

**Comment by saman1832** [comment]
Thnks for the quick response.
