### ISSUE TITLE
Avoid screen flicker when taking snapshots 

### ISSUE THREAD

**Issue by pubpy2015** [SuRGeoNix/Flyleaf#39]
Hi,

when snapshot current image from video stream, flyleaf control will flicker. Please see this video:

https://user-images.githubusercontent.com/59004953/119437551-92049180-bd48-11eb-9d9b-0c3ce56c4f18.mp4

can you avoid this ?

**Comment by SuRGeoNix** [comment]
I'm afraid not. It uses the current renderer's buffer and it resizes to the the original size before saving it. You could reduce the time I guess, by reducing the renderer's buffers (currently are 6).

**Comment by pubpy2015** [comment]
Can you implement this function by convert VideoFrame to Bitmap ?
with your previous your code version, i am convert like this:
if (decoder.vDecoder.frames.Count > 0)
                {
                    MediaFrame vFrame = null;
                    if (decoder.vDecoder.frames.TryPeek(out vFrame))
                    {
                        if (vFrame != null)
                        {
                            if (vFrame.textureRGB != null)
                            {
                                lastFrame = Utils.ConvertTexture2DToBitmap(vFrame.textureRGB);
                            }
                            else if (vFrame.textureHW != null)
                            {
                                lastFrame = Utils.ConvertHardwareTexture2DToBitmap(vFrame.textureHW);
                            }
                            else
                            {

                            }
                        }
                    }
                }

https://github.com/SuRGeoNix/Flyleaf/issues/7

**Comment by SuRGeoNix** [comment]
1) There is no ConvertTexture2DToBitmap in Utils
2) vFrame has been already disposed (might could use the next frame but that's not accurate to snapshot another frame than the one that you see)
3) To create a function for ConvertTexture2DToBitmap it will not be that simple

**Comment by SuRGeoNix** [comment]
Closing this for now as it requires a lot of effort and might not even worth it. I will review it in the future.
