### ISSUE TITLE
Event to capture mouse double click while full screen

### ISSUE THREAD

**Issue by saman1832** [SuRGeoNix/Flyleaf#391]
I want to capture the fullscreen even when we do mouse double click.
Is there any way to capture that?

I am asking one for question as dont want to open one more issue. Can we replace ffmpeg5 lib with 6 I mean will it work?

**Comment by saman1832** [comment]
@SuRGeoNix  any update on this?

**Comment by SuRGeoNix** [comment]
@saman1832 I will have a look now, btw you can use ffmpeg6 (update FFmpeg.Autogen at your application)

**Comment by saman1832** [comment]
After updating ffmpeg autogen do I also need to update ffmpeg library for v6?

**Comment by SuRGeoNix** [comment]
You will need to use ffmpeg v6 (is that what you ask?). For WPF what about disabling ToggleFullScreenOnDoubleClick and then handle double click manually?

**Comment by saman1832** [comment]
Okk. Double click issue will be resolved after this in WPF.

For ffmpeg v6 .. once we will update the ffmpeg autogen lib then we also have ffmpeg folder path in which we kept some dll of ffmpeg 5 as of now like avfirmat and all that folder also we need to replace with v6 ffmpeg libraries?

**Comment by SuRGeoNix** [comment]
FFmpeg.Autogen version must much with FFmpeg libraries version so you will provide a path only with the FFmpeg v6 libraries

**Comment by saman1832** [comment]
@SuRGeoNix  I tried updating FFmpegAutogen version 6.1 as well ffmpeg dll to 6.1 but I did in nuget of flyleaf host so it thrwing error that missing avcode59.dll.

I replace avcodec59.dll with avocdec-61.dll.
Do i need to do this with master code?

**Comment by SuRGeoNix** [comment]
@saman1832 read the wiki you don't update the nuget's FFmpegAutogen but your add a new Nuget at your app

**Comment by saman1832** [comment]
Okk will read wiki and follow the steps and let you know if face any issue

**Comment by saman1832** [comment]
@SuRGeoNix I read the wikki but not understood much. And while adding new nuget in my app for ffmpeg autogen 6 it is also updating the flyleaf ffmpeg autogen automatically.

It would be great if you can send the detail steps or share the sample.

**Comment by SuRGeoNix** [comment]
@saman1832 In the solution if you add in the main Sample Project (FlyeafPlayer WPF Control) the FFmpeg.AutoGen v6.1 NuGet and you change in App.xaml.cs the FFmpegPath to point in a folder with the v6.1 (x64 shared) (you can take them from [here](https://github.com/BtbN/FFmpeg-Builds/releases/tag/autobuild-2023-12-23-13-00)) it works fine.

**Comment by saman1832** [comment]
@SuRGeoNix thanks for the quick update.
Will try this and let you know

**Comment by saman1832** [comment]
@SuRGeoNix  I tried as per your steps. While running the code it is getting stuck in 
![image](https://github.com/SuRGeoNix/Flyleaf/assets/49141964/d6dbcc1a-d332-456d-a720-a10a9ccd7355)

in line no. 24.
While debugging when I move the debuuger to next line(25) without executing line no.24 then UI opens but i am getting 
![image](https://github.com/SuRGeoNix/Flyleaf/assets/49141964/aad12410-3e59-461e-b486-892b1e8224d8)


stream url "srt://hsg.demo.haivision.com:5175"

ffmpegv6 used:  
![image](https://github.com/SuRGeoNix/Flyleaf/assets/49141964/73faa2ac-7525-4127-b6d1-f82377b89b8e)

**Comment by saman1832** [comment]
Logs:
21.30.34.298 | Info  | [FlyleafEngine] Audio Devices
{0.0.0.00000000}.{1b7e90c7-52f7-4217-9c4e-7c769a9fffc4} | Speakers (Realtek(R) Audio) *

21.30.34.340 | Info  | [FlyleafEngine] FlyleafLib 3.7.38
21.30.34.359 | Info  | [FlyleafEngine] Loading FFmpeg libraries from 'C:\Users\aman\Downloads\ffmpeg-n6.1-7-ga888d21c8c-win64-lgpl-shared-6.1\ffmpeg-n6.1-7-ga888d21c8c-win64-lgpl-shared-6.1\bin'
21.30.34.658 | Info  | [FlyleafEngine] FFmpeg Loaded (Location: C:\Users\aman\Downloads\ffmpeg-n6.1-7-ga888d21c8c-win64-lgpl-shared-6.1\ffmpeg-n6.1-7-ga888d21c8c-win64-lgpl-shared-6.1\bin, Ver: 60.16.100) [Devices: no, Filters: yes]
21.30.34.717 | Info  | [FlyleafEngine] GPU Adapters
[#1] Intel Intel(R) Iris(R) Xe Graphics      [ID: 39497 , LUID: 71494 , DVM: 128 MB  , DSM: 0 B     , SSM: 7.87 GB]
[#2] Unknown Microsoft Basic Render Driver   [ID: 140   , LUID: 72599 , DVM: 0 B     , DSM: 0 B     , SSM: 7.87 GB]

21.30.34.837 | Info  | [FlyleafEngine] Plugin loaded (OpenDefault - 3.7.38.0)
21.30.34.837 | Info  | [FlyleafEngine] Plugin loaded (OpenSubtitles - 3.7.38.0)
21.30.34.837 | Info  | [FlyleafEngine] Plugin loaded (StreamSuggester - 3.7.38.0)
21.30.34.837 | Info  | [FlyleafEngine] [PluginHandler] No external plugins found
21.30.34.846 | Info  | [FlyleafEngine] Thread started
21.31.41.300 | Debug | [#1]     [Player        ] Creating Player (Usage = AVS)
21.31.41.314 | Info  | [#1]     [Player        ] Initialiazing audio (Default - 0 @ 48000Hz)
21.31.42.055 | Debug | [#1]     [Renderer      ] Initializing
21.31.42.174 | Debug | [#1]     [Renderer      ] GPU Adapter
Intel Intel(R) Iris(R) Xe Graphics      [ID: 39497 , LUID: 71494 , DVM: 128 MB  , DSM: 0 B     , SSM: 7.87 GB]
[Output #1] \\.\DISPLAY1         [Id: 0   	, Top: 0   , Left: 0   , Width: 1366, Height: 768 , Ratio: [683:384]

21.31.42.281 | Debug | [#1]     [Renderer      ] D3D11 Video Processor
=====================================================
MaxInputStreams           16
MaxStreamStates           16
HDR10 Limited             yes
HLG                       no

[Video Processor Device Caps]
LinearSpace               no
XvYCC                     no
RgbRangeConversion        yes
YCbCrMatrixConversion     yes
NominalRange              yes

[Video Processor Feature Caps]
AlphaFill                 yes
Constriction              yes
LumaKey                   yes
AlphaPalette              yes
Legacy                    no
Stereo                    yes
Rotation                  yes
AlphaStream               yes
PixelAspectRatio          no
Mirror                    yes
ShaderUsage               no
MetadataHdr10             yes

[Video Processor Stereo Caps]
MonoOffset                no
RowInterleaved            no
ColumnInterleaved         no
Checkerboard              no
FlipMode                  no

[Video Processor Input Format Caps]
RgbInterlaced             no
RgbProcamp                no
RgbLumaKey                no
PaletteInterlaced         no

[Video Processor Filter Caps]
Brightness                [ -1000 - 1000] | x 0.1 | *0
Contrast                  [     0 - 1000] | x0.01 | *100
Hue                       [ -1800 - 1800] | x 0.1 | *0
Saturation                [     0 - 1000] | x0.01 | *100
NoiseReduction            [     0 -   64] | x   1 | *0
EdgeEnhancement           [     0 -   64] | x   1 | *44
AnamorphicScaling         [     0 -    1] | x   1 | *0
StereoAdjustment          no

[Video Processor Input Format Caps]
Denoise                   yes
Deringing                 no
EdgeEnhancement           no
ColorCorrection           no
FleshToneMapping          yes
ImageStabilization        no
SuperResolution           no
AnamorphicScaling         no

[Video Processor Rate Conversion Caps #0]

	[Video Processor Rate Conversion Caps]
	PastFrames                          1
	FutureFrames                        1
	ProcessorCaps                       31
	ITelecineCaps                       511
	CustomRateCount                     0

	[Video Processor Processor Caps]
	DeinterlaceBlend                    yes
	DeinterlaceBob                      yes
	DeinterlaceAdaptive                 yes
	DeinterlaceMotionCompensation       yes
	InverseErseTelecine                 yes
	FrameRateConversion                 no

21.31.42.340 | Info  | [#1]     [Renderer      ] D3D11 Video Processor Initialized (Rate Caps #0)
21.31.42.348 | Info  | [#1]     [Renderer      ] Initialized with Feature Level 12.1
21.31.42.353 | Debug | [#1]     [Player        ] Created
21.31.43.969 | Debug | [#1]     [FlyleafHost #1] Assign Player #1
21.31.43.991 | Info  | [#1]     [Renderer      ] Initializing 8-bit swap chain with 2 buffers [Handle: 4264302]
21.31.51.755 | Info  | [#1]     [Player        ] Opening srt://hsg.demo.haivision.com:5175
21.31.52.648 | Debug | [#1]     [Player        ] Initializing
21.31.53.914 | Debug | [#1]     [Decoder: Video] Stopped -> Stopped
21.31.53.914 | Info  | [#1]     [Decoder: Video] Disposed
21.31.53.918 | Debug | [#1]     [Player        ] Initialized
21.31.53.948 | Info  | [#1]     [PluginHandler ] [OpenDefault] Open Success
21.31.53.952 | Info  | [#1]     [PluginHandler ] SuggestItem #0 - 
21.31.53.960 | Info  | [#1]     [PluginHandler ] [OpenDefault] Open Item (0) Success
21.31.53.975 | Debug | [#1]     [Demuxer:  Main] Stopped -> Opening
21.31.53.996 | FFmpeg | Debug   | [AVFormatContext @ 00000296e73bed40] Opening 'srt://hsg.demo.haivision.com:5175' for reading
21.31.53.998 | FFmpeg | Debug   | [srt @ 00000296f3e7cdc0] No default whitelist set
21.31.54.011 | Debug | [#1]     [Demuxer:  Main] Opening -> Stopped
21.31.54.011 | Info  | [#1]     [Demuxer:  Main] Disposed
21.31.54.014 | Info  | [#1]     [DecoderContext] [OpenPlaylistItem] None =>  [Error: Unknown: External component has thrown an exception.]
21.31.54.015 | Info  | [#1]     [DecoderContext] [Open] srt://hsg.demo.haivision.com:5175  [Error: Unknown: External component has thrown an exception.]
21.31.54.018 | Info  | [#1]     [Player        ] Opening srt://43.205.199.244:1026
21.31.54.018 | Debug | [#1]     [Player        ] Initializing
21.31.54.018 | Debug | [#1]     [Player        ] Initialized
21.31.54.019 | Info  | [#1]     [PluginHandler ] [OpenDefault] Open Success
21.31.54.019 | Info  | [#1]     [PluginHandler ] SuggestItem #0 - 
21.31.54.019 | Info  | [#1]     [PluginHandler ] [OpenDefault] Open Item (0) Success
21.31.54.019 | Debug | [#1]     [Demuxer:  Main] Stopped -> Opening
21.31.54.019 | FFmpeg | Debug   | [AVFormatContext @ 00000296e73bf2c0] Opening 'srt://43.205.199.244:1026' for reading
21.31.54.019 | FFmpeg | Debug   | [srt @ 00000296f338fac0] No default whitelist set

**Comment by saman1832** [comment]
@SuRGeoNix any update on this?

**Comment by SuRGeoNix** [comment]
@saman1832 That's an FFmpeg.AutoGen or FFmpeg issue, i tested with the FlyleafLibv4 (still under development) and it was working fine. But it uses custom FFmpeg Bindings now.

**Comment by saman1832** [comment]
Ok . Thanks for the update

**Comment by SuRGeoNix** [comment]
FFmpeg libraries, as the libraries that the FFmpeg.AutoGen has included they are working fine. You can download those I guess.

**Comment by saman1832** [comment]
@SuRGeoNix  those libraries are also not working. 
Can you also please try?

**Comment by SuRGeoNix** [comment]
I did try the FFmpeg.AutoGen and it worked from the repo

**Comment by saman1832** [comment]
I have copied the ffmpeg libraries from FFmpeg.AutoGen and updated the flyleaf wpf sample ffmpeg autogen to 6.1.
In this way it should work?

**Comment by SuRGeoNix** [comment]
yes, just use FFmpeg.AutoGen-master\FFmpeg\bin\x64 libs with 6.1 Nuget Package

**Comment by saman1832** [comment]
@SuRGeoNix  Tried same but app is getting crashed after couple of mins.
And with flyleaf master wpf control app is even not opening.

**Comment by SuRGeoNix** [comment]
@saman1832 you confuse me, the error was opening during open with srt formats only,  I used latest FFmpeg.AutoGen NuGet with the FFmpeg.AutoGen's FFmpeg libraries in Flyleaf master WPF Control and it is working fine. So I guess you are doing something wrong.

**Comment by saman1832** [comment]
@SuRGeoNix yes after using latest Ffmpeg lib and autogen srt format is opening now but it is getting crashed after 2-3 mins.
But these app crashing is not happening with this url "srt://hsg.demo.haivision.com:5175".
Actually for mine camera having srt stream this is happening(app crashing) but it is working fine with ffmpeg5 and autogen5.

I am preparing the public srt url so that you can use and debug it. will share with you

**Comment by SuRGeoNix** [comment]
@saman1832 even if it crashes that's not FlyleafLib's issue so I can't do much

**Comment by saman1832** [comment]
Okk. So let me share the logs from that only something you might get that is it from ffmpeg side or not.
