### ISSUE TITLE
Use TimeSpan instead of int/long for time properties and arguments

### ISSUE THREAD

**Issue by f1nalspace** [SuRGeoNix/Flyleaf#392]
Currently if you want to seek to a specific time, you have to pass the time as milliseconds (format int).
This is really inconvenient, because we always have to convert our time to milliseconds and vise versa - including down cast to int, loosing its precision!

Please change all public method arguments and properties to simply use the TimeSpan type instead.
This will also has the advantage that no time precision will be lost by passing around the value and only internally needs this to be converted to a value that FFMPEG can handle.

Thanks!

**Comment by SuRGeoNix** [comment]
@f1nalspace this will be included in v4, all timestamps will be in FFmpeg default (Microseconds). By the way for seek I don't see the need of precision under a millisecond. Now about TimeSpan, I think is too much overhead for the library, you should handle this in higher level.
