### ISSUE TITLE
StartRecording  and TakeSnapshotToFile  Issues

### ISSUE THREAD

**Issue by zhishiheng** [SuRGeoNix/Flyleaf#393]
StartRecording work not well 。I use Player.StartRecording() it create a file 。but the file only play a few seconds.

**Comment by zhishiheng** [comment]
i want save each frame ， i use TakeSnapshotToFile method . and i use timer 1/12s take it . but i report error.
How do I do it？

**Comment by SuRGeoNix** [comment]
Duplicate #380
