### ISSUE TITLE
Pass custom http headers.

### ISSUE THREAD

**Issue by insomniachi** [SuRGeoNix/Flyleaf#395]
I need to open a video from url, but for that i need to send some custom http headers. how would i do that.

**Comment by SuRGeoNix** [comment]
Hi @insomniachi,

Use Config.Demuxer.FormatOpt dictionary which is there to pass FFmpeg Format/Protocol Options (see [http](https://ffmpeg.org/ffmpeg-protocols.html#http)).

You can use user_agent, referer or headers (those are in format -> header: value and use \r\n for multiple headers)
