### ISSUE TITLE
Manual Update Duration

### ISSUE THREAD

**Issue by Lizhengbo0304** [SuRGeoNix/Flyleaf#397]
I use the following code to play a TS file that is being written.
` _playerStream = new FileStream(playFilePath,FileMode.Open,FileAccess.Read,FileShare.ReadWrite);
 Player.Open(_playerStream).Success;
`
Then, there is a thread that uses the following code to update the Stream in real time. However, the Duration of the Player does not change because of the change of the Stream. How can I manually update the duration of the player?
`
  _playerStream.Seek(0,SeekOrigin.End);
  _playerStream.Flush();
`

**Comment by SuRGeoNix** [comment]
@Lizhengbo0304 This is not currently supported but I could consider adding it. Just to make sure that I understand correctly. You want to manually specify the duration so you will be able to seek, right?

**Comment by Lizhengbo0304** [comment]
@SuRGeoNix Yes, you are right.A continuously written video file can continue to play after the duration, but the seek function will not work. It is advisable to have a method to update the duration so that the seek function can seek to the latest position.
