### ISSUE TITLE
Smooth playback of multiple videos

### ISSUE THREAD

**Issue by Lizhengbo0304** [SuRGeoNix/Flyleaf#401]
I am trying to play multiple video files sequentially using FlyleafHost. I initialize a List<Player> Players, set CurrentPlayer = Players[CurrentIndex], and bind the player through Player="{Binding CurrentPlayer}". However, there is a noticeable black screen flash when CurrentPlayer changes. It is very short, but it is noticeable. I am wondering if I can only use two FlyleafHost to switch between videos, or if I can use the same FlyleafHost to achieve the desired effect.

**Comment by SuRGeoNix** [comment]
@Lizhengbo0304 The problem is that you don't create renderer's for the other players so they don't have a "LastFrame" that a Renderer caches. You should be able to achieve this with two renderers (FlyleafHosts) and just swapping the players.
