### ISSUE TITLE
 shaking  when you move the slider

### ISSUE THREAD

**Issue by LauraKami** [SuRGeoNix/Flyleaf#406]
There is a lot of shaking (trembling, tremor) when moving the cursor (cursor position), it seems to me that this was not the case on older versions.
Maybe reloading the cache changes the position and then the cursor repositions the video with a few seconds lag.

And, thanks for the sound processing, it's much more pleasant ;o)

**Comment by SuRGeoNix** [comment]
Hi @LauraKami, I can't see the issue. Does this happen for you in the sample/demo release version? Maybe a .NET issue (try to update to latest runtime?)

**Comment by LauraKami** [comment]
- We can clearly see the problem on small videos of 30 seconds, 1 or 2 minutes.
- I have the problem on my app and on the library demos (wpf player).
- I use dot net 8.0.1 (next time, make the transition more slowly, not all libraries are ready for 8, including Microsoft...)

**Comment by SuRGeoNix** [comment]
@LauraKami Just to make sure I understand the issue (a video capture would help if possible).. it's a visual bug not a seeking functional issue, right? From v1.3 FlyleafME I had an update for MaterialDesignThemes, might that causes the issue? But still can't see it with library's samples. By the way, you can still use older .NET if you feel that .NET 8 is not stable enough.

**Comment by LauraKami** [comment]
- Yes it's a visual bug, seeking work.  But when we move video is shaked, whe we stop all is OK.
- I'v removed slider from video screen part to check if it's come from that, but not.
- I will try to make a video capture ...

**Comment by LauraKami** [comment]
https://github.com/SuRGeoNix/Flyleaf/assets/102795992/42846e1e-7d03-456b-bcdc-7e1f5754a6d2

video

**Comment by SuRGeoNix** [comment]
Still is not clear for me what is the issue. The slider position will change after a completed seek request to the actual keyframe time. That's why might not exactly at the position that you wanted to go. If you need to be exact you can enable the accurate seek (Ctrl+S for sample). There is an issue that sometimes when you seek forward it will not actually seek forward (I think, I'm looking it to it) however I'm not sure if you describing something similar.

**Comment by LauraKami** [comment]
-yes, accurate seek solves the tremor problem
- the default value may have changed between versions
- nevertheless the slider should have priority over the progress of the film, but it is perhaps more a problem of slider than of flyleaf

thanks for the help

**Comment by SuRGeoNix** [comment]
@LauraKami Keyframes can be 10+ seconds which means that if you move your cursor from 1-9 seconds and the duration is small the slider will move to 0 or 10 and the distance will be large.
