### ISSUE TITLE
FlyleafHost causes stuck content in TabControl tab

### ISSUE THREAD

**Issue by rkinnunen** [SuRGeoNix/Flyleaf#409]
Hello,

When using FlyleafHost(s) in a WPF TabControl, then opening a new tab for the first time, the content of the first tab, gets "stuck" on top of the new tab. In my case, it copies the layout that Flyleaf controls are drawn on top of, to the next tab. This only happens when switching to the tab for the first time. 

This might be an issue in WPF itself, https://github.com/dotnet/wpf/ + issues/5728, but something in FlyleafHost triggers it.

https://github.com/SuRGeoNix/Flyleaf/assets/21989206/0ab38312-2d17-447b-9304-174091df4c08

[flyleaf_tab_switch.log](https://github.com/SuRGeoNix/Flyleaf/files/13905636/flyleaf_tab_switch.log)

Curiously, if I call `FlyleafHost.SetOverlay();` in my own code, this problem does not occur. But this brings another problem. When "fullscreening" an element containing a FlyleafHost, the overlay on the first element does not resize properly. Sometimes it stays in fullscreen size, sometimes it resizes to smaller than the FlyleafHost itself. This in turn, does not happen when not using `FlyleafHost.SetOverlay();` in my own code. (Fullscreen mode in this case is not FlyleafHost's built-in. We swap whatever element is being toggled to fullscreen to the first slot, and remove the others, letting WPF resize it automatically. This is for legacy reasons, we have other elements than ones containing FlyleafHosts to display).

https://github.com/SuRGeoNix/Flyleaf/assets/21989206/10b55f43-9a25-4d08-8c13-df460f383d13

Finally, if I use `FlyleafHostOld`, both of these problems do not appear. But `FlyLeafHostOld ` is always on top and is drawn on top of my floating menu windows. They're drawn on a different window that follows the main window, and this works fine with `FlyleafHost` just not with `FlyleafHostOld`.

**Comment by SuRGeoNix** [comment]
Hi @rkinnunen, I think I came across this one. If possible create a very simple repo/demo to reproduce it easily. I will have a look in the weekend.

**Comment by SuRGeoNix** [comment]
@rkinnunen I can't reproduce it so I will need a minimal reproduceable sample

**Comment by SuRGeoNix** [comment]
@rkinnunen any news one this one?

**Comment by rkinnunen** [comment]
Thought to let you know that something in 3.7.42 fixed this issue.

**Comment by SuRGeoNix** [comment]
@rkinnunen nice, thanks for the update
