### ISSUE TITLE
FlyleafHost AspectRatio

### ISSUE THREAD

**Issue by eliacanavera1111** [SuRGeoNix/Flyleaf#411]
Hi, I'm using the flyleafhost as a container for the player, I would like to set the aspect ratio to 'fill'/'keep'/.. from a combobox, should i act on the player or the container? and which command should I use? (Player.Video.AspectRatio seems to be readonly)

**Comment by SuRGeoNix** [comment]
Hi @eliacanavera1111, you can use the Config.Video.AspectRatio and Config.Video.CustomAspectRatio. You can see all the config properties [here](https://github.com/SuRGeoNix/Flyleaf/blob/master/FlyleafLib/Engine/Config.cs)
