### ISSUE TITLE
WinUI Memory Leak & Possible Fix

### ISSUE THREAD

**Issue by airtaxi** [SuRGeoNix/Flyleaf#416]
I'm making  the video camera related application like below:
![image](https://github.com/SuRGeoNix/Flyleaf/assets/6309929/dfc036d2-098f-489a-89fe-3a89b3fc5e12)

Since it uses multiple camera feeds, I noticed that FlyleafLib.Controls.WinUI has a memory leak problem.

The image below is a memory usage screenshot of my program after creating 10 instances of FlyleafHost.
![image](https://github.com/SuRGeoNix/Flyleaf/assets/6309929/062efaf6-2e04-45d1-8346-1fb6d32399f5)

It's over 600+mb, and if I comment out the "Player" allocation code from Flyleaf Host, it doesn't cause the memory leak problem.

After some investigation, I found that if I add the lines of code highlighted below, the memory leak doesn't happen anymore.
![image](https://github.com/SuRGeoNix/Flyleaf/assets/6309929/36692eaa-d825-4ae8-9b85-e1baff2543ed)
![image](https://github.com/SuRGeoNix/Flyleaf/assets/6309929/a61199e7-fab9-4cc9-b6d8-e339e3342b5e)

Below is the screenshot of my application with the same condition after adding the two lines of code above.
![After](https://github.com/SuRGeoNix/Flyleaf/assets/6309929/af006f64-33fe-4065-9145-bf8ff18e0fe0)

**Comment by SuRGeoNix** [comment]
Hi @airtaxi and thanks for the finding. SwapChain release will cause issues but for WinUI it seems to work fine now. The issue comes from the SwapChainPanel that keeps a reference inside it and it should be disposed but currently using a single instance for the template.
