### ISSUE TITLE
Overlays / Stats

### ISSUE THREAD

**Issue by t3therdev** [SuRGeoNix/Flyleaf#418]
Hi @SuRGeoNix 

In continuing to work on migration to flyleaf from mpv, we had some questions about overlays and stats. 

We are looking to see what the options are to overlay stream info (fps, bitrate, frame drops, etc.) like mpv provides with their stats overlay. 

Also, we have some lua scripts we used in the past to do things like vu meters as well. 

How could we go about that in flyleaf?

Or if we can't do an actual transparent overlay, what about a wpf or similar window that can give real-time stream info?

![image](https://github.com/SuRGeoNix/Flyleaf/assets/38048656/a6542d18-da95-483f-8ca6-e189e653f296)

**Comment by t3therdev** [comment]
We will take a look at the showdebug code as well.

**Comment by SuRGeoNix** [comment]
Hi @t3therdev,

FlyleafME uses [this](https://github.com/SuRGeoNix/Flyleaf/blob/master/FlyleafLib/Controls/WPF/PlayerDebug.xaml) but you can create your own custom stats (of course transparent, not sure why you wonder about transparency here, at least for WPF).

You will need to enable the Config.Player.Stats when you show this form and consider also using from Engine's config the UIRefresh.
