### ISSUE TITLE
Brilliant library, but I'm struggling with limited doco...

### ISSUE THREAD

**Issue by davsun55** [SuRGeoNix/Flyleaf#419]
I'm doing a simple video player in C# Winforms .net8. I've been through VLC (too big and limited) and MediaToolkit (not keeping up with .Net) and have just found Flyleaf which seems to be almost perfect.

I have the samples working fine, however the limited documentation has me struggling - is there more than what's available at https://github.com/SuRGeoNix/Flyleaf/wiki/Player-(Properties-&-Methods)? 

Current issues:
- I want to take an immediate thumbnail/snapshot at say the 2sec point on opening a video, but it returns null
- .Stop() seems to be more like a .Clear() - is there a function that stops the video and resets position to 0 without unloading the video? It seems .Pause() and .SeekAccurate(0) might be OK but is that my best option?
- What do the various SeekForward/Backward/Accurate methods do and how to use them?
- How do I use FlyleafLib.MediaFramework.MediaFrame.VideoFrame to specify a frame in Player.TakeSnapshotToBitmap?

Thanks for any assistance/pointers.

David

**Comment by davsun55** [comment]
Hi John,

I appreciate your response.

I’ve taken your sample and tweaked a couple of things (mostly renaming controls) to test it all. I have this in the constructor:
            flConfig = new Config();
            flPlayer = new Player(flConfig);

And this in the form load:
        private void Form1_Load(object sender, EventArgs e)
        {
            flPlayer.OpenAsync(SampleVideo);
            flPlayer.Seek(2000, true);
            pbSnapshot.Image = flVideo.Player.TakeSnapshotToBitmap();
        }

The video starts playing correctly but there’s no snapshot. When I put in a breakpoint after the snapshot, I can see that the image is null.

I’ve tried both ‘Open’ and ‘OpenAsync’, and ‘Seek’ and ‘SeekAccurate’.

I’m using C# Winforms with .Net8 and FlyleafLib v3.7.42 from NuGet within the solution.

I’ve zipped up my solution for info, less the ffmpeg libraries and the sample.mp4 file.

I’m puzzled! Any guidance gratefully received.

BTW do you accept contributions for a couple of coffees?

😊

**Comment by SuRGeoNix** [comment]
@davsun55 You just found some issues here I guess. The problem is the Sync/Async combination. You can't use OpenAsync and then Seek directly as it will not be opened yet. You can either use OpenCompleted event or synced Open. The problem after that is that you Seek is not synced and I don't provide Synched version of it or an event. It will work if you for example put a Thread.Sleep in between just to prove it works. However, I will need to provide a better way for that (it can be done with ShowFrame but just found an issue with it when used directly after open).

Buy me a beer when you come in Greece/Crete :)

**Comment by SuRGeoNix** [comment]
@davsun55 I've added SeekCompleted so now you can better use the following:-

```csharp
Player.Config.Player.AutoPlay = false;

Player.OpenCompleted += (o, e) =>
{
    if (!e.Success)
        return;
    
    Player.Seek(20_000);
};

Player.SeekCompleted += (o, e) =>
{
    if (e == -1)
        return;

    Player.TakeSnapshotToFile(@"c:\sample.jpg");
};

Player.OpenAsync(@"c:\sample.avi");
```

**Comment by davsun55** [comment]
I can wait till your next NuGet release so you don't need to answer this, but how do I incorporate your Player.SeekCompleted changes right now? I've downloaded the current package with your changes, rebuilt it as 'release' and copied the resultant FlyleafLib.dll and FlyleafLib.xml over the top of the v3.7.42 package files. But Player.SeekCompleted is not present...

**Comment by SuRGeoNix** [comment]
The easiest way would be just adding the FlyleafLib project to your solution and reference it instead of using the NuGet package. Alternative you can release (pack) a new version custom and add a local repository folder in your VS. I would have a version for your but I want to review it before release it (I think i will do few changes).

**Comment by davsun55** [comment]
Thanks - I've got it working. Almost. I trust this is my last question:

What I'm trying to do is to grab a frame from say 2 seconds in, as a thumbnail for the video, and of course the video repositions to the frame that gets snapped.

However I'm having trouble resetting the video to the first frame after the snap:

            flPlayer.Config.Player.AutoPlay = false;
            flPlayer.OpenCompleted += (o, e) =>
            {
                if (!e.Success) return;
                flPlayer.SeekAccurate(2000);
            };
            flPlayer.SeekCompleted += (o, e) =>
            {
                if (e == -1) return;
                pbSnapshot.Image = flVideo.Player.TakeSnapshotToBitmap();
            };
            flPlayer.OpenAsync(SampleVideo);

Whenever I stop the video or seek(0) the frame that's snapped is the first one. Presumably because the event handler is still attached.

Can I remove it, or is there a better way to do this? I obviously don't want to capture a snapshot after every seek.

Thanks again,

David

**Comment by SuRGeoNix** [comment]
If understood correctly:-

```csharp
flPlayer.Config.Player.AutoPlay = false;
flPlayer.OpenCompleted += (o, e) =>
{
    if (!e.Success) return;
    flPlayer.SeekCompleted -= FlPlayer_SeekCompleted;
    flPlayer.SeekCompleted += FlPlayer_SeekCompleted;
    flPlayer.SeekAccurate(2000);
};

flPlayer.OpenAsync(SampleVideo);
...
private void FlPlayer_SeekCompleted(object sender, int e)
{
    flPlayer.SeekCompleted -= FlPlayer_SeekCompleted;
}
```

You could also check the e (int e) which is the ms that is 2000 (and not 0)

**Comment by davsun55** [comment]
A couple of tweaks but this is now working perfectly. Thanks for the hints.
```
        private void LoadVideo()
        {
            // Open the stream and immediately get a snapshot and duration.
            flPlayer.SeekCompleted += FLPlayer_SeekCompleted;
            flPlayer.OpenCompleted += (o, e) =>
            {
                if (!e.Success) return;
                flPlayer.SeekAccurate(3000);
            };
            flPlayer.OpenAsync(SampleVideo);
        }
        private void FLPlayer_SeekCompleted(object sender, int e)
        {
            flPlayer.SeekCompleted -= FLPlayer_SeekCompleted;
            if (e == -1) return;
            pbSnapshot.Image = flVideo.Player.TakeSnapshotToBitmap();
            flPlayer.Seek(0);
        }
```
