### ISSUE TITLE
Player.TogglePlayPause() doesn't restart from the pause point

### ISSUE THREAD

**Issue by davsun55** [SuRGeoNix/Flyleaf#422]
PlayPause() is working perfectly for videos, but when playing audio files (at least for .mp3 and .flac), it starts playing after the pause point - by around 1-3 secs.
Should I handle audio files differently? I've checked your sample audio player (Custom Winforms) but it's not clear what might be handled differently.
Thanks,
David

**Comment by SuRGeoNix** [comment]
Can't see the issue, I'm afraid you are doing something wrong. Can you provide your code? Maybe you should try use Player.TogglePlayPause() if you use multiple threads)

**Comment by davsun55** [comment]
Hi John,

I am in fact using TogglePlayPause which was why I was puzzled.

I've attached my code, and put my sample files here (so they don't make the email too big): https://1drv.ms/f/s!AiDriUQWS-D5qb5pyWCBDF4NB0RRPg?e=RgrFkb

Issues:
AVI: Audio only starts playing towards the end of the video
FLAC: The timer fast-forwards to 5-6 secs on play, then skips a couple of seconds if pause/play (this is the issue I originally mentioned)
MOV: Fails to take a snapshot during startup, but manually snapping using the button is OK
MP3: Also skips a couple of seconds if pause/play, but doesn't fast-forward on initial play like FLAC
OGG: (This is a video with no picture): stays at the 'snapshot' time on open, so starts playing from 2sec (seems the SeekAccurate(0) after the snapshot isn't working).
WAV: Same behaviour as FLAC
WMA: Only plays a brief moment

My samples of FLV, MP4, MPEG, WEBM, WMV all work perfectly.

I appreciate you looking at these - I can get by with what I've currently got.

Like I said - brilliant library!

D

**Comment by SuRGeoNix** [comment]
@davsun55 I cannot see your code (where did you attached it?) Can you clarify that those files are playing properly with the sample/demo app from releases?

**Comment by davsun55** [comment]
[FlyleafDemo.zip](https://github.com/SuRGeoNix/Flyleaf/files/14071979/FlyleafDemo.zip)
Apologies - I replied to the last msg via email rather than in this webpage so ZIP didn't work.
The files all play perfectly in Windows. Most play properly in your FlyleafPlayer (Custom) (Winforms) sample but there's no snapshot being taken there.
AVI still has delayed audio; FLAC still fastforwards the 'CurTime' on startup - although the actual audio playback is perfect; OGG has perfect audio (not delayed as in my demo).
If I add a play/pause button to your sample, same deal with skipping audio on restart in eg FLAC. The button only has flyleaf1.Player.TogglePlayPause();
Thanks

**Comment by SuRGeoNix** [comment]
@davsun55 Now I see them, haven't test audio only much to be honest, need review this and I will come back soon..

**Comment by SuRGeoNix** [comment]
@davsun55 Please re-test when you can with the latest fixes and let me know if you still have issues

**Comment by davsun55** [comment]
Thanks - much better, with these issues remaining:
AVI: Audio starts playing ~1 sec after the video
FLAC: Perfect
MOV: Audio has a very minor delay at the start (snapshot works now)
OGG: Still starts at position where snapshot was attempted (restart is perfect)
WMA: Perfect first time after open; However Pause; Seek(0) or SeekAccurate(0) does not reposition to the very start

**Comment by davsun55** [comment]
BTW TogglePlayPause() works perfectly on all the audio streams

**Comment by SuRGeoNix** [comment]
@davsun55 My mistake I thought it was enabled by default, use this:-

```csharp
flConfig.Audio.FiltersEnabled = true;
```

**Comment by davsun55** [comment]
Perfect - thanks.
For any file that doesn't have a timestamp, could 'SeekAccurate(0)' have an override that always sets to the first frame rather than via a timestamp?
BTW when do you think you might do a new release that incorporates these fixes?
Regards

**Comment by davsun55** [comment]
BTW, what does flConfig.Audio.FiltersEnabled = true; do? It fixed my issues!

**Comment by SuRGeoNix** [comment]
People, were asking to support mainly Speed for audio that you can actually understand what they say. So, in v3.7.3 I've started to support FFmpeg audio filters but I had my doubts for both performance but mainly for timestamps. More or less the abuffersrc / abuffersink does not work properly with timestamps but with some workarounds now it became stable enough. 

If you want to try some filters you can check those https://github.com/SuRGeoNix/Flyleaf/blob/master/Samples/FlyleafPlayer%20(WPF%20Control)%20(WPF)/MainWindow.xaml.cs#L102 for speed it will use atempo behind the scenes. For video, it is not clear from FFmpeg when it will download the frame from GPU to RAM and then re-upload it and I didn't want to lose the performance so I add the required/main filters directly in the renderer (eg. HFlip/VFlip lately). 

Generally, you can check my demo with all the settings/configuration and mess around (eg enable/disable audio filters to see the difference eg. for Speed)

**Comment by SuRGeoNix** [comment]
@davsun55 NuGet is ready, I've fixed also the WMA

**Comment by davsun55** [comment]
Wonderful – thanks.

😊
