### ISSUE TITLE
Unable to trap attempt to play an invalid video file

### ISSUE THREAD

**Issue by davsun55** [SuRGeoNix/Flyleaf#424]
I'm opening a video file that is corrupt, but am unable to trap the open exception. I have checked .CanPlay and Video.IsOpened and there is a video stream. But I'm getting the dialogue below.
Is there a way of trapping the open of such an invalid video file? 
![image](https://github.com/SuRGeoNix/Flyleaf/assets/51256983/9eaf4ebc-3071-460d-8323-f001f06108d4)
The file can be downloaded from here: https://1drv.ms/v/s!AiDriUQWS-D5qZ9oOn6m5_FkyvbAIg?e=s7BRm0
Thanks,

**Comment by SuRGeoNix** [comment]
@davsun55 Indeed, I will just need to add a validation (linesize/rowpitch/stride must be greater or equal to the texture's width)

**Comment by davsun55** [comment]
I have no idea what you're referencing, but I can see that you know what you're talking about! :)
