### ISSUE TITLE
May I ask if it is possible to restore the function of resuming playback without reconnecting the old version after interrupting the stream?

### ISSUE THREAD

**Issue by webclient163** [SuRGeoNix/Flyleaf#426]
I remember in previous versions, when playing RTSP videos (H264 encoding), if the stream stops transmitting during playback (the network is not disconnected) for a period of time, when the stream resumes transmission, the player can automatically continue playing without human intervention. But in the current version, even if the streaming is restored, it cannot continue to play and must be reconnected to play. May I ask if it is possible to restore the old version features?

When used to play real-time videos, the features in the old version may be what most users need.

**Comment by SuRGeoNix** [comment]
I will try to guess as you didn't provide me with any information, I think you will need to increase the default Config.Demuxer.ReadLiveTimeout from 20 seconds to something higher (in ticks). This probably changed from this commit https://github.com/SuRGeoNix/Flyleaf/commit/b5e95fca5ff5fd174561ea1c87870808717be3fb (applied in v3.7.34)
