### ISSUE TITLE
To get thumbnail of the video on seek bar

### ISSUE THREAD

**Issue by sharmasulekh87** [SuRGeoNix/Flyleaf#436]
Hi @SuRGeoNix ,
Thanks for the brilliant library. Just want to ask, how can we achieve the thumbnail on seekbar for the currently playing video similar to youtube with flyleaf, but without actual seeking the video?

**Comment by SuRGeoNix** [comment]
Hi @sharmasulekh87 there is similar project under Tests/DoubleVideoViewOverlay (just try a longer video to test this).
It uses two FlyleafHosts (the main for the main Player and one inside the first FlyleafHost for the thumbnail/seek Player which opens the input separately and seeks to present the current seek frame).

I'm not sure what you mean by saying "without actual seeking"... this is not possible.
