### ISSUE TITLE
about key redefine~

### ISSUE THREAD

**Issue by artmscn** [SuRGeoNix/Flyleaf#438]
Hello sir
Thank you very much for this great project.

Here i met a problem which i want to re-define the hotkey in winform application.

for example, i dont want to use space for play/pause toggle.. and i want to use + and - to zoom in and out.

how can i re-define the keys??

i have checked the wiki, but it says TODO.....

Please give some information... thank you very much!

**Comment by SuRGeoNix** [comment]
Hi @artmscn and thanks!

From Config.Player.KeyBindings...
You can use Add to add a "known"/embedded function (such as zoom in) or you can use AddCustom to add your own named Action. 
You can use Remove to remove a "known"/embedded or one of your named custom actions.

Remove Toggle Play/Pause
```csharp
Config.Player.KeyBindings.Remove(KeyBindingAction.TogglePlayPause);
```

Default Zoom In/Out already has those (Ctrl + -/+)
```csharp
Add(Key.OemPlus, KeyBindingAction.ZoomIn, false, true, false);
Add(Key.OemMinus, KeyBindingAction.ZoomOut, false, true, false);
```

Maybe you just want to remove them and add them again without Ctrl? (which by default is for speed -/+)

**Comment by artmscn** [comment]
"Maybe you just want to remove them and add them again without Ctrl? (which by default is for speed -/+)"
correct, that is what i am looking for..

Thank you very much sir.
