### ISSUE TITLE
About ShowFramePrev

### ISSUE THREAD

**Issue by artmscn** [SuRGeoNix/Flyleaf#445]
Dear sir, thank you for this great projet.
I am currently using flyleaf and working with an instant video replay system
on the program, when i click some button, it start 4 flyleafhosts and play 4 videos which cut from from cameras.

when i using showframenext, it works very well. but
when i trying to use ShowFramePrev same time on each player.. it become a super delay.

i have researched all the issues about this.. but did not found any helpful solutions. maybe seekbackward works. but in my case i need a frame by frame backward..
so is that possible to buffer it or using some switch or function to accelate the ShowFramePrev? 
(tried zerocopy and duration.buffertime but seems not working)

Any suggestion will be appreciated. Thank you

**Comment by SuRGeoNix** [comment]
HI @artmscn, this is a combination of two issues:-

1) FFmpeg bugs with HEVC and other formats that will fail to seek backwards properly
2) Flyleaf's packet/frame queue that currently does not support backwards buffering

To resolve this will require a re-design of the core of flyleaf which is already included in v4 but I'm afraid it will not be resolved with v3

**Comment by artmscn** [comment]
ok Thank you very much sir!
