### ISSUE TITLE
Open stream at current position

### ISSUE THREAD

**Issue by spektor56** [SuRGeoNix/Flyleaf#451]
Is there any way to open a stream at a predetermined position?  Whenever I call Player.OpenAsync(stream) it resets the current position of the stream to the beginning.  If i set the position of the stream and flush after i get the first half second of the beginning of the stream first.

**Comment by SuRGeoNix** [comment]
1) Set Config.Player.AutoPlay = false
2) Listen to Player.OpenCompleted event and perform a Player.Seek
3) You should either reset Config.Player.AutoPlay to true or Listen to Player.SeekCompleted and manually call Player.Play

**Comment by spektor56** [comment]
unfortunately it still plays the first part of the stream even with "Config.Player.AutoPlay = false"

**Comment by SuRGeoNix** [comment]
I just retested to ensure AutoPlay=false works. Can you provide a log file?

**Comment by spektor56** [comment]
Autoplay=false works, but when I set the position of the steam and then call play, the first half second of the beginning of the stream plays before it skips to the current stream position. I'm setting the position on the stream itself since it's a combination of raw hevc streams via ssh, so all I know is the length of the stream in bytes, not how long it is etc. Even with autoplay=false I'm assuming it's still buffering the data to play

**Comment by SuRGeoNix** [comment]
I'm not sure yet how you use it, but the proper way and build-in way to seek will flush the packet queue after the seek has been completed and it will decode until the first video frame to present it. Did you check the logs? Does the demuxer brings old packets after seek?
