### ISSUE TITLE
FlyleafSharedOverlay in wpf ViewBox

### ISSUE THREAD

**Issue by Agostino44** [SuRGeoNix/Flyleaf#455]
I have a Usercontrol, inside it is composed of a FlyleafSharedOverlay.

`<UserControl x:Class="Streaming_Manager.MosaicControl"
             xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:fl="clr-namespace:FlyleafLib.Controls.WPF;assembly=FlyleafLib">
    <fl:FlyleafSharedOverlay Name="main_host">
        <fl:FlyleafSharedOverlay.DetachedContent>
            <Canvas x:Name="detached_canvas" Background="Black" AllowDrop="True">
                
            </Canvas>
        </fl:FlyleafSharedOverlay.DetachedContent>
        <Canvas Name="MosaicCanvas" Background="Transparent" Panel.ZIndex="0">
            
        </Canvas>
    </fl:FlyleafSharedOverlay>
</UserControl>`

I tried to put this Usercontrol inside a Viewbox but seems that the usercontrol is not resized by the viewbox.
Is there a way to do this appropriately?

**Comment by maoleigepu** [comment]
Hi，how do you solve this problem?  I'm having the same issue。

**Comment by Agostino44** [comment]
> Hi，how do you solve this problem? I'm having the same issue。

I put the viewbox inside the FlyleafSharedOverlay with the Canvas MosaicCanvas inside it.

`<fl:FlyleafSharedOverlay Name="main_host">
    <fl:FlyleafSharedOverlay.DetachedContent>
            <Canvas x:Name="detached_canvas" Background="Black" AllowDrop="True">
                
            </Canvas>
    </fl:FlyleafSharedOverlay.DetachedContent>
        <Viewbox Name="viewbox_mc" Panel.ZIndex="0">
            <Canvas Name="MosaicCanvas" Background="Transparent" Panel.ZIndex="0">
                    
                </Canvas>
            </Grid>
        </Viewbox>
</fl:FlyleafSharedOverlay>`

This way it works because I don't insert flyleafhost controls into the canvas MosaicCanvas.
Flyleafhost controls only go in the detached_canvas and I resize them manually because the viewbox doesn't work with them.

**Comment by maoleigepu** [comment]
> > Hi，how do you solve this problem? I'm having the same issue。
> 
> I put the viewbox inside the FlyleafSharedOverlay with the Canvas MosaicCanvas inside it.
> 
> `<fl:FlyleafSharedOverlay Name="main_host"> <fl:FlyleafSharedOverlay.DetachedContent> <Canvas x:Name="detached_canvas" Background="Black" AllowDrop="True"> <!--here the video players--> </Canvas> </fl:FlyleafSharedOverlay.DetachedContent> <Viewbox Name="viewbox_mc" Panel.ZIndex="0"> <Canvas Name="MosaicCanvas" Background="Transparent" Panel.ZIndex="0"> <!--here other usercontrols--> </Canvas> </Grid> </Viewbox> </fl:FlyleafSharedOverlay>`
> 
> This way it works because I don't insert flyleafhost controls into the canvas MosaicCanvas. Flyleafhost controls only go in the detached_canvas and I resize them manually because the viewbox doesn't work with them.

Thanks, it helps a lot
