### ISSUE TITLE
Decoder (Subtitles): Bitmap Support

### ISSUE THREAD

**Issue by umlx5h** [SuRGeoNix/Flyleaf#460]
Thank you for your wonderful library!

I am trying to create a player that can display two subtitles in different languages simultaneously for learning purposes.

It doesn't seem to support subtitles in bitmap format (SUP) instead of text format (SRT), do you have plans to support this?

Almost all the subtitles that come with m2ts (Blu-ray) are in bitmap format, but they are not displayed in the sample player, even though it can be selected from `Embeded` lists.

mpv seems to be supported.

I don't want to use OCR to convert to SRT because it is not accurate enough for non-English.

**Comment by SuRGeoNix** [comment]
Hi @umlx5h, indeed that has not been implemented yet. It wouldn't be difficult to be included with the current d3d11 renderer but the problem it would be to control the position/size and also to clear them properly from the frame. I think I would leave this for v4.
