### ISSUE TITLE
Issues of brightness control

### ISSUE THREAD

**Issue by artmscn** [SuRGeoNix/Flyleaf#461]
Dear author:
Thank you for the great work.
I've met a problem again with flyleaf .net

When i trying to adjust video's brightness, i dont know how to write the code.

What i want to do is when pressed the Z key, brightness turns up
similar like
                if (e.KeyCode == Keys.Z)
                {
                flyleaf1.Player.Brightness += 10;

                }

And when pressed C key, brightness turns down.
How can it work??Could you please give some instructions?
Thank you

**Comment by SuRGeoNix** [comment]
This is how I could do it with the sample wpf version:-

```csharp
var keys = playerConfig.Player.KeyBindings;
keys.AddCustom(Key.U, false, () => Player.Config.Video.Filters[VideoFilters.Brightness].Value += 5, "Increase Brightness", false, false, false);
keys.AddCustom(Key.J, false, () => Player.Config.Video.Filters[VideoFilters.Brightness].Value -= 5, "Decrease Brightness", false, false, false);
```
