### ISSUE TITLE
[New feature requests]Added multi-threading support for M3U8

### ISSUE THREAD

**Issue by kuangxj** [SuRGeoNix/Flyleaf#462]
[New feature requests]

Let's see if you can add support for multi-threaded download cache in M3U8 format, or if you already have a related function, can you give a case.

Thanks.

**Comment by SuRGeoNix** [comment]
@kuangxj Can you explain in more details what do you mean with multi-thread download for m3u8? If that's a thing, I guess FFmpeg should support it and not FlyleafLib. Generally, the downloader is very limited and it will be improved in the next major version.

**Comment by kuangxj** [comment]
I mean that there is a slow problem when playing the m3u8 file. See if you can add multi-threaded cache ts, and in the case of cache, there is no need to cache again when dragging the progress bar. But now it seems that there is no implementation of this function. Every time you drag the progress bar, the ts file will be downloaded again.

**Comment by SuRGeoNix** [comment]
@kuangxj There are options in FFmpeg to increase the buffer. Flyleaf does not currently support Packet Queue that will cache packets in general. Only one way (forward) from the current position for the specified Buffered Duration from Config. However, even this cache will be cleared after seeking backwards or forwards (after the cache). This will be added in v4.
