### ISSUE TITLE
Demuxer: Blu-Ray Support

### ISSUE THREAD

**Issue by etlweather** [SuRGeoNix/Flyleaf#463]
I can play a Bluray disc in MPV with the following command:

```
mpv --fs --bluray-device=f: bd://
```

I haven't yet figured out a way to do this with Flyleaf.

Is it possible?

**Comment by etlweather** [comment]
Let's assume it is a home-made Bluray with no encryption.

**Comment by SuRGeoNix** [comment]
@etlweather I've not try to test/support blueray at all to be honest and I think the current implementation cannot support it. Generally, new features will be not included in v3 anymore as I'm trying to go to the new v4 design.

**Comment by etlweather** [comment]
@SuRGeoNix Make sense. Any idea when v4 will be ready?

**Comment by etlweather** [comment]
With `ffplay` I can play the blueray disk with `ffplay bluray:f:\` where `f:\` is the drive letter of the bluray drive.

**Comment by etlweather** [comment]
Opening the meida with `bluray:f:\` sort of worked - I get the video but I am not getting any sound.

**Comment by SuRGeoNix** [comment]
Guys, I don't even have a spare Blu-ray to test this, but I will try to include it as for v4 I've changed the design couple of times and might be ready in October (for the player, as a media library hopefully much sooner).

**Comment by SuRGeoNix** [comment]
Just tested a sample bluray and it was working fine. Here is the FFmpeg docs: https://ffmpeg.org/ffmpeg-protocols.html#bluray

* Just simple use bluray:d:\
* More advanced with options fmt://mpegts?bluray:d:\&playlist=0&angle=2

The main issue is with the subtitles (bitmaps) which I will try to support soon.
