### ISSUE TITLE
Memory Leakage

### ISSUE THREAD

**Issue by cxgym** [SuRGeoNix/Flyleaf#466]
【v3.7.48】Opening multiple streams in the same application results in a continuous increase in memory until the program crashes, log is not have error, but Opening single streams it is no problem.

**Comment by SuRGeoNix** [comment]
Once again @cxgym by trying to describe an issue with 1 line and expecting me to understand it and fix it makes no sense.

**Comment by cxgym** [comment]
I can only describe the problem I encountered because there is no valuable reference in the logs. Opening multiple streams in an application is normal if software is used to decode it. If I enable D3D hardware acceleration, it will run normally on some machines, while running on another machine will cause memory leakage. However, opening only one stream is not a problem

**Comment by cxgym** [comment]
I can only describe the problem I encountered because there is no valuable reference in the logs. Opening multiple streams in an application is normal if software is used to decode it. If I enable D3D hardware acceleration, it will run normally on some machines, while running on another machine will cause memory leakage. However, opening only one stream is not a problem

**Comment by cxgym** [comment]
I can only describe the problem I encountered because there is no valuable reference in the logs. Opening multiple streams in an application is normal if software is used to decode it. If I enable D3D hardware acceleration, it will run normally on some machines, while running on another machine will cause memory leakage. However, opening only one stream is not a problem

**Comment by cxgym** [comment]
![520](https://github.com/SuRGeoNix/Flyleaf/assets/20064260/91385635-dbf6-460f-aec7-c0d392c762de)

**Comment by cxgym** [comment]
I suspect there is a thread safety issue here

**Comment by cxgym** [comment]
Hope to receive prompt，thanks

**Comment by cxgym** [comment]
Hope to receive prompt, thanks.

**Comment by cxgym** [comment]
Hope to give me tips, thanks.

**Comment by SuRGeoNix** [comment]
Check this https://github.com/SuRGeoNix/Flyleaf/issues/450 and this https://github.com/SuRGeoNix/Flyleaf/discussions/448

**Comment by cxgym** [comment]
Is it because of a problem with the gpu driver?

**Comment by cxgym** [comment]
GPU 0
	Intel(R) Iris(R) Xe Graphics
	Drive Version:	        31.0.101.4953
	Drive Date:	        2023/11/7
	DirectX Version:	12 (FL 12.1)
it is memory leakage

GPU 1
	Intel(R) Iris(R) Xe Graphics
	Drive Version:	        27.20.100.8984
	Drive Date:	        2020/11/19
	DirectX Version:	12 (FL 12.1)
it is right

**Comment by SuRGeoNix** [comment]
From what other users said in the past is seems that is related with intel integrated graphics. Not sure if that's intel's issue or the combination of Intel/WPF. I was not able to reproduce it myself yet.

**Comment by acidmeat** [comment]
@cxgym use this
config.Decoder.ZeroCopy = FlyleafLib.ZeroCopy.Enabled;

**Comment by cxgym** [comment]
Config.Decoder.ZeroCopy = FlyleafLib.ZeroCopy.Enabled;    
It can indeed solve my problem. but it will affect other functions?

**Comment by SuRGeoNix** [comment]
Thanks interesting. The only problem by forcing ZeroCopy it would be that you will have visible codec's padding pixels at the sides. (eg. full row of green pixels at the bottom of the frame). By checking the source code it seems that intel driver has the issue with the CopySubresourceRegion. Another open intel issue possible related is this https://community.intel.com/t5/Developing-Games-on-Intel/Memory-leaks-on-Intel-Iris-Xe-graphics/td-p/1585566
