### ISSUE TITLE
Quite a number of issues using your repo in C# console project.

### ISSUE THREAD

**Issue by zydjohnHotmail** [SuRGeoNix/Flyleaf#48]
I have done the following in order to use your repo in C# console project (target .NET 5.0)
Download and unzip ffmpeg full build file from this URL: 
https://www.gyan.dev/ffmpeg/builds/ffmpeg-release-full.7z
Copy the unzipped folder to C:\Program Files\
Edit System PATH variable to add ffmpeg binary path.
I have installed nuget packages:
PM> Install-Package FFmpeg.AutoGen -Version 4.4.0
PM> Install-Package NAudio.Wasapi -Version 2.0.0
PM> Install-Package SharpDX.Mathematics -Version 4.2.0
PM> Install-Package FlyleafLib -Version 3.1.12
PM> Install-Package FlyleafLib.Controls.WPF -Version 1.1.4
Before going further, I found the following warnings:
For both FlyleafLib  & FlyleafLib.Controls.WPF, I saw yellow color icon next to the both, showing: 
Warning	NU1701	Package 'FlyleafLib 3.1.12' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework 'net5.0'. This package may not be fully compatible with your project.
Warning	NU1701	Package 'FlyleafLib.Controls.WPF 1.1.4' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework 'net5.0'. This package may not be fully compatible with your project.
For the above warnings, can you please make new nuget package to target .NET 5.0?

I have written the following C# code, trying to download one M3U8 URL to local hard drive.

using FlyleafLib;
using FlyleafLib.MediaFramework.MediaDemuxer;
using System;
using System.Threading.Tasks;

namespace FlyleafDownloadTest1
{
    class Program
    {
        public const string FFMPEG_Binary = @"C:\Program Files\ffmpeg-4.4-full_build\bin";
        public const string Output_File1 = @"C:\Videos\FFMPEG\Download1.mp4";

        private static void Downloader1_DownloadCompleted(object sender, bool success)
        {
            if (success)
            {
                Console.WriteLine("Partial/Live Download Completed!");
            }
            else
                Console.WriteLine("Download Failed!");
        }
        static async Task Main(string[] args)
        {
            Master.RegisterFFmpeg(FFMPEG_Binary);
            DemuxerBase Downloader1 = new VideoDemuxer(new Config(), 1);
            Downloader1.DownloadCompleted += Downloader1_DownloadCompleted;
            string url1 = @"https://www.rmp-streaming.com/media/big-buck-bunny-360p.mp4";
            if (Downloader1.Open(url1) != 0) 
            { Console.WriteLine("Could not open url input"); return; }
            Downloader1.EnableStream(Downloader1.VideoStreams[0]);
            if (Downloader1.AudioStreams.Count != 0) 
                Downloader1.EnableStream(Downloader1.AudioStreams[0]);
            Downloader1.Download(Output_File1);
            await Task.Delay(10000);
            if (Downloader1.Url.Contains("bunny"))
                Downloader1.Stop();
            Console.WriteLine("Done!");
        }
    }
}

I just want to see if I can use your repo to download M3U8 URL to local hard disk in C# console project, without using any GUI interface. I think this could be very basic usage, if successful, I can use it somewhere else, like WinForm project.  But I don’t like WPF, as there are too many restrictions.
However, when I run my code, I got a lot of this type errors:
System.Exception
  HResult=0x80131500
  Message=Failed to register FFmpeg libraries
  Source=FlyleafLib
  StackTrace:
   at FlyleafLib.Master.RegisterFFmpeg(String absolutePath, Int32 verbosity)
   at FlyleafDownloadTest1.Program.<Main>d__3.MoveNext() in C:\FlyleafDownloadTest1\Program.cs:line 24

  This exception was originally thrown at this call stack:
    [External Code]

Inner Exception 1:
DllNotFoundException: Unable to load DLL 'avformat.58 under C:\Program Files\ffmpeg-4.4-full_build\bin': The specified module could not be found.

I have tried to search such files and copy them to C:\Program Files\ffmpeg-4.4-full_build\bin\, but this types of error seem never end.
This is what I can see inside the full build of FFMPEG:
C:\Users\John>ffmpeg -version
ffmpeg version 4.4-full_build-www.gyan.dev Copyright (c) 2000-2021 the FFmpeg developers
built with gcc 10.2.0 (Rev6, Built by MSYS2 project)
configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-lzma --enable-libsnappy --enable-zlib --enable-librist --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-libbluray --enable-libcaca --enable-sdl2 --enable-libdav1d --enable-libzvbi --enable-librav1e --enable-libsvtav1 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-libaom --enable-libopenjpeg --enable-libvpx --enable-libass --enable-frei0r --enable-libfreetype --enable-libfribidi --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libmfx --enable-libglslang --enable-vulkan --enable-opencl --enable-libcdio --enable-libgme --enable-libmodplug --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libshine --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libilbc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-ladspa --enable-libbs2b --enable-libflite --enable-libmysofa --enable-librubberband --enable-libsoxr --enable-chromaprint
libavutil      56. 70.100 / 56. 70.100
libavcodec     58.134.100 / 58.134.100
libavformat    58. 76.100 / 58. 76.100
libavdevice    58. 13.100 / 58. 13.100
libavfilter     7.110.100 /  7.110.100
libswscale      5.  9.100 /  5.  9.100
libswresample   3.  9.100 /  3.  9.100
libpostproc    55.  9.100 / 55.  9.100

C:\Users\John>

From my understanding, the full build seem contain all necessary modules your repo needs, but maybe in different format.
Please check and let me know how I can proceed with my simple project.
Thanks,

**Comment by SuRGeoNix** [comment]
You need the shared ffmpeg's libs (do you have the .dll files?). You can download the sample demo version and copy the Libs folder to your application as well.

**Comment by SuRGeoNix** [comment]
And for the first issue that you mention you need to change your target framework to net5.0-windows. Edit your .csproj file and change the line

```
<TargetFramework>net5.0-windows</TargetFramework>
```

**Comment by SuRGeoNix** [comment]
Use also the latest package 3.1.14 as it fixes some issues for the downloader, re-open this if you still have issues

**Comment by zydjohnHotmail** [comment]
Hello:
Thanks, it is working now.
The biggest headache is, how I can know there are so many DLLs are necessary to use the repo.
Is it possible that you add all those DLLs in your nuget package, so I don't have to find them somewhere else?
Thanks,

**Comment by SuRGeoNix** [comment]
No, it wouldn't be wise to include them in the package. They don't change /update every day and it wouldn't be ideal if the package was so large on every flyleaflib update. You need only the x86 or x64 that you are going to use and you can remove the filters as far as i remember.
