### ISSUE TITLE
Audio stopped after some time in rtsp stream

### ISSUE THREAD

**Issue by sharmasulekh87** [SuRGeoNix/Flyleaf#480]
Hello @SuRGeoNix ,
I am using Flyleaf version 3.7.41 and try to play rtsp url having audio stream, but it stopped after 1 minutes approx. The video continues but no audio after that. I have set the MaxAudioFrames count to 4. Although it plays ok with ffplay. I am hereby attaching the logs. Please guide me what more can i add to rectify the issue.

[Player_1719903380.log](https://github.com/user-attachments/files/16063334/Player_1719903380.log)

**Comment by SuRGeoNix** [comment]
Hi @sharmasulekh87,

It seems that you set the Demuxer.AllowFindStreamInfo to false, I guess to faster opening the stream. However, that might be the reason for your issue as it does not read properly the stream's codec parameters. You can also try to enable/disable this Audio.FiltersEnabled. Try to increase the MaxAudioFrames even higher 40+.

I cannot see anything in the logs (use trace for flyleaf), also you saying the issue happened 1 minute after and the logs are for 30 seconds.

Regards,
John
