### ISSUE TITLE
Memory Leak when ZeroCopy = False

### ISSUE THREAD

**Issue by pubpy2015** [SuRGeoNix/Flyleaf#482]
Hi,

I have modified the sample FlyleafPlayer (Custom) (WinForms) with 4 players to play rtsp stream from camera.
I have seen that RAM memory has increased continuously. Please watch the attached video.

Debug here i see that ZeroCopy = False
23.13.11.913 | Debug | [#3]     [Decoder: Video] ==========Start Test Memory Leak==========
23.13.11.940 | Debug | [#1]     [Decoder: Video] codecCtx->width = 2688, codecCtx->height = 1520
23.13.11.943 | Debug | [#3]     [Decoder: Video] codecCtx->width = 2688, codecCtx->height = 1520
23.13.11.945 | Debug | [#1]     [Decoder: Video] textureFFmpeg.Description.Width = 2688, textureFFmpeg.Description.Height = 1536
23.13.11.947 | Debug | [#3]     [Decoder: Video] textureFFmpeg.Description.Width = 2688, textureFFmpeg.Description.Height = 1536
23.13.11.949 | Debug | [#1]     [Decoder: Video] ZeroCopy = False
23.13.11.951 | Debug | [#3]     [Decoder: Video] ZeroCopy = False
23.13.11.953 | Debug | [#1]     [Decoder: Video] ==========End Test Memory Leak==========
![ảnh](https://github.com/SuRGeoNix/Flyleaf/assets/59004953/d8369b1a-9b6e-4433-bfdf-5e1e73bacfb3)

https://github.com/SuRGeoNix/Flyleaf/assets/59004953/772c2a88-549e-4d64-be1e-76abefbf3905

**Comment by SuRGeoNix** [comment]
Closing this as duplicate (actually there couple of issues / discussions) about intel GPU issue.

**Comment by pubpy2015** [comment]
Hi,

The cause of the problem here is codecCtx->height = 1520 and textureFFmpeg.Description.Height = 1536 and therefore ZeroCopy = False.
I tried with another camera, the resolution of stream is 2560x1440.
H264 with VLC
![ảnh](https://github.com/SuRGeoNix/Flyleaf/assets/59004953/a8fda3b6-8e70-4eee-9daf-e4773244befa)
H265 with VLC
![ảnh](https://github.com/SuRGeoNix/Flyleaf/assets/59004953/a2855656-7c3c-455d-b10b-3ed84ef44858)


When video codec is H264, both codecCtx->height and textureFFmpeg.Description.Height are 1440.
`08.11.01.098 | Debug | [#1]     [Decoder: Video] ==========Start Test Memory Leak==========
08.11.01.100 | Debug | [#1]     [Decoder: Video] codecCtx->codec_id = AV_CODEC_ID_H264
08.11.01.102 | Debug | [#1]     [Decoder: Video] codecCtx->width = 2560, codecCtx->height = 1440
08.11.01.104 | Debug | [#1]     [Decoder: Video] textureFFmpeg.Description.Width = 2560, textureFFmpeg.Description.Height = 1440
08.11.01.106 | Debug | [#1]     [Decoder: Video] ZeroCopy = True
08.11.01.109 | Debug | [#1]     [Decoder: Video] ==========End Test Memory Leak==========`

But when video codec is H265, codecCtx->height = 1440 and textureFFmpeg.Description.Height = 1536
`08.19.09.472 | Debug | [#1]     [Decoder: Video] ==========Start Test Memory Leak==========
08.19.09.475 | Debug | [#1]     [Decoder: Video] codecCtx->codec_id = AV_CODEC_ID_HEVC
08.19.09.476 | Debug | [#1]     [Decoder: Video] codecCtx->width = 2560, codecCtx->height = 1440
08.19.09.479 | Debug | [#1]     [Decoder: Video] textureFFmpeg.Description.Width = 2560, textureFFmpeg.Description.Height = 1536
08.19.09.481 | Debug | [#1]     [Decoder: Video] ZeroCopy = False
08.19.09.483 | Debug | [#1]     [Decoder: Video] ==========End Test Memory Leak==========`

**Comment by SuRGeoNix** [comment]
@pubpy2015 There different types of dimensions, you have the coded dimensions and you have the display/presentation dimensions. This is mainly because each codec requires different padding/alignment of the data. So I'm not sure what you trying to say, in your case ZeroCopy = false is required in case of hevc, you can verify this by forcing it to true and see some extra pixels.

**Comment by SuRGeoNix** [comment]
The memory leak happens in intel GPU when ZeroCopy = false, which is normal not necessary an issue when ZeroCopy = false.
Now, if you could have ZeroCopy buf for some reason Flyleaf can't get it... that's a different issue (and it could be also an FFmpeg issue not Flyleaf's). I'm not sure if VLC uses the same HEVC codec with FFmpeg and if it uses a custom getBuffer callback to manually allocate the hardware frames with heigh 1440 instead of 1536 that might ffmpeg decides by default.

**Comment by pubpy2015** [comment]
When I set _ZeroCopy = ZeroCopy.Enabled, the memory leak error no longer occurs. So I just checked why _ZeroCopy = ZeroCopy.Auto became to False and found that it was due "codecCtx->height != textureFFmpeg.Description.Height".
In case the video stream codec is H264, I see that ZeroCopy always = True, so can I force to set ZeroCopy = True in all case ?

**Comment by SuRGeoNix** [comment]
No, you will see padding pixels that it is not right

**Comment by pubpy2015** [comment]
I see video from the camera normally. Do you want to rtsp url of this camera or remote to PC with Intel UHD Graphic 770 to check ? I will install visual studio 2022

**Comment by SuRGeoNix** [comment]
The difference might not easy to spot. Try take a snapshot for each and then compare them.

**Comment by pubpy2015** [comment]
Temporarily I create an exception like this so the program can run
![ảnh](https://github.com/SuRGeoNix/Flyleaf/assets/59004953/8202dba0-b17d-41ce-8782-b35618257a95)
