### ISSUE TITLE
To play i frames only in a video

### ISSUE THREAD

**Issue by sharmasulekh87** [SuRGeoNix/Flyleaf#483]
Hello @SuRGeoNix 
To play i frame only in a video, in ffplay we can use "-skip_frame nokey" option. Can we do that in flyleaf as well?
I have tried to add the option in formatopt but it didn't work. Do i need to add anything more?

**Comment by SuRGeoNix** [comment]
No, currently is not possible but I could consider adding this. Wondering what the frame duration would be in that case (eg. if you have 25 frames per GOP - keyframe to keyframe it would have 1 frame duration or 25 frames and how it would sync with audio).

**Comment by SuRGeoNix** [comment]
@sharmasulekh87 I'm not sure what will be the point of this feature feel free to advice and I will review it.
