### ISSUE TITLE
Can Multiple Audio Streams in One File Be Played Simultaneously?

### ISSUE THREAD

**Issue by Lizhengbo0304** [SuRGeoNix/Flyleaf#485]
I have a file with one video stream and eight audio streams. Can I use this player to play all the audio streams simultaneously? It's not multiple files, but multiple audio streams in one file.

**Comment by SuRGeoNix** [comment]
@Lizhengbo0304 is that the same with this https://github.com/SuRGeoNix/Flyleaf/issues/408 ?

**Comment by Lizhengbo0304** [comment]
No, the usage scenarios are different. One is to play multiple audio files together, and the other is to play multiple audio streams in the same file together.
