### ISSUE TITLE
RTSP Tcp option Not work

### ISSUE THREAD

**Issue by quickping7** [SuRGeoNix/Flyleaf#486]
Hi . 
I want to use tcp connection for rtsp stream but when i use below option , i see rtp packet in wireshark and i think it is not work. 
Config1.Demuxer.FormatOpt["rtsp_transport"] = "tcp";

thanks for your help

**Comment by SuRGeoNix** [comment]
Hi @quickping7, for Flyleaf this is set by default. Not sure why is not working but that's not related with Flyleaf.

**Comment by quickping7** [comment]
thanks for fast response. 
I tried connect to my dahua ip camera with flyleaf release app and find that in main stream mode all packet is tcp but in sub stream mode is rtp. 
also in vlc both mode is tcp.
I did not find anything related to tcp/udp connection in dahua settings.
