### ISSUE TITLE
 question about playing pictures

### ISSUE THREAD

**Issue by qinjianzhanqing** [SuRGeoNix/Flyleaf#493]
Hello, I have a question about playing pictures. Is there a parameter that can set the duration of playing images? Currently, playing images defaults to loop playback, with a property duration of 0.04 seconds. There is an image browser in the example, but it is only used for carousel. Sometimes I need to playlist play pictures and videos, but currently this requirement is not met. The default image duration of PotPlayer and VLC player is 10 seconds, and it can be set through parameter settings.

**Comment by SuRGeoNix** [comment]
@qinjianzhanqing I think the only reason for that it would be when having a playlist and you want to wait at least X time before playing the next media file? If that's the case, that is based on the "Slide Show" implementation, as Sample uses too. So you will have to implement this at higher level. The duration is one frame as it is announced from FFmpeg which could be considered also as 0. Check Slide Show that it has it's own configuration for that 'wait' time before switching to next image and let me know if you mean something else.
