### ISSUE TITLE
WinForm Flyleaf net 4.7.2 NuGet error

### ISSUE THREAD

**Issue by Revan1985** [SuRGeoNix/Flyleaf#501]
Hello,
I am trying to use the FlyLeaf in a winform project targeting 4.7.2
I am receiving this error when trying to import che nuget:

```
Attempting to gather dependency information for package 'FlyleafLib.3.7.52' with respect to project 'FlyLeafcontrol', targeting '.NETFramework,Version=v4.7.2'
Gathering dependency information took 772 ms
Attempting to resolve dependencies for package 'FlyleafLib.3.7.52' with DependencyBehavior 'Lowest'
Unable to find a version of 'SharpGen.Runtime' that is compatible with 'Vortice.D3DCompiler 2.4.2 constraint: SharpGen.Runtime (>= 2.0.0-beta.13)', 'Vortice.Direct3D11 2.4.2 constraint: SharpGen.Runtime (>= 2.0.0-beta.13)', 'Vortice.DirectComposition 2.4.2 constraint: SharpGen.Runtime (>= 2.0.0-beta.13)', 'Vortice.MediaFoundation 2.4.2 constraint: SharpGen.Runtime (>= 2.0.0-beta.13)', 'Vortice.XAudio2 2.4.2 constraint: SharpGen.Runtime (>= 2.0.0-beta.13)'.
```

I have a clean project, no code/dependency installed yet.
Thanks for any support

**Comment by Revan1985** [comment]
I have found a workaround for my case.
I need to check also the "Include prerelease" checkbox, otherwise nuget is not able to find the beta required SharpGen.Runtime[.COM] packages.
I hope this could help

**Comment by SuRGeoNix** [comment]
There were some issues with Flyleaf/Vortice-SharpGen in the past with .NET framework. Can't do something about it, if you search you can find some workarounds.
