### ISSUE TITLE
Request to add Audio Balance

### ISSUE THREAD

**Issue by vzsoft** [SuRGeoNix/Flyleaf#506]
Hi,
If possible, please add the ability to adjust Audio Balance.
thank you so much

**Comment by SuRGeoNix** [comment]
Did you try FFmpeg's audio filters, it should be possible with those.

**Comment by vzsoft** [comment]
Thank you for your answer
I changed the values ​​of the "Stereo Adjustments" filter, but nothing happens

**Comment by SuRGeoNix** [comment]
I'm not sure what is the "Stereo Adjustments" filter, what I've found is [stereotools](https://ffmpeg.org/ffmpeg-filters.html#toc-stereotools)

and I've tested with this:-

```c#
playerConfig.Audio.FiltersEnabled = true;
playerConfig.Audio.Filters = new()
{
    new() { Name = "stereotools", Args = "balance_in=1", Id = "stereotools1" },
};
```

**Comment by vzsoft** [comment]
thank you so much @SuRGeoNix
