### ISSUE TITLE
Please provide more info and exception details on FFMpeg path

### ISSUE THREAD

**Issue by datvm** [SuRGeoNix/Flyleaf#507]
I am not sure what the issue is but I keep getting this error:

> Loading FFmpeg libraries 'D:\Software\FFmpeg\ffmpeg.exe' failed

I have tried:

1. Putting in the folder `D:\Software\FFmpeg`. It contains 3 files including `ffmpeg.exe`.
2. Make a `bin` folder inside so `D:\Software\FFmpeg\bin\ffmpeg.exe` exists (and still put `D:\Software\FFmpeg` as the input).
3. Put in the full path to the exe file and not folder.
4. Since my app is a WinUI 3 app, I suspect maybe it's because I do not have permission. However, after using Folder Picker and pick the folder (presumably also give the app full permission for that folder), the error still shows up.

I have just downloaded the file fresh from: https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-master-latest-win64-gpl.zip, and my build config is `x64`. Also I do not refer to any `FFmpeg.Autogen` package so I assume `FFmpeg.Autogen` v5.1.2.1 is installed by `FlyleafLib`.

**Comment by SuRGeoNix** [comment]
@datvm you need to include the shared dll libraries not the binaries

**Comment by datvm** [comment]
Ah that makes sense. Sorry again but even pointing to the folder `D:\Software\FFmpeg\Lib` with these files:

```
"D:\Software\FFmpeg\Lib\avdevice-61.dll"
"D:\Software\FFmpeg\Lib\avfilter-10.dll"
"D:\Software\FFmpeg\Lib\avformat-61.dll"
"D:\Software\FFmpeg\Lib\avutil-59.dll"
"D:\Software\FFmpeg\Lib\postproc-58.dll"
"D:\Software\FFmpeg\Lib\swresample-5.dll"
"D:\Software\FFmpeg\Lib\swscale-8.dll"
"D:\Software\FFmpeg\Lib\avcodec-61.dll"
```

it still fails. I will clone the repo to see what exactly is happening. Perhaps I will make a PR and include an inner exception there for clarification if you think that's good?

```
   at FlyleafLib.FFmpegEngine..ctor()
   at FlyleafLib.Engine.StartInternalNonUI()
   at FlyleafLib.Engine.StartInternal(EngineConfig config, Boolean async)
   at FlyleafLib.Engine.Start(EngineConfig config)
   at RtspBabyMonitor.MainPage.InitializeEngine(String ffmpegPath) in 
```

**Comment by datvm** [comment]
Update: sorry, I downloaded the **wrong** file. I added dll files from ffmpeg-n5.1.6-7-g4ce4ecc19c-win64-gpl-shared-**5.1**.zip and it's working now :)

**Comment by SuRGeoNix** [comment]
No problem, you can add the the FFmpeg.Autogen v6 package (at your app/project) and use the FFmpeg 6 libraries if you prefer.
