### ISSUE TITLE
Can I use your repo to pick up frames from one MP4 video?

### ISSUE THREAD

**Issue by zydjohnHotmail** [SuRGeoNix/Flyleaf#51]
Hello:
I have one MP4 format video (C:\Videos\1.mp4), which contains 1000 frames.
If I want to pick up frames every 100 frames, in my case, I want to pick up the first frame, the 100th, 200th, 300th, 400th, 500th, 600th, 700th, 800th, 900th and the last frame, and put them into one array of images.
Then use ImageMagick to find the image similarity between the first frame and other frames and find which is the first frame which is more than 10% different from the first frame.
One good example for this is the basketball score board, which will change after a few seconds or a few minutes, but there is no way to know when the score change will happen.  In the worst case from my college experience, one women basket ball game ended with score: 4-0, it means it changes only twice (from 0-0 to 2-0, and from 2-0 to 4-0). But most other games will change very quickly.
Let me know if I can do this with your repo?
If yes, give me some code sample.
Thanks,

**Comment by SuRGeoNix** [comment]
Hey @zydjohnHotmail, unfortunately this is not implemented yet. I'm planning to add it in v3.2 hopefully soon. I've already a code to give you to extract specific frames but that wouldn't be enough as it will happened in GPU and you need to bring the frame back to CPU/memory. You could force it though to use RGB sws_scale. If you are up for coding check this code [here](https://stackoverflow.com/questions/67397968/how-to-get-currecnt-avframe-siquential-number-after-av-seek-frame/67404457#67404457)

**Comment by zydjohnHotmail** [comment]
Hello:
I looked at the code, but I think it was in C++, which I already forgot many years ago. Anyway, I will try to find other way to do, but if you can release new version and add the feature, let me know. 
I need some C# code with good performance, since my real job will need such feature for much bigger video files.
Thanks,

**Comment by SuRGeoNix** [comment]
The code is actually in c# that I gave you even the title says c++. It would be easy to write it without performance that's why I want to write it once for good with hardware acceleration and pixel shaders.

**Comment by SuRGeoNix** [comment]
I have just included in v3.2.2, check Sample5_ExportVideoFrames and let me know how it goes.
