### ISSUE TITLE
Remuxing to generic stream support

### ISSUE THREAD

**Issue by sTolyaR** [SuRGeoNix/Flyleaf#510]
Hello!
I'm trying to implement remuxing video to generic stream (e.g. FileStream) instead of a file on disk.
I have added class for custom IO context with write and even seek callbacks:
```csharp
public unsafe class StreamOutputAVIOContext
{
    public const int BUFFER_SIZE = 0x200000;

    Stream stream;

    avio_alloc_context_write_packet mWriteCallbackFunc;
    avio_alloc_context_seek mSeekCallbackFunc;

    public AVIOContext* context;

    private byte* buffer;
    private byte[] intBuffer;

    public StreamOutputAVIOContext(Stream srcStream)
    {
        stream = srcStream;
        mWriteCallbackFunc = IOWrite;
        mSeekCallbackFunc = IOSeek;
        buffer = (byte*)ffmpeg.av_malloc(BUFFER_SIZE + AV_INPUT_BUFFER_PADDING_SIZE);
        intBuffer = new byte[BUFFER_SIZE];
        context = avio_alloc_context(
            buffer,
            BUFFER_SIZE,
            1,
            null,
            null,
            mWriteCallbackFunc,
            mSeekCallbackFunc
            );
    }

    int IOWrite(void* opaque, byte* buf, int buf_size)
    {
        Marshal.Copy((IntPtr)buf, intBuffer, 0, buf_size);
        stream.Write(intBuffer, 0, buf_size);
        return buf_size;
    }

    long IOSeek(void* opaque, long offset, int whence)
    {
        return whence == AVSEEK_SIZE
            ? stream.Length
            : stream.Seek(offset, (SeekOrigin)whence);
    }

    public void Dispose()
    {
        if (context != null)
        {
            av_free(context->buffer);
            fixed (AVIOContext** ptr = &context)
                avio_context_free(ptr);
        }
        context = null;
        stream = null;
        mWriteCallbackFunc = null;
        mSeekCallbackFunc = null;
    }
}
```
Then I added a method overload for Remuxer.Open() :
```csharp
    public int Open(Stream stream)
    {
        int ret;
        Filename = "dummyFileName";

        streamCtx = new StreamOutputAVIOContext(stream);
        fixed (AVFormatContext** ptr = &fmtCtx)
            ret = avformat_alloc_output_context2(ptr, null, "mp4", null);

        if (ret < 0) return ret;

        fmtCtx->pb = streamCtx.context;
        fmtCtx->flags |= AVFMT_FLAG_CUSTOM_IO;
        fmt = fmtCtx->oformat;
        
        mapInStreamToDts = new Dictionary<int, long>();
        Disposed = false;

        return 0;
    }
```
Also I made public methods StartRecording and StopRecording on VideoDecoder class for passing a custom Remuxer to it.

After that all the initialization and writing methods (avio_open, avformat_write_header, av_interleaved_write_frame and so on) run without errors and return code 0, but custom callbacks aren't called at all.

Maybe you have some idea on what's going wrong with my code?

**Comment by sTolyaR** [comment]
Sorry for disturb! It's my fault. I have realized that I must not call avio_open at all while using custom IO context. Just write it out there for history.

**Comment by SuRGeoNix** [comment]
Hi @sTolyaR, did you resolve it?
Why not using library's functionality? You could just use the Downloader with your filestream as input.

**Comment by sTolyaR** [comment]
Hi! Yes, I have managed Remuxer to write to any Stream instead of file through custom IO context.
Generally we need to capture video and audio from different sources: usb webcams, rtsp streams with live preview and recording into multiple fragments. Then we need to play recorded fragments. We use custom stream implementations for media data, so we have to work with streams for input and output.
I think I will also implement some transcoding for muxing raw video from webcam into mp4 format container. The same for audio streams not supported by mp4 format.
Ideally we would like to move presentation layer from WPF to Avalonia framework in the future in order to be crossplatform.
Thank you for your great work!

**Comment by SuRGeoNix** [comment]
Nice, I've already prepared the next version (v4) at least for things like remuxing/transcoding, I will probably upload it in github the next days you might want to check.

**Comment by sTolyaR** [comment]
Sounds amazingly! Sure I will wait for it and better use library in the mainstream way.
Thanks!
