### ISSUE TITLE
Seeking doesn't work correctly

### ISSUE THREAD

**Issue by sloginov** [SuRGeoNix/Flyleaf#513]
Hi!

Thank you for your great work. I'm trying to use Flyleaf for playing and seeking video. Playing works fine, but I faced with some problems  in seeking. 
I've [attached](https://github.com/user-attachments/assets/7a331eb6-df66-4d8e-ae83-478c78fcc03f) a short video file where the issue is reproduced. 

Repro steps:
1. Set config.Player.SeekAccurate = true
2. Start FlyleafPlayer 
3. Pause video
4. Try to seek to any position

You can find that seeking doesn't work correctly (actually it doesn't work at all)
Could you please take a look into this bug?

**Comment by SuRGeoNix** [comment]
Hi @sloginov, I just tried the sample player with ctrl + s to enable accurate seeking and it works. It doesn't work for you?

https://github.com/SuRGeoNix/Flyleaf/wiki/Player-(Key-&-Mouse-Bindings)

**Comment by sloginov** [comment]
Hi @SuRGeoNix,
Did you try seeking attached video? I do the same and it doesn't work on version 3.7.53. I'm trying to seek to any position (for example to the middle of the video, but nothing changes. Also I tried to handle SeekCompleted event and log requested and actual CurTime.
```
private void Player_SeekCompleted(object sender, int e)
{
    Debug.WriteLine($"Seek to {(e / 1000f):F2} s completed. CurTime: {TimeSpan.FromTicks(Player.CurTime).TotalSeconds:F2} s");
}
```
 The result is like this:
![image](https://github.com/user-attachments/assets/4d8ad38a-7f90-487f-93c7-47875f062821)

**Comment by SuRGeoNix** [comment]
Yes, I've tried the attached. If you download the release it does not work for you? That does not make any sense.

**Comment by sloginov** [comment]
It definitely does not work.

FYI: It seems that cause of the bug is in the code 
> ret = decoder.Seek(seekData.accurate ? Math.Max(0, seekData.ms - 3000) : seekData.ms, seekData.forward, !seekData.accurate); // 3sec ffmpeg bug for seek accurate when fails to seek backwards (see videodecoder getframe)

 in `MediaPlayer/Player.Playback.cs` file. Seek works on attached video if I remove 3 seconds shift there.

**Comment by SuRGeoNix** [comment]
OK those 3secs are for an FFmpeg bug for the demuxer, still the decoders should seek accurate. I will review this.

**Comment by SuRGeoNix** [comment]
@sloginov The provided media file had decoding errors that's why it wasn't working properly with the accurate seeking. I've included the main's decoding flow logic to handle also the decoding errors. Hope that's what you wanted (tested from master if you can).
