### ISSUE TITLE
Lag in Seek change in 4K videos

### ISSUE THREAD

**Issue by vzsoft** [SuRGeoNix/Flyleaf#516]
Hello
I need to enable `Player.SeekAccurate = true;` but there is a problem in 4k videos, the video lags for a few seconds after changing Seek, is there any way to fix this problem ?

thank you

**Comment by SuRGeoNix** [comment]
The first issue with seeking accurate is that it needs to decode a lot of frames in the GOP until the requested.
The second issue is that FFmpeg seek backward does not always work so there is a 'fixed' -3 seconds from the requested seeking time to ensure it will be before the requested.

I will review the second one might having this only when it actually fails but generally there is no way to avoid the overhead of accurate seeking (decoding of GOP).
