### ISSUE TITLE
Null reference exception on new version 3.8.0

### ISSUE THREAD

**Issue by Agostino44** [SuRGeoNix/Flyleaf#518]
Hello,
I have update FlyleafLib in my wpf project from version 3.7.50 to new 3.8.0. 
I also migrated my project from .net framework 4.8.1 to .NET 8.0 in order to use new FlyleafLib. 
But now I find out a Null Reference exception when call Config constructor for the Player of the FlyleafHost.

In App.xaml.cs I initialize the Engine:

```
EngineConfig engineConfig = DefaultEngineConfig();
Engine.StartAsync(engineConfig);

private EngineConfig DefaultEngineConfig()
{
    return new EngineConfig
    {
        FFmpegPath = System.IO.Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "ffmpeg_bin"),

        // Engine configurations
        FFmpegHLSLiveSeek = true,
        UIRefresh = true,
        FFmpegDevices = true,

        FFmpegLogLevel = Flyleaf.FFmpeg.LogLevel.Quiet,
        LogLevel = LogLevel.Quiet
    };
}
```

then I have a UserControl called MyMediaPlayer with a FlyleafHost; in the code of this usercontrol I have:

```
public Player Player { get; set; }
public Config Config { get; set; }

public MyMedia_Player()
{
    InitializeComponent();

    Execution_count = 0;

    Config = new Config();
    Config.Audio.Enabled = false;
    Config.Subtitles.Enabled = false;

    Player = new Player(Config);
    
    DataContext = this;

    Player.OpenCompleted += Player_OpenCompleted;
}
```

when I instantiate a new MyMedia_Player a Null reference excpeption occured in "Config = new Config();"
the above code is the same as when I was using the old version 3.7.50 in .net framework 4.8.1.

What could it be that I'm missing?

**Comment by SuRGeoNix** [comment]
@Agostino44 Not easy to guess but I will try...

Instead of Engine.StartAsync(engineConfig); use Engine.Start(engineConfig);

You cannot initialize Player's configuration without first initialize the Engine. (Because of the Plugins)

You could either wait for the Engine.StartAsync to complete or listen to the event and do your initialization.
