### ISSUE TITLE
How to extract all frames from a MP4 video file?

### ISSUE THREAD

**Issue by zydjohnHotmail** [SuRGeoNix/Flyleaf#52]
Hello:
I can’t find a C# code sample on how to extract all frames from one MP4 video file. (C:\Videos\1.mp4).
I want to extract all the frames from the MP4 video file and save them (in PNG format) in one local folder. (C:\VideoFrames).
Please advise!
My OS is Windows 10 (Version 21H1), IDE is Visual Studio 2019 (version 16.10.4)

**Comment by SuRGeoNix** [comment]
Hey @zydjohnHotmail, please don't make duplicate issues. You already asked in #51
