### ISSUE TITLE
Can I use your repo to merge video files into one mp4 file?

### ISSUE THREAD

**Issue by zydjohnHotmail** [SuRGeoNix/Flyleaf#53]
Hello:
I have 2 video files, they are using the same video format (I can ignore the audio for now). They are like: C:\Videos\A.mp4, and C:\Videos\B.mp4.
I want to know if I can use your repo to merge the A.mp4 and B.mp4 to make a new video file, called: C:\Videos\Merge.mp4?
I think I can use FFMPEG command to do this, but as I have many of such files, like a few hundreds, so I want to have some program to make the process faster.
Please share some code samples, if possible.
Thanks,

**Comment by SuRGeoNix** [comment]
Currently the library supports only video player and downloader/recorder functions. I'm preparing v3.2 which will be possible to extend these functionalities to more generic.

**Comment by zydjohnHotmail** [comment]
Hello:
As one month is gone, I want to know if I can use this repo. to merge video files now.
I see you have brand new version of 3.3.2, did you add the functionalities already?

**Comment by SuRGeoNix** [comment]
Hey @zydjohnHotmail you can see the library's "high-level" supported features at Readme.md page of the project (Supported/Extra Features).

You could try to use this library for other purposes by using "low-level" library's features such as demuxing/decoding/remuxing but it's completely up to you to write the code and if you need specific clarifications I might be able to help. (Eg. You could create  two demuxers and two video decoders and one remuxer to add the first videos frames and at the end the second video frames. As far as the have the same video codec by just pushing second video's timestamps after the first one it should work fine).

I'm afraid that I will not be able to extend and support more than the Player/Downloader/Extractor features.
