### ISSUE TITLE
Set the "player" variable to a public Property

### ISSUE THREAD

**Issue by vzsoft** [SuRGeoNix/Flyleaf#531]
Hi,
please Set the **player** variable in the **FlyleafLib.Media.Player.Subtitles** class to a public Property.

```csharp
public class Subtitles : NotifyPropertyChanged
{
  Player player;
  public Player Player => player; //<=pls add public Property
}
```

bcz i need player in **PropertyChanged**
```csharp
 private void Subtitles_PropertyChanged(object sender, PropertyChangedEventArgs e)
 {
var subtitles = sender as FlyleafLib.MediaPlayer.Subtitles;
//subtitles.Player
}
```
thank you

**Comment by insomniachi** [comment]
what are you trying to do.

**Comment by vzsoft** [comment]
> what are you trying to do.

I need to manage subtitles that are synchronized and I need the player time.
Sample SRT file:
`
1
00:00:01,000 --> 00:00:05,000
Subtitle1

2
00:00:01,024 --> 00:00:9,024
Subtitle2
`
