### ISSUE TITLE
Problem with Qualcomm Adreno GPU

### ISSUE THREAD

**Issue by Agostino44** [SuRGeoNix/Flyleaf#535]
Good morning,
we have a Surface with Qualcomm Adreno X1-85 Gpu, a secondary monitor connected with hdmi and the monitors are settings with extended.
Our app use flyleaf for reproduce a sequence of videos on one or more window at the same time placed on secondary monitor, meanwhile the main window is on the primary monitor.
After a few dozen minutes of playing the video sequence, it seems that the rendering is blocked and the whole UI thread is blocked, you can no longer interact and the only thing that can be done is to close the process from task manager.
On PC with NVidia or Intel GPU seems all ok.
Any suggestion?
Thanks,

**Comment by Agostino44** [comment]
I thought it was a GPU related problem because on other machines with different gpu the app runs correctly.

**Comment by SuRGeoNix** [comment]
Unfortunately I cannot help you. You will need to debug it yourself. Feel free to re-open this if you find more info related to Flyleaf.

**Comment by Agostino44** [comment]
I forgot to specify that this Surface version is ARM64-Based PC with Windows 11.
could this be the reason for the problem?

**Comment by SuRGeoNix** [comment]
It could be related but it's really difficult to guess without actual debugging.
