### ISSUE TITLE
Regarding making the Hardware Acceleration device optional

### ISSUE THREAD

**Issue by fatihbahceci** [SuRGeoNix/Flyleaf#536]
Hello,

In the project we are developing, there is a scenario where the Hardware Acceleration device needs to be configurable by the user.
For this reason, could you kindly add a setting to the Config class that allows us to select this option?

Thank you and best regards.

![002](https://github.com/user-attachments/assets/de1e4f8f-54d8-44d5-8f06-34028a20ad8c)
![003](https://github.com/user-attachments/assets/972aef67-2f16-4961-a2bd-6a98f28b2c98)
![004](https://github.com/user-attachments/assets/0f7887b0-b6c7-481b-9cc4-df1aaa69740e)

**Comment by SuRGeoNix** [comment]
You already have the Config.Video.VideoAcceleration

**Comment by fatihbahceci** [comment]
Yes. For example, I would like to be able to select options like CUDA or QuickSync as the acceleration type.
If I understand correctly, are you saying that selecting these options will not be compatible with Flyleaf?

**Comment by SuRGeoNix** [comment]
Yes, the hardware frames that are required for each hardware device need special/different treatment to be able to be rendered on a D3D11 surface. This already planned for v4 to support multiple OSes/HWDevices.
