### ISSUE TITLE
Application volume is always set to 100 (for Flyleaf and all other windows applications started when Flyleaf running)

### ISSUE THREAD

**Issue by Kelvinh95** [SuRGeoNix/Flyleaf#54]
**Describe the bug**
Originally found in Race Control( robvdpol/RaceControl#195 and robvdpol/RaceControl#196), traced back to Flyleaf.
This bug has two sides to it.
With Windows Volume Mixer you can set the volume level for each individual application.

Problem 1:
When you set Flyleaf's volume in the mixer to something and reopen Flyleaf, the volume is always set back to 100.

Problem 2:
When Flyleaf is open the above problem also occurs for **every** other application you open which uses the same sound source.
This only happens to applications which get start after Flyleaf was started, so applications which were already running do not get reset.

**To Reproduce**
1. Open an application, for this example Chrome
2. Play something with sound through Chrome so that Windows recognizes it as sound output in the volume mixer
3. Set the volume to something other than 100, for example to 30
4. Open Flyleaf 
5. Close Chrome
6. Open Chrome
7. Play something with sound again. 
8. The volume is now reset to 100 because Flyleaf is open and now controlling all new audio sessions

**Expected behavior**
The expected behaviour is that the default behaviour for set volumes for the different application in the volume mixer do not get affected by Flyleaf.

**Screenshots**
Start situation:
![image](https://user-images.githubusercontent.com/5929773/127742362-9889a0ba-9c62-48f2-b079-143f25c01b87.png)
After reproduction:
![image](https://user-images.githubusercontent.com/5929773/127742462-a1a48a2c-0cf5-42df-b862-1566e61726ed.png)

**Additional context**
Upon investigation in the code the problems occurs in AudioMaster.cs in the OnSessionCreated delegate:

https://github.com/SuRGeoNix/Flyleaf/blob/5981a5bc33fd38010a78619998114f6bbd52d4e2/FlyleafLib/AudioMaster.cs#L115-L123
Here the volume will always be set to 1 (100);
https://github.com/SuRGeoNix/Flyleaf/blob/5981a5bc33fd38010a78619998114f6bbd52d4e2/FlyleafLib/AudioMaster.cs#L120

Once Flyleaf is running every new audio session will be caught by NAudio. This causes problem 2.
You can test this by setting a breakpoint in the above function and starting a any new application (which uses audio) while it is debugging.

I feel like it is not necessary to set the volume here since the default volume for windows applications will be set to 100 anyway.

A different way to fix this is to not handle the audio events which are not coming from Flyleaf (or applications which implement Flyleaf), but I think not setting the volume to 1 is way simpler for now.

**Comment by SuRGeoNix** [comment]
Well nice catch, thanks! Fixed it based on the process id which is more accurate solution. Thanks! (By the way by default the application session volume will start from the previous state)

**Comment by Kelvinh95** [comment]
Seems to work like a charm now, thanks for the quick fix!

**Comment by SuRGeoNix** [comment]
As this is not urgent I will postpone it on v3.2 which will have a lot of changes.
