### ISSUE TITLE
How I can play video file from a certain starting time?

### ISSUE THREAD

**Issue by zydjohnHotmail** [SuRGeoNix/Flyleaf#56]
Hello:
I have one video file (C:\Videos\1.mp4), which has duration of 3 minutes.  I want to start play the video from 1 minute, so the total play time will be 2 minute.
Let me know how I can use your repo to do this? I mean I skip the first 1 minute video in the mp4 file?
Thanks,

**Comment by SuRGeoNix** [comment]
Yes, you can use Player.Seek(1000);

https://github.com/SuRGeoNix/Flyleaf/blob/master/FlyleafLib/MediaPlayer/Player.cs#L718
