### ISSUE TITLE
Can’t play video file in WinForm App for Windows 10 using the repo.

### ISSUE THREAD

**Issue by zydjohnHotmail** [SuRGeoNix/Flyleaf#57]
I have done the following in order to use your repo in C# WinForm project (target .NET 5.0)
Download and unzip ffmpeg full build file from this URL: 
https://www.gyan.dev/ffmpeg/builds/ffmpeg-release-full.7z
Copy the unzipped folder to C:\Program Files
Edit System PATH variable to add ffmpeg binary path.
Also copy the lib (all the *.DLL), and change project file to use the following target item:
<TargetFramework>net5.0-windows</TargetFramework>
I have installed nuget packages:
PM> Install-Package FFmpeg.AutoGen -Version 4.4.0
PM> Install-Package NAudio.Wasapi -Version 2.0.0
PM> Install-Package SharpDX.Mathematics -Version 4.2.0
PM> Install-Package FlyleafLib -Version 3.1.14
PM> Install-Package FlyleafLib.Controls.WPF -Version 1.1.4
Then in Form1 designer, open toolbox, and drag one Flyleaf (Flyleaflib.controls) to the Form1 designer.
The following is the code from Form1.designer.cs:

namespace FlyleafPlayerForm
{
    partial class Form1
    {
        /// <summary>
        ///  Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        ///  Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        ///  Required method for Designer support - do not modify
        ///  the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.flyleaf1 = new FlyleafLib.Controls.Flyleaf();
            this.SuspendLayout();
            // 
            // flyleaf1
            // 
            this.flyleaf1.BackColor = System.Drawing.Color.Black;
            this.flyleaf1.Location = new System.Drawing.Point(28, 12);
            this.flyleaf1.Name = "flyleaf1";
            this.flyleaf1.Size = new System.Drawing.Size(760, 465);
            this.flyleaf1.TabIndex = 0;
            // 
            // Form1
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(7F, 15F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(800, 503);
            this.Controls.Add(this.flyleaf1);
            this.Name = "Form1";
            this.Text = "Form1";
            this.Load += new System.EventHandler(this.Form1_Load);
            this.ResumeLayout(false);

        }

        #endregion

        private FlyleafLib.Controls.Flyleaf flyleaf1;
    }
}

The following is the C# code for Form1.cs:
using FlyleafLib;
using System;
using System.Windows.Forms;
using FlyleafLib.MediaPlayer;

namespace FlyleafPlayerForm
{
    public partial class Form1 : Form
    {
        public const string FFMPEG_Binary = @"C:\Program Files\ffmpeg-4.4-full_build\bin";
        public const string Video_File1 = @"C:\Videos\1.mp4";

        private static Player player1;

        public Form1()
        {
            InitializeComponent();
        }

        private void Form1_Load(object sender, EventArgs e)
        {
            Master.RegisterFFmpeg(FFMPEG_Binary);
            Config config = new();
            config.demuxer.VideoFormatOpt.Add("probesize", (50 * (long)1024 * 1024).ToString());
            config.demuxer.VideoFormatOpt.Add("analyzeduration", (10 * (long)1000 * 1000).ToString());
            player1 = new Player(config)
            {
                Control = flyleaf1
            };
            player1.Open(Video_File1);
            player1.Play();
        }
    }
}

I can compile my code, but when I run it, I saw only the black screen on the player, I can’t see any video file is being played.
Let me know if I made any mistake.
However, I can’t use WPF project, as there are many restrictions, one of which is difficult to use SQL server database, but I have to use SQL server database, as all the video file locations are stored in the database.
Please advise,
Thanks,

**Comment by SuRGeoNix** [comment]
Change player1.Play(); with player1.OpenCompleted += (o, x) => { if (x.success && x.type == MediaType.Video) player1.Play(); };

And please review the [samples](https://github.com/SuRGeoNix/Flyleaf/blob/master/WinForms%20Sample%20(Basic)/BasicNaked.cs) before you asking questions

**Comment by zydjohnHotmail** [comment]
Thanks for your quick reply.
It is now working. 
But I want to add two-way control to the player, like a seeker, which I can drag to quickly forward/backward the video to another time position.
Where I can find some code example for this?
Thanks,

**Comment by SuRGeoNix** [comment]
Check the flyleaf control (winforms) from v2.6 which is had a custom bar
