### ISSUE TITLE
The video cannot be played on a 32-bit computer, and the display is blank

### ISSUE THREAD

**Issue by 123sdfa** [SuRGeoNix/Flyleaf#61]
The video cannot be played on a 32-bit computer, and the display is blank, but it can be played normally on a 64-bit computer.
![sunlogin_20210812170904_看图王_看图王](https://user-images.githubusercontent.com/12029897/129171385-f40e741e-85a4-4f54-beff-af08f5f8e7a8.jpg)
![微信截图_20210812171131](https://user-images.githubusercontent.com/12029897/129171394-af3bcdd1-0328-4a0e-9fd2-bf340bda1018.png)

**Comment by 123sdfa** [comment]
Yes, x86 libs is already included. It's Windows 7.

发自我的iPhone

**Comment by SuRGeoNix** [comment]
I just re-tested on a Win7 box and it worked fine for me. I've added a x86 release so you can tested, just to make sure you are not doing anything wrong with the libs or something [flyleaf_x86](https://github.com/SuRGeoNix/Flyleaf/releases/download/v3.2.1/Flyleaf_v3.2.1_x86.7z)

**Comment by 123sdfa** [comment]
I tested flyleaf_x86 and the same problem still occurs.
![微信截图_20210813094101](https://user-images.githubusercontent.com/12029897/129293623-f108c0b5-5d8e-46c6-8570-aa0007c17544.png)
![微信截图_20210813094650](https://user-images.githubusercontent.com/12029897/129293630-2d124f5d-2144-439a-90e3-e75908e6ddb7.png)
![微信截图_20210813094736](https://user-images.githubusercontent.com/12029897/129293633-30ef2b01-63db-47a0-9e0e-8e9020b82622.png)
![微信截图_20210813094830](https://user-images.githubusercontent.com/12029897/129293635-a31ac131-204e-467e-b101-83e973d79969.png)

**Comment by SuRGeoNix** [comment]
Can you check also the following:

1) Event logs (Windows logs -> Application)
2) Run 'dxdiag' and take a screenshot for 'System' and 'Display' tabs.
3) Ensure you have a sound card on the system

Generally, that's an old system with old hardware. However, my test was in a Win 7 x64 so I will try to setup another x86 and tested again.

**Comment by 123sdfa** [comment]
Thank you for your reply, I checked the following:
1. I did not find any event logs in Windows logs -> Application
2. Please check DxDiag.txt
3. The computer has a sound card
[DxDiag.txt](https://github.com/SuRGeoNix/Flyleaf/files/6980172/DxDiag.txt)

**Comment by SuRGeoNix** [comment]
I can't find the features supported by your OS, eg:

```
Feature Levels: 12_0,11_1,11_0,10_1,10_0,9_3,9_2,9_1
```

This issues is not about x86/x64 platforms but about DirectX and GPU drivers. I would try to update GPU drivers, update windows and check if I could install an extra package for DirectX for Windows 7. 

(Send me also a screenshot from DxDiag display tab just to confirm that)

**Comment by SuRGeoNix** [comment]
Install this one https://www.microsoft.com/en-us/download/details.aspx?id=36805

**Comment by 123sdfa** [comment]
> Install this one https://www.microsoft.com/en-us/download/details.aspx?id=36805
The system prompts that I have installed KB2670838

**Comment by 123sdfa** [comment]
DirectX Version: DirectX 11
DX Setup Parameters: Not found
   User DPI Setting: Using System DPI
 System DPI Setting: 96 DPI (100 percent)
    DWM DPI Scaling: Disabled
     DxDiag Version: 6.01.7601.17514 32bit Unicode

**Comment by 123sdfa** [comment]
---------------
Display Devices
---------------
          Card name: Intel(R) HD Graphics
       Manufacturer: Intel Corporation
          Chip type: Intel(R) HD Graphics Family
           DAC type: Internal
         Device Key: Enum\PCI\VEN_8086&DEV_0152&SUBSYS_20108086&REV_09
     Display Memory: 1649 MB
   Dedicated Memory: 256 MB
      Shared Memory: 1393 MB
       Current Mode: 1366 x 768 (32 bit) (60Hz)
       Monitor Name: 通用即插即用监视器
      Monitor Model: 
         Monitor Id: MOR1950
        Native Mode: 1366 x 768(p) (59.790Hz)
        Output Type: HD15
        Driver Name: igdumd32.dll,igd10umd32.dll,igd10umd32.dll
Driver File Version: 9.17.0010.2932 (English)
     Driver Version: 9.17.10.2932
        DDI Version: 11
       Driver Model: WDDM 1.1
  Driver Attributes: Final Retail
   Driver Date/Size: 12/12/2012 16:41:38, 11049472 bytes
        WHQL Logo'd: Yes
    WHQL Date Stamp: 
  Device Identifier: {D7B78E66-4212-11CF-42E8-1A00B7C2C435}
          Vendor ID: 0x8086
          Device ID: 0x0152
          SubSys ID: 0x20108086
        Revision ID: 0x0009
 Driver Strong Name: oem12.inf:Intel.Mfg:iIVBD0:9.17.10.2932:pci\ven_8086&dev_0152
     Rank Of Driver: 00E02001
        Video Accel: ModeMPEG2_A ModeMPEG2_C ModeWMV9_C ModeVC1_C 
   Deinterlace Caps: {BF752EF6-8CC4-457A-BE1B-08BD1CAEEE9F}: Format(In/Out)=(YUY2,YUY2) Frames(Prev/Fwd/Back)=(0,0,1) Caps=VideoProcess_YUV2RGB VideoProcess_StretchX VideoProcess_StretchY VideoProcess_AlphaBlend DeinterlaceTech_EdgeFiltering 
                     {335AA36E-7884-43A4-9C91-7F87FAF3E37E}: Format(In/Out)=(YUY2,YUY2) Frames(Prev/Fwd/Back)=(0,0,0) Caps=VideoProcess_YUV2RGB VideoProcess_StretchX VideoProcess_StretchY VideoProcess_AlphaBlend DeinterlaceTech_BOBVerticalStretch 
                     {5A54A0C9-C7EC-4BD9-8EDE-F3C75DC4393B}: Format(In/Out)=(YUY2,YUY2) Frames(Prev/Fwd/Back)=(0,0,0) Caps=VideoProcess_YUV2RGB VideoProcess_StretchX VideoProcess_StretchY VideoProcess_AlphaBlend 
                     {BF752EF6-8CC4-457A-BE1B-08BD1CAEEE9F}: Format(In/Out)=(UYVY,YUY2) Frames(Prev/Fwd/Back)=(0,0,1) Caps=VideoProcess_YUV2RGB VideoProcess_StretchX VideoProcess_StretchY VideoProcess_AlphaBlend DeinterlaceTech_EdgeFiltering 
                     {335AA36E-7884-43A4-9C91-7F87FAF3E37E}: Format(In/Out)=(UYVY,YUY2) Frames(Prev/Fwd/Back)=(0,0,0) Caps=VideoProcess_YUV2RGB VideoProcess_StretchX VideoProcess_StretchY VideoProcess_AlphaBlend DeinterlaceTech_BOBVerticalStretch 
                     {5A54A0C9-C7EC-4BD9-8EDE-F3C75DC4393B}: Format(In/Out)=(UYVY,YUY2) Frames(Prev/Fwd/Back)=(0,0,0) Caps=VideoProcess_YUV2RGB VideoProcess_StretchX VideoProcess_StretchY VideoProcess_AlphaBlend 
                     {BF752EF6-8CC4-457A-BE1B-08BD1CAEEE9F}: Format(In/Out)=(YV12,YUY2) Frames(Prev/Fwd/Back)=(0,0,1) Caps=VideoProcess_YUV2RGB VideoProcess_StretchX VideoProcess_StretchY VideoProcess_AlphaBlend DeinterlaceTech_EdgeFiltering 
                     {335AA36E-7884-43A4-9C91-7F87FAF3E37E}: Format(In/Out)=(YV12,YUY2) Frames(Prev/Fwd/Back)=(0,0,0) Caps=VideoProcess_YUV2RGB VideoProcess_StretchX VideoProcess_StretchY VideoProcess_AlphaBlend DeinterlaceTech_BOBVerticalStretch 
                     {5A54A0C9-C7EC-4BD9-8EDE-F3C75DC4393B}: Format(In/Out)=(YV12,YUY2) Frames(Prev/Fwd/Back)=(0,0,0) Caps=VideoProcess_YUV2RGB VideoProcess_StretchX VideoProcess_StretchY VideoProcess_AlphaBlend 
                     {BF752EF6-8CC4-457A-BE1B-08BD1CAEEE9F}: Format(In/Out)=(NV12,YUY2) Frames(Prev/Fwd/Back)=(0,0,1) Caps=VideoProcess_YUV2RGB VideoProcess_StretchX VideoProcess_StretchY VideoProcess_AlphaBlend DeinterlaceTech_EdgeFiltering 
                     {335AA36E-7884-43A4-9C91-7F87FAF3E37E}: Format(In/Out)=(NV12,YUY2) Frames(Prev/Fwd/Back)=(0,0,0) Caps=VideoProcess_YUV2RGB VideoProcess_StretchX VideoProcess_StretchY VideoProcess_AlphaBlend DeinterlaceTech_BOBVerticalStretch 
                     {5A54A0C9-C7EC-4BD9-8EDE-F3C75DC4393B}: Format(In/Out)=(NV12,YUY2) Frames(Prev/Fwd/Back)=(0,0,0) Caps=VideoProcess_YUV2RGB VideoProcess_StretchX VideoProcess_StretchY VideoProcess_AlphaBlend 
                     {BF752EF6-8CC4-457A-BE1B-08BD1CAEEE9F}: Format(In/Out)=(IMC1,YUY2) Frames(Prev/Fwd/Back)=(0,0,1) Caps=VideoProcess_YUV2RGB VideoProcess_StretchX VideoProcess_StretchY VideoProcess_AlphaBlend DeinterlaceTech_EdgeFiltering 
                     {335AA36E-7884-43A4-9C91-7F87FAF3E37E}: Format(In/Out)=(IMC1,YUY2) Frames(Prev/Fwd/Back)=(0,0,0) Caps=VideoProcess_YUV2RGB VideoProcess_StretchX VideoProcess_StretchY VideoProcess_AlphaBlend DeinterlaceTech_BOBVerticalStretch 
                     {5A54A0C9-C7EC-4BD9-8EDE-F3C75DC4393B}: Format(In/Out)=(IMC1,YUY2) Frames(Prev/Fwd/Back)=(0,0,0) Caps=VideoProcess_YUV2RGB VideoProcess_StretchX VideoProcess_StretchY VideoProcess_AlphaBlend 
                     {BF752EF6-8CC4-457A-BE1B-08BD1CAEEE9F}: Format(In/Out)=(IMC2,YUY2) Frames(Prev/Fwd/Back)=(0,0,1) Caps=VideoProcess_YUV2RGB VideoProcess_StretchX VideoProcess_StretchY VideoProcess_AlphaBlend DeinterlaceTech_EdgeFiltering 
                     {335AA36E-7884-43A4-9C91-7F87FAF3E37E}: Format(In/Out)=(IMC2,YUY2) Frames(Prev/Fwd/Back)=(0,0,0) Caps=VideoProcess_YUV2RGB VideoProcess_StretchX VideoProcess_StretchY VideoProcess_AlphaBlend DeinterlaceTech_BOBVerticalStretch 
                     {5A54A0C9-C7EC-4BD9-8EDE-F3C75DC4393B}: Format(In/Out)=(IMC2,YUY2) Frames(Prev/Fwd/Back)=(0,0,0) Caps=VideoProcess_YUV2RGB VideoProcess_StretchX VideoProcess_StretchY VideoProcess_AlphaBlend 
                     {BF752EF6-8CC4-457A-BE1B-08BD1CAEEE9F}: Format(In/Out)=(IMC3,YUY2) Frames(Prev/Fwd/Back)=(0,0,1) Caps=VideoProcess_YUV2RGB VideoProcess_StretchX VideoProcess_StretchY VideoProcess_AlphaBlend DeinterlaceTech_EdgeFiltering 
                     {335AA36E-7884-43A4-9C91-7F87FAF3E37E}: Format(In/Out)=(IMC3,YUY2) Frames(Prev/Fwd/Back)=(0,0,0) Caps=VideoProcess_YUV2RGB VideoProcess_StretchX VideoProcess_StretchY VideoProcess_AlphaBlend DeinterlaceTech_BOBVerticalStretch 
                     {5A54A0C9-C7EC-4BD9-8EDE-F3C75DC4393B}: Format(In/Out)=(IMC3,YUY2) Frames(Prev/Fwd/Back)=(0,0,0) Caps=VideoProcess_YUV2RGB VideoProcess_StretchX VideoProcess_StretchY VideoProcess_AlphaBlend 
                     {BF752EF6-8CC4-457A-BE1B-08BD1CAEEE9F}: Format(In/Out)=(IMC4,YUY2) Frames(Prev/Fwd/Back)=(0,0,1) Caps=VideoProcess_YUV2RGB VideoProcess_StretchX VideoProcess_StretchY VideoProcess_AlphaBlend DeinterlaceTech_EdgeFiltering 
                     {335AA36E-7884-43A4-9C91-7F87FAF3E37E}: Format(In/Out)=(IMC4,YUY2) Frames(Prev/Fwd/Back)=(0,0,0) Caps=VideoProcess_YUV2RGB VideoProcess_StretchX VideoProcess_StretchY VideoProcess_AlphaBlend DeinterlaceTech_BOBVerticalStretch 
                     {5A54A0C9-C7EC-4BD9-8EDE-F3C75DC4393B}: Format(In/Out)=(IMC4,YUY2) Frames(Prev/Fwd/Back)=(0,0,0) Caps=VideoProcess_YUV2RGB VideoProcess_StretchX VideoProcess_StretchY VideoProcess_AlphaBlend 
       D3D9 Overlay: Supported
            DXVA-HD: Supported
       DDraw Status: Enabled
         D3D Status: Enabled
         AGP Status: Enabled

**Comment by 123sdfa** [comment]
I upgraded the graphics driver and it now shows black, but it still doesn't play video.
[DxDiag.txt](https://github.com/SuRGeoNix/Flyleaf/files/6981190/DxDiag.txt)
![微信截图_20210813164857](https://user-images.githubusercontent.com/12029897/129331593-3c944d66-ca6a-4347-88db-7db8dde7072a.png)
![微信截图_20210813165059](https://user-images.githubusercontent.com/12029897/129331607-35b5fb5e-66de-4f85-98d2-846b618c74d2.png)

**Comment by SuRGeoNix** [comment]
Try to turn off hardware acceleration from flyleaf's settings

**Comment by 123sdfa** [comment]
I can play video after turning off hardware acceleration!
What is the problem? How can I turn off hardware acceleration in my project?
![微信截图_20210813170120](https://user-images.githubusercontent.com/12029897/129333116-9157c98c-b25b-4ea3-a839-046662656054.png)

**Comment by SuRGeoNix** [comment]
You have an old system (OS/hardware). You can set it to the Flyleaf's config before initializing with:

```
Config config = new Config();
config.decoder.HWAcceleration = false;
Player = new Player(config);
```

**Comment by 123sdfa** [comment]
How to judge whether the computer supports hardware acceleration?

**Comment by SuRGeoNix** [comment]
Generally, you could retrieve this information by opening an input and check whether player.decoder.VideoDecoder.VideoAccelerated is true or false. But in your case, the issue is deeper and I'm not sure if you could catch this somehow.

**Comment by 123sdfa** [comment]
Ok, thank you for your help!
