### ISSUE TITLE
For new version of Flyleaf DemuxerBase class is gone, how I can write a wrapper class?

### ISSUE THREAD

**Issue by zydjohnHotmail** [SuRGeoNix/Flyleaf#62]
Hello:
For previous release of Flyleaf package (3.1.16), I can write a class library, so I can pass a unique number uniq_id to make a unique instance for HLS download.  Like this: (C# target .NET 5.0)

using FlyleafLib;
using FlyleafLib.MediaFramework.MediaDemuxer;
using System.Diagnostics;

namespace FlyleafHLSDownloader
{
    public class Class1
    {
        public const string FFMPEG_Binary = @"C:\Program Files\ffmpeg-4.4-full_build\bin";
        public static DemuxerBase FlyleafLoader(int uniq_id, string url1, string video_file1)
        {
            Master.RegisterFFmpeg(FFMPEG_Binary);
            DemuxerBase Downloader1 = new VideoDemuxer(new Config(), uniq_id);
            if (Downloader1.Open(url1) != 0)
            {
                Debug.Print("Could not open url input");
                return null;
            }
            Downloader1.EnableStream(Downloader1.VideoStreams[0]);
            if (Downloader1.AudioStreams.Count != 0)
                Downloader1.EnableStream(Downloader1.AudioStreams[0]);
            Downloader1.Download(video_file1);
            return Downloader1;
        }
    }
}

But I found Flyleaf has released a new version 3.2.2, so I tried to use the new package, but my above code can’t get compiled, as there is no  FlyleafLib.MediaFramework.MediaDemuxer. DemuxerBase class any more.
Please advise, if I want to use new release 3.2.2 of Flyleaf, how I can rewrite my class library, so I can assign a unique-id to the downloader?
Thanks,

**Comment by SuRGeoNix** [comment]
Use the new Downloader class instead.

```
using FlyleafLib.MediaFramework.MediaContext;

...

Downloader Downloader1 = new Downloader(new Config().demuxer, uniq_id);
            if (Downloader1.Open(url1) != 0)
            {
            Debug.Print("Could not open url input");
            return null;
            }
            Downloader1.Demuxer.EnableStream(Downloader1.Demuxer.VideoStreams[0]);
            if (Downloader1.Demuxer.AudioStreams.Count != 0)
            Downloader1.Demuxer.EnableStream(Downloader1.Demuxer.AudioStreams[0]);
            Downloader1.Download(video_file1);
            return Downloader1;
            }
```
