### ISSUE TITLE
I took a snapshot, but the result is a transparent picture.

### ISSUE THREAD

**Issue by 123sdfa** [SuRGeoNix/Flyleaf#63]
I took a snapshot, but the result is a transparent picture. How can I solve this problem?
![微信截图_20210814112434](https://user-images.githubusercontent.com/12029897/129432854-4eacb339-995b-496f-82e1-b7774fd75780.png)
![微信截图_20210814113302](https://user-images.githubusercontent.com/12029897/129432879-d46976b7-d1a5-42de-835b-a69cdc56875a.png)
![微信截图_20210814113141](https://user-images.githubusercontent.com/12029897/129432883-6029c0a5-8da0-4fdd-81e6-8885b296c3fc.png)

**Comment by SuRGeoNix** [comment]
Yes, if you check my last commit I have already fixed it. I will have an updated package soon

**Comment by SuRGeoNix** [comment]
I've created a v3.2.3 package with the fix and some improvements for the export frames.

**Comment by 123sdfa** [comment]
Thank you very much!
