### ISSUE TITLE
When I play the RTSP real-time stream and then record, there will be a crash

### ISSUE THREAD

**Issue by 123sdfa** [SuRGeoNix/Flyleaf#64]
![微信图片_20210814134520](https://user-images.githubusercontent.com/12029897/129435651-a908cc7b-c011-49c8-a2e0-803f8b071596.png)
Exception information: System.AccessViolationException
   In FFmpeg.AutoGen.ffmpeg+<>c.<.cctor>b__6_282(FFmpeg.AutoGen.AVFormatContext*, FFmpeg.AutoGen.AVPacket*)
   In FFmpeg.AutoGen.ffmpeg.av_interleaved_write_frame(FFmpeg.AutoGen.AVFormatContext*, FFmpeg.AutoGen.AVPacket*)
   In FlyleafLib.MediaFramework.MediaRemuxer.Remuxer.Write(FFmpeg.AutoGen.AVPacket*)
   In FlyleafLib.MediaFramework.MediaDemuxer.Demuxer.RunInternal()
   In FlyleafLib.MediaFramework.RunThreadBase.Run()
   In FlyleafLib.MediaFramework.RunThreadBase.<Start>b__21_0()
   In System.Threading.ThreadHelper.ThreadStart_Context(System.Object)
   In System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   In System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   In System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   In System.Threading.ThreadHelper.ThreadStart()
![微信截图_20210814135333](https://user-images.githubusercontent.com/12029897/129435656-f26f9771-d78e-4c2d-aeb7-94f3453f6df1.png)

**Comment by SuRGeoNix** [comment]
Probably there is an issue with one of the embedded streams. I would guess Audio. Try to disable audio and see if that happens.

**Comment by 123sdfa** [comment]
I have turned off the audio and the same problem still occurs.
![微信截图_20210814141544](https://user-images.githubusercontent.com/12029897/129436114-845136fb-c040-46ae-8b88-941961919143.png)

**Comment by SuRGeoNix** [comment]
Are you doing anything else except playing the stream in the background?
Does it happens as you press Record or after sometime?
Can you provide the RTSP url for debugging (drop an email surgeonix@gmail.com and you change the password after sometime)?

**Comment by 123sdfa** [comment]
I didn't do anything else while playing the stream.
It crashes when I press record.
I have sent the RTSP URL to your mailbox.

**Comment by SuRGeoNix** [comment]
Nice I'm looking at it. It seems like a bug, not sure why yet...

**Comment by SuRGeoNix** [comment]
Actually, I was right. Is the audio. If you disable it it works.

**Comment by 123sdfa** [comment]
Can this problem be solved with the audio turned on?

**Comment by SuRGeoNix** [comment]
OK I thought that actually wasn't any audio but it is. So there is a problem with the remuxer.

**Comment by 123sdfa** [comment]
Will you fix this problem?

**Comment by SuRGeoNix** [comment]
Yes, I will try at least but if it requires a lot of time I will have a look at the next release. The error comes from ffmpeg libraries:-

```
Could not find tag for codec pcm_mulaw in stream #1, codec not currently supported in container
```

**Comment by 123sdfa** [comment]
Okay, the link will always be accessible, thank you.

**Comment by SuRGeoNix** [comment]
There is a fix that might is good enough for you until I will look deeper in too that. It seems that the problem is the incompatibility between the format (.mp4) and the audio codec (pcm_mulaw). So if you just change the Record to save the file as .avi it will work.

**Comment by 123sdfa** [comment]
OK, I'll test it.
