### ISSUE TITLE
How to use FlyleafLib.Config() for new version of FlyleafLib?

### ISSUE THREAD

**Issue by zydjohnHotmail** [SuRGeoNix/Flyleaf#65]
Hello:
For previous version of Flyleaf 3.1.14, I can write the following C# code to use config():
Config config = new();
config.demuxer.VideoFormatOpt.Add("probesize", (50 * (long)1024 * 1024).ToString());
config.demuxer.VideoFormatOpt.Add("analyzeduration", (10 * (long)1000 * 1000).ToString());
FLPlayer1 = new Player(config)
{
    Control = flyleaf1
};

Since there is a new version of Flyleaf: version 3.2.4, my above code did NOT work.
Please advise, how I can use FlyleafLib.Config()?

**Comment by SuRGeoNix** [comment]
VideoFormatOpt changed to global FormatOpt. Please check the [samples](https://github.com/SuRGeoNix/Flyleaf/blob/master/Wpf%20Samples/Sample1_Basic.xaml.cs) before you ask
