### ISSUE TITLE
Adding More Buffering Configuration

### ISSUE THREAD

**Issue by ghaith100994** [SuRGeoNix/Flyleaf#66]
1- Add Status Buffering That Raise When Player Status is Playing and The Movie is not Playing because MinQueueSize is > 0
2- Add a property that return how many second of the movie is being buffered for stream
3- When I seek current time + 5 second forward buffer is being clear even thought VideoDemuxer.VideoPackets.Count is more than 3000 
I think 3000 mean more than 5 second

**Comment by SuRGeoNix** [comment]
Hey, nice suggestions.

1- So you want an event to know when it actually plays and when it is buffering?
2- I have this in mind and probably I will included at the next updated
3- This requires a lot of effort to seek within the current packets queue. But its in my plans, just not yet :(

**Comment by ghaith100994** [comment]
yes and I think Adding that to Player status as enum value will be better

**Comment by SuRGeoNix** [comment]
1 - I've added the Player.IsBuffering but not sure yet if it should raise property change event (trying to avoid to many notification changes)
2 - I've added the BufferedDuration on the demuxers (you can get it from Player.VideoDemuxer.BufferedDuration)
3 - Hopefully at the next update

**Comment by ghaith100994** [comment]
In Buffering When I Pause Video Should Player Continue Buffering 
if it is true (BufferedDuration) Doesn't Fired Property Changed 
if it is false Why is that??

**Comment by SuRGeoNix** [comment]
Yep, I've noticed those I have an update already, I will review it and commit it

**Comment by SuRGeoNix** [comment]
@ghaith100994 As I have added a lot of code lately I will need to re-code and clean-up events/property changed etc. As the Player tries to be also a ViewModel it should invoke the UI properly when it requires which is not clear to me when it should do that yet (performance wise). The other problem is that when the Player is not running, there is no thread that could refresh the UI (eg. for buffered duration).

I will review all those at the next update. Any suggestions more than welcome. (I might decide to remove all the UI invokes from the Player and it will be the applications responsibility to do it)

**Comment by SuRGeoNix** [comment]
I will probably split the ViewModel also in the demuxers/decoders in a way that each thread(Play,Demuxer,Decode) will refresh whatever it is required in the UI every second. Player's buffering is different from Demuxer's buffering which means that requires different events/properties.
