### ISSUE TITLE
How do I close the Player?

### ISSUE THREAD

**Issue by 123sdfa** [SuRGeoNix/Flyleaf#67]
I have called player.Stop() after the first play, but it will automatically pause when I play the second time. Why? I have called player.Play(). How do I close the Player?
The previous RTSP URL is still available, you can use it to test.

**Comment by SuRGeoNix** [comment]
Player.Stop() will close the current input so you will have to re-open the player with Player.Open(). If you want to dispose it use Player.Dispose(). Not sure what to test?

**Comment by 123sdfa** [comment]
I have stopped, then re-open a new rtsp url and play it, but it will be automatically paused soon.

> 在 2021年8月16日，19:02，John Stamatakis ***@***.***> 写道：
> 
> Player.Stop() will close the current input so you will have to re-open the player with Player.Open(). If you want to dispose it use Player.Dispose(). Not sure what to test?

**Comment by SuRGeoNix** [comment]
It seems that you misuse the Player_OpenCompleted(). Provide some code to make sure.

Probably you call Stop/Open within the event and you call it more than once (or when you actually want)

**Comment by 123sdfa** [comment]
https://user-images.githubusercontent.com/12029897/129652271-0f82ed2a-7671-4dd0-8b00-48971e9f48bd.mp4

    public partial class Form1 : Form, INotifyPropertyChanged
    {
        Player player;

        public event PropertyChangedEventHandler PropertyChanged;

        public void OnPropertyChanged(string propertyName)
        {
            PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
        }

        public Form1()
        {
            InitializeComponent();
        }

        private void Form1_Load(object sender, EventArgs e)
        {
            Master.RegisterFFmpeg(":2");
            player = new Player();
            player.Control = flyleaf;
            if (!player.decoder.VideoDecoder.VideoAccelerated)
            {
                player.Config.decoder.HWAcceleration = false;
            }
            player.OpenCompleted += Player_OpenCompleted;
        }

        private void btnPlay_Click(object sender, EventArgs e)
        {
            player.Open(txtRtspUrl.Text);
        }

        private void Player_OpenCompleted(object sender, Player.OpenCompletedArgs e)
        {
            if (e.success && e.type == MediaType.Video)
            {
                player.Play();
            }
            OnPropertyChanged(null);
        }

        private void btnStop_Click(object sender, EventArgs e)
        {
            player.Stop();
        }
    }

**Comment by SuRGeoNix** [comment]
I was able to reproduce it. It happens only with rtsp urls and only on .NET Framework

**Comment by 123sdfa** [comment]
The same problem occurs when 64-bit.

**Comment by SuRGeoNix** [comment]
Yes true. it's an integer (long) overflow. .NET 5 seems to have some kind of protection for that but .NET framework doesn't. The crashing line:

```
Math.Abs(Int64.MinValue);
```

**Comment by 123sdfa** [comment]
Are you updating and fixing this problem?

**Comment by SuRGeoNix** [comment]
Well it should be fixed in v3.2.5.  If not let me know! Nice finding!

**Comment by 123sdfa** [comment]
The problem has been solved, thank you very much!
