### ISSUE TITLE
For Flyleaf version 3.2.4, when playing video file, always get NullReferenceException Exception.

### ISSUE THREAD

**Issue by zydjohnHotmail** [SuRGeoNix/Flyleaf#68]
Hello:
When I used the previous version 3.1.14, I can play videos without any issue.  But as Flyleaf has new version 3.2.4, so I want to try for the new version.
I created one WinForms App project, target .NET 5.0.
I installed the following nuget packages:
PM> Install-Package FlyleafLib -Version 3.2.4
PM> Install-Package FlyleafLib.Controls.WPF -Version 1.1.6
I also copied all those .DLLs(from Flyleaf-master\Libs\x86 folder)
On Form1 designer, drag and drop one Flyleaf (FlyleafLib.Controls) control on Form1 designer.
The following is my C# code:

using FlyleafLib;
using FlyleafLib.MediaPlayer;
using System;
using System.Diagnostics;
using System.Windows.Forms;

namespace Flyleaf324PlayVideoForm
{
    public partial class Form1 : Form
    {
        public const string FFMPEG_Binary = @"C:\Program Files\ffmpeg-4.4-full_build\bin";
        private static Player? FLPlayer1;

        public Form1()
        {
            InitializeComponent();
        }

        private void Form1_Load(object sender, EventArgs e)
        {
            try
            {
                Master.RegisterFFmpeg(FFMPEG_Binary);
                Config config = new();
                config.demuxer.FormatOpt.Add("probesize", (50 * (long)1024 * 1024).ToString());
                config.demuxer.FormatOpt.Add("analyzeduration", (10 * (long)1000 * 1000).ToString());
                FLPlayer1 = new Player(config);
                FLPlayer1.Open(@"C:\Videos\1.mp4");
                FLPlayer1.OpenCompleted += (o, x) =>
                { if (x.success && x.type == MediaType.Video) FLPlayer1.Play(); };
            }
            catch (NullReferenceException ex)
            {
                Debug.Print(ex.Message);
            }
        }
    }
}
Note: I can only register Ffmpeg with the path to Ffmepg binary, the others, like: 
Master.RegisterFFmpeg(":1") or Master.RegisterFFmpeg(":2")
They didn’t work, when run, I got error: Can’t register FFMEPG.

The similar code works for previous version (3.1.14).

In order to investigate further, I also downloaded GitHub repo source code, and unzip it, and load it with Visual Studio 2019 (version 16.11.0).
I found there are total 7 projects inside the solution, if I set up “Wpf Samples” project as the start up project, everything is working.
But if I set up “WinForms Sample (Basic)” as the start up project, then I can compile the project, however, when I run it, I got the following error.
Look at the picture.
![FlyleafWinFormsBasicNOK](https://user-images.githubusercontent.com/45263518/129548386-8f247e3a-971a-4f34-869f-1083acadac08.png)
I think there is some bug for the new version, please check, and let me know how to change my code, so I can play a MP4 local video file.
Due to SQL Server database requirement, I can’t use WPF project, I can only use WinForms project.

**Comment by SuRGeoNix** [comment]
You just need to build the WinForms Sample because it is not included by default. If you want to included right click on Solution 'FlyleafLib' -> Select Configuration Manager... -> Check the build for Winforms project

**Comment by zydjohnHotmail** [comment]
Hello:
I have done what you said, but if you look at the picture, I am rather sure that is NOT winforms window, it is WPF window.
Can I have a pure winforms window?
See the picture:
![RunWinFormsBasicFlyleaf324](https://user-images.githubusercontent.com/45263518/129573935-08d297cc-c570-4e8b-8d17-142a8f02f372.png)

**Comment by SuRGeoNix** [comment]
Just in Program.cs comment/uncomment the following lines

```
Application.Run(new BasicNaked());
//Application.Run(new TestingWPFwithinWinForms());
```

Except if you mean instead of .NET 5 to use .NET framework
