### ISSUE TITLE
Do you have documents ?

### ISSUE THREAD

**Issue by sornanun** [SuRGeoNix/Flyleaf#70]
First, Thanks for very good media player library.

I test open 4K video from you WPF Sample its working perfectly with low Ram usage.

I try to run Winforms.Sample (Basic) on visual studio but popup show error message debug profile does not exists.

![22](https://user-images.githubusercontent.com/10648713/129714019-d63cbc3c-97b5-42b5-ba02-bdf4a7b0681f.PNG)

And I want to use your library to my project but there are many things I don't know how to use it.
Do you have any documents?

**Comment by SuRGeoNix** [comment]
Hey, thanks! Unfortunately, there is no documentation yet, just the samples. But the purpose of the next update will be to be ready to documented. Your error is my mistake, I will update the solution to include by default also winforms.

Right click on Solution 'FlyleafLib' -> Select Configuration Manager... -> Check the build for Winforms project

**Comment by sornanun** [comment]
Thanks again [SuRGeoNix](https://github.com/SuRGeoNix) for good and fast reply.

I changed all build platform to x64 and ticked the check box of build Winform Sample (Basic) it working now.

![acb](https://user-images.githubusercontent.com/10648713/129757471-0e8250ab-ed8b-4528-9541-72c6eef1b36b.png)

I will look forward for new update with documentation. 
Have a good day :)
