### ISSUE TITLE
How to play video at 2x, 3x, ...16x speed ?

### ISSUE THREAD

**Issue by lenhatvu** [SuRGeoNix/Flyleaf#8]
Hi,

can i modify your code to play video at higher speed ?

**Comment by SuRGeoNix** [comment]
Yep, that should be fun xD

Change the following :-

1) MediaDecoder.cs at SetupVideo()
vStreamInfo.timebaseLowTicks    = (av_q2d(vStream->time_base) * 10000 * 1000) / 4;

2) MediaRouter.cs at Queues Declaration set Video Queues to...
int VIDEO_MIX_QUEUE_SIZE =  64;  int VIDEO_MAX_QUEUE_SIZE =  66;

**Comment by lenhatvu** [comment]
I tried it but your way but seem the player will pause -> seek-> play in continuous.
It's not good as MediaPlayer classic or VLC.

**Comment by SuRGeoNix** [comment]
Probably you didn't grow the queues large enough so it was restarting (you should also check the decoder threads). In any case, I didn't code it for it so i dont really mind if it doesnt work. As far from the comparison with MediaPlayer classic especially, it was really out of reality!

Next version is coming with single format context (instead from 3 different now) and i'm re-coding MediaRouter and MediaDecoder, it's already 3-4 times faster (especially at seeking). It's also ready to support hd & live streams etc. (Hopefully, I will finish in the next few days)
