### ISSUE TITLE
Need More Events for Player

### ISSUE THREAD

**Issue by ghaith100994** [SuRGeoNix/Flyleaf#80]
1- OnPlayerOpenFailed (When Player Try to Open Stream and Stream not found or host not found ....)
2- OnPlayerBufferingStarted  (When Player startBuffering ....)
3- OnPlayerBufferingEnded  (When Player endBuffering ....)
4- OnPlayerStreamFailed (When Player is streaming and internet connection stopped  )note: now when this happened PlaybackCompleted is raised

**Comment by SuRGeoNix** [comment]
1- OpenCompleted/OpenInputCompleted/OpenStreamCompleted will inform you also for failure not only for success and they will have an error message as well (e.Error)

2/3- If I remember right you've mention that before and I've added the Player.IsBuffering but it doesn't raises propertychange. Might would be wrong be design if you wanted to raise an event? I mean imagine when you seek it will change all the time from bufferingStarted to bufferingEnded. What is the point? Let me know if you really need a raise here.

4- I could see if I can add an event that fires when the player Stops without proper End or without action by user (pause/stop) and as you said now you already have Status and PlaybackCompleted that fires but you have to check by your own what went wrong (eg. internet connection failure)

**Comment by SuRGeoNix** [comment]
Closing this as duplicate to #66 and I will review it on the next update.

**Comment by SuRGeoNix** [comment]
As I've closed #66 I will re-open this to review mainly the buffering/disconnection events

**Comment by swimfish09** [comment]
onPositionChange

**Comment by SuRGeoNix** [comment]
@swimfish09 
onPlayerPositionChanged is the property changed of Player.CurTime
onPlayerStateChanged is the property changed of Player.Status
