### ISSUE TITLE
Can’t play video (MP4) format file in new version of the library.

### ISSUE THREAD

**Issue by zydjohnHotmail** [SuRGeoNix/Flyleaf#81]
Hello:
I had some C# code working for the old version of FlyLeaf library. (Tested for version 3.1.14, it is OK). 
But the similar code is not working in new version of FlyLeaf library. (Now version is 3.3.1).
I created one WinForm App project target .net 5.0, and install nuget package:
PM> Install-Package FlyleafLib -Version 3.3.1

The following is my C# code:

`using FlyleafLib;
using FlyleafLib.MediaPlayer;
using System;
using System.Windows.Forms;

namespace FlyleafPlayVideoForm
{
    public partial class Form1 : Form
    {
        public const string FFMPEG_Binary =
            @"C:\Program Files\ffmpeg-2021-08-25-full_build\bin";
        private static Player FLPlayer1;

        public Form1()
        {
            InitializeComponent();
        }

        private void Form1_Load(object sender, EventArgs e)
        {
            Master.RegisterFFmpeg(FFMPEG_Binary);
            Config config1 = new Config();
            config1.Demuxer.FormatOpt.Add("probesize", (50 * (long)1024 * 1024).ToString());
            config1.Demuxer.FormatOpt.Add("analyzeduration", (10 * (long)1000 * 1000).ToString());
            config1.Demuxer.BufferDuration = 99999999999999;    
            config1.Demuxer.ReadTimeout = 60 * 1000 * 10000; 
            config1.Video.MaxVerticalResolutionCustom = 1080; 
            FLPlayer1 = new Player(config1)
            {
                Control = flyleaf1
            };
            FLPlayer1.Open(@"C:\Videos\1.mp4");
            FLPlayer1.OpenCompleted += (o, x) =>
            {
                var show_success = x.Success;
                if (x.Success && x.Type == MediaType.Video) FLPlayer1.Play(); };
        }
    }
}
`

From my testing, I can compile my code, but when I ran it. The code never hit inside the 
FLPlayer1.OpenCompleted += (o, x) =>
For example, I added a simple test:
var show_success = x.Success;
This statement has never been hit.
Please advise what is wrong with my code?
In the Form Designer, I simply drag and drop one flyleaf control on the Form1 window.
No other GUI controls on the Form1 window.
By the way, I can’t use Master.RegisterFFmpeg(":2"); but Master.RegisterFFmpeg(FFMPEG_Binary) works.
I also copied all the .DLL from Flyleaf’s lib folder to FFMPEG_Binary.
Thanks,

**Comment by SuRGeoNix** [comment]
@zydjohnHotmail you ask too many questions that are not related with the library but the basics about programming.

1) You should register to an event before it actually calls (FLPlayer1.Open(@"C:\Videos\1.mp4"); must after FLPlayer1.OpenCompleted += (o, x) ... )

2) FLPlayer1.Open is blocking probably you wanted to use FLPlayer1.OpenAsync
