### ISSUE TITLE
Play non-seekable memory stream

### ISSUE THREAD

**Issue by GTANAdam** [SuRGeoNix/Flyleaf#85]
I'm lacking some understanding on how I could possibly have flyleaf render my fragmented stream coming from a stream of byte arrays, it constantly seems to have a duration which is against what I would like to achieve

**Comment by SuRGeoNix** [comment]
Try to explain more what you want to do so I can help you out. I'm using custom stream inputs to perform torrent streaming with part files. Not sure what you are trying to implement and what is the problem with the duration?

**Comment by GTANAdam** [comment]
> Try to explain more what you want to do so I can help you out. I'm using custom stream inputs to perform torrent streaming with part files. Not sure what you are trying to implement and what is the problem with the duration?
> 
> FFmpeg will read your custom stream and it needs to be valid (identify the format, streams etc.). Additionally, currently requires to be seekable you might though pass options/flags to the demuxer and customize it for your needs.

I'm trying to read MPEG4 encoded (header at the start and fragmented) of a continuously streaming screen capture.

Desktop Duplication/GDI Grab -> MF/FFMPEG Encoding: Data Output -> Custom Network Protocol -> FFMPEG Decoding and rendering

Currently, providing the memorystream to the player via "Open" and they "Play" would copy the received segment and be done with it instead of continuously reading the newly received data. I'm kinda confused at the moment at how this should be implemented on C#, on C++ it would be just a pointer and a loop. 

Any hints or samples would be greatly appreciated!

**Comment by SuRGeoNix** [comment]
So, currently the problem is that the demuxer/decoder will end/stop, right? And if that the issue, does it stop because it reaches the end (duration) or because it doesn't have frames and fails?

I would try to use the low latency screaming (with Config.Player.Usage = Usage.LowLatencyVideo) which is mainly for live rtsp cameras. Otherwise I could implement a new screamer method just for that. I was even thinking to make screaming pluggable for cases like that.

**Comment by SuRGeoNix** [comment]
When you say 'Custom Network Protocol' what do you mean? How does ffmpeg will know how to demux the network format?

**Comment by GTANAdam** [comment]
> When you say 'Custom Network Protocol' what do you mean? How does ffmpeg will know how to demux the network format?

Well, the custom network protocol can be http or even udp via enet, basically any means of data transport. the goal isn't to use a custom protocol for ffmpeg, the goal is to have flyleaf a constant feed of byte arrays and render.

> set the duration to 0 it should work with the current implementation. But it is up to you to set up the input format container.

Okay, that's interesting, I'll try setting duration to 0, hopefully that works out of the box.

> One more question for your design... Why would you encode and then decode the frame? Wouldn't be better to directly render the picture?

That was basically a sum up, as for real world application, the encoding to mpeg4 acts as a compression algorithm which saves bandwidth for network constrained devices.

**Comment by SuRGeoNix** [comment]
Well, you might need to clarify the format container and flags that you need to pass to the demuxer. For the format container mp4 might is not ideal for the case. What about HLS protocol with segments? Check it out and let me know if I can help any how ;)
