### ISSUE TITLE
How can I get each one frame from the video?

### ISSUE THREAD

**Issue by EjiHuang** [SuRGeoNix/Flyleaf#86]
Flyleaf is very good video control. I want to use opencv with flyleaf. But I don't know how to get each one frame from the video or rtsp stream. Is there a video frame callback event? But I can't find it. Can you help me? Thank you~

**Comment by SuRGeoNix** [comment]
Hi @EjiHuang,

Have a look at [FlyleafExtractor Sample](https://github.com/SuRGeoNix/Flyleaf/tree/master/Samples/FlyleafExtractor%20(WinForms)) it has everything you need.

Similarly you will need a DecoderContext that contains the demuxers/decoders and mainly the video decoder:

```csharp
public Config           Config          { get; set; }
public DecoderContext   DecCtx          { get; set; }
public VideoDecoder     VideoDecoder    => DecCtx.VideoDecoder;
```

You will not have an notification about each frame as the demuxer/decoder can run faster if you want. you will have all the decoded frames in the video decoder and you have to decide how you will get them.

Within the Extractor Sample I just use a while loop until I will have all the required frames:

```csharp
while (curFrameNumber <= end && (VideoDecoder.IsRunning || VideoDecoder.Frames.Count != 0))
{
	if (VideoDecoder.Frames.Count == 0) { Thread.Sleep(20); continue; }

	VideoDecoder.Frames.TryDequeue(out VideoFrame frame);
	SaveFrame(frame, curFrameNumber);
	curFrameNumber += step;
}
```
Give it a try and let me know if you need more help.

**Comment by EjiHuang** [comment]
Sorry, I only saw some samples about wpf. 
And, thank you for your help, I will try this.

**Comment by SuRGeoNix** [comment]
No problem. Feel free to ask if you want some clarification!

**Comment by EjiHuang** [comment]
``` c#

**Comment by EjiHuang** [comment]
``` csharp
public MainViewModel()
{
    Master.RegisterFFmpeg(":2");
    config = new Config();
    config.Demuxer.FormatOpt.Add("probesize", (50 * (long)1024 * 1024).ToString());
    config.Demuxer.FormatOpt.Add("analyzeduration", (10 * (long)1000 * 1000).ToString());
    
    DecCtx = new DecoderContext(config);
}
```

``` csharp
public RelayCommand PlayCommand
    => new RelayCommand(async _ =>
    {
        var result = DecCtx.OpenVideo(url, defaultAudio: false, defaultSubtitles: false);
    
        if (!result.Success)
        {
            MessageBox.Show($"{result.Error}", "Open Error", MessageBoxButton.OK, MessageBoxImage.Error);
            return;
        }
    
        if (DecCtx.VideoStream == null)
        {
            MessageBox.Show($"Cannot find video or calculate.", "Open Error", MessageBoxButton.OK, MessageBoxImage.Error);
            return;
        }
    
        DecCtx.Start();
        isClose = false;
    
        while (VideoDecoder.IsRunning || VideoDecoder.Frames.Count != 0)
        {
            VideoDecoder.Frames.TryDequeue(out VideoFrame frame);
            using Bitmap bmp = VideoDecoder.Renderer.GetBitmap(frame);
    
            if (bmp == null)
            {
                await Task.Delay(1);
                if (isClose) break;
                continue;
            }
    
            // Do opencv function with bitmap.
            // ...
    
            // Show with WriteableBitmap.
            if (RealTimeFrame == null)
            {
                RealTimeFrame = bmp.ToWriteableBitmap();
                await Task.Delay(1);
                continue;
            }
            
            realTimeFrame.UpdateWith(bmp);
    
            await Task.Delay(1);
            if (isClose) break;
        }
    
        DecCtx.Stop();
    });
```

It works very well. I am trying how to automatically reconnect with rtsp video stream when timeout. And reduce the latency better.

**Comment by SuRGeoNix** [comment]
Nice @EjiHuang,

For reconnection, you could just check when you get out from your main while loop if VideoDecoder.IsRunning and if not you re-open or just start the DecCtx.Start(). (I guess you are using RTSP live stream right?)

For latency have a look on older discussion [here](https://github.com/SuRGeoNix/Flyleaf/issues/42) that might help. Have also a look at my implementation for low latency [here](https://github.com/SuRGeoNix/Flyleaf/blob/master/FlyleafLib/MediaPlayer/Player.cs#L1566). Generally, you might also consider passing options/flags to the demuxer for that. Eg. NOBUFFER Config.Demuxer.FormatFlags |= 0x40 .

Can I ask what do you do in-between with OpenCV so you can't use my implementation directly?  Processing the bmp is not the best for the performance. Ideally, it should be done in the GPU.

**Comment by EjiHuang** [comment]
@SuRGeoNix Thank you very much.

And, I want to implement target detection on video player. Like yolo v5. And OpenCV dnn framework can help me. It can use yolo from Darknet.
