### ISSUE TITLE
Pan Drag/Move

### ISSUE THREAD

**Issue by swimfish09** [SuRGeoNix/Flyleaf#88]
now support zoom feature

**Comment by SuRGeoNix** [comment]
It already does, if you mean something more than what it already supports be more specific.

**Comment by swimfish09** [comment]
zoom and pan feature, just like this.

https://user-images.githubusercontent.com/3916975/133536629-ea94b89c-2092-4159-8e37-ddea12958fa3.mp4

**Comment by SuRGeoNix** [comment]
I've added Player.PanXOffset and Player.PanYOffset which allows you to change the location of the Panel. However, the dragging should be implemented by you. I've included on the Wpf control so you can take an idea. Check the code [here](https://github.com/SuRGeoNix/Flyleaf/blob/master/FlyleafLib.Controls.WPF/Flyleaf.xaml.cs#L249). Let me know if that's what you wanted.
