### ISSUE TITLE
curTime is wrong when play m3u8

### ISSUE THREAD

**Issue by swimfish09** [SuRGeoNix/Flyleaf#89]
player speed set to 4x and play m3u8
![image](https://user-images.githubusercontent.com/3916975/133957272-6737c899-4886-4d49-a69b-6b44ec522bfb.png)

**Comment by SuRGeoNix** [comment]
Hey @swimfish09, it should be fixed. Give it a try from master if you can and let me know if still exists. Please next time try to add some logs and a way to reproduce it.

**Comment by SuRGeoNix** [comment]
Ok found another issue...

**Comment by swimfish09** [comment]
Use latest master code
This problem appear again and with video brightness is dim.
[player-2022-02-16.log](https://github.com/SuRGeoNix/Flyleaf/files/8075865/player-2022-02-16.log)
