### ISSUE TITLE
Can I use this repo to split video into multiple parts in parallel?

### ISSUE THREAD

**Issue by zydjohnHotmail** [SuRGeoNix/Flyleaf#90]
Hello:
I can use ffmpeg to split video into multiple parts, like this:
ffmpeg -i 1.mp4 -ss 00:10 -to 01:00 1_1.mp4
ffmpeg -i 1.mp4 -ss 03:10 -to 04:00 1_2.mp4
ffmpeg -i 1.mp4 -ss 07:10 -to 07:30 1_3.mp4
……
But I found this method of splitting video into parts is rather time consuming. 
Cut one part will take 5 to 10 seconds.
I want to know if I can use this repo to split the video into multiple parts as multiple jobs, and run all the jobs at the same time.  As my PC has 16-core, I can run many such jobs at the same time.
If yes, then please share some code.
Thanks,

**Comment by SuRGeoNix** [comment]
Hey @zydjohnHotmail,

Yes, you should be able to do it. You could either use the Downloader (which actually remuxes) or even the Recorder. You could use the Buffer Duration with the PauseOnQueueFull and when the demuxer will be paused you will have the part of the video that you want. Bare in mind that seek works with keyframe so if you seek at 10 seconds it might go to 15 or even more distance. This happens to ensure that you will not have gray/broken frames. You can create multiple downloaders and run them async.

**Comment by zydjohnHotmail** [comment]
Hello:
First, the MP4 file is already saved in local disk, so I have this file: C:\Videos\1.mp4.
So, I don't need to download it, as it is already downloaded and saved in local disk.
Second, if you think the repo can do this, then please show me how to do this by some code.
Thanks,

**Comment by SuRGeoNix** [comment]
The downloader acts also as a remuxer so you can use it for that purpose. I will not write the code for you. I told you in the past that currently the library mainly supports the Player, Downloader, Extractor. Start writing and if you have a specific question a might be able to help.
