### ISSUE TITLE
How to prevent error "Thread Play did not finished properly"

### ISSUE THREAD

**Issue by pssp-sven** [SuRGeoNix/Flyleaf#93]
Hi @SuRGeoNix,

first of all thanks for this really nice library! It's really useful and I like it a lot.
Sometimes the player seems to hang and after some seconds the following error occurs:

> Thread Play did not finished properly!

Is there any way to get around this error?
If not, is there any way to fail faster? As mentioned it takes some seconds before the message appears.

Thanks again and all the best!

**Comment by SuRGeoNix** [comment]
Hey @pssp-sven, I'm glad that you find this library useful. 

You shouldn't get this Exception, which means somewhere there is a bug. Can you provide more information when does this happen, a way to reproduce maybe?

**Comment by SuRGeoNix** [comment]
That would help more. I think I've noticed that with the bitswarm plugin (which has a list of videos). I will try also to identify it and fix it.

**Comment by pssp-sven** [comment]
After several tries to reproduce the error in a simple sample project I can tell you, that everything works as expected. The error just occurs in my main project, which is pretty complex. I think there's no error that you have to fix, but I need to check why I have that problem in my project.
Sorry to having bothered you with this one and thanks again for this wonderful library! :)

**Comment by SuRGeoNix** [comment]
That's good I guess. If you come up with that again, let me know. Sounds like a lock issue between open/stop/play/enable/disable video/audio/subs. But I wasn't able to produce it at all.
