### ISSUE TITLE
Support Deinterlace and other ffmpeg filters

### ISSUE THREAD

**Issue by pssp-sven** [SuRGeoNix/Flyleaf#94]
Hello @SuRGeoNix,
what is the correct way to activate options for deinterlacing like "-vf yadif=1"?

**Comment by SuRGeoNix** [comment]
With further research it seems that ffmpeg doesn't support d3d11 hardware frames at all. The only way it would be to custom implement this with [d3d11 video processor](https://docs.microsoft.com/en-us/windows/win32/api/d3d11/ne-d3d11-d3d11_video_processor_processor_caps) which requires re-design the whole rendering implementation. Not sure if it worth the time effort as blend/bob deinterlace methods maybe not good enough and adaptive requires reference frames.

I guess we should answer the question, how often do we deal with interlace videos and why not just converting them to deinterlace with other existing tools before hand?

Now for ffmpeg filters, as they don't support d3d11 hardware frames will make playback really heavy (performance wise). Additionally, every filter requires different configuration which can't be implemented for all the ffmpeg's filters.

Sorry, for the bad news. Let me know what you think but I'm afraid that I will close this as it requires a lot of time effort and not sure if it worth it for this library which focuses on d3d11 playback.

**Comment by pssp-sven** [comment]
First of all let's drop the idea of integrating FFmpeg filters. I understand your points, that the filters are not part of the main goal of this project. So I fully agree.

Regarding the own implementation of deinterlacing I hope to convince you that this would be a quite interesting and important feature. I hope it's ok for you, when I send you an email again to discuss that topic.

**Comment by SuRGeoNix** [comment]
Sure, any time :)

I might even have a look in the future on ffmpeg filters (some commonly used) to add support with the extract frames implementation.

**Comment by pssp-sven** [comment]
Hi @SuRGeoNix,
just would like to know, if you had a chance to look at this topic again?

**Comment by SuRGeoNix** [comment]
Hi @pssp-sven, working this weekend on v3.4 and I had a look on this one. Unfortunately, all attempts failed so far. The proper way to do this requires more time effort and I'm not sure if I will be able to included yet.

**Comment by SuRGeoNix** [comment]
@pssp-sven Can you do some beta testing on master and let me know how it goes?

**Comment by pssp-sven** [comment]
Hi @SuRGeoNix,
of course I'll have a look, but probably not before this weekend. I'll give you my feedback as soon as possible.

**Comment by pssp-sven** [comment]
Hi @SuRGeoNix,
great job, it seems to work now.

**Comment by SuRGeoNix** [comment]
Good news cause I was worrying for this one as I'm not that familiar. I will close this for now but in the future I will try to add the other methods as well.
