### ISSUE TITLE
Cookie support for YT-DLP plugin

### ISSUE THREAD

**Issue by zydjohnHotmail** [SuRGeoNix/Flyleaf#98]
Hello:
I found the latest version (3.3.10) of FlyLeaf adds Youtube-DL supports, it looks good.  But I have a question on how to download some M3U8 links using cookies.
Here is what I can do now:
1) I installed Youtube-DL.exe in “C:\Program Files\Youtube-DL\”, I added Youtubr-DL.exe binary path to environment PATH variable, so I can call it anywhere in my windows 10 PC.
2) I installed M3U8 sniffer extension for chrome from this URL:
https://chrome.google.com/webstore/detail/video-m3u8-sniffer-find-h/akkncdpkjlfanomlnpmmolafofpnpjgn
3) I installed Get cookies.txt extension for chrome from this URL:
https://chrome.google.com/webstore/detail/get-cookiestxt/bgaddhkoddajcdgocldbbfleckgcbcid/
4) I visit some video web site, which has some cookies in the browser, you can’t simply download M3U8 link without providing the necessary cookies.
Then, I export the cookies from the video web site to file: C:\Videos\web1_cookies.txt
5) I browse some video links and see there is one video I want to download, it has M3U8 link like: https://xxx.videos.com/videos/hls-1080p1.m3u8 (Not actual link, as actual link is too long)
6) I can run the following command to download the M3U8 link and save in my local hard drive:
C:\Videos>youtube-dl.exe --cookies web1_cookies.txt https://xxx.videos.com/videos/hls-1080p1.m3u8  -o Video_01.mp4
This command works well.
Your repo can work for M3U8 links without cookies, I already tested, but I can’t find any code samples on how to add cookies to download M3U8 links, as many web sites need login before you can download any videos.
Please advise on how to add the cookies to Youtube-DL.exe just as I did with command line.
Thanks,

**Comment by SuRGeoNix** [comment]
Hey @zydjohnHotmail, currently Youtube-DL plugin doesn't support cookies. I will review this on next version and might add it. Until then you can write your own plugin based on the existing and change the arguments to include a cookie file [here](https://github.com/SuRGeoNix/Flyleaf/blob/aa0b276665fbc9ae9d8c771663ef9c00c98bbf34/FlyleafLib.Plugins.YoutubeDL/YoutubeDL.cs#L137)
