### ISSUE TITLE
Need some suggestion on how to download this type of live stream using the repo.

### ISSUE THREAD

**Issue by zydjohnHotmail** [SuRGeoNix/Flyleaf#99]
Hello:
I can login to watch some live sports games from one small video web site.  But there is no customer service, I don’t know how to set up a customer account. 
However, I found that the web site uses JWPlayer to play live videos, and from the web site JavaScript, I found the HLS source seems to be available for all browser without login. It is working for Google Chrome, Microsoft Edge, and Firfox without login.
The following is one of such URL, which I can watch live sport game:
https://bingsport.com/1proxy.php?id=g_13&ver=2727179&parent=247sport.net

I tried to use Youtube-DL.exe to download it, but I got error message:
[generic] 1proxy: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 1proxy: Downloading webpage
[generic] 1proxy: Extracting information
ERROR: Unsupported URL: https://bingsport.com/1proxy.php?id=g_13
I want to know what type of live stream this URL is using, and how I can download it?
For example, if I want to download this type of live stream and save as an MP4 file in my local disk using Flyleaf library, what I should do?
Thanks,

**Comment by SuRGeoNix** [comment]
If you tried yt-dlp directly and you got an error with the extractor then the issue is with the yt-dlp and you should open it there. You could try other forks of youtube-dl that might work.
